### PR TITLE
1358 remove auto api

### LINKED ISSUE #1358: remove AutoAPI
not needed anymore

### PR DESCRIPTION
**Pull request by doutriaux1**
and vcs_legacy

should fix #1358 
@dlonie @sankhesh please review

cdash is at:
https://open.cdash.org/buildSummary.php?buildid=3844786

@dlonie wonder why pep8 test is skipped

### CODE REVIEW

**Comment by dlonie** [comment]
https://open.cdash.org/testDetails.php?test=341967758&build=3842977

Doesn't look like the pep8 executable is installing correctly.

**Comment by dlonie** [comment]
Is the CDMS failure expected?

**Comment by dlonie** [comment]
All tests pass for me, including `CDMS_Test_multiple_formats`, though this is failing on @doutriaux1's system and on the garant buildbot. The pep8 test seems to be failing due to a build/install issue on Charles' system that I can't reproduce.

We should figure out what's up with the CDMS test on the failing systems before merging. I'm not worried too much about pep8 getting fixed right now since it looks like an unrelated issue to this branch.

**Comment by dlonie** [comment]
Is the CDMS thing related to #1368?

**Comment by jbeezley** [comment]
> The server is temporarily unable to service your request due to maintenance downtime or capacity problems. Please try again later.

This is the problem relying on external services in automated tests, though I'm not sure how we would go about mocking an opendap server.

**Comment by dlonie** [comment]
Ah, my eye jumped to the exception output and I missed that. Ok, since the test is passing now, LGTM :+1:

FWIW, I reran the script @jbeezley put on #1343, and there are still 10632 leaks from the vcs import, so this doesn't seem to have made much difference on that front.

**Comment by dlonie** [comment]
Let's clean up those tests (remove the commented lines, or restore them and update the baselines) before merging, though.

**Comment by doutriaux1** [comment]
cdms2 is expected because of lab firewall. pep8 also isn't related to this PR. Probably mac related or something. Again probably should be looked at in another PR.

**Comment by aashish24** [comment]
what's the final conclusion on this PR then?

**Comment by doutriaux1** [comment]
@aashish24 let me uncomment the lines and generate a new baseline.

**Comment by doutriaux1** [comment]
ok only pep8 fails on mac, but it's because it seems to be looking for it in wrong path on mac, will open a dedicated issue for it. (#1386)

mac dashboard:
https://open.cdash.org/buildSummary.php?buildid=3856909

**Comment by doutriaux1** [comment]
other projects depending on uvcdat are also falling apart because of the pyopenssl issue:

```


make[2]: *** [PYOPENSSL-prefix/src/PYOPENSSL-stamp/PYOPENSSL-install] Error 1
make[1]: *** [CMakeFiles/PYOPENSSL.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
-- Cython install command succeeded.  See also /export/gleckler1/PCMDI_METRICS/tmp/uvcdat/uvcdat_build/Cython-prefix/src/Cython-stamp/Cython-install-*.log

[ 69%] Completed 'Cython'
[ 69%] Built target Cython
-- FFMPEG build command succeeded.  See also /export/gleckler1/PCMDI_METRICS/tmp/uvcdat/uvcdat_build/FFMPEG-prefix/src/FFMPEG-stamp/FFMPEG-build-*.log

[ 69%] Performing install step for 'FFMPEG'
-- FFMPEG install command succeeded.  See also /export/gleckler1/PCMDI_METRICS/tmp/uvcdat/uvcdat_build/FFMPEG-prefix/src/FFMPEG-stamp/FFMPEG-install-*.log

[ 69%] Completed 'FFMPEG'
[ 69%] Built target FFMPEG
-- ESMF build command succeeded.  See also /export/gleckler1/PCMDI_METRICS/tmp/uvcdat/uvcdat_build/ESMF-prefix/src/ESMF-stamp/ESMF-build-*.log

[ 70%] Performing install step for 'ESMF'
-- ESMF install command succeeded.  See also /export/gleckler1/PCMDI_METRICS/tmp/uvcdat/uvcdat_build/ESMF-prefix/src/ESMF-stamp/ESMF-install-*.log

[ 70%] Completed 'ESMF'
[ 70%] Built target ESMF
make: *** [all] Error 2
 ERROR: Could not compile (make) cdat code
~/PCMDI_METRICS/tmp/uvcdat/uvcdat ~/PCMDI_METRICS/tmp/metrics

```

**Comment by doutriaux1** [comment]
@chaosphere2112 @dlonie @aashish24 @jbeezley what's the hold on this?

**Comment by dlonie** [comment]
@doutriaux1 The last comment regarding pyopenssl failing made me think there was still some work to do, or was that unrelated to this issue?

**Comment by doutriaux1** [comment]
unrelated to this issue, it is actually fixed in #1388 that needs review (urgently because this very reason)

**Comment by dlonie** [comment]
LGTM, but can't merge due to conflicts with master.

**Comment by doutriaux1** [comment]
darn! ok will rebase today.

**Comment by doutriaux1** [comment]
@dlonie @sankhesh rebased. Please review and approve.

**Comment by dlonie** [comment]
Testing now.

**Comment by dlonie** [comment]
LGTM

**Comment by aashish24** [comment]
yay :clap: :smile:

**Pull request merged**
