### PR TITLE
1577 boxfill patterns

### LINKED ISSUE #1577: Patterns & Hatches on Boxfill, Isofill
Looks like patterns and hatches work correctly for `fillarea`s and `isofill` plots, but not for `boxfill`.

```python
import vcs, cdms2

x = vcs.init()

f = cdms2.open(vcs.sample_data + "/clt.nc")
s = f("clt")

box = x.createboxfill()
box.fillareastyle = "hatch"
box.fillareacolors = [20, 50, 75]
box.fillareaindices = [5, 10, 15]
box.levels = [10, 50, 75, 100]
box.boxfill_type = "custom"

x.plot(s, box)
x.png("hatch_box.png")

isofill = x.createisofill()
isofill.fillareastyle = "hatch"
isofill.fillareacolors = [20, 50, 75]
isofill.fillareaindices = [5, 10, 15]
isofill.levels = [10, 50, 75, 100]

x.clear()

x.plot(s, isofill)
x.png("hatch_isofill")
```

Produces these two:
hatch_box
hatch_isofill

```python
import vcs, cdms2

x = vcs.init()

f = cdms2.open(vcs.sample_data + "/clt.nc")
s = f("clt")

box = x.createboxfill()
box.fillareastyle = "pattern"
box.fillareacolors = [20, 50, 75]
box.fillareaindices = [5, 10, 15]
box.levels = [10, 50, 75, 100]
box.boxfill_type = "custom"

x.plot(s, box)
x.png("pattern_box.png")

isofill = x.createisofill()
isofill.fillareastyle = "pattern"
isofill.fillareacolors = [20, 50, 75]
isofill.fillareaindices = [5, 10, 15]
isofill.levels = [10, 50, 75, 100]

x.clear()

x.plot(s, isofill)
x.png("pattern_isofill")
```

Produces these two:
pattern_box
pattern_isofill

In addition, the performance of plotting the patterns/hatches for the isofill is pretty slow:

```python
import datetime, vcs, cdms2

x = vcs.init()
f = cdms2.open(vcs.sample_data + '/clt.nc')
s = f('clt')

def t():
   return datetime.datetime.now()

isofill = x.createisofill()
isofill.fillareaindices = [1, 5, 10]
isofill.fillareacolors = [50, 100, 150]
isofill.levels = [0, 25, 75, 100]

for style in ("hatch", "pattern", "solid"):
   isofill.fillareastyle = style
   before = t()
   x.plot(s, isofill)
   after = t()
   print after - before
```
gives us these times:
0:00:03.027187 (hatch)
0:00:03.077247 (pattern)
0:00:00.559602 (solid)

So, that's some pretty serious overhead.

### PR DESCRIPTION
**Pull request by sankhesh**
Fixes #1577 
Baselines added in UV-CDAT/uvcdat-testdata#71

### CODE REVIEW

**Comment by doutriaux1** [comment]
@sankhesh seems to be failing

**Comment by sankhesh** [comment]
@doutriaux1  Tests are passing now. The remaining failures are due to uvcdat-testdata not being fetched from the right branch on the dashboard machines. Not sure what is the reason.

**Comment by aashish24** [comment]
@doutriaux1 @sankhesh are we good with this branch then?

**Comment by sankhesh** [comment]
Yes. Needs review and merge.

**Comment by doutriaux1** [comment]
yes we are good but I want to figure out why the baselines are not checked out anymore.

**Pull request merged**
