### PR TITLE
Issue1312 durack1 readme.md update

### LINKED ISSUE #1312: tagg all externals repos as well as uvcdat repo
and make sure uvcdat points to these so that build a few weeks from now will still fetch the correct tag points.
repos: VTK Vistrails, uvcmetrics, uvcdat-testata

### PR DESCRIPTION
**Pull request by durack1**
fix #1312 - Update readme.md for 2.2.0 release

### CODE REVIEW

**Comment by durack1** [comment]
@jbeezley I wonder if there is a disconnect between the source the buildbot is picking up - this PR was issued against `master` and yet the error indicates `Version: uvcdat-2.2.0rc1-42-gaa1a3da`:
```
Successfully updated your environment to use UVCDAT
(changes are valid for this session/terminal only)
Version: uvcdat-2.2.0rc1-42-gaa1a3da
Location: /home/buildbot/buildbot/uvcdat-garant-linux-release/build/install
Found Baselines:
- /home/buildbot/buildbot/uvcdat-garant-linux-release/build/uvcdat-testdata/baselines/vcs/test_canvas_background.png
Comparing 'test_backgroundcolor_white.png' to '/home/buildbot/buildbot/uvcdat-garant-linux-release/build/uvcdat-testdata/baselines/vcs/test_canvas_background.png'...diff=234313.725490, New best!
All baselines failed! Lowest error (234313.725490) exceeds threshold (10.000000).
Saving image diff at 'test_backgroundcolor_white_diff.png'.
```

**Comment by aashish24** [comment]
@durack1 its not that. We will fix in the next release. what happens is that when we tag a commit, we need to bring that commit as "s ours" or else master will see that tag as well. I think buildbot uses the git describe which use the last tag information.

**Comment by jbeezley** [comment]
It isn't buildbot.  It is the `setup_runtime.sh`.  It [uses](https://github.com/UV-CDAT/uvcdat/blob/master/CMakeLists.txt#L695) `git describe`.  The version message contains the hash of the commit being tested: <code>uvcdat-2.2.0rc1-42-g**​aa1a3​da**</code>

```
$ git log --oneline -n 1 aa1a3da
aa1a3da fix #1312 - Update readme.md for 2.2.0 release
```

**Comment by doutriaux1** [comment]
@aashish24 let's bring the tag back into master. Yet another reason I really don't like the "release" branch. But we can debate this ad vitam eternam...

**Comment by durack1** [comment]
@jbeezley @aashish24 it seems a bunch of the test images aren't being downloaded to compare: https://open.cdash.org/viewTest.php?onlyfailed&buildid=3822441

I wonder if the branch checkout in the unmerged #1321 (https://github.com/UV-CDAT/uvcdat/blob/issue_1312_tag_repos/CMake/cdat_modules_extra/checkout_testdata.cmake#L31) will solve this?

**Comment by aashish24** [comment]
@doutriaux1 the problem is not related to release branch. Whether or not we have a release branch this problem the information will exists because of how git describe uses the information. If we want something else, we need to either give up git describe and use something else. Or use tag master.

**Comment by aashish24** [comment]
It might. I am working on a branch that will automatically follow the branch name in uvcdat for uvcdat-testdata.

**Comment by durack1** [comment]
@aashish24 can you kick off another buildbot test once you've pulled #1321 back into master? It seems it's getting close now and is passing on garant..

**Comment by durack1** [comment]
@doutriaux1 the PYOPENSSL error is causing grief here https://open.cdash.org/viewBuildError.php?buildid=3822471 - is that fix you were working on in master yet?

**Comment by jbeezley** [comment]
It looks like you may need to install `libffi-dev` on `test-laptop`.

**Comment by aashish24** [comment]
Thanks @jbeezley I just installed it.

**Comment by durack1** [comment]
@aashish24 wanna kick off `test-laptop` again then?

**Comment by jbeezley** [comment]
Done

**Comment by durack1** [comment]
@jbeezley thanks! Now I hope it passes..

**Comment by durack1** [comment]
@jbeezley ok great, it's just got a slight issue with the test image (problems with right boundary being written and not in test case: https://open.cdash.org/testDetails.php?test=338045449&build=3822602)

**Comment by doutriaux1** [comment]
@jbeezley I fixed this in my netcdf branch. we do build libffi so that's not the issue, one issue if the cffi_deps that as an issue with upper vs lower.

**Comment by durack1** [comment]
@doutriaux1 the only remaining issue with this current build is the test image - as you can see at https://open.cdash.org/testDetails.php?test=338045449&build=3822602 it's got a column of pixels being written to the image (far right side) which is not in the test image: https://open.cdash.org/displayImage.php?imgid=381312

**Comment by doutriaux1** [comment]
seems like the widgets color are different too

**Comment by doutriaux1** [comment]
@aashish24 just realizing you merged the wrong one.... You should have merged the one going to release not master... now the release will break as soon we update baselines...

**Comment by aashish24** [comment]
@doutriaux1 which branch you are referring to?

**Pull request merged**
