### PR TITLE
Pressing the "i" key makes button disappear (and other issues)

### PR DESCRIPTION
**Pull request by chaosphere2112**
Fixes 3 issues I found while testing text in the GUI; one was difficult to write a test for, so I punted on it, one was just a plain-out error, and the third is now properly tested.

1. In certain circumstances, you could get an error message when stopping editing text, due to the manager of the widget having been `del`'d by `detach`. This has been fixed.
2. If you pressed "Escape" to stop editing a text box, it would turn to just a blank box. Fixed, and tested.
3. Pressing the "i" key would hide a random widget, and pressing it again would bring it back. Tracked down where in the VTK documentation it mentions something pertaining to that, turned off that feature for all widgets. Couldn't come up with a good way to recreate programmatically.

### CODE REVIEW

**Comment by chaosphere2112** [comment]
@aashish24 @doutriaux1

**Comment by doutriaux1** [comment]
```
348: Test command: /lgm/uvcdat/2.2.0-rc1/bin/python "/git/uvcdat/testing/vcs/vtk_ui/test_vtk_ui_textbox_blank_test.py"
348: Test timeout computed to be: 1500
348: /lgm/uvcdat/2.2.0-rc1/bin/python: can't open file '/git/uvcdat/testing/vcs/vtk_ui/test_vtk_ui_textbox_blank_test.py': [Errno 2] No such file or directory
1/1 Test #348: test_vtk_ui_textbox_blank_text ...***Failed    0.02 sec
```
forgot to add the file?

**Comment by chaosphere2112** [comment]
@doutriaux1 Nope, I typo'd. Should be blank_text. I'll update.

**Comment by chaosphere2112** [comment]
@doutriaux1 Should be fixed now

**Comment by aashish24** [comment]
will have a look at it today..

**Comment by doutriaux1** [comment]
ok tests pass for me, merging

**Pull request merged**
