### PR TITLE
1644 patterns wrap

### LINKED ISSUE #1644: pattern are not wrapped around
```python
import vcs
import cdms2
import os


f=cdms2.open(os.path.join(vcs.sample_data,"clt.nc"))
s=f("clt")

print s.getLongitude()
x=vcs.init()

gm = x.createisofill()

gm.fillareastyle= "pattern"

levels = range(0,110,10)
cols = vcs.getcolors(levels)
gm.fillareacolors = cols
gm.levels = levels

gm.fillareaindices = range(1,12)
gm.datawc_x1 = 0.

gm.datawc_x2 = 360.
x.plot(s,gm)
x.png("pattern_wrapped")
```
pattern_wrapped

### PR DESCRIPTION
**Pull request by sankhesh**
Fixes #1644

### CODE REVIEW

**Comment by sankhesh** [comment]
@doutriaux1 I've not changed anything for meshfill plots since you said you have changes to support meshfill patterns on a different branch. I didn't want to create merge conflicts.

**Comment by sankhesh** [comment]
@aashish24 @doutriaux1 @chaosphere2112  Please review

**Comment by doutriaux1** [comment]
yes I have branch coming up for meshfill patterns thx!

**Comment by doutriaux1** [comment]
@sankhesh lots of failures

**Comment by sankhesh** [comment]
@doutriaux1 @aashish24 This branch is ready to be merged.

**Comment by sankhesh** [comment]
:bell: Ping!

**Comment by aashish24** [comment]
@sankhesh it has a merge conflict now. Also, @doutriaux1 wanted to merge the color maps first but since you will looking at that, I would suggest, we update this branch with master and get it merged.

**Comment by doutriaux1** [comment]
@sankhesh yes feel free to merge this and #1688  into colormaps so we can merge all at once. But I was thinking of doing colormaps first and then this and #1688 one at a time to limit the merge conflict and make potential breakages easier to spot and fix.

**Pull request merged**
