### PR TITLE
Fixes bug where hovering over meshfill raised exceptions

### LINKED ISSUE #1764: Meshfill + interact() leads to error message
Doing a meshfill will cause an error in the configurator in the hover function:

```
Traceback (most recent call last):
  File "/Users/fries2/build/install/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/vcs/configurator.py", line 364, in hover
    actor = self.actor_at_point(*point)
  File "/Users/fries2/build/install/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/vcs/configurator.py", line 315, in actor_at_point
    if back.IsA("vtkProp"):
AttributeError: 'str' object has no attribute 'IsA'
```

I'll fix this issue and get a PR for this release.

### PR DESCRIPTION
**Pull request by chaosphere2112**
Fixes #1764 by adding a missing try/except

### CODE REVIEW

**Comment by aashish24** [comment]
@chaosphere2112 why back would not be a vtkProp?

**Comment by aashish24** [comment]
Other than that LGTM :+1:

**Comment by chaosphere2112** [comment]
Meshfill apparently stores a string in the display plot's backend; a pretty diverse list of objects get shoved in there, not exclusively vtkProps. I had added try/except checks for that call in two other places, just missed it for this one.

**Comment by aashish24** [comment]
thanks @chaosphere2112

**Pull request merged**
