### PR TITLE
Issue 1499 runtest and mpi args broken

### PR DESCRIPTION
**Pull request by doutriaux1**

### CODE REVIEW

**Comment by doutriaux1** [comment]
@aashish24 @sankhesh @jbeezley RH6 FULL now seems to pass all tests (still fails the same isoline ones as the "regular" build. Please merge in.

**Comment by aashish24** [comment]
@doutriaux1 changes looks good to me. Please allow me to give some suggestions on commit messages. 

* It would be great if you can follow camel-case style (or other) having some consistency would be nice
* Should fix #1499 could be Implemented (added ...etc) fix for #1499 

Other than that :+1: :clap:

**Comment by doutriaux1** [comment]
@aashish24 not sure I get your camel case comment (at least in the context of this PR). just added another tweak to get matplotlib to build on mac, hoping it doesn't break things on Linux. Somehow editing directly in github seem to nto trigger the webhook for my bot... I guess I need to figure a way to trigger build for my bot manually based on commit number. Please review again the last commit, if it looks good to you and the travis and garant pass I would recommend approving.

**Comment by doutriaux1** [comment]
maybe it did trigger them and it's just in the queue...

**Comment by doutriaux1** [comment]
@aashish24 I can git squash it when you're ready to merge if you really really really really care

**Comment by doutriaux1** [comment]
@aashish24 care to approve please will help other PRs as well.

**Comment by doutriaux1** [comment]
@dnadeau4 feel free to use and approve this

**Comment by dnadeau4** [comment]
@doutriaux1 the changes are approved.  I am a bit worried about the unsuccessful check on the MAC and Red Hat.  They don't seem to be related to the cdms2 change.

**Comment by doutriaux1** [comment]
@dnadeau4 yes we are trying to bring the dashboards to green. One baby step at a time.

**Pull request merged**
