### PR TITLE
issue1686 durack1 update seawater 3.3.2 to 3.3.4

### LINKED ISSUE #1686: Update python-seawater to 3.3.4

### PR DESCRIPTION
**Pull request by durack1**
Fix #1686 - Update seawater 3.3.2 to 3.3.4

### CODE REVIEW

**Comment by aashish24** [comment]
@durack1 waiting for garant to finish..

**Comment by durack1** [comment]
@aashish24 it never will it's been sitting there for about 24hrs..

**Comment by durack1** [comment]
@aashish24 also, unless `garant` is building `ALL` (which I'm pretty sure it isn't) it's not going to touch the tarball and install step anyway..

**Comment by aashish24** [comment]
@durack1 ah. I see. Also, why others are not running?

**Comment by durack1** [comment]
@aashish24 as this is a peripheral package, I was keen not to block up the `bot` queue.. If there's build test time available you can select the `update branch` button below and it'll then requeue to build across the full `bot` suite..

**Comment by aashish24** [comment]
LGTM :+1:

**Pull request merged**
