### PR TITLE
Issue1126 durack1 matplotlib1.4.3 update

### LINKED ISSUE #1126: Update matplotlib to 1.4.3
We are a patch release behind matplotlib latest (1.4.2 vs 1.4.3).

@doutriaux1 @aashish24 want to assign me to this task as a 2.3 milestone?

### PR DESCRIPTION
**Pull request by durack1**
fix #1126 - Update matplotlib 1.4.2 to 1.4.3

### CODE REVIEW

**Comment by durack1** [comment]
@doutriaux1 looks like a bunch of the testimages aren't there https://open.cdash.org/testDetails.php?test=337667048&build=3821032

**Comment by durack1** [comment]
@aashish24 @jbeezley @doutriaux1 it seems that timeouts are causing build grief with travis again https://travis-ci.org/UV-CDAT/uvcdat/builds/63255084 - maybe my attempted `travis_wait` solution tried at #1129 and documented at http://docs.travis-ci.com/user/build-timeouts/#Build-times-out-because-no-output-was-received

**Comment by durack1** [comment]
@jbeezley @aashish24 is there a reason that this PR (#1329) is triggering the `test-laptop` buildbot only, wheras #1330 triggered both `garant` and `test-laptop` and #1341 doesn't appear to have trigger any buildbot tests?

**Comment by durack1** [comment]
@jbeezley @aashish24 additionally, it seems that the same single column of pixels along right hand side of test image is appearing again: https://open.cdash.org/displayImage.php?imgid=383269

**Comment by aashish24** [comment]
@durack1 looks like it trigged both this time. What did we miss?

**Comment by durack1** [comment]
@aashish24 weird, it seems like these tests are really flaky, it's failed, then passed, failed then passed.. I think the issue with the buildbot was that they weren't triggered until later as another PR was already being tested..

**Comment by aashish24** [comment]
that shouldn't cause this trouble. I haven't see something like this before (with other branches). It seems to be happening only with yours? Is that right?

**Comment by durack1** [comment]
I'm only familiar with what's happening with my PRs.. So I can't make any useful statement on your question above.. But, yes it's happening to mine..

**Comment by durack1** [comment]
@doutriaux1 this PR seems good to go..

**Comment by doutriaux1** [comment]
could plot something with it, approving

**Comment by durack1** [comment]
@aashish24 @doutriaux1 it appears that this PR is no longer in master (a similar situation to #1441) can you restore and merge back into master?

**Comment by aashish24** [comment]
How that happened? Did someone forced push master?

**Comment by durack1** [comment]
@aashish24 not sure, I believe this got tangled up with problems with the `release` branch changes being merged back into `master`.. It's the 2nd such case that I've become aware of.. I'll keep my eyes open for more, there probably are additional cases..

**Comment by durack1** [comment]
@doutriaux1 pinging you on this too..

**Comment by doutriaux1** [comment]
@sankhesh that ight help (or be the cause) of your PySide/PyQt issues

**Comment by sankhesh** [comment]
I don't think this is the issue. However, I can merge these changes in my basemap_build branch with other fixes.

**Comment by doutriaux1** [comment]
Yes please lets merge this into your branch.

**Pull request merged**
