### PR TITLE
Click info point dataset

### PR DESCRIPTION
**Pull request by danlipsa**

### CODE REVIEW

**Comment by danlipsa** [comment]
Needs:
https://github.com/UV-CDAT/uvcdat-testdata/pull/130

**Comment by danlipsa** [comment]
@aashish24 @doutriaux1 Please review. Test results are at
https://open.cdash.org/index.php?compare1=63&filtercount=2&field1=buildname%2Fstring&project=UV-CDAT&field2=buildstarttime%2Fdate&showfilters=0&limit=100&compare2=83&value1=7483fc3c&showfeed=0&value2=20160511T213043
Note that for some reason, the correct baselines are not pulled by annie, so more tests are reported as failures that it should.

**Comment by danlipsa** [comment]
@aashish24 @doutriaux1 Please review.

**Comment by danlipsa** [comment]
@doutriaux1 @aashish24 ping

**Comment by doutriaux1** [comment]
two failures on my mac:
```
	115 - test_vcs_boxfill_robinson_wrap (Failed)
	432 - test_vcs_no_continents (Failed)
```

I'm not sure why it wasn't uploaded!

**Comment by doutriaux1** [comment]
robinson is just a line that is not on top on mac, attaching the `good` (mac good)
test_robinson_wrap
 file here

**Comment by doutriaux1** [comment]
baseline missing for no continents?
```
432: vtkPNGReader (0x7fca2b623260): Unable to open file /Users/doutriaux1/build/uvcdat-testdata/baselines/vcs/test_vcs_no_continents.png
```

**Comment by danlipsa** [comment]
@doutriaux1 Is this ready? I think continents were fixed on master and I rebased. Not sure about test_vcs_boxfill_robinson_wrap. There seems to be a baseline without the to line.

**Comment by danlipsa** [comment]
This is what fails on my machine:
	 54 - test_vcs_read_old_scr_2 (Failed)
	 65 - test_vcs_verify_boxfill_basics (Failed)
	 66 - test_vcs_verify_proj_basics (Failed)
	 67 - test_vcs_verify_fillarea_basics (Failed)
	111 - test_vcs_canvas_background (Failed)
	565 - diags_test_02 (Failed)
	566 - diags_test_03 (Failed)
	567 - diags_test_04 (Failed)
	568 - diags_test_41 (Failed)
	569 - diags_test_05 (Failed)
	570 - diags_test_06 (Failed)
	571 - diags_test_07 (Failed)
	572 - diags_test_08 (Failed)
	573 - diags_test_09 (Failed)
	574 - diags_test_10 (Failed)
	575 - diags_test_11 (Failed)
	576 - diags_test_12 (Failed)
	577 - diags_test_13 (Failed)
	578 - diags_test_15 (Failed)

**Comment by doutriaux1** [comment]
I think the first one is on me, I need to fix that. What about the other three?

**Comment by danlipsa** [comment]
@doutriaux1 The verify tests? They all say:
[~/projects/uvcdat/build]$ "/home/danlipsa/projects/uvcdat/build/install/bin/python" "/home/danlipsa/projects/uvcdat/src/testing/vcs/test_vcs_verify_boxfill_basics.py"
Traceback (most recent call last):
  File "/home/danlipsa/projects/uvcdat/src/testing/vcs/test_vcs_verify_boxfill_basics.py", line 6, in <module>
    from vcs_test_common import *
ImportError: No module named vcs_test_common

**Comment by doutriaux1** [comment]
@chaosphere2112  do you know why would that be?

**Comment by chaosphere2112** [comment]
@danlipsa Did you rerun cmake after testing @aashish24's branch?

**Comment by aashish24** [comment]
@danlipsa can you rebase / update this branch on top of my testing branch?

**Comment by danlipsa** [comment]
@aashish24 @doutriaux1 Why not merge this branch into master as these failure are not related and happen on master as well. If @aashish24 testing branch fixes those, all the better.
I think a branch should have a focused goal, reach that and merge. We should not attempt to fix everything before we merge.

**Comment by aashish24** [comment]
> @aashish24 @doutriaux1 Why not merge this branch into master

@danlipsa the only reason I was asking you to merge my branch since my branch has very large change  and every time a new branch goes into master I have to make sure there is no conflict (size of the baselines, etc). Since I know for sure we are going to have conflict, that's why one of us would have to update. I just thought it would be easier for your branch since its small compare to mine but I am fine other way as well.

**Comment by danlipsa** [comment]
@aashish24 I don't debate who should merge into master first. What I say is that we should test unrelated topics separately. If a topic is ready to merge it should be merged.
In this case I don't mind to wait for your topic to go in first.

**Comment by aashish24** [comment]
> In this case I don't mind to wait for your topic to go in first.

That sounds great to me :+1:, thanks for letting me finish first :runner:

**Comment by danlipsa** [comment]
@chaosphere2112 I removed CDAT-prefix, rerun cmake but I get the same failure. I remember seeing those on master as well at one point. Did you fix those?

**Comment by chaosphere2112** [comment]
@danlipsa I'm not clear what tests you're talking about at this point; I haven't done any work on any of the failing tests, pretty much ever. Not entirely clear why I got tagged in the first place, really :smile:

**Comment by danlipsa** [comment]
@chaosphere2112 :smile:

**Pull request merged**
