### PR TITLE
Fixed conversion to base64 string

### PR DESCRIPTION
**Pull request by aashish24**

### CODE REVIEW

**Comment by aashish24** [comment]
@doutriaux1 please review. You may want to checkout branch locally since the diff is really confusing because of the indentation changes I made.

**Comment by doutriaux1** [comment]
@aashish24 it's ok I looked at the diff on your first commit. I remember we looked at this together. Changes look good to me. Looks like my bots are dead again... Will test locally but I don't expect any issue. I'm tempted though to ask you to edit your last commit message because you have a typo in it :stuck_out_tongue_winking_eye: You know just so that the history look good :wink:

**Comment by aashish24** [comment]
> I'm tempted though to ask you to edit your last commit message because you have a typo in it  You know just so that the history look good

you should ask. Not sure why my spell check didn't get it.

**Comment by aashish24** [comment]
thanks @doutriaux1 if looks good can I merge it?

**Pull request merged**
