### PR TITLE
moved sample data with over sample data

### LINKED ISSUE #1501: mac dv3d sample data put in different place
data_file is used in setup.py to move the sample_data file. This leads to a path that is different on mac (Framework etc..)
see: https://open.cdash.org/testDetails.php?test=366620272&build=3974508

### PR DESCRIPTION
**Pull request by doutriaux1**
this fix #1501 where DV3D would fail finding the sample data

### CODE REVIEW

**Comment by doutriaux1** [comment]
@aashish24 dv3d fixed on Mac please approve

**Comment by aashish24** [comment]
Thanks @doutriaux1 LGTM :+1:

**Comment by doutriaux1** [comment]
@aashish24 I thought you said you merged this one? Merging now.

**Comment by aashish24** [comment]
Yup LGTM meaning that you can merge!

**Pull request merged**
