### PR TITLE
3D support for vcs.update

### PR DESCRIPTION
**Pull request by chaosphere2112**
@ThomasMaxwell I was trying to cook up a camera manipulation demo for @jypeter when I discovered that updating the camera on a 3D graphics method wasn't doing much, even when I replotted / called `canvas.update()`. I made a few minimal tweaks to better support those operations. If you can take a look at what I did and make sure it wasn't anything dumb, that'd be awesome.

### CODE REVIEW

**Comment by ThomasMaxwell** [comment]
Sam,
      As long as the ctests pass this should be fine.  Thanks.

— Tom

**Comment by chaosphere2112** [comment]
Passes everything for me. @aashish24 Mind running tests / merging?

**Comment by aashish24** [comment]
Sure.. I will run the test and if all works will merge it.

**Comment by aashish24** [comment]
LGTM :+1:

**Comment by jypeter** [comment]
Thanks Sam et al!
I'm still experimenting with DV3D and I have a few issues to submit before I forget about them. I have only completed #1187 so far

**Pull request merged**
