### PR TITLE
wrong baseline src file names

### PR DESCRIPTION
**Pull request by doutriaux1**

### CODE REVIEW

**Comment by doutriaux1** [comment]
goes with https://github.com/UV-CDAT/uvcdat-testdata/pull/72
@sankhesh on all bots now these are missing, this should fix the baseline

**Comment by aashish24** [comment]
@doutriaux1 the baselines looks great. I will wait for buildbot to finish.

**Comment by doutriaux1** [comment]
@aashish24 not sure what the ocean only failure is about

**Comment by doutriaux1** [comment]
@aashish24 not sure why garant is failing diag test 1 but not related to this pr

**Pull request merged**
