### PR TITLE
Histogram fixup

### PR DESCRIPTION
**Pull request by chaosphere2112**
I reworked the histogram object a while back, and apparently never submitted a pull request. This dramatically improves the histogram to take an arbitrary variable and display population and variance for the bins (which you can choose).

### CODE REVIEW

**Comment by chaosphere2112** [comment]
Found one small bug in this; this is very much in the backlog stage, no rush to get it merged.

**Comment by doutriaux1** [comment]
@chaosphere2112 do you mind
 * adding a test
 * waiting for 2.6 ?

**Comment by chaosphere2112** [comment]
@doutriaux1 Nope, no problem for me. This is backburnered, I just wanted to make sure it was entered somewhere into the system so I would have a reminder to wrap it up.

**Comment by aashish24** [comment]
@chaosphere2112 could you please open it again when you are ready?

**Pull request closed without merging**
