### PR TITLE
Add flake8 test for vcs.

### PR DESCRIPTION
**Pull request by dlonie**
The test currently fails. The code needs to be cleaned up before merging.

@doutriaux1 @aashish24

### CODE REVIEW

**Comment by doutriaux1** [comment]
@aashish24 @dlonie @sankhesh this one is `finally` ready!
Let's merge as soon as possible to avoid too many merge conflicts in the future.

**Comment by doutriaux1** [comment]
Mac dashboard: https://open.cdash.org/viewTest.php?onlypassed&buildid=3907770

**Comment by doutriaux1** [comment]
Ubuntu dashboard: https://open.cdash.org/viewTest.php?onlypassed&buildid=3907746

**Comment by doutriaux1** [comment]
@aashish24 pinging you on this.

**Comment by aashish24** [comment]
@doutriaux1 will review it today.

**Comment by aashish24** [comment]
@doutriaux1 this is good stuff. Thanks for doing this. Minor suggestion: Commit messages could be improved for example "moving along". You can squash these commit messages into some more meaningful so that we can have a good code history. I understand that these messages are typically created during the developement.

**Comment by doutriaux1** [comment]
@aashish24 you're right, I really need to get going with the squash thing before submitting PRs. Thanks for the merge!

**Comment by aashish24** [comment]
You are welcome my friend. Squash is really useful :smile:

**Pull request merged**
