### PR TITLE
Split repos

### PR DESCRIPTION
**Pull request by doutriaux1**
@aashish24 @danlipda @sankhesh  @chaosphere2112 I think this takes care of most repos, removed some dead ones, most of what is left is for historical reasons, and the contributed packages. Not sure what to do with them, I think it's ok to leave them here for now.

### CODE REVIEW

**Comment by doutriaux1** [comment]
@aashish24 @danlipsa @sankhesh we need to move the test suites to their own repo. Do you guys mind doing this on this branch?

**Comment by aashish24** [comment]
> @aashish24 @danlipsa @sankhesh we need to move the test suites to their own repo. Do you guys mind doing this on this branch?

Okay, I will assign my self on it.

**Comment by doutriaux1** [comment]
@aashish24 @danlipsa it's ready, not it will try to checkout the same branch as the one you're in for all other repos (vcs/cds,etc..)
you also need to review and approve https://github.com/UV-CDAT/vcs/pull/8 at the same time

**Comment by aashish24** [comment]
Mostly looks good to me however there might be some issues which we can fix in subsequent PR's

**Comment by doutriaux1** [comment]
@aashish24 let's merge then.

**Pull request merged**
