### PR TITLE
VCS2D Animation Speedup

### PR DESCRIPTION
**Pull request by chaosphere2112**
Big speedup of animation in 2D– just had to stop saving PNGs while running the animation, and removed some redundant `Render` calls.

@doutriaux1 @williams13 @aashish24

### CODE REVIEW

**Comment by doutriaux1** [comment]
@chaosphere2112 that works great! Thank you! The one thing though is that it kills the zoom feature.
@williams13 do we want to keep it? @williams13 the other option is to turn on pngs (slow) when zooming? Your thoughts.

**Comment by williams13** [comment]
Let's not do the zooming for this release. We will revisit for the next release.

**Comment by aashish24** [comment]
@chaosphere2112 when does it write the PNGs then?

**Comment by chaosphere2112** [comment]
@aashish24 It writes the PNGs when you call `canvas.animate.save("path.mp4")`; takes longer to save out the animation, but we get >30FPS when running, so it seems like a useful tradeoff; @williams13 and @doutriaux1 indicated that the most common use case is to just run the animation to take a look at it, and then to manually generate PNGs in which you manipulate a variety of things, then call `canvas.ffmpeg` on those PNGs.

**Comment by aashish24** [comment]
okay sounds good. Earlier we had a diffirirent strategy as we suggested not to write file while we run the animation. I totally support this approach.

**Comment by doutriaux1** [comment]
@williams13 go ahead and rebuild

**Pull request merged**
