### PR TITLE
fixed tag point for external repos

### PR DESCRIPTION
**Pull request by doutriaux1**

### CODE REVIEW

**Comment by doutriaux1** [comment]
@aashish24 @sankhesh @chaosphere2112 when we are ready. I already tagged all externals repos as well so if we change anything in libcdms, cmor, vtk, vistrails or uvcmetrics that we want in the release we will need to move their `uvcdat-2.4.0` tag point as well

**Comment by durack1** [comment]
@doutriaux1 paraview is out?

**Comment by doutriaux1** [comment]
I must have missed a tag point on some repo here...

**Comment by aashish24** [comment]
> @doutriaux1 paraview is not included in the build anymore? Doesn't it also need a tag point set?

@durack1 ParaView is out. We no longer build ParaView.

**Pull request merged**
