### PR TITLE
Change pep8 to flake8.

### PR DESCRIPTION
**Pull request by dlonie**
Removed the existing pep8 test -- will readd it as a flake8 test in a later PR.

@doutriaux1 Which modules did you want tested again? I think we said 'everything under `Packages/`, but that includes things like `vcs_legacy` and a ton of other modules that I'm not sure are under active development, or are even used anymore.

Here's the full list of modules with the number of flake8 issues detected. Let me know which you want flake8 coverage for.

- AutoAPI: 417 flake8 issues found.
- browser: 48017 flake8 issues found.
- cdms2: 18353 flake8 issues found.
- cdtime: 35 flake8 issues found.
- cdutil: 6492 flake8 issues found.
- cmor: 10766 flake8 issues found.
- dat: 0 flake8 issues found.
- demo: 3396 flake8 issues found.
- distarray: 257 flake8 issues found.
- DV3D: 16964 flake8 issues found.
- eof_workbench: 87 flake8 issues found.
- esg: 555 flake8 issues found.
- genutil: 7897 flake8 issues found.
- globus: 24 flake8 issues found.
- gui_support: 122 flake8 issues found.
- help: 463 flake8 issues found.
- kinds: 129 flake8 issues found.
- lats: 885 flake8 issues found.
- ncml: 243 flake8 issues found.
- Properties: 194 flake8 issues found.
- psql: 22 flake8 issues found.
- pydebug: 2940 flake8 issues found.
- regrid2: 1802 flake8 issues found.
- reqm: 78 flake8 issues found.
- Thermo: 1459 flake8 issues found.
- unidata: 310 flake8 issues found.
- vcs: 107263 flake8 issues found.
- vcsaddons: 1646 flake8 issues found.
- vcs_legacy: 55394 flake8 issues found.
- visus: 14189 flake8 issues found.
- WK: 1333 flake8 issues found.
- xmgrace: 5509 flake8 issues found.

@doutriaux1 @chaosphere2112 @aashish24 Please review/merge as soon as possible so I can start pushing test PRs.

### CODE REVIEW

**Comment by doutriaux1** [comment]
@dlonie AutoAPI and vcs_legacy are gone as soon as you approve my PR :wink: 
Properties, browser,gui_support, kinds lats and ncml should be removed as well.
visus is not built (yet) 
reqm and eof_workbench I have no idea what that is....
help and demo should be moved out by @chaosphere2112 and put on tutorials (it is not built now)
globus and esg are used by the esgf team, not us

**Comment by dlonie** [comment]
So which should be tested? All of the others?

**Comment by aashish24** [comment]
@dlonie I think so.

**Comment by doutriaux1** [comment]
@dlonie yes all of the others. But again, submitting in multiple PR would be great so we can slowly merge them one at a time

**Comment by dlonie** [comment]
@doutriaux1 Cool. That's the plan -- once this PR is in I'll start setting up tests for the following modules:

- cdms2
- cdtime
- cdutil
- cmor
- dat
- distarray
- DV3D
- genutil
- psql
- pydebug
- regrid2
- Thermo
- unidata
- vcs
- vcsaddons
- WK
- xmgrace

**Comment by doutriaux1** [comment]
yep. I think dat is empty nowadays. No?

**Comment by dlonie** [comment]
That's why I'm asking what you want covered -- I don't know what any of these are.

**Comment by doutriaux1** [comment]
so yes that list but not dat there's no python in there anyway

**Comment by dlonie** [comment]
Ok, updated list.

**Comment by dlonie** [comment]
Anything holding up this PR?

**Comment by aashish24** [comment]
So I guess in this branch we are not using flake8 for testing. Is that correct?

**Comment by dlonie** [comment]
Correct -- this just sets up the superbuild, and then I'll add tests. I can't add them yet because then tests would start failing when this gets merged, and this needs to be merged so I can base the other PRs off of it.

**Comment by aashish24** [comment]
there seems to be some weird issue on test-laptop (I will check) but other than that it looks good to me.

**Comment by aashish24** [comment]
LGTM

**Comment by dlonie** [comment]
The failure looks related to fetching the flake8 file. Maybe the host was down?

**Comment by aashish24** [comment]
It is possible. I guess in the future, LLNL can host these sources as well.

**Comment by aashish24** [comment]
I think if that's the case, then we should merge this.

**Comment by aashish24** [comment]
@doutriaux1 can we delete other modules?

**Comment by durack1** [comment]
@dlonie @aashish24 the problem with fetching resources (flake8 above) and connecting to the dap server (issues dealing with timeouts during `cdms` opendap tests (see [here](https://open.cdash.org/testDetails.php?test=344170858&build=3855046), [here](https://open.cdash.org/testDetails.php?test=342344087&build=3844793) and [here](https://open.cdash.org/testDetails.php?test=342348597&build=3844806))) seems to indicate a flaky network connection on the `test-laptop` - is there a way to make this connection more robust? Or potentially trigger `CMake` to re-try failed downloads a number of times..?

**Comment by doutriaux1** [comment]
@aashish24 will address (someday) the remval of other modules as part of @durack1 PR #1341

**Comment by durack1** [comment]
@doutriaux1 and #1353!!

**Comment by dlonie** [comment]
Skipping cdtime, as it just has C code.

**Comment by dlonie** [comment]
`psql` too.

**Comment by dlonie** [comment]
All test PRs are in. I've edited my comment above to contain links to each module's PR.

**Comment by doutriaux1** [comment]
Thanks @dlonie ! Let the fun begin!

**Pull request merged**
