### PR TITLE
something bad happen 

### PR DESCRIPTION
**Pull request by doutriaux1**

### CODE REVIEW

**Comment by aashish24** [comment]
@doutriaux1 what this branch is about? Could you please add bit more description here?

**Comment by doutriaux1** [comment]
@aashish24 sorry @dnadeau4 and I found a major issue in 2.6 1hour before I go in vacation, we did emergency patching so 2.6 is ok (or at least same as 2.4) But essentially the pcmdi_metrics repo started to give out different numbers with the "pep8ed/flake8ed" cdms2. @dnadeau4 and I will investigate further this week or next. All is good. I pushed this as a safe guard.

**Comment by doutriaux1** [comment]
@danlipsa when I last ran tis branch against the PMP ( http://github.com/PCMDI/pcmdi_metrics.git ) test suite I had different results from the PMP. Which freaked us out here. Let me run the PMP test suite against this branch. Thanks.

**Comment by danlipsa** [comment]
@doutriaux1 many vcs tests failed as well with this branch. I think there is also a commit in master which affects the animate tests - which fail on the master branch.

**Comment by aashish24** [comment]
hey guys @doutriaux1 @danlipsa can we change the name of this PR :smile:. Also, I am little behind on this branch. Is this ready to be reviewed?

**Pull request closed without merging**
