### PR TITLE
Issue1539 durack1 update ipython3.0.0 to4.0.0

### PR DESCRIPTION
**Pull request by aashish24**

### CODE REVIEW

**Comment by aashish24** [comment]
@durack1 please review. 

@doutriaux1 the issue was related to race condition. If the python was built before PYEXPECT, it will build and no error shows up (on travis CI and some systems) but on some other systems,  if the Python was not built, you will get the error which you got.

**Comment by durack1** [comment]
@aashish24 `garant` is still complaining..

**Comment by aashish24** [comment]
@durack1 these are test failures. I wouldn't rely on garant as we are working on fixing buildbot issues. If you can test it manually that would be good. 

We will merge it post 2.4.1

**Comment by aashish24** [comment]
@doutriaux1 should we update this branch and merge it since we have release 2.4.1?

**Comment by doutriaux1** [comment]
this branch is irrelevant now that we are using conda, let's close it.

**Comment by durack1** [comment]
@doutriaux1 @aashish24 as we're still not completely dead using the old CMake install, how about this one last PR is updated (to the latest iPython by me) and then merged.. So if you reopen I will sort the update (along with dependencies in May) and then forget about it..?

**Pull request closed without merging**
