### PR TITLE
fix #1776

### LINKED ISSUE #1776: User specified axis to run vertical interpolation. myvar.getAxis(1).designateLevel()
Charles helped me with specifying the axis of input variables to get logLinearInterpolation function working.

Thanks,
Jill

### PR DESCRIPTION
**Pull request by doutriaux1**
let user pass an axis argument, rather than always picking z level, that allows for non cf use
also pep8ed the file

### CODE REVIEW

**Comment by doutriaux1** [comment]
@aashish24 @danlipsa @chaosphere2112 should be a quick one to review

**Comment by sankhesh** [comment]
**Buildbot dashboards**

[Gitlab](https://gitlab.kitware.com/UV-CDAT/uvcdat-mirror/merge_requests/2293#note_123681)

[CDash](https://open.cdash.org/index.php?compare1=63&filtercount=2&field1=buildname%2Fstring&project=UV-CDAT&field2=buildstarttime%2Fdate&showfilters=0&limit=100&compare2=83&value1=d0418738&showfeed=0)

**Comment by aashish24** [comment]
@doutriaux1 looks like some tests are failing.

**Comment by aashish24** [comment]
@sankhesh looks like crunchy still have issues.

**Comment by aashish24** [comment]
@sankhesh can you run buildbot again?

**Comment by sankhesh** [comment]
@aashish24 Its building. The CDash link above is still valid.

**Pull request merged**
