### PR TITLE
Do not wrap again in update_input

### LINKED ISSUE #1086: animation does not work on projected plots
```python
import cdms2,vcs,os

f=cdms2.open(os.path.join(vcs.sample_data,"clt.nc"))

print f.variables.keys()

ice = f("clt",latitude=(90,30))
print ice.shape

x=vcs.init()

gm = x.createisofill()

levs = vcs.mkscale(ice.min(),ice.max())
cols=vcs.getcolors(levs)

gm.levels= levs
gm.fillareacolors = cols
gm.projection="polar"
x.plot(ice,gm)

x.animate.create()

import time
time.sleep(1)
print "Creating"

x.animate.save("ice.mp4")

print x.close(preserve_pngs=True)
```

### PR DESCRIPTION
**Pull request by sankhesh**
This change fixes the issue wherein no output was being produced
when animating projected data. Each draw_frame call invokes
VTKPlots::update_input which in turn calls doWrap on the
actor. Trying to wrap projected data fails.

Fixes #1086

### CODE REVIEW

**Comment by sankhesh** [comment]
@doutriaux1 @aashish24 Please review

**Comment by aashish24** [comment]
@sankhesh this is great! Makes sense and LGTM :+1: Should we add a test for projected dataset animation as well?

**Comment by sankhesh** [comment]
Yup. I can add one.

**Comment by aashish24** [comment]
@sankhesh can add one soon so that we can make it done?

**Comment by aashish24** [comment]
@sankhesh we should really get this one in master asap. Can you please add test soon?

Thanks,

**Comment by sankhesh** [comment]
Baselines added in UV-CDAT/uvcdat-testdata#81

**Comment by sankhesh** [comment]
@doutriaux1 While adding the test for this issue, I found that meshfill plots with mercator projection fails. Documented here: #1671

**Comment by sankhesh** [comment]
Not sure why we have those test failures. They don't fail on my machine. 
@aashish24 @doutriaux1  Can you reproduce those failures?

**Comment by aashish24** [comment]
@sankhesh which machine you are seeing these failures?

**Comment by sankhesh** [comment]
annie, crunchy

**Comment by doutriaux1** [comment]
@sankhesh both annie and crunchy are running behind Xvfb. Can you try with Xvfb?

**Comment by aashish24** [comment]
@sankhesh any luck with testing?

**Comment by sankhesh** [comment]
@aashish24 I've pushed a new change to test only the last image of the animation as you suggested. Waiting on the dashboards to complete.

**Comment by aashish24** [comment]
thanks @sankhesh much appreciated!

**Pull request merged**
