### PR TITLE
2072 export vector patterns

### LINKED ISSUE #2072: export patterns / hatches as vectors for vector formats

### PR DESCRIPTION
**Pull request by sankhesh**
Fixes #2072 

Sample PDFs attached

[test_fillarea_list.pdf](https://github.com/UV-CDAT/uvcdat/files/523076/test_fillarea_list.pdf)

[test_fillarea.pdf](https://github.com/UV-CDAT/uvcdat/files/523077/test_fillarea.pdf)

### CODE REVIEW

**Comment by sankhesh** [comment]
@doutriaux1 @aashish24 @bonfils2

**Comment by doutriaux1** [comment]
@sankhesh there are conflicts

**Comment by doutriaux1** [comment]
@sankhesh I'll try it as is for now. Thanks.

**Comment by sankhesh** [comment]
Arf... Forgot to rebase onto the modularization changes. Will do it tomorrow.

**Comment by sankhesh** [comment]
@williams13 @doutriaux1 @aashish24 

Fixed the issue with the overlapping patterns.

See: 
[test_fillarea_list.pdf](https://github.com/UV-CDAT/uvcdat/files/526138/test_fillarea_list.pdf)
[test_fillarea.pdf](https://github.com/UV-CDAT/uvcdat/files/526139/test_fillarea.pdf)

**Comment by doutriaux1** [comment]
@sankhesh please rebase. Thanks.

**Comment by sankhesh** [comment]
@doutriaux1 Sure. Its not just a rebase since the whole repo has changed. I'll have to apply the changes as patches. Doing it now.

**Comment by doutriaux1** [comment]
sankhesh
in your branch
```
git subtree split -P Packages/vcs -b vcs-only
```
then
```
cd /git/vcs
git pull /pth/to/uvcdat vcs-only
```

**Comment by sankhesh** [comment]
@doutriaux1 Sorry forgot to update here.
Created an updated pull request here: UV-CDAT/vcs#23

I ended up using git format-patch. However, you subtree idea seems good as well.

**Pull request closed without merging**
