### PR TITLE
Setting the correct PYTHON_SITE_PACKAGES_PREFIX on Apple

### PR DESCRIPTION
**Pull request by jbeezley**
This will hopefully fix the latest Apple build failures.

### CODE REVIEW

**Comment by aashish24** [comment]
@jbeezley what version of Mac you tested this against?

**Comment by jbeezley** [comment]
I have 10.10, but it also fixes the travis build.  The problem it fixes should be independent of the OS version AFAIK.

**Comment by aashish24** [comment]
Interesting. Are you using 10.10 SDK? Or is it finding the 10.9 SDK (check you cache file please). Iwill be curious.

**Comment by jbeezley** [comment]
Well, both I guess.

```
$ grep SDK CMakeCache.txt 
CMAKE_OSX_SYSROOT:PATH=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk
CURL_INCLUDE_DIR:PATH=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/usr/include
LIBXML2_INCLUDE_DIR:PATH=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/usr/include/libxml2
LIBXSLT_INCLUDE_DIR:PATH=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/usr/include
READLINE_INCLUDE_DIR:PATH=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/usr/include/readline
UUID_INCLUDE_DIR:PATH=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/usr/include/uuid
ZLIB_INCLUDE_DIR:PATH=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/usr/include
FIND_PACKAGE_MESSAGE_DETAILS_LibXml2:INTERNAL=[/usr/lib/libxml2.dylib][/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/usr/include/libxml2][v2.9.0()]
FIND_PACKAGE_MESSAGE_DETAILS_LibXslt:INTERNAL=[/usr/lib/libxslt.dylib][/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/usr/include][v1.1.28()]
FIND_PACKAGE_MESSAGE_DETAILS_READLINE:INTERNAL=[/usr/lib/libreadline.dylib][/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/usr/include/readline][v()]
FIND_PACKAGE_MESSAGE_DETAILS_UUID:INTERNAL=[/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/usr/include/uuid][v()]
FIND_PACKAGE_MESSAGE_DETAILS_ZLIB:INTERNAL=[/usr/lib/libz.dylib][/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/usr/include][v1.2.5()]
```

**Comment by aashish24** [comment]
Makes sense. We don't have a pure 10.10 build. Other than that it looks good.

**Pull request merged**
