### PR TITLE
ENH: ratio=autot works for geographic projected datasets

### PR DESCRIPTION
**Pull request by danlipsa**
Baselines in: https://github.com/UV-CDAT/uvcdat-testdata/pull/118

### CODE REVIEW

**Comment by aashish24** [comment]
Work left to do: (from @danlipsa notes)
- axes names do not follow the data but stay next to the side of the window
- axes names overlap the data labels in certain cases
- ratio=autot does not work for meshfill linear projection
- in the interface you cannot switch ratio=autot on and off. It stays always on.

**Comment by doutriaux1** [comment]
@danlipsa that's neat, did you check that we can still long click a point and it returns the correct info?

**Comment by danlipsa** [comment]
@doutriaux1 I did not. I rely on the tests I added which pass.

**Comment by doutriaux1** [comment]
then we should be good.

**Comment by danlipsa** [comment]
@doutriaux1 @aashish24 Do you guys know anything about the diags_test_... tests? I think I picked those issues up from master. I did not have them with my changes on top of a5d3dd6f36453be9b2b26b7db26ae63a9af59b29.

**Comment by doutriaux1** [comment]
these are changing and it seems they keep getting overwritten. I'm going crazy over this, can we please not create any baselines uuntil after the release which should stabilize the metrics baselines. After the release I  plan on taking metrics tests out completely and move them to their own space.

**Comment by danlipsa** [comment]
@doutriaux1 Can we push stuff the existing baselines and trigger new builds? If that gets in your way I can wait until this is fixed. Let me know.

**Comment by doutriaux1** [comment]
@danlipsa I'm afraid you'll have to re-update the baselines after, not sure.

**Comment by danlipsa** [comment]
@doutriaux1 Thats fine. Let me know when master is fixed and I can rebase.

**Comment by danlipsa** [comment]
@jbeezley Is garant working? It's been working at the tests for a while.

**Comment by jbeezley** [comment]
I turned it off because it has been consistently failing for several weeks now due to network timeouts, and I don't have the time to fix it.  I just removed it as an expected status, so it should no longer show up.

**Comment by danlipsa** [comment]
@doutriaux1 @aashish24 Any update on the failing tests on master? diags_test_... and vcs_test_continents and vcs_read_old_scr_2 still fail there. Maybe we should remove the offending commit.

**Comment by danlipsa** [comment]
@doutriaux1 @aashish24 Do I merge this in or any of you want to merge it?

**Pull request merged**
