### PR TITLE
added a test for @aashish24

### PR DESCRIPTION
**Pull request by doutriaux1**
@aashish24 this adds a test that shows the leak.
if you turn bg=0 then you see less of a leak.
do not merge now, there's nothing to it.

### CODE REVIEW

**Comment by aashish24** [comment]
thanks @doutriaux1 do you see any VTK objects in the leak?

**Comment by doutriaux1** [comment]
no idea, we should run it through the runTest but not in this branch because the dv3d will just drawn them in the noise.

**Comment by aashish24** [comment]
Okay thanks. @dlonie how did you disable dv3d?

**Comment by dlonie** [comment]
Did you mean @doutriaux1?

**Comment by aashish24** [comment]
I meant @dlonie -:) When you were doing test on memory leaks, you were able to bypass dv3d module loading.

**Comment by dlonie** [comment]
IIRC, i just removed the import statements that imported either dv3d.py from the VCS module or the DV3D module (I don't think there were any of the latter, though).

Be warned that I'm still seeing a ton of circular references and bound methods leaking when anything more involved than `import vcs` is run, so there will still be a lot of noise, even without `dv3d`.

**Comment by doutriaux1** [comment]
@aashish24 this is somewhat urgent see: https://github.com/UV-CDAT/uvcdat/issues/1397

**Comment by doutriaux1** [comment]
@sankhesh @dlonie I think tis is different from the leaks @dlonie wants me to look at. Can one/both of you please take a look. Thanks,

**Comment by dlonie** [comment]
@doutriaux1 If you can reproduce this using pure VTK, I'll take a look, but working with VCS is beyond the current scope of my involvement in UV-CDAT.

Again, I'd suggest using tools like `objgraph` that let you track memory state and see what object are being created and not freed in between calls to `plot`. Given the number of memory issues we've had with VCS and that I've never heard of this happening with VTK before, I doubt the issue is on our end unless I see a script that reproduces this without VCS's additional layers clouding the waters.

**Comment by doutriaux1** [comment]
@aashish24 I will let you find someone at Kitware to take a look at this.

**Comment by aashish24** [comment]
@doutriaux1 did you try reproducing it in pure VTK?

**Comment by durack1** [comment]
@aashish24 it would be great to solve this issue for `2.4.0` any chance of that? It's a pretty nasty usability bug that keeps tripping me over..

**Comment by aashish24** [comment]
@durack1 look at the other thread on memory leak. Atleast we have a fix on vtk offscreen memory leaks now. We still have other memory leaks but I am hoping that we can start tracing those in near future as well.

**Pull request closed without merging**
