### PR TITLE
Issue 1763 lambert newer proj4

### PR DESCRIPTION
**Pull request by doutriaux1**

### CODE REVIEW

**Comment by doutriaux1** [comment]
@aashish24 @danlipsa sooo.... The new proj4 does not make any difference for our issue, but AEQD plots look much more like they should be looking like (default are just bad)... I tried both setting `over` all the time or not, it's the same on my mac, polar fails badly. The only think I can think of is that some parameter is initialized correctly on my Ubuntu but not on Mac. I will go through the aeqd projection parameters and try to figure out what the default values are on boty my mac and Linux. But it's probably at the C++ level... OR the proj4 C level.... Anyhow this branch has lambert test and lamber working it supersed the branch that I reverted. Once the bot have ran feel free to approve and merge this. Once this is done I will review and merge @danlipsa other branch. And then come back to our bug. @chaosphere2112 will tst this on his mac.

**Comment by aashish24** [comment]
@doutriaux1 let me talk to @danlipsa what he thinks.. will reply back.

**Comment by aashish24** [comment]
@doutriaux1 annie is failing.

**Comment by doutriaux1** [comment]
@aashish24 intersting proj4 is NOT failing on one mac but not the others... I think the one that pass (like my mac here) has XCode 7...

**Comment by doutriaux1** [comment]
interesting, but mac and annie fail for the same reason! But both OS pass... Could it be an order thing? Or a compiler?

**Comment by doutriaux1** [comment]
ok an annie automake was missing

**Comment by doutriaux1** [comment]
@chaosphere2112 can you please add it to list of package rquired?

**Comment by doutriaux1** [comment]
ok i'm at loss mac full and mac nogui are supposedly the exact same hardwrae/os...

**Comment by doutriaux1** [comment]
my mac log does say that missing was too old but did go on... 
```
configure:2452: result: yes
configure:2490: WARNING: 'missing' script is too old or missing
configure:2603: checking for a thread-safe mkdir -p
```

**Comment by chaosphere2112** [comment]
@doutriaux1 Sure, I'll add automake. I'm running tests right now on my computer, but (spoiler alert) I passed the -3 tests.

**Comment by doutriaux1** [comment]
mac full
```
doutriaux1@macbot2:[uvbot]:[master]:[152]> xcodebuild -version
Xcode 6.4
Build version 6E35b
doutriaux1@macbot2:[uvbot]:[master]:[152]> clang --version
Apple LLVM version 6.1.0 (clang-602.0.53) (based on LLVM 3.6.0svn)
Target: x86_64-apple-darwin14.5.0
Thread model: posix
```
mac nogui
```
doutriaux1@macbot1:[uvbot]:[master]:[236]> xcodebuild -version
Xcode 6.4
Build version 6E35b
doutriaux1@macbot1:[uvbot]:[master]:[236]> clang --version
Apple LLVM version 6.1.0 (clang-602.0.53) (based on LLVM 3.6.0svn)
Target: x86_64-apple-darwin14.5.0
Thread model: posix
```

**Comment by danlipsa** [comment]
Do we want to require automake for building uvcdat? This is a new requirement. To integrate the new proj4 into VTK we'll have to make it work with cmake only.

**Comment by doutriaux1** [comment]
seems like that's why annie failed. don't know why mac work though, they never had automake...

**Comment by chaosphere2112** [comment]
https://open.cdash.org/viewTest.php?onlyfailed&buildid=4181939

**Comment by doutriaux1** [comment]
I'm at loss maybe we just forget about upgrading proj4 for now... and simply merge the original lambert branch it seems safer. I will reopen the PR and revert the changes I made in it to pick the prj4 vtk. What do you think?

**Comment by danlipsa** [comment]
I agree we should not upgrade proj4 now, before the release. We should definitely look into it after the release. Our proj4 was not updated in over 10 years. While I think most proj4 changes will be positive we might run into some issues as well. I think the initial testing you guys did looks promising though.

**Comment by aashish24** [comment]
@danlipsa @doutriaux1 yeah...lets update the proj4 post 2.4 also that will give us time to look into the new library some more.

**Comment by aashish24** [comment]
@doutriaux1 I am closing this pull request based on my understanding here.

**Comment by doutriaux1** [comment]
yes the issue does not seem to be proj4 the commit that introduced the bug is: 0552f7a so now we know, let's figure out what went in this commit....

**Pull request closed without merging**
