### PR TITLE
Export all graphics (including patterns) as vectors

### LINKED ISSUE #2072: export patterns / hatches as vectors for vector formats

### PR DESCRIPTION
**Pull request by sankhesh**
Fixes #2072

### CODE REVIEW

**Comment by sankhesh** [comment]
Do: test

**Comment by aashish24** [comment]
@sankhesh any progress with autotrace? I looked into the inkscape and the results were very good. Let's talk about it today.

**Comment by sankhesh** [comment]
@aashish24 Sure. The only obstacle is hinted and anti-aliased text now. 
That should be done in VTK with libfreetype.

**Comment by aashish24** [comment]
Just wanted ot update everyone that we are looking for an alternate solution that will minimize the file size but it will require some work to create the patterns as geometry in the first place. More update on this soon.

**Comment by aashish24** [comment]
@sankhesh I am going to close this PR as we are likely to follow the geometry path all the way.

**Comment by doutriaux1** [comment]
@aashish24 actually I think it's the way to go @chaosphere2112 was actually suggesting that we should pass fillarea object as patterns. That would be awesome.

**Pull request closed without merging**
