### PR TITLE
Issue png size updated

### PR DESCRIPTION
**Pull request by aashish24**

### CODE REVIEW

**Comment by doutriaux1** [comment]
@aashish24 why did you rerun with master in? The bots do that for us automatically.

**Comment by aashish24** [comment]
@doutriaux1 looks like build is broken on garant @jbeezley is this new?

**Comment by aashish24** [comment]
@doutriaux1 so that we can see the diffs clearly. Please see our conversation (Sam, Deanue, and myself on the last PR).

**Comment by jbeezley** [comment]
I haven't seen that particular error before, but it could be related to the Cython build race condition we've seen in the past.  I retriggered the build just in case.

**Comment by aashish24** [comment]
@doutriaux1 please avoid commits like: 

| ok this time should have everything going

Can you squash your commits?

**Comment by doutriaux1** [comment]
@aashish24 sure...

**Comment by doutriaux1** [comment]
@aashish24 will let the bot run. And will merge in the morning. Not sure it was worth holding the RC tag but it's done now.

**Pull request merged**
