### PR TITLE
Issue1070 durack1 update pyspharm

### PR DESCRIPTION
**Pull request by durack1**
@doutriaux1 take a look at this in response to #1070 and also convert the magic bit to build under `ALL`

### CODE REVIEW

**Comment by durack1** [comment]
@doutriaux1 it seems like this is being prompted to build:
`[INFO] These are the packages that we will try to build: basemap;CDAT;CURL;Cython;FFMPEG;g2clib;gdal;GEOS;gui_support;h5py;HDF5;ZMQ;pyzmq;tornado;IPYTHON;jasper;jpeg;LAPACK;lepl;libcf;Matplotlib;SIX;DATEUTILS;PYPARSING;Mpi4py;PYOPENSSL;setuptools;MyProxyClient;NetCDF;NetCDFPLUS;Numexpr;NUMPY;MPI;OSMesa;Python;VTK;pkgconfig;png;**pyspharm**;PyTables;readline;R;scikits;SCIPY;pip;Shapely;pygments;markupsafe;jinja2;docutils;Sphinx;freetype;zlib;libXML2;libXSLT;png;pixman;fontconfig;tiff;Curses;CMOR;udunits2;uuid;UVCMETRICS;vistrails;YASM;PYLIBXML2;CDATLogger;pyclimate;scientificpython;windspharm;eof2;eofs;windfield`

**Comment by doutriaux1** [comment]
@durack1 you need to make them dependent on python at least

**Comment by doutriaux1** [comment]
pyspharm needs spherepack... I remember now.

**Comment by durack1** [comment]
Seems like alot of these things need tweaks: 
https://github.com/UV-CDAT/uvcdat/blob/master/CMake/cdat_modules/pyspharm_deps.cmake

**Comment by durack1** [comment]
@doutriaux1 the sources (apart from spherepack) are in place but I'm unfamiliar about the install so handing this over to you..

**Comment by durack1** [comment]
@doutriaux1 want to label this a 2.3 milestone?

**Comment by doutriaux1** [comment]
btw the issue was already labeled as 2.3 so we were good.

**Comment by durack1** [comment]
@doutriaux1 just to get this one done and dusted, `spherepack3.2.tar` is now uploaded and ready to be sourced from `$LLNL_URL`

Do you need any other help with this?

`pyspharm 1.0.8` is still the current version

**Comment by durack1** [comment]
Closing as this PR - it's replaced with a rebased update #1444

**Pull request closed without merging**
