### PR TITLE
Vcs fix geometry instantiation

### PR DESCRIPTION
**Pull request by aashish24**

### CODE REVIEW

**Comment by aashish24** [comment]
Now: 
```
In [2]: import vcs

In [3]: x = vcs.init()

In [4]: x.geometry()

In [5]: x.geometry(100, 100)

In [6]: x.open()

In [7]: x.geometry(200, 100)

In [8]: x.geometry(200, 100)

In [9]: x.close()

In [10]: x.geometry()
Out[10]: {'height': 100, 'width': 200}
```

**Comment by aashish24** [comment]
@doutriaux1 @danlipsa this is ready for review as well. Just look at the last 2-3 commits (rest came from the other branch for testing).

**Comment by aashish24** [comment]
Do: test

**Comment by aashish24** [comment]
Do: test

**Comment by danlipsa** [comment]
@aashish24 LGTM.

**Pull request merged**
