### PR TITLE
Fixed resizing issue and added two tests to cover it

### LINKED ISSUE #1241: Resizing window in interact mode moves button labels
Looks like I broke some of my auto-positioning logic for text labels. I'll fix this right now.

### PR DESCRIPTION
**Pull request by chaosphere2112**
This fixes #1241 (I forgot to add the new `actor_renderer` to the show/hide gui commands, which made my labels get removed from the render window on resize events). The tests cover resizing in VCS as well as pure VTK; helped me narrow down the cause.

@aashish24 are we submitting PRs against release or master?

### CODE REVIEW

**Comment by chaosphere2112** [comment]
Testdata branch: UV-CDAT/uvcdat-testdata#41

**Comment by aashish24** [comment]
against release would be idea :+1: which you did, thanks,

**Comment by doutriaux1** [comment]
missing file?
```
test 318
    Start 318: vcs_test_configurator_resize

318: Test command: /lgm/uvcdat/2.2.0-rc1/bin/python "/git/uvcdat/testing/vcs/test_vcs_configurator_resize.py" "/home/doutriaux1/build/uvcdat-testdata/baselines/vcs/test_vcs_configurator_resize.png"
318: Test timeout computed to be: 1500
318: /lgm/uvcdat/2.2.0-rc1/bin/python: can't open file '/git/uvcdat/testing/vcs/test_vcs_configurator_resize.py': [Errno 2] No such file or directory
1/1 Test #318: vcs_test_configurator_resize .....***Failed    0.02 sec

0% tests passed, 1 tests failed out of 1

Total Test time (real) =   0.07 sec
```

**Comment by chaosphere2112** [comment]
@doutriaux1 looks like! I'll add it when I get in tomorrow.

**Comment by chaosphere2112** [comment]
@doutriaux1 @aashish24 
Alright, added the missing test. Should I merge from release to resolve the conflict?

https://open.cdash.org/testSummary.php?project=44&name=vcs_test_configurator_resize&date=2015-05-01

**Comment by doutriaux1** [comment]
@chaosphere2112 yes please merge from release, I'll run test and merge it in. Then I will build on rhea.

**Comment by chaosphere2112** [comment]
@doutriaux1 Merged and tested, works for me.

**Comment by doutriaux1** [comment]
@chaosphere2112 ok running it on my ubuntu and merging in if ok.

**Comment by doutriaux1** [comment]
works for me

**Pull request merged**
