### PR TITLE
Fixed the ordering of images for regression testing

### PR DESCRIPTION
**Pull request by aashish24**
So that the cdash will show them correctly in the right
order

@jbeezley @doutriaux1 @ThomasMaxwell  please review

### CODE REVIEW

**Comment by doutriaux1** [comment]
Thanks!

**Comment by jbeezley** [comment]
That caused the error to go away completely when it should have just switched the images in cdash.  This [line](https://github.com/UV-CDAT/uvcdat/blob/be51764d9d410e114ee6011b59338946fad925ee/testing/dv3d/TestManager.py#L142) makes me very suspicious.  I think an `IOError` is raised in the try block somewhere causing the test to return successfully when it should actually fail.  If there really is a reason to do this, the condition should probably be more narrowly defined.

**Comment by doutriaux1** [comment]
what are you saying @jbeezley ? You don't like "magic"? 
More seriously should we worry about this now, or open a new issue for 2.3? I'll leave it up to you.

**Comment by jbeezley** [comment]
I would say leave it for 2.3 and go over all of the tests to make sure failures are reported correctly (as in #1015).

**Comment by aashish24** [comment]
@jbeezley agree with you. it should have ret = (anything but 0). I will push a branch post 2.2 release.

**Pull request merged**
