### PR TITLE
Issue 1312 tag repos

### PR DESCRIPTION
**Pull request by doutriaux1**
@aashish24 @dlonie @chaosphere2112 please review

### CODE REVIEW

**Comment by aashish24** [comment]
@doutriaux1 we would have -s ours when we bring this change to master.

**Comment by aashish24** [comment]
Cloning into 'VTK'...
error: pathspec 'uvcdat-2.2.0' did not match any file(s) known to git.
CMake Error at /home/buildbot/buildbot/uvcdat-garant-linux-release/build/VTK-prefix/tmp/VTK-gitclone.cmake:28 (message):
  Failed to checkout tag: 'uvcdat-2.2.0'

**Comment by doutriaux1** [comment]
you merged it in before I applied the tag I think, can you try again, the tag should be on VTK since last night

**Comment by aashish24** [comment]
I didn't. The error is from buildbot machines. When you pushed a branch buildbot slaves ran the build.

**Comment by jbeezley** [comment]
I reset the builds.  Buildbot will start a build every time you push a change even if there isn't a PR for it yet.

**Comment by doutriaux1** [comment]
I see. Well we're good now, the tags are in place. Can we restart the test?

**Comment by jbeezley** [comment]
I already did.  [Here](https://open.cdash.org/index.php?compare1=65&filtercount=2&field1=buildname%2Fstring&project=UV-CDAT&field2=buildstarttime%2Fdate&showfilters=0&limit=100&compare2=83&value1=cce69050-build274-uvcdat-garant-linux-release&showfeed=0&display=project&value2=No) is one of the results.

**Comment by doutriaux1** [comment]
oh god... Looks like the tag point for VTK is wrong, let me double check, I might have tagged master rather than uvcdat-master.... Doh!

**Comment by doutriaux1** [comment]
@jbeezley how to do you restart the buildbot? I moved the tag point.

**Comment by jbeezley** [comment]
You have to be connected to our local network for the moment.  I think we are working on exposing the buildbot interface, but for now just ping me.

**Comment by aashish24** [comment]
yup, I am talking to the sys admins here to see if we can expose it to LLNL or allow @doutriaux1 to login to that machine somehow.

**Comment by doutriaux1** [comment]
@jbeezley or @aashish24 can you restart it then for this time, the tag on VTK is correct now.

**Comment by jbeezley** [comment]
I did, they are in the queue.  Patience, «petit scarabée».

**Comment by doutriaux1** [comment]
I loved that show! And I definitely need to learn the mysterious ways of the path to patience....

**Comment by aashish24** [comment]
For some reason garant has lot more tests failing. @jbeezley do you know why?

**Comment by jbeezley** [comment]
Looks like the [baselines](https://github.com/UV-CDAT/uvcdat-testdata/commit/8a4dd6921c28fbd49d326f2a25fc13fe6cc5f037) were updated.  It isn't just this branch, the current master is [failing](https://open.cdash.org/viewTest.php?onlyfailed&buildid=3817988) as well.

**Comment by aashish24** [comment]
@doutriaux1 we still need to merge this branch right?

**Comment by durack1** [comment]
@doutriaux1 @aashish24 it seems [2.2.0rc1](https://zenodo.org/record/17412) is what has been issued the DOI at zenodo and not 2.2.0.. 

It might be good to get the additional tweaks into master and then move the 2.2.0 tag point?

**Comment by durack1** [comment]
@doutriaux1 @aashish24 it seems that the correct 2.2.0 zenodo DOI is [10.5281/zenodo.13976](https://zenodo.org/record/17633) - I'll update in PR #1334

**Comment by doutriaux1** [comment]
can't believe i didn't notice @aashish24 did merge this one in master not release before tagging.... Well merging now...

**Comment by aashish24** [comment]
@doutriaux1 I didn't merge this one. In face this branch should go last in release.

**Comment by aashish24** [comment]
338ff31 Merge pull request #1328 from UV-CDAT/issue1212_durack1_Spyder2
5590d67 Merge pull request #1334 from UV-CDAT/issue1312_durack1_ReadmeU
b9508a5 Merge pull request #1322 from UV-CDAT/sync_release
10cf953 Merge branch 'newdiagtesCharles'
68abd0d Merge remote-tracking branch 'origin/release' into sync_release
87b49e2 Merge pull request #1253 from UV-CDAT/pyopenssl-0.14
3ab2222 Merge pull request #1303 from UV-CDAT/add_pep8_master
91e9f3b Merge pull request #1318 from UV-CDAT/issue_1308_isofill_unprop
f0ea001 Merge pull request #1320 from UV-CDAT/issue_1319_match_osx_toSD
b70346c Merge pull request #1291 from UV-CDAT/issue_1274_import_missing
3f99c8e Merge pull request #1316 from UV-CDAT/buildbot-passing
66bab1b Merge pull request #1307 from UV-CDAT/fix_vcs3d_test_image_orde
b14e373 Merge pull request #1296 from UV-CDAT/sync_master
d28dc1d Merge pull request #1298 from UV-CDAT/fix-libcf-build
8a9b545 Merge pull request #1267 from UV-CDAT/issue_903_turn_off_paravi
538cf4b Merge pull request #1229 from dlonie/vtk-refactor
94f63d6 Merge pull request #1287 from UV-CDAT/vcs3D_fix_dv3d_list
5d7882e Merge pull request #1273 from chaosphere2112/toolbar_layout_fix
3850d33 Merge pull request #1242 from chaosphere2112/text_resizing_wind
3650d29 Merged master

**Comment by doutriaux1** [comment]
yes but you merged in into master where it didn't really need to go. Then I thought you merged it in release and TAGGED release assuming it was in....

**Comment by durack1** [comment]
@aashish24 pedantic point, but your info contained in the README.md for https://github.com/UV-CDAT/uvcdat/tree/2.2.0 is out of sync with the tag..

**Pull request merged**
