### PR TITLE
Fix list method

### LINKED ISSUE #1285: dv3d list broken
```
In [1]: dsc=x.create3d_scalar()

In [2]: dsc.list()
 ---------- DV3D (Gfdv3d) member (attribute) listings ---------
name = __3d_scalar_642267851670046
axes = xyz
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-2-b9c9df306f2c> in <module>()
----> 1 dsc.list()

/lgm/uvcdat/2.2.0/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/vcs/dv3d.pyc in list(self)
    185         print 'axes =',self.axes
    186         for pname in self.parameter_names:
--> 187             print ' = '.join( [ pname, self.getParameter( pname ) ] )
    188 
    189 class Gf3Dvector(Gfdv3d):

TypeError: sequence item 1: expected string, NoneType found

```

### PR DESCRIPTION
**Pull request by ThomasMaxwell**
Fixes  #1285 .

### CODE REVIEW

**Comment by doutriaux1** [comment]
@ThomasMaxwell what about setting the default values to not None? Is that ok they are None?

**Comment by ThomasMaxwell** [comment]
They are supposed to be None.   Setting then to non-None overrides the default value.

**Comment by ThomasMaxwell** [comment]
Vcs3D assumes that default values might be computed as a function of the input dataset (e.g. vertical scaling as a function of the number of levels in the dataset), therefore they are not hard coded in the graphics method.   Anything specified in the graphics method overrides the default value.

From: <Maxwell>, "Maxwell, Thomas P. (GSFC-606.2)[SCIENCE APPLICATIONS INTL CORP]" <thomas.maxwell@nasa.gov<mailto:thomas.maxwell@nasa.gov>>
Date: Wednesday, May 6, 2015 at 2:06 PM
To: UV-CDAT/uvcdat <reply@reply.github.com<mailto:reply@reply.github.com>>
Subject: Re: [uvcdat] Fix list method (#1287)

They are supposed to be None.   Setting then to non-None overrides the default value.

**Comment by doutriaux1** [comment]
makes sense. thanks.

**Pull request merged**
