### PR TITLE
need to pass -b to build cdat_info out of source

### PR DESCRIPTION
**Pull request by doutriaux1**
@danlipsa  @chaosphere2112 please review.

@danlipsa you can inspire yourself (and improve) to do al the out of source building

### CODE REVIEW

**Comment by danlipsa** [comment]
@doutriaux1 I don't see the text version of cdat_info.py.in deleted from build.sh

**Comment by doutriaux1** [comment]
@danlipsa I forgot to push it the first time it should be in now

**Comment by sankhesh** [comment]
Do: check

**Comment by sankhesh** [comment]
Do: test

**Comment by danlipsa** [comment]
@doutriaux1 I still cannot see the deleted python source in the commit.

**Comment by doutriaux1** [comment]
@danlipsa what is the issue here?

**Comment by danlipsa** [comment]
@doutriaux1 The source for cdat_info.py.in was originally included in build.sh and should be deleted from there, isn't it?

**Comment by doutriaux1** [comment]
@danlipsa yes once we merged that in I will need to update the conda_recipes repo to yank from there.

**Comment by danlipsa** [comment]
@doutriaux1 I see. I was looking for that in here. LGTM :+1:

**Pull request merged**
