### PR TITLE
Enforce CMake minimum version 2.8.12

### LINKED ISSUE #1751: openssl cmake error on RHEA
```
Could not detect matplotlib, /lustre/atlas/world-shared/cli900/sw/rhea/uvcdat/2016-01-04brian_testbed/bin/python
CMake Error at CMake/cdat_modules/openssl_pkg.cmake:6 (get_filename_component):
  get_filename_component unknown component DIRECTORY
Call Stack (most recent call first):
  CMakeLists.txt:482 (include)
```

### PR DESCRIPTION
**Pull request by sankhesh**
Fixes #1751

### CODE REVIEW

**Comment by sankhesh** [comment]
@doutriaux1 @jbeezley Please review

**Comment by doutriaux1** [comment]
Is it only to fix the issue with the message telling us where openssl is? I'd rather not we have a lot of RH6 system where this change will force them to upgrade to their cmake making the build seem even more painful. It tested on RH6 by commenting out this message and it's all good and happy, wouldn't it be better to simply remove the `DIRECTORY` directive in the message [here](https://github.com/UV-CDAT/uvcdat/blob/master/CMake/cdat_modules/openssl_pkg.cmake#L5-L11) ?

**Comment by sankhesh** [comment]
Do: test

**Comment by sankhesh** [comment]
Do: test

**Comment by sankhesh** [comment]
Do: test

**Pull request merged**
