### PR TITLE
Basemap build

### PR DESCRIPTION
**Pull request by sankhesh**
#1406 #1458

### CODE REVIEW

**Comment by sankhesh** [comment]
@aashish24 @doutriaux1 
Please review

**Comment by doutriaux1** [comment]
@sankhesh can you please look into the pyside/qt5 error? We are using Qt4.

**Comment by doutriaux1** [comment]
@sankhesh still tries to grap PySide

**Comment by doutriaux1** [comment]
@chaosphere2112 where are we with converstion to PySide vs PyQt? Might not be worth fixing this if you are close.

**Comment by chaosphere2112** [comment]
@doutriaux1 A ways out still; hoping to have a barebones version in the next month and half, and flesh it out from there.

**Comment by sankhesh** [comment]
@doutriaux1 

I don't think this issue is related to qt.. I spoke to Aashish and for now, I am going to change the matplotlib backend to the default one instead of PySide/PyQt.

**Comment by doutriaux1** [comment]
@sankhesh what is the "default" one?

**Comment by sankhesh** [comment]
[Anti Grain Geometry (Agg)] (http://matplotlib.org/faq/usage_faq.html#what-is-a-backend)

**Comment by doutriaux1** [comment]
Seems like it only does backgrond-like mode. PNG only. We need some sort of viz on screen directly.

It used to work perfectly what changed?

C.

**Comment by sankhesh** [comment]
@doutriaux1 

The issue crops up only on the buildbot machine. Buildbot turns off CDAT_BUILD_GUI that in turn disables building of PyQt and SIP. Since matplotlib expects PyQt and doesn't find it, it looks for PySide. But that fails as well and matplotlib only reports a partial error. I'll try adding some logic to the matplotlibrc to switch to Agg backend if CDAT_BUILD_GUI is OFF.

**Comment by doutriaux1** [comment]
Oh ok! Then it totally makes sense. Ok can you please tweak the build then to use Agg if GUI is OFF?

Thanks.

**Comment by sankhesh** [comment]
@doutriaux1 

This branch is ready to be merged. The test failure is because the testdata was updated in a different branch. It should be fixed when this branch is merged.

**Comment by doutriaux1** [comment]
passes! Yeah! https://open.cdash.org/viewTest.php?onlyfailed&buildid=3937013

**Pull request merged**
