### PR TITLE
respects png sizes

### LINKED ISSUE #1588: x.png(outFileName, width=XX, height=XX) doesn't resize output file
At the commandline:
```python
x.png(outFileName,width=850,height=654) ;
```
Appears to write a `*.png` file correctly, however it should yield an output file that is 850x654 pixels, however this yields a file with dimensions 814x629

### PR DESCRIPTION
**Pull request by doutriaux1**
fix #1588

### CODE REVIEW

**Comment by doutriaux1** [comment]
@aashish24 pretty cool how I broke the entire baseline. :wink:

**Comment by doutriaux1** [comment]
@aashish24 @chaosphere2112 please review

**Comment by chaosphere2112** [comment]
@doutriaux1 Are there multiple PRs in here? That seems like a weird amount of stuff to size PNGs (plus commits in CDMS?)

**Comment by aashish24** [comment]
@doutriaux1 I am confused as well..

**Comment by durack1** [comment]
@chaosphere2112 @aashish24 @doutriaux1 looks like it's pulled in some commits from #1601 - which are now in master..

**Comment by dnadeau4** [comment]
As @durack1:  merge of branch 'master' into issue_png_size caused the confusion between issues.  Can @chaosphere2112 @aashish24  review the part that has not thing to do with parallel?  The #1601 has been merged already.

**Comment by aashish24** [comment]
@dnadeau4 I updated this branch with latest master https://github.com/UV-CDAT/uvcdat/pull/1604

**Pull request closed without merging**
