### PR TITLE
cleaned up lean mode build and test suite

### LINKED ISSUE #1575: Fix test suite for LEAN mode
Some tests are run in LEAN mode that requires bits that are not built.
See https://open.cdash.org/viewTest.php?onlyfailed&buildid=4038079

### PR DESCRIPTION
**Pull request by doutriaux1**
fix #1575

### CODE REVIEW

**Comment by doutriaux1** [comment]
@sankhesh @aashish24 @dnadeau4 please review and merge

**Comment by doutriaux1** [comment]
@aashish24 @sankhesh @dnadeau4 should be good to merge

**Comment by aashish24** [comment]
LGTM :+1: should we add a buildbot for leanmode?

**Comment by durack1** [comment]
@doutriaux1 the `pcmdi10.llnl.gov - redhat7.1` machine is available and could be configured for `LEAN`..

**Comment by doutriaux1** [comment]
@aashish24 we already have one that's how I saw that it doesn't work, see: https://github.com/UV-CDAT/uvcdat/pull/1578/commits#

**Comment by doutriaux1** [comment]
@aashish24 this is what we have:
``` 
cont-int/LLNL/Linux-annie Ubuntu 15.04 (FULL/MESA) 
cont-int/LLNL/Darwin-Mac 10.10.5 (LEAN) 
cont-int/LLNL/Darwin-Mac1 10.10.5 (NOGUI) 
cont-int/LLNL/Darwin-Mac2 10.10.5 (FULL)
cont-int/LLNL/Linux-crunchy RH6 (FULL) 
cont-int/LLNL/Linux-oceanonly RH6 (MESA/NOGUI) 
```

**Comment by aashish24** [comment]
Cool!.. @doutriaux1 thanks. Should we document it somewhere?

**Comment by doutriaux1** [comment]
Hum... I don't know I guess it builds the user confidence to know it's systematically tested. @chaosphere2112 @mattben where do you think we should put this information?

**Comment by chaosphere2112** [comment]
@doutriaux1 That looks like the kind of information that would work nicely on the wiki, since it'll probably get updated over time.

**Pull request merged**
