### PR TITLE
Newdiagstes charles

### PR DESCRIPTION
**Pull request by doutriaux1**

### CODE REVIEW

**Comment by doutriaux1** [comment]
goes with: https://github.com/UV-CDAT/uvcmetrics/pull/114 and https://github.com/UV-CDAT/uvcdat-testdata/pull/39

**Comment by doutriaux1** [comment]
@aashish24 @painter1 should get tests passing, difficult ones have been commented out for this release

@painter1 don't forget to move tag point for metrics once this is in

**Comment by aashish24** [comment]
I am looking into it now.

**Comment by aashish24** [comment]
@doutriaux1 please avoid appending names to the branches :smile:

**Comment by aashish24** [comment]
1/5 Test  #60: vcs_test_dump_taylordiagram ......   Passed    0.84 sec
    Start 388: diags_test_01
2/5 Test #388: diags_test_01 ....................***Failed    0.91 sec
    Start 389: diags_test_03
3/5 Test #389: diags_test_03 ....................   Passed    3.90 sec
    Start 390: diags_test_04
4/5 Test #390: diags_test_04 ....................   Passed    3.43 sec
    Start 391: diags_test_41
5/5 Test #391: diags_test_41 ....................   Passed    3.27 sec

80% tests passed, 1 tests failed out of 5

**Comment by aashish24** [comment]
Hey  all, one test is failing but this is an improvement so I am going ahead and merging.

**Comment by doutriaux1** [comment]
@aashish24 agreed on branch names but in the interest of both time and babysitting non-git experts that's what we came up with :wink:

**Comment by aashish24** [comment]
@doutriaux1 that's fine but I don't think naming a branch should take more than 5 minutes right? I am not picking on anyone but just wanted to make sure that I point out these kinds of things to ensure best practices. Please do the same to me because sometimes I do the same as well.

**Comment by doutriaux1** [comment]
@aashish24 ok. But I actually don't have 5 mn! 30sec is the most I can spend on naming a branch!

**Pull request merged**
