### PR TITLE
Update Numpy to 1.10.4 & Numexpr to 2.4.6

### PR DESCRIPTION
**Pull request by dnadeau4**
Add numpy.1.10.1.tar.gz to the LLNL repository.
Add numexpr-2.4.4.tar.gz to the LLNL repository.

### CODE REVIEW

**Comment by aashish24** [comment]
@dnadeau4 do we want this for 2.4?

**Comment by dnadeau4** [comment]
I tried to have this for 2.4, but numexpr was failing and they are still some test that seem to be failing.   2.4 is already out so it's kind of too late.    If we have a point release 2.4.1 it should go in...

**Comment by durack1** [comment]
fix #885

**Comment by durack1** [comment]
@dnadeau4 does this just work with `cdms2`? From memory the `numpy 1.9.0` managed to sneak under the radar and just worked, whereas with `1.9.1` enough had changed to cause problems with `NaN` values and other things - see commentary in #885

**Comment by dnadeau4** [comment]
I think the NaN was fixed in 2.4 by @doutriaux.   I tried to resubmit 
the job to see if it passed, but "cdash" connection failed and most of 
errors seems to be related to "vcs".    The new Numpy seems to have 
"fixed" some label problem.  I think we lost the informationin "cdash"

https://open.cdash.org/index.php?compare1=65&filtercount=2&field1=buildname%2Fstring&project=UV-CDAT&field2=buildstarttime%2Fdate&value1=macbot2.llnl.gov9982-3ed50daa58f7e559ccc1f93071f640a4bf586cba

**Comment by durack1** [comment]
@dnadeau4 @doutriaux1 it looks like `numpy 1.10.1` still has a ?few? regression that they're [trying to iron out](https://github.com/numpy/numpy/issues?q=is%3Aopen+is%3Aissue+milestone%3A%221.10.2+release%22) so it might pay for this to settle before baking a new `numpy` into UV-CDAT..

**Comment by durack1** [comment]
@doutriaux1 can you point @dnadeau4 to the post where you had tested `numpy 1.9.1` and the `mean` function was causing problems.. I can't seem to find the thread..

**Comment by durack1** [comment]
@dnadeau4 I'm also not sure that the test coverage for `cdms2` is thorough enough to trigger errors in the build tests.. I think I need to provide you with a bunch of examples that can be incorporated into a through test suite to ensure that changes don't cause weird behaviors and changes to results that we don't know about.. I'm sure @doutriaux1 will have an opinion on this?

**Comment by doutriaux1** [comment]
@dnadeau4 the vcs failure are triggered by the change in numpy, because they pass on master.

**Comment by dnadeau4** [comment]
@durack1  Can we work out some more cdms2 too with "cdms2.transientVariable.mean()" and other that you might have in mind?  We can use the "clt.nc" file for our tests.

**Comment by durack1** [comment]
@dnadeau4 sure, is the simple example at https://github.com/UV-CDAT/uvcdat/pull/915 suitable to get started?

**Comment by dnadeau4** [comment]
I was investigating some test failure last Friday and found test_no_extra_elements.py in vcs was failing with the following message.

* AttributeError: 'numpy.ndarray' object has no attribute '_mask'
the test that is failing is:
* x.plot(data, "default", "1d", bg=0)

Not sure why this masked_array is different then the other yet.

**Comment by dnadeau4** [comment]
Found a conflict between tvariable.copy() and numpy.ma.copy().    I created  a new wrapper, and I am testing.  I have 50 tests failing, some in vcs due to labelling.  Not sure if the failed tests are related to numpy.

**Comment by dnadeau4** [comment]
List of failed tests with numpy 1.10
	 
52 - vcs_test_antialiasing (Failed)
	166 - vcs_test_basic_boxfill_zero (Failed)
	169 - vcs_test_basic_isofill_zero (Failed)
	172 - vcs_test_basic_isoline_zero (Failed)
	175 - vcs_test_basic_vector_zero (Failed)
	178 - vcs_test_basic_meshfill_zero (Failed)
	181 - vcs_test_basic_yxvsx_zero (Failed)
	184 - vcs_test_basic_xvsy_zero (Failed)
	187 - vcs_test_basic_xyvsy_zero (Failed)
	190 - vcs_test_basic_1d_zero (Failed)
	193 - vcs_test_basic_scatter_zero (Failed)
	221 - vcs_test_basic_boxfill_aeqd_proj_NH (Failed)
	251 - vcs_test_basic_isofill_aeqd_proj_NH (Failed)
	281 - vcs_test_basic_isoline_aeqd_proj_NH (Failed)
	342 - vcs_test_boxfill_lev1_lev2_ta_missing (Failed)
	350 - vcs_test_animate_isoline_colored (Failed)
	351 - vcs_test_animate_isoline_text_labels (Failed)
	352 - vcs_test_animate_isoline_text_labels_colored (Failed)
	363 - vcs_test_click_info (Failed)
	103 - dv3d_hovmoller_test (Failed)
	160 - diags_test_03 (Failed)
	162 - diags_test_41 (Failed)
	163 - diags_test_05 (Failed)
	164 - diags_test_06 (Failed)
	165 - diags_test_07 (Failed)
	166 - diags_test_08 (Failed)
	167 - diags_test_09 (Failed)
	172 - diags_test_15 (Failed)
	173 - rpy2_verify_import (Failed)
	174 - matplotlib_verify_import (Failed)
	175 - basemap_verify_import (Failed)

**Comment by durack1** [comment]
@dnadeau4 `numpy 1.10.2` is out, along with `numexpr 2.4.6` so I have updated the issue title

**Comment by dnadeau4** [comment]
Excellent!  I hope they fix the interp() bug.

**Comment by durack1** [comment]
@dnadeau4 looks like it is fixed in `numpy 1.10.2` as per https://github.com/numpy/numpy/issues/6468

**Comment by aashish24** [comment]
@dnadeau4 @durack1 is this branch still relevant?

**Comment by durack1** [comment]
@aashish24 I'll defer to @dnadeau4 for this. It'll likely need to be worked on as part of the planned `cdms3` work

**Comment by doutriaux1** [comment]
@aashish24 eventually we want to upgrade numpy. @dnadeau4 is planning to work on it soon again.

**Comment by dnadeau4** [comment]
We really need to upgrade numpy to 1.10 or 1.11 in cdms.  They are many conflicts and they are hard to track,  right now I am 100% on CMOR-3.

**Comment by durack1** [comment]
@dnadeau4 @aashish24 as this is labeled against the 3.0 milestone I think it's appropriate to leave it intact

**Comment by aashish24** [comment]
> @dnadeau4 @aashish24 as this is labeled against the 3.0 milestone I think it's appropriate to leave it intact

thansk @dnadeau4 @doutriaux1. @durack1 I recommend we close it and when we have more time, or time to get back to it, open it again.

**Comment by aashish24** [comment]
Also, currently we have 20 pull requests sitting idle for very long time. In general it's not a good or standard practice to have a situation like this.

**Comment by doutriaux1** [comment]
@aashish24 feel free to clean up the pep8 ones :stuck_out_tongue_winking_eye:

**Pull request closed without merging**
