### PR TITLE
Update VTK

### PR DESCRIPTION
**Pull request by danlipsa**

### CODE REVIEW

**Comment by danlipsa** [comment]
Data in
https://github.com/UV-CDAT/uvcdat-testdata/pull/160

VTK md5: 89e56da6b8cc350d02d13bf3e99e588468eaf1b2

**Comment by danlipsa** [comment]
Fixes:
https://github.com/UV-CDAT/vcs/issues/47
https://github.com/UV-CDAT/vcs/issues/76

**Comment by danlipsa** [comment]
@doutriaux1 @aashish24 Please review. Especially pay attention to the 400+ baseline changes. Not sure how do we update VTK. I included the md5 for the VTK I tested with (from yesterday).

**Comment by danlipsa** [comment]
@doutriaux1 @aashish24 Ping! 
These are the tests failing on my linux:
	  4 - testAccuracy (Failed)
	 39 - flake8_vcs (Failed)
	646 - flake8_Thermo (Failed)
	669 - flake8_xmgrace (Failed)
I think the flake tests fail because of newer flake on conda. I don't know about testAccuracy.

**Comment by doutriaux1** [comment]
@danlipsa we should look into the newer flake8, probably just a matter of adding a few rules to the excepted ones.

**Comment by danlipsa** [comment]
@doutriaux1 OK, I'll fix those.

**Comment by danlipsa** [comment]
@doutriaux1 They all pass. flake8 was not installed in my conda env.

**Comment by danlipsa** [comment]
@doutriaux1 @aashish24 Lets merge this! :-)
I rerun the tests: These are the failures:
	  4 - testAccuracy (Failed)
	654 - /home/danlipsa/projects/uvcdat/build/cdms/Test/test_all_formats.py (Failed)

The last test reason is:
ncopen: filename "http://test.opendap.org/opendap/hyrax/data/nc/coads_climatology.nc": NetCDF: file not found

**Comment by danlipsa** [comment]
@doutriaux1 @aashish24 I can do it myself, I just need the go ahead!

**Comment by aashish24** [comment]
+2 :LGTM

**Comment by doutriaux1** [comment]
@chaosphere2112 @aashish24 I'm offline for another day at least, please take a careful look and let's have @chaosphere2112 merge in.

**Comment by aashish24** [comment]
@doutriaux1 I would prefer the developers merge their branch. I am fine with @chaosphere2112 review the branch. This is master branch and not a release. if someone finds a new bug which is not captured by our testing then we can always fix them later. Let's merge it on Thursday as I need this branch for some of my changes.

**Comment by aashish24** [comment]
@danlipsa I believe you will push another branch with GL2PS fixes after this one?

**Comment by danlipsa** [comment]
@doutriaux1 @chaosphere2112 Guys, any progress on reviewing this? My finger itches to press "Merge pull request".

**Comment by aashish24** [comment]
@danlipsa I will review the baselines tomorrow and will run the tests on my linux. If both looks good to me, I will merge it.

**Comment by aashish24** [comment]
> @danlipsa I will review the baselines tomorrow and will run the tests on my linux. If both looks good to me, I will merge it.

Unless someone else beats me to it.

**Comment by aashish24** [comment]
@danlipsa what's your process of running your tests right now?

**Comment by danlipsa** [comment]
This is what I use. Not all steps are necessary once are done the first time. 

cd projects

Create uvcdat repo and build the conda env
-----------------------------------------------------------
mkdir uvcdat
cd uvcdat
git clone https://github.com/UV-CDAT/uvcdat.git src
mkdir build
cd build
cmake ../src
make -j10

See the name of the created conda env
-----------------------------------------------------
conda env list
Currently the conda env is: v2.8-1-gbf17786

Delete the created conda env and create another one with the same name using conda-forge
------------------------------------------------------------------------------------------------
conda env remove -n  v2.8-1-gbf17786
conda create -n v2.8-1-gbf17786 -c conda-forge -c uvcdat uvcdat


Clone vcs repo and overwrite vcs in the conda env.
-------------------------------------------------------------------
cd ..
mkdir vcs
cd vcs
git clone https://github.com/UV-CDAT/vcs.git src
cd src
source activate v2.8-1-gbf17786
python setup.py install --old-and-unmanageable

Run the tests
------------------
cd ../../uvcdat/build
ctest -j6

**Comment by aashish24** [comment]
thanks @danlipsa

**Comment by danlipsa** [comment]
@aashish24 Note I added a step for rebuilding VTK

**Comment by aashish24** [comment]
@danlipsa I am at the last step of building everything, hoping to publish my results soon.

**Comment by aashish24** [comment]
@danlipsa the new test_vcs_basic_boxfill_aeqd_proj_SH.png looks little off. Mind having a look at it?

**Comment by aashish24** [comment]
compare

**Comment by aashish24** [comment]
@danlipsa I would suggest comparing the baselines in some viewer: I wrote this script (below) to do that

for i in ls *.png; do echo "<html><head></head><body><table><tr><td></img></td><td></img></td></tr></table></body></html>" >> $i.html; done;

**Comment by danlipsa** [comment]
@aashish24 Yes, I am doing something similar. Do you see this difference on Linux, or a Mac?
 Are you sure you are on the update-vtk for uvcdat-testdata as well as for uvcdat?

**Comment by danlipsa** [comment]
@aashish24 All these tests pass in 2.8 because of a _1 version with the blue-yellow color map. Now the _1 version was promoted to the main version as it should.

**Comment by danlipsa** [comment]
@aashish24 @doutriaux1 Can I merge this?

**Comment by doutriaux1** [comment]
reviewing this afternoon.

**Comment by aashish24** [comment]
> @aashish24 All these tests pass in 2.8 because of a _1 version with the blue-yellow color map. Now the _1 version was promoted to the main version as it should.

Sounds good.

**Comment by aashish24** [comment]
> @aashish24 @doutriaux1 Can I merge this?

Let's give @doutriaux1 this afternoon to review 🤓 but I would suggest we merge it tomorrow morning. We need to move forward with some branches so unless we find any critical issue with this branch we merge it tomorrow.

**Comment by doutriaux1** [comment]
Since github.com/UV-CDAT/vcs/pull/112 is already merged i am merging this as well

**Comment by doutriaux1** [comment]
@danlipsa shouldn't there be a vtk pr to merge as well? Also travis still fails....

**Comment by danlipsa** [comment]
@doutriaux1 the first comment has the SHA and url for the VTK I used in the tests. Do we need to merge anything in or we can use that in conda-receipes? I'll have to merge in the data as well.

**Comment by danlipsa** [comment]
@doutriaux1 @aashish24 conda-recipes/vtk-cdat/meta.yaml.in has
git_rev: master
git_url: git://github.com/Kitware/VTK.git

includes the changes we want, but this is a moving target. I think we should use a specific SHA we tested with.

**Comment by aashish24** [comment]
> This includes the changes we want, but it is a moving target. I think we should use a specific SHA we tested with

+1 I was wondering about it as well.

**Comment by doutriaux1** [comment]
@danlipsa we need to update our vtk repo and build a nightly.

**Comment by doutriaux1** [comment]
@danlipsa I will update .travis.yaml to use nightly builds

**Comment by danlipsa** [comment]
@doutriaux1 Not sure I follow. What is our VTK repo? As I said conda-recipes/vtk-cdat/meta.yaml.in points to git://github.com/Kitware/VTK.git, master now.

**Comment by aashish24** [comment]
@doutriaux1 we need to use a SHA vs the master. Using master of VTK repo is risky in some ways.

**Comment by doutriaux1** [comment]
@aashish24 @danlipsa we have https://github.com/uv-cdat/VTK just for that purpose. @aashish24 created this. uvcdat-master is the branch that we should use for nightly I retag uvcdat-master wth each release.

**Comment by danlipsa** [comment]
@doutriaux1 @aashish24 OK, so I'll point that branch to the VTK SHA I tested with. We should probably change conda-recipes/vtk-cdat/meta.yaml.in to point to that as well isn't it?

**Comment by danlipsa** [comment]
@doutriaux1 @aashish24 I updated uvcdat-master on  https://github.com/uv-cdat/VTK to point to the SHA I tested (VTK from Dec 22). @doutriaux1 Are you going to update conda-recipes or you want me to do it?

**Comment by doutriaux1** [comment]
@danlipsa conda-recipe should point to uvcdat-master of  https://github.com/uv-cdat/VTK  which at this point I think should really be just master I dont see the point of having a uvcdat-master branch.

**Comment by doutriaux1** [comment]
@danlipsa so I don't think conda-recipe needs an update.

**Comment by danlipsa** [comment]
@doutriaux1 We got used with uvcdat-master, so maybe we should leave it as is. Also master could be interpreted as VTK master which is not. So I vote to keep using uvcdat-master.

**Comment by aashish24** [comment]
@danlipsa @doutriaux1 I think if we use uvcdat/vtk, using master is fine since we will only update the master when we know vtk original master is in good condition for UV-CDAT>

**Comment by doutriaux1** [comment]
@danlipsa @aashish24 I'm fine either way. Let's revisit this next time we merge something from VTK into our VTK repo.

**Pull request merged**
