### PR TITLE
issue1539 durack1 update iPython 3.0.0 to 4.0.0

### LINKED ISSUE #1539: Update iPython to 4.1.2
We are a full release behind iPython latest (3.0.0 vs 4.0.0).

@doutriaux1 want to assign me as a 2.4 milestone?

### PR DESCRIPTION
**Pull request by durack1**
Fix #1539 - Update iPython 3.0.0 to 4.0.0

### CODE REVIEW

**Comment by doutriaux1** [comment]
Seems to have broken matplotlib

**Comment by durack1** [comment]
@doutriaux1 only looks like [4 `vcs` errors on garant](https://open.cdash.org/viewTest.php?onlyfailed&buildid=4003488)

Is the aims4.llnl.gov machine down - I can't query any of the others..

**Comment by durack1** [comment]
@doutriaux1 only looks like [4 `vcs` errors on garant](https://open.cdash.org/viewTest.php?onlyfailed&buildid=4003488)

Is the aims4.llnl.gov machine down - I can't query any of the others..

**Comment by doutriaux1** [comment]
@durack1 please don't do that whitespace thing, just ask us, it makes the history uggly.

**Comment by durack1** [comment]
@doutriaux1 what's going on with the buildbot testing? Looks like this is hanging or the server isn't live or some other issue..

**Comment by doutriaux1** [comment]
i'm "finetuning it" please do NOT resubmit any I will retrigger manually as I fix the bot process.

**Comment by durack1** [comment]
@doutriaux1 `ocean` is rebooted, so can you initialize the bot testing for this PR again please?

**Comment by durack1** [comment]
@doutriaux1 this now looks good, only [`crunchy` failed and the error is the standard](https://open.cdash.org/viewTest.php?onlyfailed&buildid=4083839):
```
The following tests FAILED:
	 88 - vcs_test_background_mode_rotate (Failed)
```

**Comment by doutriaux1** [comment]
@durack1  I restored your branch it's complaining about traits now:

```
Traceback (most recent call last):
  File "/lgm/uvcdat/2015-11-04/bin/ipython", line 4, in <module>
    from IPython import start_ipython
  File "/lgm/uvcdat/2015-11-04/lib/python2.7/site-packages/IPython/__init__.py", line 47, in <module>
    from .core.application import Application
  File "/lgm/uvcdat/2015-11-04/lib/python2.7/site-packages/IPython/core/application.py", line 22, in <module>
    from traitlets.config.application import Application, catch_config_error
ImportError: No module named traitlets.config.application
```

**Comment by doutriaux1** [comment]
@durack1 here's what you need to add:
```Collecting ipython
  Downloading ipython-4.0.0-py2-none-any.whl (730kB)
    100% |████████████████████████████████| 733kB 421kB/s 
Collecting decorator (from ipython)
  Downloading decorator-4.0.4-py2.py3-none-any.whl
Collecting simplegeneric>0.8 (from ipython)
  Downloading simplegeneric-0.8.1.zip
Collecting pexpect (from ipython)
  Downloading pexpect-4.0.1.tar.gz (143kB)
    100% |████████████████████████████████| 147kB 532kB/s 
Collecting traitlets (from ipython)
  Downloading traitlets-4.0.0-py2.py3-none-any.whl (56kB)
    100% |████████████████████████████████| 57kB 3.2MB/s 
Collecting pickleshare (from ipython)
  Downloading pickleshare-0.5.tar.gz
Collecting ptyprocess>=0.5 (from pexpect->ipython)
  Downloading ptyprocess-0.5.tar.gz
Collecting ipython-genutils (from traitlets->ipython)
  Downloading ipython_genutils-0.1.0-py2.py3-none-any.whl
Collecting path.py (from pickleshare->ipython)
  Downloading path.py-8.1.2-py2.py3-none-any.whl
Installing collected packages: decorator, simplegeneric, ptyprocess, pexpect, ipython-genutils, traitlets, path.py, pickleshare, ipython
```

**Comment by durack1** [comment]
@doutriaux1, ok will load the PR up with even more dependencies.. I wonder if the `pypi` package contains all these pieces, the source was obtained direct from github..

**Comment by doutriaux1** [comment]
Yes I got these dependencies listed while installing it via pip install.

**Comment by doutriaux1** [comment]
you will probably need to open a new PR since this one has been merged and reverted.

**Pull request merged**
