### PR TITLE
Issue 1585 ez template tweaks

### PR DESCRIPTION
**Pull request by doutriaux1**

### CODE REVIEW

**Comment by aashish24** [comment]
@doutriaux1 what is a ez template?

**Comment by durack1** [comment]
@aashish24 take a peek at the [EzTemplates here](http://uv-cdat.llnl.gov/gallery.html)

**Comment by aashish24** [comment]
Hard to review the changes..but looks like cdash is happy. I am giving +1. Someone else should reivew it.

Thanks @durack1

**Comment by doutriaux1** [comment]
@chaosphere2112 please review and approve don't worry about the W>H I improved this logic in https://github.com/UV-CDAT/uvcdat/pull/1595

**Comment by durack1** [comment]
@doutriaux1 if I'm reading this correctly it resolves #1423 - fix #1423?

**Comment by doutriaux1** [comment]
@durack1 yes.

**Comment by chaosphere2112** [comment]
@doutriaux1 I'm testing this one now, then I'll move over to #1595

**Comment by chaosphere2112** [comment]
@doutriaux1 I ran into some failed tests, but none of them look related to this (all of them are CDMS, I think). :+1: from me.

**Comment by aashish24** [comment]
+2

**Pull request merged**
