### PR TITLE
Final commits to make buildbot pass

### PR DESCRIPTION
**Pull request by jbeezley**
This has 2f508c3 cherry picked from `release` and 9a3e300 from #1314.

### CODE REVIEW

**Comment by jbeezley** [comment]
Well that didn't work...

**Comment by aashish24** [comment]
:cry: how did you know?

**Comment by jbeezley** [comment]
Build [failed](https://open.cdash.org/buildSummary.php?buildid=3809950), but I reset it.  I installed qt while the build was happening last time, so that could have broken something.

**Comment by aashish24** [comment]
Okay, should we go ahead and  merge?

**Comment by jbeezley** [comment]
Hold off for a bit.  I'm going to see what is happening with vtk.

**Comment by aashish24** [comment]
Sounds good to me....

**Comment by jbeezley** [comment]
VTK build failed because the qt install messed up the GL setup.  I can fix that, but the build failure wasn't reported by ctest and I'm not sure why:
```
make[5]: *** No rule to make target `/usr/lib/x86_64-linux-gnu/libGL.so', needed by `lib/libvtkftgl-6.3.so.1'.  Stop.
make[5]: *** No rule to make target `/usr/lib/x86_64-linux-gnu/libGL.so', needed by `lib/libvtkgl2ps-6.3.so.1'.  Stop.
make[5]: *** No rule to make target `lib/libvtkftgl-6.3.so.1', needed by `lib/libvtkRenderingFreeType-6.3.so.1'.  Stop.
make[5]: *** No rule to make target `lib/libvtkRenderingFreeType-6.3.so.1', needed by `lib/libvtkRenderingAnnotation-6.3.so.1'.  Stop.
make[5]: *** No rule to make target `lib/libvtkRenderingFreeType-6.3.so.1', needed by `lib/libvtkRenderingLabel-6.3.so.1'.  Stop.
make[5]: *** No rule to make target `/usr/lib/x86_64-linux-gnu/libGL.so', needed by `lib/libvtkRenderingOpenGL-6.3.so.1'.  Stop.
make[5]: *** No rule to make target `lib/libvtkRenderingFreeType-6.3.so.1', needed by `lib/libvtkRenderingContext2D-6.3.so.1'.  Stop.
make[5]: *** No rule to make target `lib/libvtkRenderingContext2D-6.3.so.1', needed by `lib/libvtkRenderingContextOpenGL-6.3.so.1'.  Stop.
make[5]: *** No rule to make target `lib/libvtkRenderingFreeType-6.3.so.1', needed by `lib/libvtkRenderingFreeTypeOpenGL-6.3.so.1'.  Stop.
make[5]: *** No rule to make target `lib/libvtkRenderingOpenGL-6.3.so.1', needed by `lib/libvtkRenderingVolumeOpenGL-6.3.so.1'.  Stop.
make[5]: *** No rule to make target `lib/libvtkRenderingAnnotation-6.3.so.1', needed by `lib/libvtkInteractionWidgets-6.3.so.1'.  Stop.
make[5]: *** No rule to make target `lib/libvtkInteractionWidgets-6.3.so.1', needed by `lib/libvtkViewsCore-6.3.so.1'.  Stop.
make[5]: *** No rule to make target `lib/libvtkRenderingContextOpenGL-6.3.so.1', needed by `lib/libvtkRenderingGL2PS-6.3.so.1'.  Stop.
make[5]: *** No rule to make target `lib/libvtkInteractionWidgets-6.3.so.1', needed by `lib/libvtkInteractionImage-6.3.so.1'.  Stop.
make[5]: *** No rule to make target `lib/libvtkRenderingContext2D-6.3.so.1', needed by `lib/libvtkChartsCore-6.3.so.1'.  Stop.
make[5]: *** No rule to make target `lib/libvtkInteractionWidgets-6.3.so.1', needed by `lib/libvtkGeovisCore-6.3.so.1'.  Stop.
make[5]: *** No rule to make target `lib/libvtkRenderingAnnotation-6.3.so.1', needed by `lib/libvtkIOExport-6.3.so.1'.  Stop.
make[5]: *** No rule to make target `lib/libvtkChartsCore-6.3.so.1', needed by `lib/libvtkViewsInfovis-6.3.so.1'.  Stop.
make[5]: *** No rule to make target `lib/libvtkGeovisCore-6.3.so.1', needed by `lib/libvtkViewsGeovis-6.3.so.1'.  Stop.
make[5]: *** No rule to make target `lib/libvtkRenderingOpenGL-6.3.so.1', needed by `lib/libvtkRenderingOpenGLPython27D-6.3.so.1'.  Stop.
make[5]: *** No rule to make target `lib/libvtkRenderingFreeType-6.3.so.1', needed by `lib/libvtkRenderingFreeTypePython27D-6.3.so.1'.  Stop.
make[5]: *** No rule to make target `lib/libvtkRenderingAnnotation-6.3.so.1', needed by `lib/libvtkRenderingAnnotationPython27D-6.3.so.1'.  Stop.
make[5]: *** No rule to make target `lib/libvtkRenderingLabel-6.3.so.1', needed by `lib/libvtkRenderingLabelPython27D-6.3.so.1'.  Stop.
make[5]: *** No rule to make target `lib/libvtkRenderingFreeTypeOpenGL-6.3.so.1', needed by `lib/libvtkRenderingFreeTypeOpenGLPython27D-6.3.so.1'.  Stop.
make[5]: *** No rule to make target `lib/libvtkRenderingAnnotationPython27D-6.3.so.1', needed by `lib/vtkRenderingAnnotationPython.so'.  Stop.
make[5]: *** No rule to make target `lib/libvtkRenderingFreeTypePython27D-6.3.so.1', needed by `lib/vtkRenderingFreeTypePython.so'.  Stop.
make[5]: *** No rule to make target `lib/libvtkRenderingLabelPython27D-6.3.so.1', needed by `lib/vtkRenderingLabelPython.so'.  Stop.
make[5]: *** No rule to make target `lib/libvtkRenderingOpenGLPython27D-6.3.so.1', needed by `lib/vtkRenderingOpenGLPython.so'.  Stop.
make[5]: *** No rule to make target `lib/libvtkRenderingVolumeOpenGL-6.3.so.1', needed by `lib/libvtkRenderingVolumeOpenGLPython27D-6.3.so.1'.  Stop.
make[5]: *** No rule to make target `lib/libvtkRenderingContext2D-6.3.so.1', needed by `lib/libvtkRenderingContext2DPython27D-6.3.so.1'.  Stop.
make[5]: *** No rule to make target `lib/libvtkRenderingFreeTypeOpenGLPython27D-6.3.so.1', needed by `lib/vtkRenderingFreeTypeOpenGLPython.so'.  Stop.
make[5]: *** No rule to make target `lib/libvtkRenderingVolumeOpenGLPython27D-6.3.so.1', needed by `lib/vtkRenderingVolumeOpenGLPython.so'.  Stop.
make[5]: *** No rule to make target `lib/libvtkRenderingContextOpenGL-6.3.so.1', needed by `lib/libvtkRenderingContextOpenGLPython27D-6.3.so.1'.  Stop.
make[5]: *** No rule to make target `lib/libvtkRenderingContext2DPython27D-6.3.so.1', needed by `lib/vtkRenderingContext2DPython.so'.  Stop.
make[5]: *** No rule to make target `lib/libvtkRenderingContextOpenGLPython27D-6.3.so.1', needed by `lib/vtkRenderingContextOpenGLPython.so'.  Stop.
make[5]: *** No rule to make target `lib/libvtkChartsCore-6.3.so.1', needed by `lib/libvtkChartsCorePython27D-6.3.so.1'.  Stop.
make[5]: *** No rule to make target `lib/libvtkRenderingGL2PS-6.3.so.1', needed by `lib/libvtkRenderingGL2PSPython27D-6.3.so.1'.  Stop.
make[5]: *** No rule to make target `lib/libvtkChartsCorePython27D-6.3.so.1', needed by `lib/vtkChartsCorePython.so'.  Stop.
make[5]: *** No rule to make target `lib/libvtkRenderingGL2PSPython27D-6.3.so.1', needed by `lib/vtkRenderingGL2PSPython.so'.  Stop.
make[5]: *** No rule to make target `lib/libvtkIOExport-6.3.so.1', needed by `lib/libvtkIOExportPython27D-6.3.so.1'.  Stop.
make[5]: *** No rule to make target `lib/libvtkIOExportPython27D-6.3.so.1', needed by `lib/vtkIOExportPython.so'.  Stop.
make[5]: *** No rule to make target `lib/libvtkInteractionWidgets-6.3.so.1', needed by `lib/libvtkInteractionWidgetsPython27D-6.3.so.1'.  Stop.
make[5]: *** No rule to make target `lib/libvtkInteractionWidgetsPython27D-6.3.so.1', needed by `lib/vtkInteractionWidgetsPython.so'.  Stop.
make[5]: *** No rule to make target `lib/libvtkViewsCore-6.3.so.1', needed by `lib/libvtkViewsCorePython27D-6.3.so.1'.  Stop.
make[5]: *** No rule to make target `lib/libvtkInteractionImage-6.3.so.1', needed by `lib/libvtkInteractionImagePython27D-6.3.so.1'.  Stop.
make[5]: *** No rule to make target `lib/libvtkViewsCorePython27D-6.3.so.1', needed by `lib/vtkViewsCorePython.so'.  Stop.
make[5]: *** No rule to make target `lib/libvtkInteractionImagePython27D-6.3.so.1', needed by `lib/vtkInteractionImagePython.so'.  Stop.
make[5]: *** No rule to make target `lib/libvtkViewsInfovis-6.3.so.1', needed by `lib/libvtkViewsInfovisPython27D-6.3.so.1'.  Stop.
make[5]: *** No rule to make target `lib/libvtkGeovisCore-6.3.so.1', needed by `lib/libvtkGeovisCorePython27D-6.3.so.1'.  Stop.
make[5]: *** No rule to make target `lib/libvtkGeovisCorePython27D-6.3.so.1', needed by `lib/vtkGeovisCorePython.so'.  Stop.
make[5]: *** No rule to make target `lib/libvtkViewsInfovisPython27D-6.3.so.1', needed by `lib/vtkViewsInfovisPython.so'.  Stop.
make[5]: *** No rule to make target `lib/libvtkViewsGeovis-6.3.so.1', needed by `lib/libvtkViewsGeovisPython27D-6.3.so.1'.  Stop.
make[5]: *** No rule to make target `lib/libvtkViewsGeovisPython27D-6.3.so.1', needed by `lib/vtkViewsGeovisPython.so'.  Stop.
CMake Error at ThirdParty/ftgl/cmake_install.cmake:51 (FILE):
  file INSTALL cannot find
  "/home/buildbot/buildbot/uvcdat-garant-linux-release/build/build/VTK-build/lib/libvtkftgl-6.3.so.1".
Call Stack (most recent call first):
  cmake_install.cmake:121 (INCLUDE)
```

**Comment by aashish24** [comment]
what machine is this?

**Comment by jbeezley** [comment]
garant.kitware.com.  The GL library it picked up was an invalid symlink.  The error above was in the `VTK-install-err.log` and there was a similar error in `VTK-build-err.log`.

**Comment by aashish24** [comment]
Sounds like a system specific issue to me.

**Comment by jbeezley** [comment]
Yes, the error is system specific, but it should have been reported as a build error to cdash.  It wasn't: https://open.cdash.org/buildSummary.php?buildid=3809950

**Comment by aashish24** [comment]
that is odd. Can you file a new issue for that? In the mean time I am merging this branch.

**Pull request merged**
