### PR TITLE
Pattern size scaling

### PR DESCRIPTION
**Pull request by chaosphere2112**
Cleaned up version of #1651, with a revisionist take on history.

### CODE REVIEW

**Comment by chaosphere2112** [comment]
@aashish24 @doutriaux1 Cleaned up my PR

**Comment by doutriaux1** [comment]
@chaosphere2112 mac1 fails on scipy again.... :rage4: will this ever stop... I wonder what started this... Anyhow not related to this PR.

**Comment by aashish24** [comment]
thanks @chaosphere2112 will review it tonight

**Comment by aashish24** [comment]
@chaosphere2112 looks good to me but some tests are failing on garant.. @jbeezley would it be possible to fix these broken links that I believe were generated by bot?

**Comment by jbeezley** [comment]
I attempted to fix the links a couple of weeks ago, but I apparently failed.  I'll ask Ben if he has any ideas.

**Comment by jbeezley** [comment]
Actually, this one is a build failure.
```
fatal: unable to connect to github.com:
github.com: No address associated with hostname
```
I have a lot of strange random network failures on that machine.  I have no idea why.  I'll restart the build.

**Comment by doutriaux1** [comment]
the bots have github failures too sometimes, on and off, might be a github issue.

**Pull request merged**
