### PR TITLE
Vcs3 d fix 2.2 interaction problems

### PR DESCRIPTION
**Pull request by ThomasMaxwell**
Fixes the broken interactions in the 3D plots.

### CODE REVIEW

**Comment by doutriaux1** [comment]
thanks @ThomasMaxwell 
@chaosphere2112 said he will take a look tomorrw to make sure his branch and yours don't clash.

**Comment by aashish24** [comment]
Looks good to me ( I haven't built the branch but looked at the code). @ThomasMaxwell did you run ctest? 

@doutriaux1 we don't need to worry about conflicts when two branches are up for the development. When the first goes in the second has to resolve the conflicts. The changes here seems mostly orthogonal.

**Comment by ThomasMaxwell** [comment]
This branch passed all ctests yesterday with the master at that time.

**Comment by doutriaux1** [comment]
works for me. Merging

**Comment by aashish24** [comment]
Great. Thanks @doutriaux1.Yes @ThomasMaxwell the branch looked good to me.

**Comment by ThomasMaxwell** [comment]
I’m now getting the following errors building python in the current master branch in OS X 10.10:



/usr/bin/gcc -bundle -undefined dynamic_lookup -L/Developer/Projects/EclipseWorkspace/uvcdat/master/build/install/Externals/lib -Wl,-rpath,/Developer/Projects/EclipseWorkspace/uvcdat/master/build/install/lib -Wl,-rpath,/Developer/Projects/EclipseWorkspace/uvcdat/master/build/install/Externals/lib -L/System/Library/Frameworks/ImageIO.framework/Versions/A/Resources -bind_at_load -mmacosx-version-min=10.10 -fno-strict-aliasing -fno-common -dynamic -I/Developer/Projects/EclipseWorkspace/uvcdat/master/build/install/Externals/include -L/Developer/Projects/EclipseWorkspace/uvcdat/master/build/install/Externals/lib -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/usr/include -L/System/Library/Frameworks/ImageIO.framework/Versions/A/Resources -bind_at_load -mmacosx-version-min=10.10 -fPIC -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes build/temp.macosx-10.4-x86_64-2.7/Developer/Projects/EclipseWorkspace/uvcdat/master/build/build/Python/Modules/pyexpat.o build/temp.macosx-10.4-x86_64-2.7/Developer/Projects/EclipseWorkspace/uvcdat/master/build/build/Python/Modules/expat/xmlparse.o build/temp.macosx-10.4-x86_64-2.7/Developer/Projects/EclipseWorkspace/uvcdat/master/build/build/Python/Modules/expat/xmlrole.o build/temp.macosx-10.4-x86_64-2.7/Developer/Projects/EclipseWorkspace/uvcdat/master/build/build/Python/Modules/expat/xmltok.o -L/Developer/Projects/EclipseWorkspace/uvcdat/master/build/install/Externals/lib -L/System/Library/Frameworks/ImageIO.framework/Versions/A/Resources -L/usr/local/lib -o build/lib.macosx-10.4-x86_64-2.7/pyexpat.so

*** WARNING: renaming "pyexpat" since importing it failed: dlopen(build/lib.macosx-10.4-x86_64-2.7/pyexpat.so, 2): Symbol not found: _XML_ErrorString

  Referenced from: build/lib.macosx-10.4-x86_64-2.7/pyexpat.so

  Expected in: flat namespace

 in build/lib.macosx-10.4-x86_64-2.7/pyexpat.so

building '_elementtree' extension

/usr/bin/gcc -fno-strict-aliasing -fno-common -dynamic -I/Developer/Projects/EclipseWorkspace/uvcdat/master/build/install/Externals/include -L/Developer/Projects/EclipseWorkspace/uvcdat/master/build/install/Externals/lib -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/usr/include -L/System/Library/Frameworks/ImageIO.framework/Versions/A/Resources -bind_at_load -mmacosx-version-min=10.10 -fPIC -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -DHAVE_EXPAT_CONFIG_H=1 -DUSE_PYEXPAT_CAPI -I/Developer/Projects/EclipseWorkspace/uvcdat/master/build/build/Python/./Modules/expat -I/Developer/Projects/EclipseWorkspace/uvcdat/master/build/build/Python/Mac/Include -I/Developer/Projects/EclipseWorkspace/uvcdat/master/build/build/Python/Mac/Include -I. -IInclude -I./Include -I/Developer/Projects/EclipseWorkspace/uvcdat/master/build/install/Externals/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/usr/include -I/usr/local/include -I/Developer/Projects/EclipseWorkspace/uvcdat/master/build/build/Python/Include -I/Developer/Projects/EclipseWorkspace/uvcdat/master/build/build/Python -c /Developer/Projects/EclipseWorkspace/uvcdat/master/build/build/Python/Modules/_elementtree.c -o build/temp.macosx-10.4-x86_64-2.7/Developer/Projects/EclipseWorkspace/uvcdat/master/build/build/Python/Modules/_elementtree.o

clang: warning: argument unused during compilation: '-L/Developer/Projects/EclipseWorkspace/uvcdat/master/build/install/Externals/lib'

clang: warning: argument unused during compilation: '-L/System/Library/Frameworks/ImageIO.framework/Versions/A/Resources'

clang: warning: argument unused during compilation: '-bind_at_load'

/usr/bin/gcc -bundle -undefined dynamic_lookup -L/Developer/Projects/EclipseWorkspace/uvcdat/master/build/install/Externals/lib -Wl,-rpath,/Developer/Projects/EclipseWorkspace/uvcdat/master/build/install/lib -Wl,-rpath,/Developer/Projects/EclipseWorkspace/uvcdat/master/build/install/Externals/lib -L/System/Library/Frameworks/ImageIO.framework/Versions/A/Resources -bind_at_load -mmacosx-version-min=10.10 -fno-strict-aliasing -fno-common -dynamic -I/Developer/Projects/EclipseWorkspace/uvcdat/master/build/install/Externals/include -L/Developer/Projects/EclipseWorkspace/uvcdat/master/build/install/Externals/lib -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/usr/include -L/System/Library/Frameworks/ImageIO.framework/Versions/A/Resources -bind_at_load -mmacosx-version-min=10.10 -fPIC -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes build/temp.macosx-10.4-x86_64-2.7/Developer/Projects/EclipseWorkspace/uvcdat/master/build/build/Python/Modules/_elementtree.o -L/Developer/Projects/EclipseWorkspace/uvcdat/master/build/install/Externals/lib -L/System/Library/Frameworks/ImageIO.framework/Versions/A/Resources -L/usr/local/lib -o build/lib.macosx-10.4-x86_64-2.7/_elementtree.so

*** WARNING: renaming "_elementtree" since importing it failed: PyCapsule_Import could not import module "pyexpat"


Python build finished, but the necessary bits to build these modules were not found:

_bsddb             dl                 gdbm

imageop            linuxaudiodev      ossaudiodev

spwd               sunaudiodev

To find the necessary bits, look in setup.py in detect_modules() for the module's name.



Failed to build these modules:

_elementtree       pyexpat

**Comment by chaosphere2112** [comment]
@ThomasMaxwell Was this meant for the uvcdat-devel mailing list? Or maybe #1183 ?

**Pull request merged**
