### PR TITLE
Find the highest version first and then use the lower versions

### LINKED ISSUE #1183: Build issues on 10.10
Hey @aashish24, I'm having some issues building on 10.10 (with 10.9 SDKs installed as well as 10.10)

I'm trying to do a clean build, but when it gets to `enable_language(Fortran)` (line 244 of CMakeLists.txt), it fails and dumps out this error message:

```
  CMAKE_OSX_DEPLOYMENT_TARGET is '10.9' but CMAKE_OSX_SYSROOT:

   ""

  is not set to a MacOSX SDK with a recognized version.  Either set
  CMAKE_OSX_SYSROOT to a valid SDK or set CMAKE_OSX_DEPLOYMENT_TARGET to
  empty.
Call Stack (most recent call first):
  /Applications/CMake.app/Contents/share/cmake/Modules/CMakeSystemSpecificInformation.cmake:36 (include)
  CMakeLists.txt:3 (project)


CMake Error: Internal CMake error, TryCompile configure of cmake failed
-- Configuring incomplete, errors occurred!
See also "/Users/samfries/build/CMakeFiles/CMakeOutput.log".
```

I did a `message` that printed out CMAKE_OSX_SYSROOT prior to the call to `enable_language`, and it's pointing at my 10.9 SDK. I'm not sure why, but it looks like somewhere in `enable_language`, the `CMAKE_OSX_SYSROOT` variable must be getting reset? Any ideas?

### PR DESCRIPTION
**Pull request by aashish24**
@chaosphere2112 please try it. Fixes #1183

### CODE REVIEW

**Comment by chaosphere2112** [comment]
:disappointed:
```
CMake Error at /Applications/CMake.app/Contents/share/cmake/Modules/Platform/Darwin.cmake:76 (message):
  CMAKE_OSX_DEPLOYMENT_TARGET is '10.10' but CMAKE_OSX_SYSROOT:

   ""

  is not set to a MacOSX SDK with a recognized version.  Either set
  CMAKE_OSX_SYSROOT to a valid SDK or set CMAKE_OSX_DEPLOYMENT_TARGET to
  empty.
Call Stack (most recent call first):
  /Applications/CMake.app/Contents/share/cmake/Modules/CMakeSystemSpecificInformation.cmake:36 (include)
  CMakeLists.txt:3 (project)
```

**Comment by aashish24** [comment]
:cry: Okay, I will look some more.. Did you install command line tools when you / after you installed xcode 62

**Comment by chaosphere2112** [comment]
Yup, pretty sure... only things available in the "Downloads" section are documentation and iOS simulators.

**Comment by aashish24** [comment]
https://developer.apple.com/downloads/index.action# You are talking about download section here right? the command line tools need to be downloaded separately

**Comment by chaosphere2112** [comment]
Not sure. I'll double check when I get home today.

**Comment by doutriaux1** [comment]
@aashish24 should we close this? I remember you arguing against this method because you were worried when a new version comes out, it might break the build, whereas using an older SDK should still work.

**Comment by aashish24** [comment]
@doutriaux1 I am waiting for @chaosphere2112 to syncup on this.

**Comment by chaosphere2112** [comment]
@aashish24 I'm pretty sure I tried this and didn't get anywhere. I'll give it another go this afternoon, and step out a little early to test it on my laptop at home.

**Comment by chaosphere2112** [comment]
@aashish24  Just updated Xcode to 6.3.1, OSX to 10.10.3, and command line tools to 10.10 (for 6.3.1). Still failing, here's the log.
https://gist.github.com/chaosphere2112/0774a0a7b996fa230c4b

**Comment by chaosphere2112** [comment]
@aashish24 So, I think I figured out my issue. I had two different versions of cmake on my path, and I think it barfed somewhere on that fact. I removed one from my path, and now it all works!

**Comment by chaosphere2112** [comment]
Many documents died to bring us this information.

... I accidentally rm -rf'd my personal computer's home directory this morning. I then proceeded to start using an online backup service. :cry:

**Comment by doutriaux1** [comment]
closing #1321 is a better solution

**Pull request closed without merging**
