### PR TITLE
Brings back the font menu

### PR DESCRIPTION
**Pull request by chaosphere2112**
Fix for #1093

### CODE REVIEW

**Comment by durack1** [comment]
@doutriaux1 it seems the vcs labels (no lines behind contour values) issue is still a problem on oceanonly - do the test images need to be updated?:
```
The following tests FAILED:
	 45 - vcs_test_antialiasing (Failed)
	296 - vcs_test_isoline_labels_multi_label_input_types (Failed)
	297 - vcs_test_isoline_labels (Failed)
	298 - vcs_test_isoline_labelskipdistance (Failed)
	299 - vcs_test_isofill_isoline_labels (Failed)
	321 - vcs_test_animate_isoline_text_labels (Failed)
	322 - vcs_test_animate_isoline_text_labels_colored (Failed)
```

**Comment by doutriaux1** [comment]
@durack1 it is a RH6 specific issue. @dlonie and @aashish24 are looking into it, something about gl drivers being bad...

**Comment by doutriaux1** [comment]
No test for this?

**Comment by chaosphere2112** [comment]
@doutriaux1 I can add a test; I'll have something in an hour or so.

**Pull request merged**
