### PR TITLE
Add flake8 test for xmgrace.

### PR DESCRIPTION
**Pull request by dlonie**
The test currently fails. The code needs to be cleaned up before merging.

@doutriaux1 @aashish24

### CODE REVIEW

**Comment by doutriaux1** [comment]
@aashish24 @dlonie @sankhesh 1 done! Many to go :Wink:

**Comment by aashish24** [comment]
You are awesome @doutriaux1 Did you use some tool to fix most of these?

**Comment by aashish24** [comment]
@dlonie @sankhesh I will have you review it

**Comment by dlonie** [comment]
The warning should be properly fixed, or the specific line excluded. Let's not change the directory-level scanning.

**Comment by doutriaux1** [comment]
ok it's in. I left the import * because I don't want to risk breaking anything by forgetting an import. This module is pretty much legacy anyway now, I don't think anybody new to uvcdat would pick this up, it's mainly for our current/past users.

**Comment by dlonie** [comment]
LGTM

**Pull request merged**
