### PR TITLE
Fix export svg

### PR DESCRIPTION
**Pull request by aashish24**

### CODE REVIEW

**Comment by aashish24** [comment]
Fixes: https://github.com/UV-CDAT/uvcmetrics/issues/214#issuecomment-232415355

**Comment by aashish24** [comment]
@sankhesh @doutriaux1 please review.

**Comment by doutriaux1** [comment]
Awesome! thanks @aashish24 will take a look as soon as possible!

**Comment by aashish24** [comment]
Do: test

**Comment by sankhesh** [comment]
LGTM :+1:

**Comment by doutriaux1** [comment]
@aashish24 @sankhesh I'm about to test this, but I doubt it's going to change anything since my test was a regular isofill no hatch or pattern.

**Comment by doutriaux1** [comment]
@aashish24 @sankhesh ok I just produced an ungroupable svg on my mac with this branch. I'm going to try it on a Linux system and see if it fixes the svgs for metadiags. Thanks

**Comment by doutriaux1** [comment]
@aashish24 @sankhesh with that branch I can ungroup svgs for both boxfill and isofill but not with master. I'm not really sure what's the diff... But hey I'm so happy!

**Comment by aashish24** [comment]
great! thanks for the update @doutriaux1

**Pull request merged**
