### PR TITLE
Added missing test file

### PR DESCRIPTION
**Pull request by aashish24**

### CODE REVIEW

**Comment by aashish24** [comment]
Folks, I am running the entire test-suite as Dan found 3 new tests failing.

**Comment by danlipsa** [comment]
Yes, now that test passes on your branch.

**Comment by danlipsa** [comment]
LGTM

**Comment by aashish24** [comment]
@danlipsa sorry, I am not done yet. I just wanted to let folks know that I am working on fixing them and that's why the PR. I will be done in few minutes.

**Comment by danlipsa** [comment]
Sounds good.

**Comment by aashish24** [comment]
@danlipsa this branch is ready to be reviewed. The only other test failing is the continent on my machine but it seems like it couldn't not be caused by my branch  since it shaving a very small diff which looks more like a aliasing or some other issue not related to my branch.

**Comment by aashish24** [comment]
Ref: https://github.com/UV-CDAT/uvcdat/issues/1919

**Comment by danlipsa** [comment]
@aashish24 See the end of this PR where I listed all failing tests.
https://github.com/UV-CDAT/uvcdat-testdata/pull/121
continents is failing for a long time, so it wasn't you. :-)

What about test_vcs_wmo_markers? That is still failing.

**Comment by aashish24** [comment]
@danlipsa that is because I pushed the data afterwards (my bad): Its here; https://github.com/UV-CDAT/uvcdat-testdata/pull/124

**Comment by danlipsa** [comment]
@aashish24 Indeed, with that data all 3 test pass now. LGTM.

**Comment by aashish24** [comment]
thansk!

**Pull request merged**
