### PR TITLE
Build in source

### PR DESCRIPTION
**Pull request by dlonie**
Updated build in source test.

New PR is due to the old branch being in a fork (and thus not update-able by the team). #798 should be replaced by this PR.

This should go without saying, but please remain professional and respectful while discussing this patch. We're on the same team here -- I'd rather not see another issue history like #798.

### CODE REVIEW

**Comment by dlonie** [comment]
@aashish24 @doutriaux1 @remram44 

Added tests for functionality.

**Comment by aashish24** [comment]
LGTM :+1: I will just wait for Travis (as policy) and then will merge.. thanks

**Comment by aashish24** [comment]
Looks like we are hitting the cmake version issue. I will push a separate fix for that.

**Comment by jbeezley** [comment]
A while back I updated Girder's `.travis.yml` to update to the latest cmake.  You can install from the binaries hosted at Kitware pretty easily. See here: https://github.com/girder/girder/pull/564.

**Comment by aashish24** [comment]
@jbeezley thanks. We had it for Linux but not for OSX.

**Pull request merged**
