### PR TITLE
Allow unicode strings for subsetting.

### PR DESCRIPTION
**Pull request by danlipsa**
This is how they come from the web.

### CODE REVIEW

**Comment by doutriaux1** [comment]
wow there are still some `types` floating around! I thought I removed them all! Maybe we should check the rest of the file(s) for use of `types` and clean this up as well

**Comment by danlipsa** [comment]
Sure, I can do the string ones. What do you do for the rest of the types?

**Comment by danlipsa** [comment]
https://gitlab.kitware.com/UV-CDAT/uvcdat/merge_requests/614
@doutriaux1 @aashish24 I think this is ready. We can clean up in a different PR.

**Comment by aashish24** [comment]
Dashboard looks good to me thanks to @sankhesh' effort. LGTM 👍

**Comment by doutriaux1** [comment]
@aashish24 @sankhesh is that the url for buildbot results? https://gitlab.kitware.com/UV-CDAT/uvcdat/merge_requests/614/builds ? I only see kitware there, I thought we had at least oceanonly and crunchy going.

**Comment by sankhesh** [comment]
@doutriaux1 Nope. Buildbot auto-generates a custom CDash link for builds specific to the merge request and posts a comment on the merge request. 

Here is an example: https://gitlab.kitware.com/UV-CDAT/uvcdat/merge_requests/614#note_90623

**Comment by doutriaux1** [comment]
thanks @sankhesh

**Comment by doutriaux1** [comment]
@danlipsa there's failure on the few bots we have.

**Comment by danlipsa** [comment]
@doutriaux1 Are you talking about oceanonly? Those tests fail on master as well. There is the diag tests that fail for some time and recently I started seeing some vcs_verify tests failing because they cannot find a py file.

**Comment by danlipsa** [comment]
@doutriaux1 Ready to merge?

**Comment by doutriaux1** [comment]
@danlipsa while we are at it I would like to clean this up a bit more, I'll push an updated version in 10mn

**Comment by danlipsa** [comment]
@doutriaux1 We could always do the clean-up as a separate PR. I would rather do it that way instead of delaying this any further.

**Comment by danlipsa** [comment]
@doutriaux1 This is the issue so that we don't forget
https://github.com/UV-CDAT/uvcdat/issues/1950

**Comment by doutriaux1** [comment]
@danlipsa ok just pushed the changes I wanted. Please review and merge if tests pass for you.

**Comment by doutriaux1** [comment]
@danlipsa I see you already merged it... Oh well...

**Comment by danlipsa** [comment]
@doutriaux1 Just make another PR and I can review it and merge it quickly.

**Comment by doutriaux1** [comment]
@danlipsa see: #1951

**Pull request merged**
