### PR TITLE
Ansible vagrant install

### PR DESCRIPTION
**Pull request by zachmullen**

### CODE REVIEW

**Comment by jbeezley** [comment]
This doesn't trigger other builders because it is from an external repository.  It doesn't really matter in this case because it is only devops content.

**Comment by zachmullen** [comment]
I am not sure if it should even go in the main uvcdat repo or if I should just keep it on my fork, just wanted to put it out there for comments just in case.

**Comment by jbeezley** [comment]
It's a little bit contrived for your use case, but so is the Dockerfile for cdatweb.  I think it is useful enough to serve as an example of a deployment method.  I'll wait for some else to give the final okay though.

**Comment by doutriaux1** [comment]
@aashish24 I'm ok with merging this, I will let you have the final say.

**Comment by aashish24** [comment]
@zachmullen @doutriaux1 I only have one suggestion. Can we move these files to its own specific folder (may be create deploy at the root level?) and then move docker and these there?

**Comment by zachmullen** [comment]
That is possible, it may require a reconfigure of server-side hooks on docker hub if they exist for the current docker file though.

**Comment by jbeezley** [comment]
The `Dockerfile` at the root actually needs to be there, but you can move the `/docker` directory anywhere.

**Comment by jbeezley** [comment]
We don't currently have any automated docker deployments (dockerhub fails to build for some unknown reason).  Dockerfiles don't support `ADD`-ing files from parent directories, so we would need a manual step to copy the `Dockerfile` to the root.  I'm not even sure if that is possible in dockerhub.

**Comment by zachmullen** [comment]
@aashish24 I moved the ansible and docker code under a "deploy" directory.

**Comment by aashish24** [comment]
thanks @zachmullen. LGTM :+1:

**Comment by zachmullen** [comment]
(BTW I don't have write access to this repo)

**Comment by aashish24** [comment]
I will add you. In the mean time, I am merging this.

**Comment by aashish24** [comment]
@doutriaux1 is it okay to add @zachmullen ?

**Comment by doutriaux1** [comment]
of course.

**Pull request merged**
