### PR TITLE
Cleanup for conda and setuptools

### PR DESCRIPTION
**Pull request by doutriaux1**
@aashish24 @chaosphere2112 can we p[lease review and merge this super fast, master is broken without out:

```
2:     f = open(os.path.join(vcs.prefix, "share", "vcs", "wmo_symbols.json"))

2: IOError: [Errno 2] No such file or directory: '/usr/local/uvcdat/04_04_16/Library/Frameworks/Python.framework/Versions/2.7/share/vcs/wmo_symbols.json'

1/1 Test #2: diags_test_02 ....................***Failed    5.62 sec
```

### CODE REVIEW

**Comment by aashish24** [comment]
LGTM :+1:

**Comment by aashish24** [comment]
@doutriaux1 I am going to update the branch with current master to trigger build again.

**Comment by doutriaux1** [comment]
@aashish24 thanks

**Comment by aashish24** [comment]
@doutriaux1 can we merge this branch?

**Comment by aashish24** [comment]
@doutriaux1 I am going to build this branch from scratch and if builds and runs fine, I am going to merge it into master since you said we needed this asap in master.

**Comment by doutriaux1** [comment]
@aashish24 yes please pretty please merge this.

**Comment by aashish24** [comment]
Okay, I will merge it after I update it to current master and run it again manually.

**Comment by aashish24** [comment]
Still building...

**Comment by aashish24** [comment]
40 - flake8_vcs (Failed)
	425 - test_vcs_continents (Failed)
	541 - test_unidata_basic_functionalities (Failed)
	542 - test_unidata_undunits2_functionalities (Failed)
	569 - CDMS_Test_multiple_formats (Failed)
	573 - CDMS_Test_detecting_axes_type (Failed)
	580 - diags_test_01 (Failed)
	581 - diags_test_02 (Failed)
	582 - diags_test_03 (Failed)
	583 - diags_test_04 (Failed)
	584 - diags_test_41 (Failed)
	585 - diags_test_05 (Failed)
	586 - diags_test_06 (Failed)
	587 - diags_test_07 (Failed)
	588 - diags_test_08 (Failed)
	589 - diags_test_09 (Failed)
	590 - diags_test_10 (Failed)
	591 - diags_test_11 (Failed)
	592 - diags_test_12 (Failed)
	593 - diags_test_13 (Failed)
	594 - diags_test_15 (Failed)

**Comment by aashish24** [comment]
1. 
40: Test command: /home/chaudhary/tools/uvcdat/build_debug/install/bin/flake8 "/home/chaudhary/tools/uvcdat/src.git/Packages/vcs/vcs/" "--show-source" "--statistics" "--max-line-length=120"
40: Test timeout computed to be: 1500
40: /home/chaudhary/tools/uvcdat/src.git/Packages/vcs/vcs/install_vcs.py:8:1: F401 'vcs' imported but unused
40: import vcs
40: ^
40: /home/chaudhary/tools/uvcdat/src.git/Packages/vcs/vcs/install_vcs.py:15:5: F811 redefinition of unused 'vcs' from line 8
40:     import vcs
40:     ^
40: /home/chaudhary/tools/uvcdat/src.git/Packages/vcs/vcs/install_vcs.py:38:13: E128 continuation line under-indented for visual indent
40:             "data_continent_states",
40:             ^
40: /home/chaudhary/tools/uvcdat/src.git/Packages/vcs/vcs/install_vcs.py:39:13: E128 continuation line under-indented for visual indent
40:             "data_continent_political",

2.

**Comment by aashish24** [comment]
[chaudhary@einstein build_debug]$ ctest -R "test_unidata_basic_functionalities" -V
UpdateCTestConfiguration  from :/home/chaudhary/tools/uvcdat/build_debug/DartConfiguration.tcl
Parse Config file:/home/chaudhary/tools/uvcdat/build_debug/DartConfiguration.tcl
UpdateCTestConfiguration  from :/home/chaudhary/tools/uvcdat/build_debug/DartConfiguration.tcl
Parse Config file:/home/chaudhary/tools/uvcdat/build_debug/DartConfiguration.tcl
Test project /home/chaudhary/tools/uvcdat/build_debug
Constructing a list of tests
Done constructing a list of tests
Checking test dependency graph...
Checking test dependency graph end
test 541
    Start 541: test_unidata_basic_functionalities

541: Test command: /home/chaudhary/tools/uvcdat/build_debug/install/bin/runtest "/home/chaudhary/tools/uvcdat/build_debug/install/bin/python" "/home/chaudhary/tools/uvcdat/src.git/testing/unidata/test_udunits.py"
541: Environment variables: 
541:  UVCDAT_ANONYMOUS_LOG=no
541: Test timeout computed to be: 1500
541: Successfully updated your environment to use UVCDAT
541: (changes are valid for this session/terminal only)
541: Version: v2.5.0-283-g5ff1645
541: Location: /home/chaudhary/tools/uvcdat/build_debug/install
541: Reset these changes by running: source /home/chaudhary/tools/uvcdat/build_debug/install/bin/reset_runtime.sh
541: 5.0 m
541: 7.0 cm
541: 3.0 in
541: 5.0 feet
541: Traceback (most recent call last):
541:   File "/home/chaudhary/tools/uvcdat/src.git/testing/unidata/test_udunits.py", line 20, in <module>
541:     o = m+cm
541:   File "/home/chaudhary/tools/uvcdat/build_debug/install/lib/python2.7/site-packages/unidata/udunits.py", line 238, in __add__
541:     s, i = udunits_wrap.convert(other.units, self.units)
541: TypeError: UDUNITS Error: invalid udunits: cm
1/1 Test #541: test_unidata_basic_functionalities ...***Failed    0.11 sec

0% tests passed, 1 tests failed out of 1

**Comment by aashish24** [comment]
@doutriaux1 few new tests are failing on my machine. Can you confirm if they are failing for you as well?

**Comment by doutriaux1** [comment]
let me run it here as well

**Comment by doutriaux1** [comment]
similar issues as you @aashish24 looking into it right now:

The following tests FAILED:
	 40 - flake8_vcs (Failed)
	425 - test_vcs_continents (Failed)
	541 - test_unidata_basic_functionalities (Failed)
	542 - test_unidata_undunits2_functionalities (Failed)
	573 - CDMS_Test_detecting_axes_type (Failed)
	580 - diags_test_01 (Failed)
	582 - diags_test_03 (Failed)
	583 - diags_test_04 (Failed)
	584 - diags_test_41 (Failed)
	585 - diags_test_05 (Failed)
	586 - diags_test_06 (Failed)
	587 - diags_test_07 (Failed)
	588 - diags_test_08 (Failed)
	589 - diags_test_09 (Failed)
	590 - diags_test_10 (Failed)
	593 - diags_test_13 (Failed)
	594 - diags_test_15 (Failed)

**Comment by doutriaux1** [comment]
@aashish24 @chaosphere2112 thinks the vcs_test_continents is meesed up and should be updated. I fixed the other issues, I think it's worth merging in asap and fix vcs_test_continent in a separate PR.

**Comment by aashish24** [comment]
> @aashish24 @chaosphere2112 thinks the vcs_test_continents is meesed up and should be updated.

@doutriaux1 I totally agree with you. it has been broken for some time see message from @danlipsa. I will test your branch again and if other tests are passing, then will give +2 today.

**Comment by aashish24** [comment]
LGTM +2 

	425 - test_vcs_continents (Failed)
	569 - CDMS_Test_multiple_formats (Failed)
	581 - diags_test_02 (Failed)
	582 - diags_test_03 (Failed)
	583 - diags_test_04 (Failed)
	584 - diags_test_41 (Failed)
	585 - diags_test_05 (Failed)
	586 - diags_test_06 (Failed)
	587 - diags_test_07 (Failed)
	588 - diags_test_08 (Failed)
	589 - diags_test_09 (Failed)
	590 - diags_test_10 (Failed)
	591 - diags_test_11 (Failed)
	592 - diags_test_12 (Failed)
	593 - diags_test_13 (Failed)
	594 - diags_test_15 (Failed)

**Comment by doutriaux1** [comment]
Thnaks @aashish24 I'll be sending a PR with updated baselines for diags shortly.

**Pull request merged**
