### PR TITLE
Vtk master bump

### PR DESCRIPTION
**Pull request by dlonie**
Update code to work with new VTK master. See commit messages for details of changes.

This PR requires the following changes to the following repos:
- VTK needs to use UV-CDAT/VTK#5
- uvcdat-testdata needs UV-CDAT/uvcdat-testdata#53

**I'm missing one baseline from the testdata patch.** I'm on arch, so the dv3d vector test fails for me (https://open.cdash.org/testDetails.php?test=339707560&build=3831990). Can someone run that test with this uvcdat/vtk and send me a baseline with the new text, but not the line. IIRC the bug doesn't affect ubuntu or mac.

This PR should also be manually tested, since the buildbots won't pick up the VTK change.

@doutriaux1 @chaosphere2112

### CODE REVIEW

**Comment by dlonie** [comment]
@aashish24 The changes to vector plots (removing `vcs2vtk.stripGrid`) required a patch to VTK. The corresponding VTK merge request is here:

https://gitlab.kitware.com/vtk/vtk/merge_requests/242

**Comment by chaosphere2112** [comment]
@dlonie I've just finished a build with this update, so I'm going to run the tests + give you the new baseline.

**Comment by chaosphere2112** [comment]
@dlonie [Here](https://open.cdash.org/viewTest.php?onlyfailed&buildid=3832183) are my results... your updated baselines for test_vtk_ui_label_(top|x|y|left) are all incorrect. Don't know why the lines rendered that way on your system, but they should look like they used to (with a single pixel line).

**Comment by chaosphere2112** [comment]
@dlonie Looks like the dv3d tests are only different in the label, so they should be fine.

**Comment by chaosphere2112** [comment]
@dlonie Rest of the issues were all with this:
```
  File "/Users/samfries/bin/uvcdat/new_vtk/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/vcs/vcs2vtk.py", line 62, in putMaskOnVTKGrid
    vtk.vtkDataSetAttributes.GhostArrayName())
AttributeError: GhostArrayName
```

**Comment by chaosphere2112** [comment]
@dlonie And this:

```
  File "/Users/samfries/bin/uvcdat/new_vtk/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/vcs/vcs2vtk.py", line 79, in putMaskOnVTKGrid
    vtk.vtkDataSetAttributes.HIDDENPOINT
AttributeError: HIDDENPOINT

```

**Comment by chaosphere2112** [comment]
@dlonie Also has an issue with `GhostArrayName` on line 51 of vcs2vtk

**Comment by dlonie** [comment]
@chaosphere2112 

Re: Text alignment: I noticed the line was thicker on my system, but the text looks better aligned to my eye. Might be another platform issue? Feel free to send me some better ones if they look better on your system.

Re: vtkDataSetAttributes.* issues: Did you checkout the new VTK branch, and run `make install` in build/VTK-build? Those symbols are defined in the new VTK.

**Comment by doutriaux1** [comment]
@dlonie what's the status on this? Should I try and generate a new baseline? From Ubunut? From Mac?

**Comment by dlonie** [comment]
I think Mac would be ideal, since I've run the tests on linux, and should check for platform specific stuff on Mac. Just be sure to build and install the VTK branch mentioned in the first post. Let me know if you run into any issues with it.

Thanks!

**Comment by doutriaux1** [comment]
works for me on mac now see:
https://open.cdash.org/buildSummary.php?buildid=3841120

**Comment by doutriaux1** [comment]
merging

**Comment by dlonie** [comment]
What is the state of this at the moment? I see that this was merged, and then there's a closed, unmerged PR to revert it, and neither this branch nor the revert branch appear in master.

The VTK branch will have to be manually pushed, unless we have a new procedure for it. We've been just rebasing and pushing manually in the past to keep the modifications on top to more easily identify the difference with upstream.

**Comment by doutriaux1** [comment]
@dlonie I first merged this one then realized that would break everything since I couldn't update VTK. So I created a revert PR. But then I realize that @aashish24 would complain that the history is not clean. So I pushed back (-f) to the state before this PR goes in and closed the revert PR. Once you merged VTK we can use the re-issued PR to merge this ( #1357 ) which you merged so we should be good.

**Pull request merged**
