### PR TITLE
1625 line stipple

### LINKED ISSUE #1625: isolines GUI editor not connected

### PR DESCRIPTION
**Pull request by sankhesh**
Fixes #1625

### CODE REVIEW

**Comment by sankhesh** [comment]
@doutriaux1 @aashish24

**Comment by sankhesh** [comment]
:bell: Ping!

**Comment by aashish24** [comment]
@sankhesh this branch needs to be updated as it has merge conflict..

**Comment by doutriaux1** [comment]
@sankhesh I would like to merge this branch AFTER the colormaps one, as I think it will be easier to merge potential breakage that way.

**Comment by sankhesh** [comment]
@doutriaux1 This branch is ready for merge.

The failures are because I did not merge your `colormaps` baselines with this branch's baselines. If you like I can do that and re-trigger these builds.

**Comment by sankhesh** [comment]
Please make sure to merge #1693 before merging this branch.

**Comment by sankhesh** [comment]
Re-triggered builds with new baselines.

**Comment by doutriaux1** [comment]
Rh full issues are xfvb related. I probably need to restart it. Rh mesa passes. Will wait for a Mac and merge in

**Comment by doutriaux1** [comment]
@sankesh will update thrshold on your test failing on Ubuntu 15.10 before merging in if macs come out ok

**Comment by aashish24** [comment]
@doutriaux1 so this would be our last PR for now?

**Comment by doutriaux1** [comment]
@aashish24 yes, but stipple test fails. What do you prefer try with a new baseline? Or increase threshold and merge?

**Comment by aashish24** [comment]
@doutriaux1 I looked at the differences and to me it seems to be system specific changes and not that the code is buggy. I would suggest increase the threshold and merge.

**Comment by aashish24** [comment]
@sankhesh can you increase the threshold?

**Comment by chaosphere2112** [comment]
@sankhesh @aashish24 Yeah, I had to up the threshold for my stipple test.

**Comment by sankhesh** [comment]
Done.

**Comment by aashish24** [comment]
thanks @sankhesh

**Pull request merged**
