### PR TITLE
we used to have two path for rendering a frame

### LINKED ISSUE #1845: animation save does not preserve the colormap
```python
import vcs
import cdms2
f=cdms2.open(vcs.sample_data+"/clt.nc")
s=f("clt")
x=vcs.init()
x.setcolormap("AMIP")
x.plot(s)
x.interact()
```

### PR DESCRIPTION
**Pull request by doutriaux1**
the one saving pngs was broken and not preserving pngs
two paths are now unified
this also fixes zoom on animations.
fix #1845

---
This change is [Reviewable](https://reviewable.io/reviews/uv-cdat/uvcdat/2028)

### CODE REVIEW

**Comment by doutriaux1** [comment]
@aashish24 @chaosphere2112

**Comment by doutriaux1** [comment]
@danlipsa

**Comment by aashish24** [comment]
How do we test it @doutriaux1 ?

**Comment by doutriaux1** [comment]
```python
import vcs
import cdms2
import os
            
f=cdms2.open(os.path.join(vcs.sample_data,"clt.nc"))
s=f("clt",slice(0,12))
            
x=vcs.init(geometry=(800,600))
x.colormap = "AMIP" 
x.plot(s)       
x.animate.create(thread_it=1)
x.animate.zoom(2)
#x.animate.run()
raw_input("Press enter")
x.animate.save("crap.mp4")
```

**Comment by danlipsa** [comment]
@doutriaux1 Do we have a test that failed before and passes with this change?

**Comment by doutriaux1** [comment]
nope. and animation testing are such a pain... I guess we could edit all of our exisiting animation test and force them to have a different colormap.

**Comment by danlipsa** [comment]
@doutriaux1 Probably its enough if you only change one. If its easy to do it may be worth it - if not, its fine.

**Comment by aashish24** [comment]
LGTM :+1: but I didn't run testing.

**Comment by aashish24** [comment]
@doutriaux1 @danlipsa can we merge this now?

**Pull request merged**
