### PR TITLE
Updated coverage

### PR DESCRIPTION
**Pull request by aashish24**
Refs #1302 

Pushed so that we can buildbot on it

### CODE REVIEW

**Comment by chaosphere2112** [comment]
@aashish24 I'll move my development over to this branch, so I can keep it up to date with buildbot.

**Comment by aashish24** [comment]
@chaosphere2112 any update on this?

**Comment by chaosphere2112** [comment]
Nope; just got back from paternity, my top priority right now is getting the ACME Issues site working, so I'll be getting back to this in hopefully the next week or so.

**Comment by aashish24** [comment]
@chaosphere2112 any update on this?

**Comment by chaosphere2112** [comment]
@aashish24 Still nothing to report; I haven't touched this as of yet. I'm working with Remi this week on GUI stuff, so hopefully next week I can go back in and get this to a merge-able state.

**Pull request closed without merging**
