### PR TITLE
Fixed doWrap method for vectors

### PR DESCRIPTION
**Pull request by aashish24**

### CODE REVIEW

**Comment by aashish24** [comment]
Fixes #653 #1560

**Comment by aashish24** [comment]
@doutriaux1 @sankhesh please review. 

@doutriaux1 how can I create a test that will force the code to duplicate the data?

**Comment by aashish24** [comment]
@williams13 if this works, this should fix all of the remaining issues with vector plots and projection. Please test it when you get a chance

**Comment by williams13** [comment]
Will do!  Thanks!

**Comment by aashish24** [comment]
@doutriaux1 all of the tests are passing.

**Comment by doutriaux1** [comment]
@aashish24 please add a test for it. How do you even know it works if you didn't test it?
to test read data let's say between 0 360 and plot -180/180 or vice versa.
to read data within a range:
```python
import cdms2
f=cdms2.open(file)
s=f(data,longitude=(0,360))
```

**Comment by doutriaux1** [comment]
@aashish24 also your commit quality wasn't what you used us to. No description of what you changed and why. A bit disappointed here :wink:

**Comment by doutriaux1** [comment]
@aashish24 I just add a test that shows it is still broken. Run the file with either `lon1 = 0.` or `lon1 = -180.` it fails in two different ways.

**Comment by aashish24** [comment]
> @aashish24 also your commit quality wasn't what you used us to. No description of what you changed and why. A bit disappointed here

:) The changes I made should be obvious and since the other lines were not commented, I didn't comment new lines. I am planning to update these classes in the future.

**Comment by aashish24** [comment]
@doutriaux1 ah.. thanks for the test. that was my other question.

**Comment by aashish24** [comment]
@doutriaux1 your original test code is buggy, you are getting clt for both u and v. If I modified your code to get the actual vectors, I am getting the right plot. Here is the code:
```python
import cdms2
import vcs
import os
import sys

f=cdms2.open(os.path.join(vcs.sample_data,"clt.nc"))

# -180 failks as well
lon1 = -180
u=f("u")
v=f("v")

u=u(longitude=(lon1,lon1+360.))
v=v(longitude=(lon1,lon1+360.))

x=vcs.init()
Vec = x.createvector()
p = x.createprojection()
p.type = "mercator"
Vec.projection = p
x.plot(u,v,Vec)
raw_input("press enter")
```
mercator

**Comment by aashish24** [comment]
Now I used the mercator. With Polar, I think vector plot will be really bad in general but I think that's a separate issue which I believe I mentioned earlier that vector plot in polar coordinates may require some more work.

**Comment by aashish24** [comment]
@doutriaux1 fixed the scaling issue that was causing vectors not to show up in polar coordinates.

**Comment by aashish24** [comment]
Goes with: https://github.com/UV-CDAT/uvcdat-testdata/pulls

**Comment by aashish24** [comment]
@doutriaux1 @sankhesh please approve

**Comment by doutriaux1** [comment]
@aashish24 my original code was NOT buggy, "u" and "v" are wrong in this file and do not get wrapped around by cdms2. Which is why I used "clt" twice, we don't care about how realstic the test is, only that is reproduces the features we are trying to fix.

**Comment by doutriaux1** [comment]
@aashish24 you need to at least flake8 it. I will review your test because I'm worried your change to "u" and "v" actually prevents it from reproducing the bug we are trying to fix.

**Comment by aashish24** [comment]
@doutriaux1 just using CLT twice would not produce any reasonable vectors. I don't understand why we cannot use u and v? for all other tests aren't we using u and v? I was able to reproduce the bug if I don't fix the scale factor. In case of POLAR coordinates the scales were off.

**Comment by aashish24** [comment]
@doutriaux1 I will fix the style issue. I didn't see them on garant and that's why I thought all is good.

**Comment by aashish24** [comment]
> @aashish24 my original code was NOT buggy, "u" and "v" are wrong in this file and do not get wrapped around by cdms2. Which is why I used "clt" twice, we don't care about how realstic the test is, only that is reproduces the features we are trying to fix.

@doutriaux1 thanks. Is it possible to use better data? If we use clt twice then when projected, vectors will be drawn really bad or not drawn at all.

**Comment by aashish24** [comment]
@doutriaux1 flake8 should be fixed now (had unused import). Also, I tried with clt (for both u and v) works for me. Once you look at it, I can update the test to use clt

**Comment by aashish24** [comment]
Okay, tested with clt, vectors look awful but the code seems to be working. @doutriaux1 please let me know if the code is still broken. I saw another issue (not with vectors but with continental lines).

**Comment by aashish24** [comment]
@doutriaux1 should be all good. Please review.

**Comment by aashish24** [comment]
@doutriaux1 ping!

**Comment by aashish24** [comment]
@doutriaux1

**Comment by aashish24** [comment]
@doutriaux1 :smiley_cat:

**Comment by doutriaux1** [comment]
@aashish24 catching up... slowly...

**Comment by doutriaux1** [comment]
@aashish24 still fails for ploar is that expected you say?

**Comment by doutriaux1** [comment]
polar

**Comment by aashish24** [comment]
@doutriaux1 if you use just clt and polar, yes since it will spread them weirdly. If i just use u and v (no wrapping) it does look reasonable but please have a closer look at polar one. All other projections looks great to me.

**Comment by aashish24** [comment]
@doutriaux1 thanks :+1: :smile: :

**Pull request merged**
