### PR TITLE
Issue1379 durack1 update Python 2.7.9 to 2.7.10

### PR DESCRIPTION
**Pull request by durack1**

### CODE REVIEW

**Comment by durack1** [comment]
@jbeezley @doutriaux1 is the `test-laptop` missing some package(s) which is causing the DODS read failure?

**Comment by jbeezley** [comment]
`503 Service Temporarily Unavailable` That seems to happen fairly regularly.

**Comment by durack1** [comment]
@jbeezley it does seem to happen quite alot.. It seems at least from here that the connection to http://test.opendap.org/opendap/hyrax/ is really slow, I wonder if a connection timeout can be avoided here?

**Comment by durack1** [comment]
@doutriaux1 @dlonie @chaosphere2112 the `time.sleep(2)` in [this PR](https://github.com/UV-CDAT/uvcdat/blob/issue788_durack1_removeDeprecatedFoldersAndFiles/testing/vcs/vtk_ui/test_vtk_ui_manager_resize.py#L20)

**Comment by durack1** [comment]
@doutriaux1 @dlonie @chaosphere2112 the `time.sleep(2)` in [this PR](https://github.com/UV-CDAT/uvcdat/blob/issue788_durack1_removeDeprecatedFoldersAndFiles/testing/vcs/vtk_ui/test_vtk_ui_manager_resize.py#L20) #1341 would appear to solve the [vcs test problem](https://open.cdash.org/testDetails.php?test=345370187&build=3861303) below

Apologies for the partially completed comment earlier - the above should be more descriptive..

**Comment by durack1** [comment]
@doutriaux1 can you check and merge this, it's also got the `time.sleep(2)` fix made in #1341 - this one reduces the `sleep` to 1s

**Pull request merged**
