### PR TITLE
Issue1212 durack1 spyder2.3.4 update

### LINKED ISSUE #1212: Update spyder to 2.3.4
We're a patch release behind the latest spyder (2.3.3 vs 2.3.4) - a number of bug fixes in 2.3.4 are worth the effort in updating..

### PR DESCRIPTION
**Pull request by durack1**

### CODE REVIEW

**Comment by durack1** [comment]
@aashish24 this is a great candidate for testing out the travis build issue - the `lean` build never touches the spyder source, so there is absolutely no reason why this pull request should have reported an error.

**Comment by durack1** [comment]
@aashish24 @jbeezley @doutriaux1 should I tweak and resubmit this PR for testing through the new build system? As noted above spyder is never even touched in the lean builds that were configured last time this PR was updated...

**Comment by aashish24** [comment]
@durack1 don't worry about it. Can it wait until 2.2 happens?

**Comment by durack1** [comment]
@aashish24 @doutriaux1 if it was possible it'd be great to get this patch update into 2.2.. But if you guys are trying to simplify things 2.3 would be ok I suppose..

**Comment by aashish24** [comment]
@durack1 we have a strict deadline which is due in next few days. You wait is really appreciated. We will get it merged as soon as we tag 2.2

**Comment by durack1** [comment]
@doutriaux1 @aashish24 I just had a go at rebasing this off UV-CDAT/uvcdat release branch, I'm doubtful this will build.. So please ignore this..

**Comment by durack1** [comment]
@doutriaux1 @aashish24 ok wow, it did (not all that surprising as it's now basically just the release branch, with the spyder update which is never built)..

@doutriaux1 I'm not sure you folks feel comfortable about merging such changes for 2.2?

**Comment by doutriaux1** [comment]
@durack1 I'll try a full build again once #1267 has been approved. If it works then I guess i'll merge it in.

**Comment by durack1** [comment]
Ok great, I'll do the same rebasing for #1129, #1130 and #1131 and see how these also go..

**Comment by durack1** [comment]
@doutriaux1 you might want to cherry pick the one file that's changed CMake/cdat_modules/spyder_pkg.cmake

**Comment by durack1** [comment]
@doutriaux1 @aashish24 @jbeezley this PR should be deprecated by #1300 which seems to have triggered the buildbot testing

**Comment by durack1** [comment]
@aashish24 @jbeezley @doutriaux1 it still seems those 3 errors, DVD3D image lines, DODS and netcdf version being picked up errors are still occurring: https://open.cdash.org/viewTest.php?onlyfailed&buildid=3808629

**Comment by durack1** [comment]
@aashish24 @jbeezley it seems that netcdf version issue is only a problem on garant. The test-laptop only has the DVD3D image line and the DODS issue..

**Comment by jbeezley** [comment]
I fixed that in #1298, which isn't in master.  `test-laptop` is compiling `libcf` against a system installed `lapack`.  `garant` doesn't have a system installed `lapack`, so it builds without regridding.

**Comment by durack1** [comment]
@doutriaux1 @aashish24 should #1298 also be merged into master then?

**Comment by aashish24** [comment]
@durack1 looks like @jbeezley had it merged into another PR.

**Comment by durack1** [comment]
@doutriaux1 closing this and will reissue a new PR rebased off current master

**Pull request closed without merging**
