### PR TITLE
adds a warning about removing .dodsrc file

### PR DESCRIPTION
**Pull request by doutriaux1**

### CODE REVIEW

**Comment by durack1** [comment]
@doutriaux1 almost all green! Just a couple of tweaks required:
```
crunchy
The following tests FAILED:
	 26 - testDistTransientVar6Pes (Timeout)
	487 - rpy2_verify_import (Failed)
```
```
annie
The following tests FAILED:
	 26 - testDistTransientVar6Pes (Timeout)
	479 - CDMS_Test_multiple_formats (Failed)
```

**Comment by dnadeau4** [comment]
testDistTransientVar6Pes is the weird numpy bug that I found.

    vi .lib/python2.7/site-packages/numpy/ma/core.py:3405

                 _fill_value = target  #works????



Denis

**Comment by doutriaux1** [comment]
@dnadeau4 @aashish24  please merge in

**Comment by aashish24** [comment]
LGTM :100:

**Pull request merged**
