### PR TITLE
issue1538 durack1 update Cython 0.22.1 to 0.23.3

### LINKED ISSUE #1538: Update Cython to 0.23.3
We are a couple of patches behind Cython latest (0.22.1 vs 0.23.2).

@doutriaux1 want to assign me as a 2.4 milestone?

### PR DESCRIPTION
**Pull request by durack1**
Fix #1538 - Update Cython 0.22.1 to 0.23.1

### CODE REVIEW

**Comment by durack1** [comment]
@doutriaux1 on `oceanonly` it seems there are some files missing:
```
389/461 Test #309: vcs_test_isofill_patterns ...............................***Failed   65.23 sec
File "/export/doutriaux1/bots_oceanonly/build/uvcdat-testdata/baselines/vcs/test_isofill_patterns.png" not found.
```

**Comment by durack1** [comment]
@doutriaux1 looks to be a [similar missing test image issue on garant](https://open.cdash.org/viewTest.php?onlyfailed&buildid=4003435) along with a behavior change with [overplotting hatching or similar](https://open.cdash.org/testDetails.php?test=372352977&build=4003435)

**Comment by durack1** [comment]
Looks like [`0.23.2` just landed](http://trac.cython.org/query?group=status&milestone=0.23.2) to fix an issue on `OS X` I'll update the PR..

**Comment by durack1** [comment]
@doutriaux1 is `aims4` the buildbot server up and running today?

**Comment by doutriaux1** [comment]
on and off, playing with it. I will resubmit yours. But only the RHs are up at the moment, Mac decided to not let me in...

**Comment by durack1** [comment]
@doutriaux1 the `0.23.2` patch release was specifically created to deal with an `OS X` issue, so it would certainly be good to test this against the `macbot` if you can..

**Comment by durack1** [comment]
@doutriaux1 the `0.23.2` patch release was specifically created to deal with an `OS X` issue, so it would certainly be good to test this against the `macbot` if you can..

**Comment by durack1** [comment]
@doutriaux1 `macbot` still choking? It also seems the other `LLNLbots` are also having some problems..

**Comment by durack1** [comment]
@doutriaux1 looks like `Xvfb` might need a restart on `oceanonly` - is there a way to trigger a new `Xvfb` session for each test?

**Comment by doutriaux1** [comment]
@durack1 I restarted Xfvb, I 'm afraid some bad PR went in....

**Comment by doutriaux1** [comment]
and no they're not choking I just went to look, just seem to be taking forever...

**Comment by doutriaux1** [comment]
@aashish24 I just double check a bunch of tests are now failing on RH6... Checking Ubuntu as well...

These used to work, I'm going to go back slowly and see last commit that worked... I think some PR went in too hastily.

**Comment by jbeezley** [comment]
According to cdash [77c1c61bece](https://open.cdash.org/buildSummary.php?buildid=4009653) had only 1 failure on ocean only.  The only commits merged after that are the following:

```
$ git cherry -v 77c1c61bece origin/master
+ 7dcafcd24f33f48068ebb6804ee59dc456a7d6ab Dramatically cuts down on the number of renderers used per plot
+ f7cf54cdc0f4f7d41ae4165ea3c48925df656532 Fixed missing background/vtk errors for click_info, added a test
+ 616cf4d61589739c3403d4b4e3264ba9318928e3 Update isofillpipeline.py
+ 91316fff34bc4a1b24d36d43c8809db39ed7e0fe Removed extra tab to trigger rebuild
+ 3ff13b4c8834941ce3abf0b823e262a6cdccdae0 Put extra tab back to resolve merge conflict
```

**Comment by doutriaux1** [comment]
@jbeezley yes i went way way back and it still shows up the same errors whereas crunchy is stable. So something happened to oceanonly. That's good in the sense that it means our code is not broken!

**Comment by durack1** [comment]
@doutriaux1 and using my interactive session these are the errors I also get:
```
91% tests passed, 40 tests failed out of 458

Total Test time (real) = 249.77 sec

The following tests FAILED:
         42 - vcs_no_xtra_elts (Failed)
         43 - vcs_line_duplicate_points_fix (Failed)
         46 - vcs_test_antialiasing (Failed)
         94 - vcs_test_markers (Failed)
         95 - vcs_test_star_triangle_markers (Failed)
        104 - test_vcs_box_custom_as_def_vistrails_exts (Failed)
        118 - vcs_test_bad_time_units (Failed)
        119 - vcs_test_plot_file_varible (Failed)
        269 - vcs_test_basic_meshfill_0_proj_NH (Failed)
        273 - vcs_test_basic_meshfill_0_proj_NH_gm (Failed)
        274 - vcs_test_basic_meshfill_0_proj_NH_gm_flip (Failed)
        279 - vcs_test_basic_meshfill_-3_proj_NH (Failed)
        283 - vcs_test_basic_meshfill_-3_proj_NH_gm (Failed)
        284 - vcs_test_basic_meshfill_-3_proj_NH_gm_flip (Failed)
        289 - vcs_test_basic_meshfill_aeqd_proj_NH (Failed)
        293 - vcs_test_basic_meshfill_aeqd_proj_NH_gm (Failed)
        294 - vcs_test_basic_meshfill_aeqd_proj_NH_gm_flip (Failed)
        297 - vcs_test_isoline_labels_multi_label_input_types (Failed)
        298 - vcs_test_isoline_labels (Failed)
        299 - vcs_test_isoline_labelskipdistance (Failed)
        300 - vcs_test_isofill_isoline_labels (Failed)
        302 - vcs_test__patterns (Failed)
        314 - vcs_test_close (Failed)
        322 - vcs_test_animate_isoline_text_labels (Failed)
        323 - vcs_test_animate_isoline_text_labels_colored (Failed)
        326 - vcs_test_configurator_click_text (Failed)
        328 - vcs_test_configurator_click_marker (Failed)
        382 - test_vtk_ui_manager_resize (Failed)
        390 - vcs_addons_preview_2x2 (Failed)
        391 - vcs_addons_test_12_plot_one_leg_per_row (Failed)
        392 - vcs_addons_test_12_plot_one_leg_per_row_right (Failed)
        393 - vcs_addons_test_EzTemplate_12_plots_margins_thickness (Failed)
        394 - vcs_addons_test_EzTemplate_12_plots_legd_direction (Failed)
        395 - vcs_addons_test_EzTemplate_12_plots_mix_glb_local (Failed)
        396 - vcs_addons_test_EzTemplate_12_plots_spacing (Failed)
        398 - Hovmoller_volume_test (Failed)
        399 - dv3d_vector_test (Failed)
        400 - dv3d_slider_test (Failed)
        401 - dv3d_volume_test (Failed)
        447 - CDMS_Test_multiple_formats (Failed)
```

**Comment by durack1** [comment]
@doutriaux1 and what has been upgraded since 20th August 2015:
```
flash-plugin                             Thu 20 Aug 2015 01:42:03 PM PDT
httpd-tools                              Thu 27 Aug 2015 11:02:36 AM PDT
httpd                                    Thu 27 Aug 2015 11:02:37 AM PDT
thunderbird                              Thu 27 Aug 2015 11:02:45 AM PDT
firefox                                  Sat 29 Aug 2015 11:49:15 AM PDT
nss-softokn-freebl                       Sun 06 Sep 2015 05:30:08 PM PDT
nss-softokn-freebl-devel                 Sun 06 Sep 2015 05:30:09 PM PDT
nss-softokn                              Sun 06 Sep 2015 05:30:09 PM PDT
gdk-pixbuf2                              Sun 06 Sep 2015 05:30:10 PM PDT
bind-libs                                Sun 06 Sep 2015 05:30:12 PM PDT
selinux-policy                           Sun 06 Sep 2015 05:30:13 PM PDT
selinux-policy-targeted                  Sun 06 Sep 2015 05:30:15 PM PDT
bind-utils                               Sun 06 Sep 2015 05:30:37 PM PDT
gdk-pixbuf2-devel                        Sun 06 Sep 2015 05:30:37 PM PDT
libXfont                                 Sun 06 Sep 2015 05:30:38 PM PDT
nss-softokn-devel                        Sun 06 Sep 2015 05:30:38 PM PDT
nss-softokn-freebl                       Sun 06 Sep 2015 05:30:38 PM PDT
nss-softokn                              Sun 06 Sep 2015 05:30:38 PM PDT
spice-server                             Sun 06 Sep 2015 05:30:38 PM PDT
gdk-pixbuf2                              Sun 06 Sep 2015 05:30:39 PM PDT
tk                                       Thu 10 Sep 2015 04:32:15 PM PDT
```

**Comment by doutriaux1** [comment]
@durack1 I'm at a loss here. crunchy still works and it seems to have been upgraded as well... Trying with MESA now, if that still fails let's go for a reboot...

**Comment by durack1** [comment]
@doutriaux1 yep I think that sounds like a good idea.. I'll poll other users in the interim..

**Comment by durack1** [comment]
@doutriaux1 `ocean` is rebooted, so can you initialize the bot testing for this PR again please?

**Comment by doutriaux1** [comment]
@durack1 please stop pushing PR for now, we have do let the bots deal with the 2.4 branches first. Thanks

**Comment by durack1** [comment]
@doutriaux1 I'm not touching this.. Just hoping the buildbots can run an accurate test against the PR however..

**Comment by jbeezley** [comment]
@doutriaux1 Assuming you haven't changed the tangelo proxy.  It builds on push not on PR, so **any** push to this repository that updates the SHA of **any** branch will trigger it.

**Comment by doutriaux1** [comment]
yes so that's why I was asking @durack1 to try to refrain to trigger any rebuild until after the release because we push more frequently when near the release and we need to see the results as fast as possible.

**Comment by durack1** [comment]
@doutriaux1 looks like there are persistent errors, both with this PR and #1539:
```
crunchy
The following tests FAILED:
	486 - rpy2_verify_import (Failed)
```
and
```
annie
The following tests FAILED:
	478 - CDMS_Test_multiple_formats (Failed)
```

**Comment by durack1** [comment]
@doutriaux1 looks like the same`vcs_test_click_info` [graphics issue on `garant`](https://github.com/UV-CDAT/uvcdat/pull/1557#issuecomment-142749695) is also happening with this [PR](https://open.cdash.org/testDetails.php?test=376430179&build=4027061)

**Comment by durack1** [comment]
@doutriaux1 @chaosphere2112 at least travis doesn't discriminate my PR queue priority.. Look at those shiny green ticks..

**Comment by chaosphere2112** [comment]
@durack1 All part of @doutriaux1's cunning plan to slowly drive you mad :smiling_imp:

**Comment by doutriaux1** [comment]
why slowly? Oh yes it's more fun to watch the process `slowly` working.

**Comment by durack1** [comment]
`##bot @doutriaux1 says I'm not worthy##`

**Comment by durack1** [comment]
@doutriaux1 @chaosphere2112 have the lower class PR citizens queues started running yet?

**Comment by doutriaux1** [comment]
@durack1 happy now? :wink:

**Comment by durack1** [comment]
@doutriaux1 well at least that's one less PR to block up the `bot` queue..

**Pull request merged**
