### PR TITLE
remove default parameter assignment on getcolors. Fixes #2097.

### LINKED ISSUE #2097: VCS: vcs.utils.getcolors provides a default value for colors parameter
huge_range
This makes the documentation horrible to look at, and is probably bad practice anyway. 
I'm going to set colors=None and put an if statement in the function that assigns it to this range if colors=None, to clean it up.

### PR DESCRIPTION
**Pull request by embrown**
changed colors=range(16, 240) to colors=None. 
Added if statement to set colors=range(16, 240) if parameter not provided.

### CODE REVIEW

**Comment by aashish24** [comment]
@embrown I liked the idea. Can you fix the style?

**Comment by doutriaux1** [comment]
@embrown is just for the doc? Makes the code look silly, like we don't know about default values.

**Comment by embrown** [comment]
@doutriaux1 Yeah, it was primarily for the doc. When sphinx went through to generate the function prototype for this one, it spit out that full range of numbers inside the prototype, which looked horrible.
Thank you for merging!

**Comment by aashish24** [comment]
@doutriaux1 @embrown it would have been nice to fix the bad white space before merging.

**Comment by doutriaux1** [comment]
yes... it will be merged next time

**Pull request merged**
