### PR TITLE
Coverage.py integration

### PR DESCRIPTION
**Pull request by chaosphere2112**
This PR integrates our ctest infrastructure with `coverage.py` to measure the coverage numbers of our tests. To measure coverage, you have to use a special build flag: `-DCDAT_MEASURE_COVERAGE=ON`. You should then be able to just run ctest at whatever your preferred parallelism is, and when your tests finish running (we should probably add a test that fails based on coverage numbers, but that's beyond the scope of this PR), your `Testing` directory will be littered with `.coverage` files. At that point, you can run the new script I've added, `coverage_report`, which will gather all of those files and merge them into a single data file then provide package-level statistics on the coverage numbers. It will also ask if you want to generate an HTML report that provides a per-file analysis of each module measured, and let you know which lines were not executed. You can re-run `coverage_report` as many times as you like without rerunning tests; it will ask if you want to replace the current coverage file (which you should only answer `y` to after you re-run tests).

@aashish24 @jbeezley If someone at Kitware wants to integrate `coverage.py` with CDash, you can go ahead; this is good enough for LLNL's purposes, I think.

If you're interested, here's where we're at on coverage:

   Package   |  % Covered  |Lines Missing| Total Lines 
-------------|-------------|-------------|-------------
    cdms2    |   51.46%    |    6189     |    12750    
   cdutil    |   58.46%    |    1103     |    2655     
    DV3D     |   37.54%    |    8576     |    13730    
   genutil   |   19.21%    |    2931     |    3628     
   regrid2   |   55.66%    |    1007     |    2271     
     vcs     |   59.40%    |    7457     |    18369    
 vcs.editors |   28.53%    |     957     |    1339     
 vcs.vcsvtk  |   89.77%    |     148     |    1447     
 vcs.vtk_ui  |   74.47%    |     490     |    1919     
  vcsaddons  |   32.07%    |     625     |     920

### CODE REVIEW

**Comment by chaosphere2112** [comment]
This one's for you, @durack1 :wink:

**Comment by chaosphere2112** [comment]
Also @doutriaux1 may be interested in these numbers

**Comment by aashish24** [comment]
> Also @doutriaux1 may be interested in these numbers

This is great @chaosphere2112 :clap: only one comment that it wasn't planned in this sprint :cry:. Let's make sure that plan tasks in advance. Yes, I believe there is a way to intergration into cdash. I or @danlipsa can look into it.

**Comment by aashish24** [comment]
vcsvtk coverage looks great, genutil definately needs some love. @jbeezley and I were talking about coverage last week so this is great that we have some numbers. I was hoping for 50% for VCS :smile:

**Comment by durack1** [comment]
@chaosphere2112 nice! I'm sure @dnadeau4 will also be very interested in this

**Comment by jbeezley** [comment]
Girder pushes coverage to cdash like this: https://github.com/girder/girder/blob/master/tests/PythonTests.cmake#L33-L618

Basically, you just have to generate an xml report (`coverage report xml`) as a file named `${PROJECT_BINARY_DIR}/coverage.xml` and the submission phase of `ctest` will pick it up.

**Comment by chaosphere2112** [comment]
@aashish24 Yeah, this work was almost entirely done in like November and I put off finishing it till "after the release", which wound up being now. I just spent a few hours cleaning it up and formatting it into a PR.

@jbeezley If that's all that's necessary, it should be pretty easy to hammer out. Is there any convenient way to specify some tasks to run after tests are complete? Or should I just have a "test" that generates the coverage report?

**Comment by jbeezley** [comment]
@chaosphere2112 There aren't any explicit setUp/tearDown capabilities in CMake, but you can create tests that run before and after other tests using the `DEPENDS` properties.  See the last few lines from [the girder example](https://github.com/girder/girder/blob/master/tests/PythonTests.cmake#L59-L61) and [here](https://github.com/girder/girder/blob/master/tests/PythonTests.cmake#L137-L138).

**Comment by aashish24** [comment]
> @aashish24 Yeah, this work was almost entirely done in like November and I put off finishing it till "after the release", which wound up being now. I just spent a few hours cleaning it up and formatting it into a PR.

Thanks for the info @chaosphere2112, sounds good to me. I would still prefer we discuss this sort of stuff so that we can plan better for the future.

**Comment by doutriaux1** [comment]
@chaosphere2112 @aashish24 anything holding this up? (I just updated the branch to match master)

**Comment by aashish24** [comment]
> @chaosphere2112 @aashish24 anything holding this up? (I just updated the branch to match master)

Yes, we need to link this to cdash but I am okay if do that in a separate PR. Dan or Sankhesh can do it.

**Comment by doutriaux1** [comment]
yes that was my thinking as well, merging

**Comment by doutriaux1** [comment]
will wait for travis to merge.

**Pull request merged**
