### PR TITLE
Issue1871 durack1 update freetype 2.4.10 to 2.6.3

### LINKED ISSUE #1871: Build failure on OS X (10.11) - Freetype
This is a duplicate of https://github.com/PCMDI/pcmdi_metrics/issues/307

Will updating the freetype libraries solve this issue?

The issue is OS X specific with the following specs:
```
OS X: 10.11.3
XCode: 7.2.1
XQuartz: 2.7.8
gfortran: 5.2.0
git: 2.6.2
```
So building UV-CDAT `LEAN` using the `install_metrics.bash` options:
```python
num_cpus=1
build_graphics=true
build_graphics_against_mesa=false
build_cmor=true
build_parallel=false
keep_uvcdat_build_dir=false
cmake_version="3.4.3"
cdat_version="master"
```
The error I hit is:
```
[ 11%] Performing build step for 'freetype'
CMake Error at /Users/pauldurack/Desktop/PCMDI_METRICS/tmp/uvcdat/uvcdat_build/freetype-prefix/src/freetype-stamp/freetype-build.cmake:56 (message):
  CTEST_FULL_OUTPUT
...
Do you want more here?
```

### PR DESCRIPTION
**Pull request by durack1**
Fix #1871 - Update freetype 2.4.10 to 2.6.3

### CODE REVIEW

**Comment by durack1** [comment]
@doutriaux1 @dnadeau4 @aashish24 this seems to sail through on `OS X 10.9.5` the `travis` environment - it still fails on `OS X 10.11.3`

**Comment by durack1** [comment]
Here's the error:
```
[ 15%] Performing build step for 'freetype'
CMake Error at /Users/pauldurack/Desktop/PCMDI_METRICS/tmp/uvcdat/uvcdat_build/freetype-prefix/src/freetype-stamp/freetype-build.cmake:56 (message):
  CTEST_FULL_OUTPUT

   Command failed: 2
   '/Applications/Xcode.app/Contents/Developer/usr/bin/make'
   From /Users/pauldurack/Desktop/PCMDI_METRICS/tmp/uvcdat/uvcdat_build/freetype-prefix/src/freetype-stamp/freetype-build-out.log

  -------------------------------------------------

  libtool: compile:
  /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
  -ansi
  -I/Users/pauldurack/Desktop/PCMDI_METRICS/tmp/uvcdat/uvcdat_build/build/freetype/objs
  -I./builds/unix
  -I/Users/pauldurack/Desktop/PCMDI_METRICS/tmp/uvcdat/uvcdat_build/build/freetype/include
  -I/Users/pauldurack/Desktop/PCMDI_METRICS/Externals/include
  -I/Users/pauldurack/Desktop/PCMDI_METRICS/Externals/lib/libffi-3.1/include
  -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/include
  -I/usr/X11R6/include -m64 -mmacosx-version-min=10.11 -isysroot
  /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk
  -pipe -c -Wall -I/Users/pauldurack/Desktop/PCMDI_METRICS/Externals/include
  -I/Users/pauldurack/Desktop/PCMDI_METRICS/Externals/lib/libffi-3.1/include
  -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/include
  -L/usr/X11R6/lib
  -L/System/Library/Frameworks/ImageIO.framework/Versions/A/Resources
  -bind_at_load -mmacosx-version-min=10.11 -DDARWIN_NO_CARBON
  -DFT_CONFIG_OPTION_SYSTEM_ZLIB -DFT_CONFIG_OPTION_USE_BZIP2
  -I/opt/X11/include/libpng15 -DFT_CONFIG_OPTION_USE_PNG
  "-DFT_CONFIG_CONFIG_H=<ftconfig.h>" -DFT2_BUILD_LIBRARY
  "-DFT_CONFIG_MODULES_H=<ftmodule.h>" builds/unix/ftsystem.c -fno-common
  -DPIC -o
  /Users/pauldurack/Desktop/PCMDI_METRICS/tmp/uvcdat/uvcdat_build/build/freetype/objs/.libs/ftsystem.o


  libtool: compile:
  /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
  -ansi
  -I/Users/pauldurack/Desktop/PCMDI_METRICS/tmp/uvcdat/uvcdat_build/build/freetype/objs
  -I./builds/unix
  -I/Users/pauldurack/Desktop/PCMDI_METRICS/tmp/uvcdat/uvcdat_build/build/freetype/include
  -I/Users/pauldurack/Desktop/PCMDI_METRICS/Externals/include
  -I/Users/pauldurack/Desktop/PCMDI_METRICS/Externals/lib/libffi-3.1/include
  -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/include
  -I/usr/X11R6/include -m64 -mmacosx-version-min=10.11 -isysroot
  /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk
  -pipe -c -Wall -I/Users/pauldurack/Desktop/PCMDI_METRICS/Externals/include
  -I/Users/pauldurack/Desktop/PCMDI_METRICS/Externals/lib/libffi-3.1/include
  -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/include
  -L/usr/X11R6/lib
  -L/System/Library/Frameworks/ImageIO.framework/Versions/A/Resources
  -bind_at_load -mmacosx-version-min=10.11 -DDARWIN_NO_CARBON
  -DFT_CONFIG_OPTION_SYSTEM_ZLIB -DFT_CONFIG_OPTION_USE_BZIP2
  -I/opt/X11/include/libpng15 -DFT_CONFIG_OPTION_USE_PNG
  "-DFT_CONFIG_CONFIG_H=<ftconfig.h>" -DFT2_BUILD_LIBRARY
  "-DFT_CONFIG_MODULES_H=<ftmodule.h>" builds/unix/ftsystem.c -o
  /Users/pauldurack/Desktop/PCMDI_METRICS/tmp/uvcdat/uvcdat_build/build/freetype/objs/ftsystem.o
  >/dev/null 2>&1

  libtool: compile:
  /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
  -ansi
  -I/Users/pauldurack/Desktop/PCMDI_METRICS/tmp/uvcdat/uvcdat_build/build/freetype/objs
  -I./builds/unix
  -I/Users/pauldurack/Desktop/PCMDI_METRICS/tmp/uvcdat/uvcdat_build/build/freetype/include
  -I/Users/pauldurack/Desktop/PCMDI_METRICS/Externals/include
  -I/Users/pauldurack/Desktop/PCMDI_METRICS/Externals/lib/libffi-3.1/include
  -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/include
  -I/usr/X11R6/include -m64 -mmacosx-version-min=10.11 -isysroot
  /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk
  -pipe -c -Wall -I/Users/pauldurack/Desktop/PCMDI_METRICS/Externals/include
  -I/Users/pauldurack/Desktop/PCMDI_METRICS/Externals/lib/libffi-3.1/include
  -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/include
  -L/usr/X11R6/lib
  -L/System/Library/Frameworks/ImageIO.framework/Versions/A/Resources
  -bind_at_load -mmacosx-version-min=10.11 -DDARWIN_NO_CARBON
  -DFT_CONFIG_OPTION_SYSTEM_ZLIB -DFT_CONFIG_OPTION_USE_BZIP2
  -I/opt/X11/include/libpng15 -DFT_CONFIG_OPTION_USE_PNG
  "-DFT_CONFIG_CONFIG_H=<ftconfig.h>" -DFT2_BUILD_LIBRARY
  "-DFT_CONFIG_MODULES_H=<ftmodule.h>"
  /Users/pauldurack/Desktop/PCMDI_METRICS/tmp/uvcdat/uvcdat_build/build/freetype/src/base/ftdebug.c
  -fno-common -DPIC -o
  /Users/pauldurack/Desktop/PCMDI_METRICS/tmp/uvcdat/uvcdat_build/build/freetype/objs/.libs/ftdebug.o


  libtool: compile:
  /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
  -ansi
  -I/Users/pauldurack/Desktop/PCMDI_METRICS/tmp/uvcdat/uvcdat_build/build/freetype/objs
  -I./builds/unix
  -I/Users/pauldurack/Desktop/PCMDI_METRICS/tmp/uvcdat/uvcdat_build/build/freetype/include
  -I/Users/pauldurack/Desktop/PCMDI_METRICS/Externals/include
  -I/Users/pauldurack/Desktop/PCMDI_METRICS/Externals/lib/libffi-3.1/include
  -I/Applications/Xcode.app/Contents/Developer/Platf-------------------------------------------------


   From /Users/pauldurack/Desktop/PCMDI_METRICS/tmp/uvcdat/uvcdat_build/freetype-prefix/src/freetype-stamp/freetype-build-err.log

  -------------------------------------------------

  clang: warning: argument unused during compilation: '-L/usr/X11R6/lib'

  clang: warning: argument unused during compilation:
  '-L/System/Library/Frameworks/ImageIO.framework/Versions/A/Resources'

  clang: warning: argument unused during compilation: '-bind_at_load'

  clang: warning: argument unused during compilation: '-L/usr/X11R6/lib'

  clang: warning: argument unused during compilation:
  '-L/System/Library/Frameworks/ImageIO.framework/Versions/A/Resources'

  clang: warning: argument unused during compilation: '-bind_at_load'

  clang: warning: argument unused during compilation: '-L/usr/X11R6/lib'

  clang: warning: argument unused during compilation:
  '-L/System/Library/Frameworks/ImageIO.framework/Versions/A/Resources'

  clang: warning: argument unused during compilation: '-bind_at_load'

  clang: warning: argument unused during compilation: '-L/usr/X11R6/lib'

  clang: warning: argument unused during compilation:
  '-L/System/Library/Frameworks/ImageIO.framework/Versions/A/Resources'

  clang: warning: argument unused during compilation: '-bind_at_load'

  clang: warning: argument unused during compilation: '-L/usr/X11R6/lib'

  clang: warning: argument unused during compilation:
  '-L/System/Library/Frameworks/ImageIO.framework/Versions/A/Resources'

  clang: warning: argument unused during compilation: '-bind_at_load'

  clang: warning: argument unused during compilation: '-L/usr/X11R6/lib'

  clang: warning: argument unused during compilation:
  '-L/System/Library/Frameworks/ImageIO.framework/Versions/A/Resources'

  clang: warning: argument unused during compilation: '-bind_at_load'

  clang: warning: argument unused during compilation: '-L/usr/X11R6/lib'

  clang: warning: argument unused during compilation:
  '-L/System/Library/Frameworks/ImageIO.framework/Versions/A/Resources'

  clang: warning: argument unused during compilation: '-bind_at_load'

  clang: warning: argument unused during compilation: '-L/usr/X11R6/lib'

  clang: warning: argument unused during compilation:
  '-L/System/Library/Frameworks/ImageIO.framework/Versions/A/Resources'

  clang: warning: argument unused during compilation: '-bind_at_load'

  clang: warning: argument unused during compilation: '-L/usr/X11R6/lib'

  clang: warning: argument unused during compilation:
  '-L/System/Library/Frameworks/ImageIO.framework/Versions/A/Resources'

  clang: warning: argument unused during compilation: '-bind_at_load'

  clang: warning: argument unused during compilation: '-L/usr/X11R6/lib'

  clang: warning: argument unused during compilation:
  '-L/System/Library/Frameworks/ImageIO.framework/Versions/A/Resources'

  clang: warning: argument unused during compilation: '-bind_at_load'

  clang: warning: argument unused during compilation: '-L/usr/X11R6/lib'

  clang: warning: argument unused during compilation:
  '-L/System/Library/Frameworks/ImageIO.framework/Versions/A/Resources'

  clang: warning: argument unused during compilation: '-bind_at_load'

  clang: warning: argument unused during compilation: '-L/usr/X11R6/lib'

  clang: warning: argument unused during compilation:
  '-L/System/Library/Frameworks/ImageIO.framework/Versions/A/Resources'

  clang: warning: argument unused during compilation: '-bind_at_load'

  clang: warning: argument unused during compilation: '-L/usr/X11R6/lib'

  clang: warning: argument unused during compilation:
  '-L/System/Library/Frameworks/ImageIO.framework/Versions/A/Resources'

  clang: warning: argument unused during compilation: '-bind_at_load'

  clang: warning: argument unused during compilation: '-L/usr/X11R6/lib'

  clang: warning: argument unused during compilation:
  '-L/System/Library/Frameworks/ImageIO.framework/Versions/A/Resources'

  clang: warning: argument unused during compilation: '-bind_at_load'

  clang: warning: argument unused during compilation: '-L/usr/X11R6/lib'

  clang: warning: argument unused during compilation:
  '-L/System/Library/Frameworks/ImageIO.framework/Versions/A/Resources'

  clang: warning: argument unused during compilation: '-bind_at_load'

  clang: warning: argument unused during compilation: '-L/usr/X11R6/lib'

  clang: warning: argument unused during compilation:
  '-L/System/Library/Frameworks/ImageIO.framework/Versions/A/Resources'

  clang: warning: argument unused during compilation: '-bind_at_load'

  clang: warning: argument unused during compilation: '-L/usr/X11R6/lib'

  clang: warning: argument unused during compilation:
  '-L/System/Library/Frameworks/ImageIO.framework/Versions/A/Resources'

  clang: warning: argument unused during compilation: '-bind_at_load'

  clang: warning: argument unused during compilation: '-L/usr/X11R6/lib'

  clang: warning: argument unused during compilation:
  '-L/System/Library/Frameworks/ImageIO.framework/Versions/A/Resources'

  clang: warning: argument unused during compilation: '-bind_at_load'

  clang: warning: argument unused during compilation: '-L/usr/X11R6/lib'

  clang: warning: argument unused during compilation:
  '-L/System/Library/Frameworks/ImageIO.framework/Versions/A/Resources'

  clang: warning: argument unused during compilation: '-bind_at_load'

  clang: warning: argument unused during compilation: '-L/usr/X11R6/lib'

  clang: warning: argument unused during compilation:
  '-L/System/Library/Frameworks/ImageIO.framework/Versions/A/Resources'

  clang: warning: argument unused during compilation: '-bind_at_load'

  clang: warning: argument unused during compilation: '-L/usr/X11R6/lib'

  clang: warning: argument unused during compilation:
  '-L/System/Library/Frameworks/ImageIO.framework/Versions/A/Resources'

  clang: warning: argument unused during compilation: '-bind_at_load'

  clang: warning: argument unused during compilation: '-L/usr/X11R6/lib'

  clang: warning: argument unused during compilation:
  '-L/System/Library/Frameworks/ImageIO.framework/Versions/A/Resources'

  clang: warning: argument unused during compilation: '-bind_at_load'

  clang: warning: argument unused during compilation: '-L/usr/X11R6/lib'

  clang: warning: argument unused during compilation:
  '-L/System/Library/Frameworks/ImageIO.framework/Versions/A/Resources'

  clang: warning: argument unused during compilation: '-bind_at_load'

  clang: warning: argument unused during compilation: '-L/usr/X11R6/lib'

  clang: warning: argument unused during compilation:
  '-L/System/Library/Frameworks/ImageIO.framework/Versions/A/Resources'

  clang: warning: argument unused during compilation: '-bind_at_load'

  clang: warning: argument unused during compilation: '-L/usr/X11R6/lib'

  clang: warning: argument unused during compilation:
  '-L/System/Library/Frameworks/ImageIO.framework/Versions/A/Resources'

  clang: warning: argument unused during compilation: '-bind_at_load'

  clang: warning: argument unused during compilation: '-L/usr/X11R6/lib'

  clang: warning: argument unused during compilation:
  '-L/System/Library/Frameworks/ImageIO.framework/Versions/A/Resources'

  clang: warning: argument unused during compilation: '-bind_at_load'

  clang: warning: argument unused during compilation: '-L/usr/X11R6/lib'

  clang: warning: argument unused during compilation:
  '-L/System/Library/Frameworks/ImageIO.framework/Versions/A/Resources'

  clang: warning: argument unused during compilation: '-bind_at_load'

  clang: warning: argument unused during compilation: '-L/usr/X11R6/lib'

  clang: warning: argument unused during compilation:
  '-L/System/Library/Frameworks/ImageIO.framework/Versions/A/Resources'

  clang: warning: argument unused during compilation: '-bind_at_load'

  clang: warning: argument unused during compilation: '-L/usr/X11R6/lib'

  clang: warning: argument unused during compilation:
  '-L/System/Library/Frameworks/ImageIO.framework/Versions/A/Resources'

  clang: warning: argument unused during compilation: '-bind_at_load'

  clang: warning: argument unused during compilation: '-L/usr/X11R6/lib'

  clang: warning: argument unused during compilation:
  '-L/System/Library/Frameworks/ImageIO.framework/Versions/A/Resources'

  clang: warning: argument unused during compilation: '-bind_at_load'

  clang: warning: argument unused during compilation: '-L/usr/X11R6/lib'

  clang: warning: argument unused during compilation:
  '-L/System/Library/Frameworks/ImageIO.framework/Versions/A/Resources'

  clang: warning: argument unused during compilation: '-bind_at_load'

  clang: warning: argument unused during compilation: '-L/usr/X11R6/lib'

  clang: warning: argument unused during compilation:
  '-L/System/Library/Frameworks/ImageIO.framework/Versions/A/Resources'

  clang: warning: argument unused during compilation: '-bind_at_load'

  clang: warning: argument unused during compilation: '-L/usr/X11R6/lib'

  clang: warning: argument unused during compilation:
  '-L/System/Library/Frameworks/ImageIO.framework/Versions/A/Resources'

  clang: warning: argument unused during compilation: '-bind_at_load'

  clang: warning: argument unused during compilation: '-L/usr/X11R6/lib'

  clang: warning: argument unused during compilation:
  '-L/System/Library/Frameworks/ImageIO.framework/Versions/A/Resources'

  clang: warning: argument unused during compilation: '-bind_at_load'

  clang: warning: argument unused during compilation: '-L/usr/X11R6/lib'

  clang: warning: argument unused during compilation:
  '-L/System/Library/Frameworks/ImageIO.framework/Versions/A/Resources'

  clang: warning: argument unused during compilation: '-bind_at_load'

  clang: warning: argument unused during compilation: '-L/usr/X11R6/lib'

  clang: warning: argument unused during compilation:
  '-L/System/Library/Frameworks/ImageIO.framework/Versions/A/Resources'

  clang: warning: argument unused during compilation: '-bind_at_load'

  clang: warning: argument unused during compilation: '-L/usr/X11R6/lib'

  clang: warning: argument unused during compilation:
  '-L/System/Library/Frameworks/ImageIO.framework/Versions/A/Resources'

  clang: warning: argument unused during compilation: '-bind_at_load'

  clang: warning: argument unused during compilation: '-L/usr/X11R6/lib'

  clang: warning: argument unused during compilation:
  '-L/System/Library/Frameworks/ImageIO.framework/Versions/A/Resources'

  clang: warning: argument unused during compilation: '-bind_at_load'

  clang: warning: argument unused during compilation: '-L/usr/X11R6/lib'

  clang: warning: argument unused during compilation:
  '-L/System/Library/Frameworks/ImageIO.framework/Versions/A/Resources'

  clang: warning: argument unused during compilation: '-bind_at_load'

  clang: warning: argument unused during compilation: '-L/usr/X11R6/lib'

  clang: warning: argument unused during compilation:
  '-L/System/Library/Frameworks/ImageIO.framework/Versions/A/Resources'

  clang: warning: argument unused during compilation: '-bind_at_load'

  clang: warning: argument unused during compilation: '-L/usr/X11R6/lib'

  clang: warning: argument unused during compilation:
  '-L/System/Library/Frameworks/ImageIO.framework/Versions/A/Resources'

  clang: warning: argument unused during compilation: '-bind_at_load'

  clang: warning: argument unused during compilation: '-L/usr/X11R6/lib'

  clang: warning: argument unused during compilation:
  '-L/System/Library/Frameworks/ImageIO.framework/Versions/A/Resources'

  clang: warning: argument unused during compilation: '-bind_at_load'

  
  /Users/pauldurack/Desktop/PCMDI_METRICS/tmp/uvcdat/uvcdat_build/build/freetype/src/tools/apinames.c:19:10:
  fatal error: 'stdio.h' file not found

  #include <stdio.h>

           ^

  1 error generated.

  make[3]: ***
  [/Users/pauldurack/Desktop/PCMDI_METRICS/tmp/uvcdat/uvcdat_build/build/freetype/objs/apinames]
  Error 1

  -------------------------------------------------



make[2]: *** [freetype-prefix/src/freetype-stamp/freetype-build] Error 1
make[1]: *** [CMakeFiles/freetype.dir/all] Error 2
make: *** [all] Error 2
 ERROR: Could not compile (make) cdat code
~/Desktop/PCMDI_METRICS/tmp/uvcdat/uvcdat ~/Desktop/PCMDI_METRICS/tmp/metrics

Sorry...
This action did not complete successfully
Please try to re-run this task until successful before continuing further

 ERROR: Could not compile (make) cdat code
~/Desktop/PCMDI_METRICS/tmp/metrics

Sorry...
This action did not complete successfully
Please try to re-run this task until successful before continuing further
```

**Comment by durack1** [comment]
@doutriaux1 @dnadeau4 @aashish24 any tips on resolving:
```
  /Users/pauldurack/Desktop/PCMDI_METRICS/tmp/uvcdat/uvcdat_build/build/freetype/src/tools/apinames.c:19:10:
  fatal error: 'stdio.h' file not found

  #include <stdio.h>
```

**Comment by durack1** [comment]
@doutriaux1 @dnadeau4 @aashish24 `freetype 2.6.3` is now building on `OS X 10.11.3` - I missed installing the `XCode command line tools` once these are installed `stdio.h` is found.

It's taking a while to complete with `num_cpus=1` however will re-check this tomorrow and run using a couple of other build variants to make sure it's fixed things completely.

I think this PR is good to merge - it's just a package update

**Comment by aashish24** [comment]
@durack1 yeah, xcode is listed in the requirement: https://github.com/UV-CDAT/uvcdat/wiki/Install-on-Mac-OS-X

**Comment by aashish24** [comment]
@durack1 I will build locally since garant seems to stuck and will merge if all goes well

**Comment by durack1** [comment]
@aashish24 @doutriaux1 this looks good to me from my testing - passes using a number of build options on `OS X 10.11.3` - It's good to merge

**Comment by doutriaux1** [comment]
@durack1 I will take a look, loks like flake8 is freaking out. Windows edits?

**Comment by durack1** [comment]
@doutriaux1 nope this is a linux-edited file - all good?

**Comment by aashish24** [comment]
@durack1 what do we need to do with this branch?

**Comment by durack1** [comment]
@aashish24 it's a straight package update.. I was hitting `freetype` build issues on `OS X` and updated this to see if it solved the problems

**Comment by aashish24** [comment]
thanks @durack1. Looks like travis is passing. but based on earlier comment looks like @doutriaux1 wants to have a look at the flake8 stuff?

@durack1 is it possible for you to update this branch with current master?

**Comment by aashish24** [comment]
@durack1 same here. Let's open it after 2.4.1.

**Comment by durack1** [comment]
@aashish24 @doutriaux1 I really think closing this trivial PR rather than spending an extra couple of minutes to get such a trivial update merged is wasted effort.. Too much "management" and not enough actual code improvement in my opinion.

As I'm not employed by the UV-CDAT project I am not sure I will ever get back to resubmitting this PR..

**Comment by aashish24** [comment]
Hi @durack1, I agree with you that we should not have long standing PR's. At the same time, we need to synchronize so that we don't update packages before the release. I can open the PR post 2.4.1. Not a problem.

**Pull request closed without merging**
