### PR TITLE
Continents & Continent Lines

### PR DESCRIPTION
**Pull request by chaosphere2112**
This PR fixes some existing functionality (changing what continents to use) and adds a new piece of functionality (changing the appearance of the lines used to draw the continents).

While we technically supported drawing continents of a variety of types using a keyword argument (continents=1-12) on `plot`, as soon as a call to `configureEvent` on the VTK Backend happened, the continents were reset to the canvas' globally defined setting.

Now, we can do things like this plot:

nice_continents

@doutriaux1 @aashish24

### CODE REVIEW

**Comment by doutriaux1** [comment]
@chaosphere2112 some failures

**Comment by aashish24** [comment]
Great.. @chaosphere2112 what issue this fixes it? Did we have existing issue on github for it?

**Comment by aashish24** [comment]
Is it going to conflict with https://github.com/UV-CDAT/uvcdat/pull/1688? @sankhesh @chaosphere2112?

**Comment by aashish24** [comment]
@chaosphere2112 @sankhesh yes, I think there is going to some conflict (or code duplication), if I am not mistaken. If that's the case, please coordinate with me or @doutriaux1 before hand.

**Comment by sankhesh** [comment]
I don't see a conflict with #1688 since most of my changes were for isoline pipeline only.

**Comment by chaosphere2112** [comment]
@aashish24 Nope, no conflicts. This is a completely separate piece of code.
@doutriaux1 Whoops, looks like I neglected to call a validation function, just the module. Running the tests locally again and sending up.

**Comment by aashish24** [comment]
Cool! thanks @chaosphere2112 @sankhesh there seems to be some code duplication on line stipple pattern..

**Comment by chaosphere2112** [comment]
@aashish24 There technically already is the code duplication (the code you see in my PR was just refactored out of `prepLine`). If we merge mine, then we can just use the same `stippleLine` function in the isolines.

**Comment by chaosphere2112** [comment]
So found another bug while I was poking around; had an extraneous `int()` cast that was making all of the continents black (whoops!), which was left over from before I fixed colors properly (I thought they were supposed to be in the range 0-255, but they needed to be 0.-1.). Also updated the baseline to match the correct color output (the baseline was made while I was doing 0-255, which meant it was SUPER RED AND MAYBE SOME OTHER COLORS rather than kind of dark red).

**Comment by aashish24** [comment]
sure @chaosphere2112 sounds great@ thanks!

**Comment by sankhesh** [comment]
Sounds good. I can make the change to #1688 once this is merged.

**Comment by aashish24** [comment]
@chaosphere2112 continent lines test is failing..

**Comment by chaosphere2112** [comment]
@aashish24 Looks like it's a threshold issue. The diffs are almost impossible to see.

**Comment by chaosphere2112** [comment]
@aashish24 I'll update the threshold.

**Comment by chaosphere2112** [comment]
@aashish24 and fix the merge conflict while I'm at it

**Comment by aashish24** [comment]
thanks @chaosphere2112 now it looks like multiple tests are failing. May be related to a bad conflict fix?

**Comment by aashish24** [comment]
@chaosphere2112 the lines were thicker in test than in validated image. For @doutriaux1 and me it was obvious but may be we missed something?

**Comment by aashish24** [comment]
@chaosphere2112 I rebased this branch again with a hope that it fixes the failures I have in the last rebase. Sorry, I couldn't ask you to do it because of the time of the day but I cherry-picked your threshold change.

**Comment by aashish24** [comment]
@doutriaux1 the branch is looking good on my machine and on other linux dashboards. Macs are not building because of NUMPY. I am going to merge this one soon if I don't hear any objection from you.

**Comment by aashish24** [comment]
LGTM :+1:

**Comment by doutriaux1** [comment]
@aashish24 thanks is there a baseline with this? did oyu merge it?

**Comment by doutriaux1** [comment]
@aashish24 I don't see a baseline, the test added should have a new baseline. Did all the test passed for you?

**Comment by doutriaux1** [comment]
@chaosphere2112 baseline?

**Comment by aashish24** [comment]
@doutriaux1 it passed on my system. test_continents.png seems to be in the baseline already

**Pull request merged**
