### PR TITLE
New test for opacity of masked values

### PR DESCRIPTION
**Pull request by sankhesh**
Test for UV-CDAT/vcs#123.
Fixes UV-CDAT/vcs#121

### CODE REVIEW

**Comment by sankhesh** [comment]
@doutriaux1 @durack1

**Comment by durack1** [comment]
@sankhesh thanks

**Comment by danlipsa** [comment]
@sankhesh Do you have the uvcdat-testdata branch as well?

**Comment by sankhesh** [comment]
@danlipsa Yes, see UV-CDAT/uvcdat-testdata#161

**Comment by durack1** [comment]
@sankhesh it looks like ~660 of the 664 tests are failing here

**Comment by sankhesh** [comment]
@durack1 I don't think this change is causing the failures. I ran all the tests on my local machine and they pass.

**Comment by sankhesh** [comment]
@doutriaux1 Good to merge this one too?

**Comment by doutriaux1** [comment]
@durack1 test suite on travis is broken.

**Comment by aashish24** [comment]
thanks @sankhesh @doutriaux1

**Pull request merged**
