### PR TITLE
fix #1212 - Update spyder 2.3.3 to 2.3.4

### LINKED ISSUE #1212: Update spyder to 2.3.4
We're a patch release behind the latest spyder (2.3.3 vs 2.3.4) - a number of bug fixes in 2.3.4 are worth the effort in updating..

### PR DESCRIPTION
**Pull request by durack1**
@doutriaux1 @aashish24 @jbeezley here's that pull request #1213 and #1299 issued against the uvcdat master branch - I'm hoping this triggers the buildbot testing.

If so (and it passes) I'll close the existing PRs #1213 and #1299

### CODE REVIEW

**Comment by durack1** [comment]
@jbeezley @aashish24 is there something wrong with the buildbot config? It would seem this PR doesn't do much and shouldn't have errored like it has..

**Comment by jbeezley** [comment]
These builds don't contain #1296 which just went into master.  If you merge in the latest master and repushed, it will probably fix the problem.

**Comment by durack1** [comment]
@jbeezley ok will do..

**Comment by durack1** [comment]
@doutriaux1 @aashish24 @jbeezley I'll just let this go and see if it returns any errors, then clean it up back to the original 1 file change in a new PR..

**Comment by durack1** [comment]
@jbeezley seems that same DODS problem is recurring https://open.cdash.org/testDetails.php?test=334469530&build=3804894

**Comment by durack1** [comment]
@jbeezley so DODS is still a problem, and the lines across the test image https://open.cdash.org/testDetails.php?test=334473135&build=3804928

**Comment by durack1** [comment]
@jbeezley as noted by @doutriaux1 it also seems that the netcdf version being picked up might be wrong https://open.cdash.org/testDetails.php?test=334479306&build=3804923

**Comment by ThomasMaxwell** [comment]
As for the lines across the test image, I have been unable to reproduce this on any of the platforms here at NASA.  I looked over the code and it looks fine to me.   So right now I really don’t know what would be causing this.

— Tom

**Comment by jbeezley** [comment]
Yes, those failures are unrelated.  Hopefully soon we will have all the tests passing on master.

**Comment by aashish24** [comment]
@durack1 I will have a look at this branch. Please don't merge until then. 

thanks,

**Comment by durack1** [comment]
@aashish24 this branch needs some cleaning once it passes.. It'll be cleaner if I just close this and issue another PR once the tests are fixed.. I'll do this for my other PRs too

**Comment by durack1** [comment]
@aashish24 should I clean up this PR and resubmit? Are the DODS and other issues above resolved?

**Comment by durack1** [comment]
@doutriaux1 @aashish24 @jbeezley closing this PR and will re-issue a new PR once all the changes which have made their way into `release` are back in master..

**Pull request closed without merging**
