### PR TITLE
BUG: Fix memory override for vtkContourFiler in isofillpipeline.

### PR DESCRIPTION
**Pull request by danlipsa**
This resulted in vtkStripper to generate double coverage of isocountours which resulted in
messed-up patterns.
Also adjusted plot patterns to easier to discriminate.

### CODE REVIEW

**Comment by danlipsa** [comment]
Data in:
https://github.com/UV-CDAT/uvcdat-testdata/pull/133

**Comment by danlipsa** [comment]
@doutriaux1 @aashish24 please review.

**Comment by doutriaux1** [comment]
I'm excited about this one!

**Comment by aashish24** [comment]
what was the logic behind:

**Comment by danlipsa** [comment]
This writes over the end of the array.
Not sure what was the original intention.

**Comment by aashish24** [comment]
Yeah it seems weird, I couldn't think of why it was like this. 

LGTM :+1:

**Comment by aashish24** [comment]
@danlipsa you want to use regression module. 

so instead of this

```
+
 +x = vcs.init(bg=1, geometry=(1620, 1080))
 +x.setantialiasing(0)
 +x.drawlogooff()
```

You can do:

x = regression.init(bg=1, geometry=(800, 600)) # Let's use 800x600 from now on 
....
..
..
regression.run(x, "filename")
```

**Comment by danlipsa** [comment]
@aashish24 Should we do 800 x 600 even for background images? That seems very small considering that we can make images as big as we want.

**Comment by aashish24** [comment]
@danlipsa if we make images smaller for testing, then we will have faster checkout of baselines. In vtk the sizes are 400, 400.

**Comment by doutriaux1** [comment]
@danlipsa @aashish24 I don[t think making the picture smaller will make the test much faster, but we will  lose precision in the output and we might not be able to catch small difference, in things like dotted line and such. Just my two cents.

**Comment by danlipsa** [comment]
@aashish24 @doutriaux1 Indeed, for this particular test, 800 x 600 does not catch the difference between a wrong file and a good one - the difference is about 5.

**Comment by danlipsa** [comment]
For the current resolution the difference is 20 is the error is caught.

**Comment by danlipsa** [comment]
@aashish24 Should we merge this in? Note the many sizes we currently have in the repo:
250 x 500
400 x 768
400 x 800
500 x 250
500 x 500
800 x 400
800 x 600
814 x 303
814 x 606
814 x 628
1091 x 1200
1200 x 1090
1200 x 1091
2400 x 2182

**Comment by aashish24** [comment]
@danlipsa in that case can we use 1200 x 1091 (the default size in regression.py) unless you don't think it catches the error. I see your point that we have different size for testing right now but most of them are using regression.py so it would be nice if we can use 1200x1091.

**Comment by aashish24** [comment]
but I am fine if the current resolution is best for the testing  too :+1:

**Comment by danlipsa** [comment]
@doutriaux1 @aashish24 1200 x 1091 is fine. In that case we should look at the baselines of size 1200 x 1090 and make sure we don't compare them against images of size 1200 x 1091.

**Comment by danlipsa** [comment]
@doutriaux1 @aashish24 Note line stipples are not supported yet in OpenGL2 backend for VTK because they have been removed from OpenGL 3.1.
http://www.vtk.org/Bug/view.php?id=15799

**Pull request merged**
