### PR TITLE
Update PyOpenSSL to 0.14.

### PR DESCRIPTION
**Pull request by dlonie**
#1084 is popping up for me again on Arch Linux. This bumps PyOpenSSL to 0.14, which fixes the issue.

I'm targeting master for this, let me know if it should go into release instead/also.

@doutriaux1 @chaosphere2112 @aashish24

### CODE REVIEW

**Comment by aashish24** [comment]
in theory, master should be good for new changes. I won't suggest it for release for now unless @doutriaux1 thinks otherwise.

**Comment by dlonie** [comment]
Can we get this merged soon? I have to cherry-pick it every time I pull a branch at the moment.

**Comment by aashish24** [comment]
Since we already have a release branch. This can go in without further delay. @doutriaux1 can you do a quick test on it? 

@dlonie since we have buildbot working now (not before), can you push a dummy commit on this branch so that we can trigger bulid again?

**Comment by remram44** [comment]
I can't build this on my machine, I get weird C compiler errors... [PYOPENSSL-install-err.log](https://gist.githubusercontent.com/remram44/68be5be37ff83c88b474/raw/PYOPENSSL-install-err.log)

**Comment by doutriaux1** [comment]
@remram44 so this is a 10.10 machine right? but the logs seem to indicate it's picking up 10.9 SDK. Just for now, can you please try to move your 10.9 SDK directory so that it's not picked up? 
@aashish24 we should really switch this all SDK logic so that it picks the SDK that matches your OS, not just the lower or greater one... I'll open an issue for this. @remram44 can you please tell me if moving the SDK fixes things for you for now. Thanks.

**Comment by dlonie** [comment]
I had issues building this when I had the setup_runtime.py sourced, since the pkg-config in the UVCDAT build won't detect the system libraries properly. Dunno if that's related, but it might be a similar issue.

**Comment by aashish24** [comment]
@doutriaux1 that will be hard for reasons that a user can have multiple SDK's. I think my other branch addresses that. If you have 10.10 SDK, it will pick that first since we know that you installed that and therefore you moved on to the new version.

**Comment by doutriaux1** [comment]
@aashish24 why is it hard?
```
uname -a
Darwin sofia.llnl.gov 14.3.0 Darwin Kernel Version 14.3.0: Mon Mar 23 11:59:05 PDT 2015; root:xnu-2782.20.48~5/RELEASE_X86_64 x86_64
```
From that we know we should be using 10.10, no?

**Comment by doutriaux1** [comment]
10.9:
```
Darwin maryam 13.4.0 Darwin Kernel Version 13.4.0: Wed Mar 18 16:20:14 PDT 2015; root:xnu-2422.115.14~1/RELEASE_X86_64 x86_64
```

**Comment by aashish24** [comment]
its hard because a user can have 10.9 or 10.10 SDK both at the same time. What I was saying is that we can fall back to the latest SDK in that case. What OS you are on is not so relevant. I think whats more relevant is what XCode version you have with what SDK.

**Comment by remram44** [comment]
Looks like Python didn't build correctly with the 10.10 SDK out of the way

**Comment by doutriaux1** [comment]
and 10.8
```
uname -a
Darwin sofia.llnl.gov 12.6.0 Darwin Kernel Version 12.6.0: Wed Dec 17 19:11:40 PST 2014; root:xnu-2050.48.15~1/RELEASE_X86_64 x86_64
```

**Comment by doutriaux1** [comment]
@aashish24 I disagree, the BEST guess is to match OS version and SDK. Then if you can't match them go ahead and do what we do.

**Comment by doutriaux1** [comment]
@remram44 so you're on 10.9? Ok, starting a build on 10.9 to see if I can reproduce as well.

**Comment by remram44** [comment]
I'm on 10.10. [This seems to be the issue](http://stackoverflow.com/questions/27976312/how-to-cope-with-non-gcc-compatible-code-in-os-x-yosemite-core-headers), compiling with clang now.

**Comment by remram44** [comment]
With clang, it works with the 10.9 SDK out of the way, but not if I don't move it, as you had suspected.

**Comment by doutriaux1** [comment]
ok. @aashish24 I will submit a branch where we match SDK to user's OS by default. Too many people seem to run into this issue.

**Comment by doutriaux1** [comment]
ok new PR at: https://github.com/UV-CDAT/uvcdat/pull/1320

**Pull request merged**
