### PR TITLE
New test, for spaghetti/multiline plots (plot set 3).

### PR DESCRIPTION
**Pull request by painter1**

### CODE REVIEW

**Comment by aashish24** [comment]
@painter1 did you forget to add new baseline? 

I am getting: /home/chaudhary/tools/uvcdat/build_debug/uvcdat-testdata/baselines/metrics/metrics/set3_Global_JJA_TS-combined.png

**Comment by aashish24** [comment]
@painter1 i pushed a simple fix but test is failing. Here is the output I am getting: 

379: Test command: /home/chaudhary/tools/uvcdat/build_debug/install/bin/python "/home/chaudhary/tools/uvcdat/src.git/testing/metrics/diagtest03.py" "--datadir=/home/chaudhary/uvcmetrics_test_data" "--baseline=/home/chaudhary/tools/uvcdat/build_debug/uvcdat-testdata/baselines/metrics"
379: Environment variables: 
379:  UVCDAT_ANONYMOUS_LOG=no
379: Test timeout computed to be: 1500
379: UV-CDAT Diagnostics, command-line version
379: Added set:  {'climos': 'no', 'end': None, 'name': None, 'filter': None, 'start': None, 'path': '/home/chaudhary/uvcmetrics_test_data/cam_output', 'type': 'model'}
379: Added set:  {'climos': 'yes', 'end': None, 'name': None, 'filter': "f_contains('NCEP')", 'start': None, 'path': '/home/chaudhary/uvcmetrics_test_data/obs_atmos', 'type': 'obs'}
379: Enabling NetCDF compression on output files
379: filt:  None
379: INFO:  file /home/chaudhary/uvcmetrics_test_data/cam_output/c_t_b30.009.cam2.h0.0600-01.nc has an axis bound with no bounds.
379: An attempt will be made to compute bounds, but that is unreliable compared to bounds provided by the data file.
379: INFO:  file /home/chaudhary/uvcmetrics_test_data/cam_output/c_t_b30.009.cam2.h0.0600-01.nc has an axis lev with no bounds.
379: An attempt will be made to compute bounds, but that is unreliable compared to bounds provided by the data file.
379: There will be no more bad data warnings from constructing this filetable.
379: filt:  f_contains('NCEP')
379: INFO:  file /home/chaudhary/uvcmetrics_test_data/obs_atmos/c_t_NCEP_01_climo.nc has an axis bound with no bounds.
379: An attempt will be made to compute bounds, but that is unreliable compared to bounds provided by the data file.
379: INFO:  file /home/chaudhary/uvcmetrics_test_data/obs_atmos/c_t_NCEP_01_climo.nc has an axis lev with no bounds.
379: An attempt will be made to compute bounds, but that is unreliable compared to bounds provided by the data file.
379: There will be no more bad data warnings from constructing this filetable.
379: using seasons= ['JJA']
379: plot set 3 - Line Plots of  Zonal Means
379: WARNING: Couldn't find any of the requested variables: ['TS']
379: among ['AODVIS', 'CLDHGH_ISCCP', 'CLDHGH_TAU1.3-9.4_MODIS', 'CLDHGH_TAU1.3_MODIS', 'CLDHGH_TAU9.4_MODIS', 'CLDHGH_VISIR', 'CLDLOW_ISCCP', 'CLDLOW_TAU1.3-9.4_MISR', 'CLDLOW_TAU1.3_MISR', 'CLDLOW_TAU9.4_MISR', 'CLDLOW_VISIR', 'CLDMED_ISCCP', 'CLDMED_VISIR', 'CLDTOT_ISCCP', 'CLDTOT_TAU1.3-9.4_ISCCP', 'CLDTOT_TAU1.3-9.4_MISR', 'CLDTOT_TAU1.3-9.4_MODIS', 'CLDTOT_TAU1.3_ISCCP', 'CLDTOT_TAU1.3_MISR', 'CLDTOT_TAU1.3_MODIS', 'CLDTOT_TAU9.4_ISCCP', 'CLDTOT_TAU9.4_MISR', 'CLDTOT_TAU9.4_MODIS', 'CLDTOT_VISIR', 'CLISCCP', 'CLMISR', 'FLUT', 'FSNTOA', 'LHFLX', 'PRECT', 'QFLX', 'RESTOM', 'SHFLX', 'T', 'TGCLDLWP', 'TREFHT', 'bound', 'bounds_lat', 'bounds_lon', 'lat', 'lev', 'lon']
379: total number of (compound) diagnostic plots generated = 0
379: Test 3: Diagnostic multi-line (spaghetti) plots ...  jfp pathout= /tmp/tmpQYv1s3
379: ERROR: In /home/chaudhary/tools/uvcdat/build_debug/build/VTK/IO/Image/vtkPNGReader.cxx, line 44
379: vtkPNGReader (0x209e7f0): Unable to open file /tmp/tmpQYv1s3/set3_Global_JJA_TS-combined.png
379: 
379: ERROR: In /home/chaudhary/tools/uvcdat/build_debug/build/VTK/Imaging/Core/vtkImageExtractComponents.cxx, line 239
379: vtkImageExtractComponents (0x24813d0): Execute: Component 1 is not in input.
379: 
379: Found Baselines:
379: - /home/chaudhary/tools/uvcdat/build_debug/uvcdat-testdata/baselines/metrics/set3_Global_JJA_TS-combined.png
379: ERROR: In /home/chaudhary/tools/uvcdat/build_debug/build/VTK/Imaging/Core/vtkImageDifference.cxx, line 397
379: vtkImageDifference (0x24896b0): ExecuteInformation: Input are not the same size.
379:  Input1 is: 0,0,0,0,0,0
379:  Input2 is: 0,605,0,813,0,0
379: 
379: ERROR: In /home/chaudhary/tools/uvcdat/build_debug/build/VTK/Imaging/Core/vtkImageDifference.cxx, line 221
379: vtkImageDifference (0x24896b0): Execute: All ScalarTypes must be unsigned char
379: 
379: Comparing '/tmp/tmpQYv1s3/set3_Global_JJA_TS-combined.png' to '/home/chaudhary/tools/uvcdat/build_debug/uvcdat-testdata/baselines/metrics/set3_Global_JJA_TS-combined.png'...diff=8000.000000, New best!
379: All baselines failed! Lowest error (8000.000000) exceeds threshold (10.000000).
379: Saving image diff at '/tmp/tmpQYv1s3/set3_Global_JJA_TS-combined_diff.png'.
379: Warning: In /home/chaudhary/tools/uvcdat/build_debug/build/VTK/IO/Image/vtkPNGWriter.cxx, line 215
379: vtkPNGWriter (0x24858f0): PNGWriter only supports unsigned char and unsigned short inputs
379: 
379: <DartMeasurement name="ImageError" type="numeric/double">8000.000000</DartMeasurement>
379: <DartMeasurementFile name="DifferenceImage" type="image/png">/tmp/tmpQYv1s3/set3_Global_JJA_TS-combined_diff.png</DartMeasurementFile>
379: <DartMeasurementFile name="ValidImage" type="image/png">/home/chaudhary/tools/uvcdat/build_debug/uvcdat-testdata/baselines/metrics/set3_Global_JJA_TS-combined.png</DartMeasurementFile>
379: Graphics file /tmp/tmpQYv1s3/set3_Global_JJA_TS-combined.png match difference: -1
379: Traceback (most recent call last):
379:   File "/home/chaudhary/tools/uvcdat/src.git/testing/metrics/diagtest03.py", line 80, in <module>
379:     close1 = closeness( varname1, filename, pathout, baselinepath, rtol, atol )
379:   File "/home/chaudhary/tools/uvcdat/src.git/testing/metrics/diagtest03.py", line 36, in closeness
379:     f = cdms2.open( fname )
379:   File "/home/chaudhary/tools/uvcdat/build_debug/install/lib/python2.7/site-packages/cdms2/dataset.py", line 221, in openDataset
379:     if not os.path.exists(path): return CdmsFile(path,mode)
379:   File "/home/chaudhary/tools/uvcdat/build_debug/install/lib/python2.7/site-packages/cdms2/dataset.py", line 890, in __init__
379:     raise CDMSError, 'Cannot open file %s (%s)'%(path,err)
379: cdms2.error.CDMSError: Cannot open file /tmp/tmpQYv1s3/set3_TS_JJA_None,None.nc (No error)
1/1 Test #379: diags_test_03 ....................***Failed    1.78 sec
File "/tmp/tmpQYv1s3/set3_Global_JJA_TS-combined.png" not found.
File "/tmp/tmpQYv1s3/set3_Global_JJA_TS-combined_diff.png" not found.

**Comment by mcenerney1** [comment]
I've been working on this for a couple days and I have fixes that I'll commit shortly.

**Comment by aashish24** [comment]
okay, sounds good.

**Comment by mcenerney1** [comment]
Revised diagtest03 and CMakeLists.txt

**Comment by mcenerney1** [comment]
Aashish
I'm having trouble with git. I have new data in uvcdat-testdata in a branch newdiagsdata. I'm trying to do a pull request in uv-cdat/uvcdat-testdata
and I can't seem to set it up properly.  I also thought I setup a pull request in uvcdat with changes in testing/metrics. But I don't see it.
Help! Thanks!
Jim

**Comment by aashish24** [comment]
@mcenerney1 what error you are getting?

**Comment by aashish24** [comment]
@mcenerney1  I added you to uvcdat test data repository. Do you see that invitation? Once seen, try again/

**Comment by mcenerney1** [comment]
This could all be just rookie mistakes.  I've commit my changes to newdiagsdata in uvcdat-testdata.
I think I should commit to master. Below is the output.


[hilbert:~/uvcdat-testdata] mcenerney1% git commit
# On branch master
# Your branch is ahead of 'origin/master' by 1 commit.
#   (use "git push" to publish your local commits)
#
nothing to commit, working directory clean



[hilbert:~/uvcdat-testdata] mcenerney1% git push
warning: push.default is unset; its implicit value is changing in
Git 2.0 from 'matching' to 'simple'. To squelch this message
and maintain the current behavior after the default changes, use:

  git config --global push.default matching

To squelch this message and adopt the new behavior now, use:

  git config --global push.default simple

See 'git help config' and search for 'push.default' for further information.
(the 'simple' mode was introduced in Git 1.7.11. Use the similar mode
'current' instead of 'simple' if you sometimes use older versions of Git)

fatal: remote error:
  You can't push to git://github.com/UV-CDAT/uvcdat-testdata.git
  Use https://github.com/UV-CDAT/uvcdat-testdata.git

**Comment by painter1** [comment]
Try changing the push url to the git@ form.  I think that's
    git@github.com:UV-CDAT/uvcdat-testdata.git
    but I might have my slashes wrong.
    - Jeff
    
    On 4/24/15 9:47 AM, James McEnerney
      wrote:
    
    
      
      This could all be just rookie mistakes. I've commit my changes to
      newdiagsdata in uvcdat-testdata.
      I think I should commit to master. Below is the output.
      
      
      [hilbert:~/uvcdat-testdata] mcenerney1% git commit
      # On branch master
      # Your branch is ahead of 'origin/master' by 1 commit.
      # (use "git push" to publish your local commits)
      #
      nothing to commit, working directory clean
      
      
      
      [hilbert:~/uvcdat-testdata] mcenerney1% git push
      warning: push.default is unset; its implicit value is changing in
      Git 2.0 from 'matching' to 'simple'. To squelch this message
      and maintain the current behavior after the default changes, use:
      
      git config --global push.default matching
      
      To squelch this message and adopt the new behavior now, use:
      
      git config --global push.default simple
      
      See 'git help config' and search for 'push.default' for further
      information.
      (the 'simple' mode was introduced in Git 1.7.11. Use the similar
      mode
      'current' instead of 'simple' if you sometimes use older versions
      of Git)
      
      fatal: remote error:
      You can't push to git://github.com/UV-CDAT/uvcdat-testdata.git
      Use https://github.com/UV-CDAT/uvcdat-testdata.git
      
      
      From: Aashish Chaudhary
      <notifications@github.com<mailto:notifications@github.com>>
      Reply-To: UV-CDAT/uvcdat
      <reply@reply.github.com<mailto:reply@reply.github.com>>
      Date: Friday, April 24, 2015 9:27 AM
      To: UV-CDAT/uvcdat
<uvcdat@noreply.github.com<mailto:uvcdat@noreply.github.com>>
      Cc: James McEnerney
      <mcenerney1@llnl.gov<mailto:mcenerney1@llnl.gov>>
      Subject: Re: [uvcdat] New test, for spaghetti/multiline plots
      (plot set 3). (#1218)
      
      
      @mcenerney1<https://github.com/mcenerney1> I added you to
      uvcdat test data repository. Do you see that invitation? Once
      seen, try again/
      
      —
      Reply to this email directly or view it on
GitHub<https://github.com/UV-CDAT/uvcdat/pull/1218#issuecomment-95985389>.
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by mcenerney1** [comment]
Ok I think I have finally pushed the new data to master in uvcdat_testdata and new diagtest03 in uvcdat.
Please look it over. Thanks!

**Comment by mcenerney1** [comment]
This pull request requires the data in uvcdat-testdata

**Pull request merged**
