### PR TITLE
Vtk ui

### PR DESCRIPTION
**Pull request by doutriaux1**

### CODE REVIEW

**Comment by dlonie** [comment]
Building and testing now.

**Comment by doutriaux1** [comment]
@chaosphere2112 got this going, closing

**Comment by doutriaux1** [comment]
@dlonie don't bother with this one. I got @chaosphere2112 branch going and we already found a few things on ubunut (see original PR) @chaosphere2112 is working on it in his branch. Thanks though!

**Comment by dlonie** [comment]
okeydoke

**Pull request closed without merging**
