### PR TITLE
fix to get pyopensll build again

### PR DESCRIPTION
**Pull request by doutriaux1**
@isubsmith please test on your system.

@aashish24 @dlonie @sankhesh feel free to start reviewing

@aashish24 I know you don't like building ffi, but until you guys implemented the USE_SYSTEM we have to build it (plus we will still need to build it if users don't have root and can't add this packages)

@cdampi bit is only for PARALLEL build, I had to do this on my system to get mpi and esmf parallel to install correctly. If anybody as issues with it we can revert for this branch to what's in master
pnetcdf is also only built in parallel mode, same thing if anybody has issues with it we can take it off from this branch.

### CODE REVIEW

**Comment by doutriaux1** [comment]
@aashish24 @jbeezley what kind of laptop is this? No m4!!! I guess we need to add to the linux requirements... I'm with @aashish24 on this one we are not going to install m4.

**Comment by isubsmith** [comment]
This must be against master/HEAD?

I was hoping to build 2.2 release but I suppose I can switch.

Brian Smith
smithbe@ornl.gov<mailto:smithbe@ornl.gov>



On Jun 8, 2015, at 4:48 PM, Charles Doutriaux <notifications@github.com<mailto:notifications@github.com>> wrote:


@isubsmith<https://github.com/isubsmith> please test on your system.

@aashish24<https://github.com/aashish24> @dlonie<https://github.com/dlonie> @sankhesh<https://github.com/sankhesh> feel free to start reviewing

@aashish24<https://github.com/aashish24> I know you don't like building ffi, but until you guys implemented the USE_SYSTEM we have to build it (plus we will still need to build it if users don't have root and can't add this packages)

@cdampi bit is only for PARALLEL build, I had to do this on my system to get mpi and esmf parallel to install correctly. If anybody as issues with it we can revert for this branch to what's in master
pnetcdf is also only built in parallel mode, same thing if anybody has issues with it we can take it off from this branch.

________________________________
You can view, comment on, or merge this pull request online at:

  https://github.com/UV-CDAT/uvcdat/pull/1370

Commit Summary

  *   pipinstaller was using @ instead of $ for variable

File Changes

  *   M CMake/cdat_modules/cffi_deps.cmake<https://github.com/UV-CDAT/uvcdat/pull/1370/files#diff-0> (2)
  *   M CMake/cdat_modules/cython_pkg.cmake<https://github.com/UV-CDAT/uvcdat/pull/1370/files#diff-1> (8)
  *   M CMake/cdat_modules/hdf5_deps.cmake<https://github.com/UV-CDAT/uvcdat/pull/1370/files#diff-2> (3)
  *   M CMake/cdat_modules/hdf5_external.cmake<https://github.com/UV-CDAT/uvcdat/pull/1370/files#diff-3> (14)
  *   M CMake/cdat_modules/hdf5_pkg.cmake<https://github.com/UV-CDAT/uvcdat/pull/1370/files#diff-4> (4)
  *   M CMake/cdat_modules/netcdf_deps.cmake<https://github.com/UV-CDAT/uvcdat/pull/1370/files#diff-5> (3)
  *   M CMake/cdat_modules/netcdf_external.cmake<https://github.com/UV-CDAT/uvcdat/pull/1370/files#diff-6> (13)
  *   M CMake/cdat_modules/netcdf_pkg.cmake<https://github.com/UV-CDAT/uvcdat/pull/1370/files#diff-7> (4)
  *   A CMake/cdat_modules/pnetcdf_deps.cmake<https://github.com/UV-CDAT/uvcdat/pull/1370/files#diff-8> (1)
  *   A CMake/cdat_modules/pnetcdf_external.cmake<https://github.com/UV-CDAT/uvcdat/pull/1370/files#diff-9> (17)
  *   A CMake/cdat_modules/pnetcdf_pkg.cmake<https://github.com/UV-CDAT/uvcdat/pull/1370/files#diff-10> (13)
  *   A CMake/cdat_modules/pycparser_deps.cmake<https://github.com/UV-CDAT/uvcdat/pull/1370/files#diff-11> (1)
  *   A CMake/cdat_modules/pycparser_external.cmake<https://github.com/UV-CDAT/uvcdat/pull/1370/files#diff-12> (6)
  *   A CMake/cdat_modules/pycparser_pkg.cmake<https://github.com/UV-CDAT/uvcdat/pull/1370/files#diff-13> (10)
  *   M CMake/cdat_modules/pyopenssl_deps.cmake<https://github.com/UV-CDAT/uvcdat/pull/1370/files#diff-14> (2)
  *   A CMake/cdat_modules_extra/cdatmpi_configure_step.cmake.in<https://github.com/UV-CDAT/uvcdat/pull/1370/files#diff-15> (21)
  *   M CMake/cmake_modules/pipinstaller.cmake<https://github.com/UV-CDAT/uvcdat/pull/1370/files#diff-16> (4)
  *   M CMakeLists.txt<https://github.com/UV-CDAT/uvcdat/pull/1370/files#diff-17> (15)

Patch Links:

  *   https://github.com/UV-CDAT/uvcdat/pull/1370.patch
  *   https://github.com/UV-CDAT/uvcdat/pull/1370.diff

**Comment by doutriaux1** [comment]
@isubsmith you can always build then checkout 2.2.0 and re-install vcs/dv3d on top of it.

**Comment by aashish24** [comment]
@doutriaux1 I think this change is no longer valid anymore. Closing this request. Open when you are done.

**Comment by doutriaux1** [comment]
@aashish24 yes it went into the other branch you merged #1388

**Pull request closed without merging**
