### PR TITLE
Fix #1008

### LINKED ISSUE #1008: invalid units lead to error at plot time
```
Traceback (most recent call last):
  File "/usr/local/uvcdat/2.1.0/vistrails/vistrails/gui/uvcdat/project_controller.py", line 776, in plot_was_dropped
    self.check_update_cell(sheetName,row,col, update)
  File "/usr/local/uvcdat/2.1.0/vistrails/vistrails/gui/uvcdat/project_controller.py", line 910, in check_update_cell
    self.update_cell(sheetName, row, col, reuse_workflow)
  File "/usr/local/uvcdat/2.1.0/vistrails/vistrails/gui/uvcdat/project_controller.py", line 992, in update_cell
    reuse_workflow)
  File "/usr/local/uvcdat/2.1.0/vistrails/vistrails/gui/uvcdat/project_controller.py", line 1038, in update_workflow
    self.execute_plot(cell.current_parent_version)
  File "/usr/local/uvcdat/2.1.0/vistrails/vistrails/gui/uvcdat/project_controller.py", line 807, in execute_plot
    (results, changed) = self.vt_controller.execute_current_workflow()
  File "/usr/local/uvcdat/2.1.0/vistrails/vistrails/gui/vistrail_controller.py", line 337, in execute_current_workflow
    None)])
  File "/usr/local/uvcdat/2.1.0/vistrails/vistrails/gui/vistrail_controller.py", line 312, in execute_workflow_list
    vistrails)
  File "/usr/local/uvcdat/2.1.0/vistrails/vistrails/core/vistrail/controller.py", line 2337, in execute_workflow_list
    result = interpreter.execute(pipeline, **kwargs)
  File "/usr/local/uvcdat/2.1.0/vistrails/vistrails/core/utils/lockmethod.py", line 40, in decorated
    result = method(self, *args, **kwargs)
  File "/usr/local/uvcdat/2.1.0/vistrails/vistrails/core/interpreter/cached.py", line 611, in execute
    result = self.unlocked_execute(pipeline, **new_kwargs)
  File "/usr/local/uvcdat/2.1.0/vistrails/vistrails/core/interpreter/cached.py", line 513, in unlocked_execute
    res = self.execute_pipeline(pipeline, *(res[:2]), **kwargs)
  File "/usr/local/uvcdat/2.1.0/vistrails/vistrails/core/interpreter/cached.py", line 421, in execute_pipeline
    obj.update()
  File "/usr/local/uvcdat/2.1.0/vistrails/vistrails/core/modules/vistrails_module.py", line 327, in update
    self.compute()
  File "/usr/local/uvcdat/2.1.0/vistrails/vistrails/packages/uvcdat_cdms/init.py", line 1282, in compute
    self.cellWidget = self.displayAndWait(QCDATWidget, input_ports)
  File "/usr/local/uvcdat/2.1.0/vistrails/vistrails/packages/spreadsheet/basic_widgets.py", line 247, in displayAndWait
    return spreadsheetWindow.displayCellEvent(e)
  File "/usr/local/uvcdat/2.1.0/vistrails/vistrails/packages/spreadsheet/spreadsheet_window.py", line 491, in displayCellEvent
    sheet.setCellByType(row, col, e.cellType, e.inputPorts)
  File "/usr/local/uvcdat/2.1.0/vistrails/vistrails/packages/spreadsheet/spreadsheet_tab.py", line 320, in setCellByType
    newCell.updateContents(inputPorts)
  File "/usr/local/uvcdat/2.1.0/vistrails/vistrails/packages/uvcdat_cdms/init.py", line 1457, in updateContents
    self.canvas.plot(cgm,*args,**kwargs)
  File "/usr/local/uvcdat/2.1.0/lib/python2.7/site-packages/vcs/Canvas.py", line 2589, in plot
    a = self.__plot( arglist, keyargs )
  File "/usr/local/uvcdat/2.1.0/lib/python2.7/site-packages/vcs/Canvas.py", line 3649, in __plot
    returned_kargs = self.backend.plot(*arglist,**keyargs)
  File "/usr/local/uvcdat/2.1.0/lib/python2.7/site-packages/vcs/VTKPlots.py", line 390, in plot
    returned.update(self.plot2D(data1,data2,tpl,gm,vtk_backend_grid=vtk_backend_grid,vtk_backend_geo=vtk_backend_geo))
  File "/usr/local/uvcdat/2.1.0/lib/python2.7/site-packages/vcs/VTKPlots.py", line 1123, in plot2D
    returned.update(self.renderTemplate(tmpl,data1,gm,t,z))
  File "/usr/local/uvcdat/2.1.0/lib/python2.7/site-packages/vcs/VTKPlots.py", line 1181, in renderTemplate
    tstr = str(cdtime.reltime(taxis[0],taxis.units).tocomp(taxis.getCalendar()))
Cdtime error: Invalid relative time units
```

### PR DESCRIPTION
**Pull request by doutriaux1**
@aashish24 @dlonie @chaosphere2112

### CODE REVIEW

**Comment by aashish24** [comment]
Is there a corresponding test image branch as well?

**Comment by doutriaux1** [comment]
nope

**Comment by aashish24** [comment]
LGTM

**Comment by doutriaux1** [comment]
@aashish24 what's holding this one?

**Comment by doutriaux1** [comment]
oh I see no automerge, let me merge master back in and fix conflicts.

**Comment by doutriaux1** [comment]
@aashish24 auto  merge ok now.

**Comment by doutriaux1** [comment]
@aashish24 friendly ping

**Pull request merged**
