### PR TITLE
Issue 903 turn off paraview

### PR DESCRIPTION
**Pull request by doutriaux1**

### CODE REVIEW

**Comment by doutriaux1** [comment]
@dlonie @aashish24 @chaosphere2112 @jbeezley

**Comment by aashish24** [comment]
LGTM, lets wait for the buildbot

**Comment by doutriaux1** [comment]
does the buildbot turn on CDAT_BUILD_MODE=ALL ? otherwise the buldbot won't see that change :wink:

**Comment by jbeezley** [comment]
No, at the moment it doesn't.

**Comment by doutriaux1** [comment]
well then...

**Comment by jbeezley** [comment]
Also the results from buildbot are going to be useless because this doesn't contain #1261.

**Comment by doutriaux1** [comment]
and now i get this again:
```
  -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk/usr/include
  -m64 -mmacosx-version-min=10.9 -isysroot
  /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk
  -pipe -m64 -mmacosx-version-min=10.9 -isysroot
  /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk
  -c src/pmpi-vt-hyb.c -o build/temp.macosx-10.4-x86_64-2.7/src/pmpi-vt-hyb.o

  running build_ext

  MPI configuration: [mpi] from 'mpi.cfg'

  MPI C compiler: /Users/doutriaux1/build/install/Externals/bin/mpicc

  MPI C++ compiler: /Users/doutriaux1/build/install/Externals/bin/mpicxx

  MPI F77 compiler: /Users/doutriaux1/build/install/Externals/bin/mpif77

  MPI F90 compiler: /Users/doutriaux1/build/install/Externals/bin/mpif90

  checking for MPI compile and link ...

  checking for header 'mpi.h' ...

  /Users/doutriaux1/build/install/Externals/bin/mpicc -fno-strict-aliasing
  -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes
  -I/Users/doutriaux1/build/install/Externals/include
  -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk/usr/include
  -m64 -mmacosx-version-min=10.9 -isysroot
  /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk
  -pipe -m64 -mmacosx-version-min=10.9 -isysroot
  /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk
  -I/Users/doutriaux1/build/install/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7
  -c _configtest.c -o _configtest.o

  failure.

  removing: _configtest.c _configtest.o

  failure.

  

  CMake Error at /Users/doutriaux1/build/CMake/mpi4py_make_step.cmake:18
  (message):

    Error in config of mpi4py

  

  

  -------------------------------------------------



make[2]: *** [Mpi4py-prefix/src/Mpi4py-stamp/Mpi4py-build] Error 1
make[1]: *** [CMakeFiles/Mpi4py.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
```

It had been a while....

**Comment by aashish24** [comment]
@doutriaux1 can you update this branch once #1261 goes in?

**Comment by doutriaux1** [comment]
sure but I don't think it will help with my error. Let's wait and see.

**Comment by aashish24** [comment]
no it wont much but it will verify that default build is not broken because of this change. We still have to fix the MPI issue.

**Comment by doutriaux1** [comment]
I tried with a simple "make" (not parallel)
I get the error on esmf, so it doesn't help:
```
[ 23%] Performing build step for 'ESMF'
CMake Error at /Users/doutriaux1/build/ESMF-prefix/src/ESMF-stamp/ESMF-build.cmake:56 (message):
  CTEST_FULL_OUTPUT

   Command failed: 1
   '/Applications/CMake.app/Contents/bin/cmake' '-P' '/Users/doutriaux1/build/CMake/ESMF_make_step.cmake'
   From /Users/doutriaux1/build/ESMF-prefix/src/ESMF-stamp/ESMF-build-out.log

  -------------------------------------------------

  -------------------------------------------------

   From /Users/doutriaux1/build/ESMF-prefix/src/ESMF-stamp/ESMF-build-err.log

  -------------------------------------------------

  CMake Warning (dev) in /Users/doutriaux1/build/CMake/ESMF_make_step.cmake:

    Syntax Warning in cmake code at

  

      /Users/doutriaux1/build/CMake/ESMF_make_step.cmake:31:28

  

    Argument not separated from preceding token by whitespace.

  This warning is for project developers.  Use -Wno-dev to suppress it.

  

  [INFO] ADDITIONAL CFLAGS

  Make Errors detected:

   

  --------------------------------------------------------------

  Make version:

  GNU Make 3.81

  Copyright (C) 2006 Free Software Foundation, Inc.

  This is free software; see the source for copying conditions.

  There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A

  PARTICULAR PURPOSE.

  

  This program built for i386-apple-darwin11.3.0

  

  --------------------------------------------------------------

  Fortran Compiler version:

  

  --------------------------------------------------------------

  C++ Compiler version:

  

  --------------------------------------------------------------

  Preprocessor version:

  Apple LLVM version 6.1.0 (clang-602.0.49) (based on LLVM 3.6.0svn)

  Target: x86_64-apple-darwin14.3.0

  Thread model: posix

  

  --------------------------------------------------------------

  ESMF_VERSION_STRING: 6.3.0rp1

  --------------------------------------------------------------

   

  --------------------------------------------------------------

   * User set ESMF environment variables *

  ESMF_OS=Darwin

  ESMF_OPENMP=OFF

  ESMF_PTHREADS=OFF

  ESMF_DIR=/Users/doutriaux1/build/build/ESMF/esmf

  ESMF_ARRAYLITE=TRUE

  ESMF_COMM=openmpi

  ESMF_INSTALL_PREFIX=/Users/doutriaux1/build/install/Externals

  ESMF_MOAB=OFF

  ESMF_ABI=64

  ESMF_COMPILER=gfortran

   

  --------------------------------------------------------------

   * ESMF environment variables *

  ESMF_DIR: /Users/doutriaux1/build/build/ESMF/esmf

  ESMF_OS: Darwin

  ESMF_MACHINE: x86_64

  ESMF_ABI: 64

  ESMF_COMPILER: gfortran

  ESMF_BOPT: O

  ESMF_COMM: openmpi

  ESMF_SITE: default

  ESMF_PTHREADS: OFF

  ESMF_OPENMP: OFF

  ESMF_OPENACC: OFF

  ESMF_ARRAY_LITE: FALSE

  ESMF_NO_INTEGER_1_BYTE: TRUE

  ESMF_NO_INTEGER_2_BYTE: TRUE

  ESMF_FORTRANSYMBOLS: default

  ESMF_DEFER_LIB_BUILD: ON

  ESMF_SHARED_LIB_BUILD: ON

  ESMF_TESTEXHAUSTIVE: OFF

  ESMF_TESTWITHTHREADS: OFF

  ESMF_TESTMPMD: OFF

  ESMF_TESTSHAREDOBJ: OFF

  ESMF_TESTFORCEOPENMP: OFF

  ESMF_TESTFORCEOPENACC: OFF

  ESMF_TESTHARNESS_ARRAY: default

  ESMF_TESTHARNESS_FIELD: default

  ESMF_MPIRUN: mpirun

   

  --------------------------------------------------------------

   * ESMF environment variables pointing to 3rd party software *

  ESMF_MOAB: OFF

  ESMF_LAPACK: internal

   

  --------------------------------------------------------------

   * ESMF environment variables for final installation *

  ESMF_INSTALL_PREFIX: /Users/doutriaux1/build/install/Externals

  ESMF_INSTALL_HEADERDIR: include

  ESMF_INSTALL_MODDIR: mod/modO/Darwin.gfortran.64.openmpi.default

  ESMF_INSTALL_LIBDIR: lib/libO/Darwin.gfortran.64.openmpi.default

  ESMF_INSTALL_BINDIR: bin/binO/Darwin.gfortran.64.openmpi.default

  ESMF_INSTALL_DOCDIR: doc

   

  --------------------------------------------------------------

   * Compilers, Linkers, Flags, and Libraries *

  Location of the preprocessor: /usr/bin/gcc

  Location of the Fortran compiler:
  /Users/doutriaux1/build/install/Externals/bin/mpif90

  Location of the Fortran linker:
  /Users/doutriaux1/build/install/Externals/bin/mpif90

  Location of the C++ compiler:
  /Users/doutriaux1/build/install/Externals/bin/mpicxx

  Location of the C++ linker:
  /Users/doutriaux1/build/install/Externals/bin/mpicxx

  

  Fortran compiler flags:

  ESMF_F90COMPILEOPTS: -O -m64 -mcmodel=small -ffree-line-length-none

  ESMF_F90COMPILEPATHS:
  -I/Users/doutriaux1/build/build/ESMF/esmf/mod/modO/Darwin.gfortran.64.openmpi.default
  -I/Users/doutriaux1/build/build/ESMF/esmf/src/include

  ESMF_F90COMPILECPPFLAGS: -DESMF_NO_INTEGER_1_BYTE -DESMF_NO_INTEGER_2_BYTE
  -DESMF_LAPACK=1 -DESMF_MPIIO -DESMF_NO_PTHREADS -DESMF_NO_OPENMP
  -DESMF_NO_OPENACC -DSx86_64_small=1 -DESMF_OS_Darwin=1

  ESMF_F90COMPILEFREECPP:

  ESMF_F90COMPILEFREENOCPP: -ffree-form

  ESMF_F90COMPILEFIXCPP: -cpp -ffixed-form

  ESMF_F90COMPILEFIXNOCPP:

  

  Fortran linker flags:

  ESMF_F90LINKOPTS: -m64 -mcmodel=small

  ESMF_F90LINKPATHS:
  -L/Users/doutriaux1/build/build/ESMF/esmf/lib/libO/Darwin.gfortran.64.openmpi.default
  -L

  ESMF_F90LINKRPATHS:

  ESMF_F90LINKLIBS: -lmpi_cxx -lstdc++

  ESMF_F90ESMFLINKLIBS: -lesmf -lmpi_cxx -lstdc++

  

  C++ compiler flags:

  ESMF_CXXCOMPILEOPTS: -O -DNDEBUG -DESMF_LOWERCASE_SINGLEUNDERSCORE -m64
  -mcmodel=small

  ESMF_CXXCOMPILEPATHS: -I/Users/doutriaux1/build/build/ESMF/esmf/src/include


  ESMF_CXXCOMPILECPPFLAGS: -DESMF_NO_INTEGER_1_BYTE -DESMF_NO_INTEGER_2_BYTE
  -DESMF_LAPACK=1 -DESMF_MPIIO -DESMF_NO_PTHREADS -DESMF_NO_OPENMP
  -DESMF_NO_OPENACC -DSx86_64_small=1 -DESMF_OS_Darwin=1 -D__SDIR__=''
  -DESMF_NO_SIGUSR2

  

  C++ linker flags:

  ESMF_CXXLINKOPTS: -m64 -mcmodel=small

  ESMF_CXXLINKPATHS:
  -L/Users/doutriaux1/build/build/ESMF/esmf/lib/libO/Darwin.gfortran.64.openmpi.default
  -L

  ESMF_CXXLINKRPATHS:

  ESMF_CXXLINKLIBS: -lmpi_f77 -lgfortran

  ESMF_CXXESMFLINKLIBS: -lesmf -lmpi_f77 -lgfortran

  

  Shared library build:

  ESMF_SL_LIBS_TO_MAKE: libesmf

  ESMF_SL_SUFFIX: dylib

  ESMF_SL_LIBLINKER: mpicxx

  ESMF_SL_LIBOPTS: -dynamiclib

  ESMF_SL_LIBLIBS:
  -L/Users/doutriaux1/build/build/ESMF/esmf/lib/libO/Darwin.gfortran.64.openmpi.default
  -L -lmpi_cxx -lstdc++
  -L/Users/doutriaux1/build/build/ESMF/esmf/lib/libO/Darwin.gfortran.64.openmpi.default
  -L -lmpi_f77 -lgfortran

  

  

  --------------------------------------------------------------

  Compiling on Mon May 4 16:00:25 PDT 2015 on sofia.llnl.gov

  Machine characteristics: Darwin sofia.llnl.gov 14.3.0 Darwin Kernel Version
  14.3.0: Mon Mar 23 11:59:05 PDT 2015; root:xnu-2782.20.48~5/RELEASE_X86_64
  x86_64

  ==============================================================

   

  Making directory
  /Users/doutriaux1/build/build/ESMF/esmf/lib/libO/Darwin.gfortran.64.openmpi.default
  for library

  Making directory
  /Users/doutriaux1/build/build/ESMF/esmf/mod/modO/Darwin.gfortran.64.openmpi.default
  for *.mod files

  Making directory
  /Users/doutriaux1/build/build/ESMF/esmf/obj/objO/Darwin.gfortran.64.openmpi.default
  for *.o files

  Making directory /Users/doutriaux1/build/build/ESMF/esmf/src/include for
  include files

  Making directory /Users/doutriaux1/build/build/ESMF/esmf/src/etc for
  Attribute package files

  /Users/doutriaux1/build/build/ESMF/esmf/src

  tree_include tree_etc in: /Users/doutriaux1/build/build/ESMF/esmf/src

  /Users/doutriaux1/build/build/ESMF/esmf/src/prologue

  tree_include tree_etc in:
  /Users/doutriaux1/build/build/ESMF/esmf/src/prologue

  /Users/doutriaux1/build/build/ESMF/esmf/src/prologue/tests

  tree_include tree_etc in:
  /Users/doutriaux1/build/build/ESMF/esmf/src/prologue/tests

  /Users/doutriaux1/build/build/ESMF/esmf/src/test_harness

  tree_include tree_etc in:
  /Users/doutriaux1/build/build/ESMF/esmf/src/test_harness

  /Users/doutriaux1/build/build/ESMF/esmf/src/test_harness/src

  tree_include tree_etc in:
  /Users/doutriaux1/build/build/ESMF/esmf/src/test_harness/src

  /Users/doutriaux1/build/build/ESMF/esmf/src/Infrastructure

  tree_include tree_etc in:
  /Users/doutriaux1/build/build/ESMF/esmf/src/Infrastructure

  /Users/doutriaux1/build/build/ESMF/esmf/src/Infrastructure/stubs

  tree_include tree_etc in:
  /Users/doutriaux1/build/build/ESMF/esmf/src/Infrastructure/stubs

  /Users/doutriaux1/build/build/ESMF/esmf/src/Infrastructure/stubs/mpiuni

  tree_include tree_etc in:
  /Users/doutriaux1/build/build/ESMF/esmf/src/Infrastructure/stubs/mpiuni

  /Users/doutriaux1/build/build/ESMF/esmf/src/Infrastructure/Util

  tree_include tree_etc in:
  /Users/doutriaux1/build/build/ESMF/esmf/src/Infrastructure/Util

  /Users/doutriaux1/build/build/ESMF/esmf/src/Infrastructure/Util/src

  tree_include tree_etc in:
  /Users/doutriaux1/build/build/ESMF/esmf/src/Infrastructure/Util/src

  /Users/doutriaux1/build/build/ESMF/esmf/src/Infrastructure/Util/interface

  tree_include tree_etc in:
  /Users/doutriaux1/build/build/ESMF/esmf/src/Infrastructure/Util/interface

  /Users/doutriaux1/build/build/ESMF/esmf/src/Infrastructure/Util/tests

  tree_include tree_etc in:
  /Users/doutriaux1/build/build/ESMF/esmf/src/Infrastructure/Util/tests

  /Users/doutriaux1/build/build/ESMF/esmf/src/Infrastructure/Util/examples

  tree_include tree_etc in:
  /Users/doutriaux1/build/build/ESMF/esmf/src/Infrastructure/Util/examples

  /Users/doutriaux1/build/build/ESMF/esmf/src/Infrastructure/Util/doc

  tree_include tree_etc in:
  /Users/doutriaux1/build/build/ESMF/esmf/src/Infrastructure/Util/doc

  /Users/doutriaux1/build/build/ESMF/esmf/src/Infrastructure/LogErr

  tree_include tree_etc in:
  /Users/doutriaux1/build/build/ESMF/esmf/src/Infrastructure/LogErr

  /Users/doutriaux1/build/build/ESMF/esmf/src/Infrastructure/LogErr/src

  tree_include tree_etc in:
  /Users/doutriaux1/build/build/ESMF/esmf/src/Infrastructure/LogErr/src

  
  /Users/doutriaux1/build/build/ESMF/esmf/src/Infrastructure/LogErr/interface


  tree_include tree_etc in:
  /Users/doutriaux1/build/build/ESMF/esmf/src/Infrastructure/LogErr/interface


  /Users/doutriaux1/build/build/ESMF/esmf/src/Infrastructure/LogErr/examples

  tree_include tree_etc in:
  /Users/doutriaux1/build/build/ESMF/esmf/src/Infrastructure/LogErr/examples

  /Users/doutriaux1/build/build/ESMF/esmf/src/Infrastructure/LogErr/doc

  tree_include tree_etc in:
  /Users/doutriaux1/build/build/ESMF/esmf/src/Infrastructure/LogErr/doc

  /Users/doutriaux1/build/build/ESMF/esmf/src/Infrastructure/LogErr/tests

  tree_include tree_etc in:
  /Users/doutriaux1/build/build/ESMF/esmf/src/Infrastructure/LogErr/tests

  /Users/doutriaux1/build/build/ESMF/esmf/src/Infrastructure/VM

  tree_include tree_etc in:
  /Users/doutriaux1/build/build/ESMF/esmf/src/Infrastructure/VM

  /Users/doutriaux1/build/build/ESMF/esmf/src/Infrastructure/VM/src

  tree_include tree_etc in:
  /Users/doutriaux1/build/build/ESMF/esmf/src/Infrastructure/VM/src

  /Users/doutriaux1/build/build/ESMF/esmf/src/Infrastructure/VM/interface

  tree_include tree_etc in:
  /Users/doutriaux1/build/build/ESMF/esmf/src/Infrastructure/VM/interface

  /Users/doutriaux1/build/build/ESMF/esmf/src/Infrastructure/VM/doc

  tree_include tree_etc in:
  /Users/doutriaux1/build/build/ESMF/esmf/src/Infrastructure/VM/doc

  /Users/doutriaux1/build/build/ESMF/esmf/src/Infrastructure/VM/examples

  tree_include tree_etc in:
  /Users/doutriaux1/build/build/ESMF/esmf/src/Infrastructure/VM/examples

  /Users/doutriaux1/build/build/ESMF/esmf/src/Infrastructure/VM/tests

  tree_include tree_etc in:
  /Users/doutriaux1/build/build/ESMF/esmf/src/Infrastructure/VM/tests

  /Users/doutriaux1/build/build/ESMF/esmf/src/Infrastructure/Base

  tree_include tree_etc in:
  /Users/doutriaux1/build/build/ESMF/esmf/src/Infrastructure/Base

  /Users/doutriaux1/build/build/ESMF/esmf/src/Infrastructure/Base/src

  tree_include tree_etc in:
  /Users/doutriaux1/build/build/ESMF/esmf/src/Infrastructure/Base/src

  /Users/doutriaux1/build/build/ESMF/esmf/src/Infrastructure/Base/interface

  tree_include tree_etc in:
  /Users/doutriaux1/build/build/ESMF/esmf/src/Infrastructure/Base/interface

  /Users/doutriaux1/build/build/ESMF/esmf/src/Infrastructure/Base/doc

  tree_include tree_etc in:
  /Users/doutriaux1/build/build/ESMF/esmf/src/Infrastructure/Base/doc

  /Users/doutriaux1/build/build/ESMF/esmf/src/Infrastructure/Base/tests

  tree_include tree_etc in:
  /Users/doutriaux1/build/build/ESMF/esmf/src/Infrastructure/Base/tests

  /Users/doutriaux1/build/build/ESMF/esmf/src/Infrastructure/TimeMgr

  tree_include tree_etc in:
  /Users/doutriaux1/build/build/ESMF/esmf/src/Infrastructure/TimeMgr

  /Users/doutriaux1/build/build/ESMF/esmf/src/Infrastructure/TimeMgr/src

  tree_include tree_etc in:
  /Users/doutriaux1/build/build/ESMF/esmf/src/Infrastructure/TimeMgr/src

  
  /Users/doutriaux1/build/build/ESMF/esmf/src/Infrastructure/TimeMgr/interface


  tree_include tree_etc in:
  /Users/doutriaux1/build/build/ESMF/esmf/src/Infrastructure/TimeMgr/interface


  
  /Users/doutriaux1/build/build/ESMF/esmf/src/Infrastructure/TimeMgr/examples


  tree_include tree_etc in:
  /Users/doutriaux1/build/build/ESMF/esmf/src/Infrastructure/TimeMgr/examples


  /Users/doutriaux1/build/build/ESMF/esmf/src/Infrastructure/TimeMgr/tests

  tree_include tree_etc in:
  /Users/doutriaux1/build/build/ESMF/esmf/src/Infrastructure/TimeMgr/tests

  /Users/doutriaux1/build/build/ESMF/esmf/src/Infrastructure/TimeMgr/doc

  tree_include tree_etc in:
  /Users/doutriaux1/build/build/ESMF/esmf/src/Infrastructure/TimeMgr/doc

  /Users/doutriaux1/build/build/ESMF/esmf/src/Infrastructure/DELayout

  tree_include tree_etc in:
  /Users/doutriaux1/build/build/ESMF/esmf/src/Infrastructure/DELayout

  /Users/doutriaux1/build/build/ESMF/esmf/src/Infrastructure/DELayout/src

  tree_include tree_etc in:
  /Users/doutriaux1/build/build/ESMF/esmf/src/Infrastructure/DELayout/src

  
  /Users/doutriaux1/build/build/ESMF/esmf/src/Infrastructure/DELayout/interface


  tree_include tree_etc in:
  /Users/doutriaux1/build/build/ESMF/esmf/src/Infrastructure/DELayout/interface


  /Users/doutriaux1/build/build/ESMF/esmf/src/Infrastructure/DELayout/tests

  tree_include tree_etc in:
  /Users/doutriaux1/build/build/ESMF/esmf/src/Infrastructure/DELayout/tests

  
  /Users/doutriaux1/build/build/ESMF/esmf/src/Infrastructure/DELayout/examples


  tree_include tree_etc in:
  /Users/doutriaux1/build/build/ESMF/esmf/src/Infrastructure/DELayout/examples


  /Users/doutriaux1/build/build/ESMF/esmf/src/Infrastructure/DELayout/doc

  tree_include tree_etc in:
  /Users/doutriaux1/build/build/ESMF/esmf/src/Infrastructure/DELayout/doc

  /Users/doutriaux1/build/build/ESMF/esmf/src/Infrastructure/Config

  tree_include tree_etc in:
  /Users/doutriaux1/build/build/ESMF/esmf/src/Infrastructure/Config

  /Users/doutriaux1/build/build/ESMF/esmf/src/Infrastructure/Config/src

  tree_include tree_etc in:
  /Users/doutriaux1/build/build/ESMF/esmf/src/Infrastructure/Config/src

  
  /Users/doutriaux1/build/build/ESMF/esmf/src/Infrastructure/Config/interface


  tree_include tree_etc in:
  /Users/doutriaux1/build/build/ESMF/esmf/src/Infrastructure/Config/interface


  /Users/doutriaux1/build/build/ESMF/esmf/src/Infrastructure/Config/examples

  tree_include tree_etc in:
  /Users/doutriaux1/build/build/ESMF/esmf/src/Infrastructure/Config/examples

  /Users/doutriaux1/build/build/ESMF/esmf/src/Infrastructure/Config/doc

  tree_include tree_etc in:
  /Users/doutriaux1/build/build/ESMF/esmf/src/Infrastructure/Config/doc

  /Users/doutriaux1/build/build/ESMF/esmf/src/Infrastructure/Config/tests

  tree_include tree_etc in:
  /Users/doutriaux1/build/build/ESMF/esmf/src/Infrastructure/Config/tests

  /Users/doutriaux1/build/build/ESMF/esmf/src/Infrastructure/ArraySpec

  tree_include tree_etc in:
  /Users/doutriaux1/build/build/ESMF/esmf/src/Infrastructure/ArraySpec

  /Users/doutriaux1/build/build/ESMF/esmf/src/Infrastructure/ArraySpec/src

  tree_include tree_etc in:
  /Users/doutriaux1/build/build/ESMF/esmf/src/Infrastructure/ArraySpec/src

  
  /Users/doutriaux1/build/build/ESMF/esmf/src/Infrastructure/ArraySpec/interface


  tree_include tree_etc in:
  /Users/doutriaux1/build/build/ESMF/esmf/src/Infrastructure/ArraySpec/interface


  /Users/doutriaux1/build

  -------------------------------------------------



make[2]: *** [ESMF-prefix/src/ESMF-stamp/ESMF-build] Error 1
make[1]: *** [CMakeFiles/ESMF.dir/all] Error 2
make: *** [all] Error 2

```

**Comment by doutriaux1** [comment]
looking at esmf_external.cmake i see:
```
set(ESMF_openmp "ON")

if(APPLE)
  if("${CMAKE_C_COMPILER_ID}" STREQUAL "Clang" AND ${CMAKE_C_COMPILER_VERSION} VERSION_GREATER 4.2)
    # xcode 5 clang does not support openmp
    set(ESMF_openmp "OFF")
  endif()
endif()

# Check if ESMF should be built in parallel
set(emsf_enable_mpi FALSE)
if(CDAT_BUILD_ESMF_PARALLEL)
  set(emsf_enable_mpi TRUE)
endif()

if("${emsf_enable_mpi}")
  set(ESMF_comm "${CDAT_BUILD_ESMF_COMM}")
else()
  message("[INFO] CDAT will build ESMF serial")
  set(ESMF_comm "mpiuni")
endif()
```
Should we worry about the openmp bit?

**Comment by doutriaux1** [comment]
ok. After it fails. sourcing setup_runtime.sh and rerunnig make makes it work. Will see if I can add this to the make files.

**Comment by dlonie** [comment]
Is it guaranteed that setup_runtime.sh will be available at this point during building?

It seems a cleaner solution to add the missing environment components to the esmf build script directly, rather than relying on sourcing the setup script during compilation. I've actually run into problems with sourcing setup_runtime during compilation -- it confuses some of the builds, e.g. `pkg-config` has trouble finding system libraries when the uvcdat pkg-config is used, rather than the system version.

**Comment by doutriaux1** [comment]
@dlonie I was thinking about this. We already tend to do this for other modules. But setup_runtime is created at the time we run cmake. so when building it will be there. I was thinking we should use this, because this is being updated constantly and it reflects more precisely the user environment when uvcdat will be ran. What do you think?

**Comment by potter2** [comment]
we cannot rely on setup script. i was referring to cmake of whats failing.

**Comment by doutriaux1** [comment]
@potter2 ???

**Comment by doutriaux1** [comment]
ok since merging in release evrything seems to build smoothly again... not 100% sure of what happened, I guess #1261 helped a lot. Anybody care to approve/merge this.

**Comment by doutriaux1** [comment]
by the way looking at the failed test on garant:
https://open.cdash.org/testDetails.php?test=333421116&build=3800361
it almost looks like it's not picking up the correct netcdf at runtime.

**Comment by aashish24** [comment]
LGTM :+1:

**Comment by stefraynaud** [comment]
`CDAT_BUILD_PARAVIEW=OFF` seems to have no effect

    cmake -DCDAT_BUILD_PARAVIEW=OFF
    ...
    [INFO] Setting build package -- ParaView ON -- as required by VisIt
    ...

What is the right combination of cmake keys to switch paraview off when we don't need it and its dependencies?

**Comment by doutriaux1** [comment]
it should be off by default on master. Is this release or master or some other tag? Thanks.

**Pull request merged**
