### PR TITLE
Fix continents=0

### PR DESCRIPTION
**Pull request by chaosphere2112**
Fixes an issue where plotting without continents would break stuff indefinitely. Test inbound.

### CODE REVIEW

**Comment by chaosphere2112** [comment]
@doutriaux1 @aashish24 @danlipsa Please review. Bumped into this while doing an example for someone, should go in 2.4.2.

**Comment by aashish24** [comment]
LGTM :+1: you meant 2.6? I don't think we talkd about 2.4.2?

**Comment by aashish24** [comment]
ping @chaosphere2112 just wanted to make sure you saw my +2

**Comment by chaosphere2112** [comment]
@aashish24 I was confused about a UVCMetrics thing; UVCMetrics is getting a 2.4.2, but since it's now decoupled from UV-CDAT's release cycle, we won't be having a corresponding release. Should go in 2.6, though. Sorry, I've been out sick for a few days.

**Comment by aashish24** [comment]
> @aashish24 I was confused about a UVCMetrics thing; UVCMetrics is getting a 2.4.2, but since it's now decoupled from UV-CDAT's release cycle, we won't be having a corresponding release. Should go in 2.6, though. Sorry, I've been out sick for a few days.

No problem. thanks for the update. this branch is good to go if you want to merge it.

**Pull request merged**
