### PR TITLE
BUG #1739: fitToViewport uses dataset bounds instead of recomputing them

### PR DESCRIPTION
**Pull request by danlipsa**
fitToViewport used to recompute the dataset bounds using an 2D array of points.
This was slow and imprecise. Now we pass the dataset bounds as parameters.

### CODE REVIEW

**Comment by danlipsa** [comment]
This is still work in progress. I need to replace all fitToViewport with the bounds version.

**Comment by aashish24** [comment]
@danlipsa do you want to post update to all of us?

**Comment by aashish24** [comment]
https://github.com/UV-CDAT/uvcdat-testdata/pull/98

**Comment by aashish24** [comment]
@doutriaux1 did you review this branch?

**Comment by doutriaux1** [comment]
Not yet, was working on bots and lambert yesterday.

**Comment by aashish24** [comment]
@doutriaux1 let's merge this one as well soon so that we can release it today.

**Comment by doutriaux1** [comment]
there's no release w/o projections. Will take a look at this one when proj are in better shape.

**Comment by aashish24** [comment]
> there's no release w/o projections. Will take a look at this one when proj are in better shape.

@doutriaux1 lets talk about this in the afternoon. I don't understand what you are saying here. Based on our discussions, we should release as things are better and not more broken than before.

**Comment by doutriaux1** [comment]
all i'm saying is I want to give a fair shot to the projection part, if we keep adding bits in the mean time it makes it harder to fix the proj issue. I will take a look at tihs when we fix or quit the proj issues

**Comment by doutriaux1** [comment]
@aashish24 @danlipsa ok this branch look good, but there's going to be baseline conflicts with lambert branch (whichever you decide on). LEt's merge lambert first and then update again this PR. Ok?

**Comment by doutriaux1** [comment]
once lambert is in master I will trigger a rebuild of this one so we can see which files need updating.

**Comment by aashish24** [comment]
> @aashish24 @danlipsa ok this branch look good, but there's going to be baseline conflicts with lambert branch (whichever you decide on). LEt's merge lambert first and then update again this PR. Ok?

@doutriaux1 we should merge this branch first as this was pushed before the lambert one. It would be nice if we follow the queue approach. Also, the lambert is the small one. I would prefer if you merge this one first.

**Comment by doutriaux1** [comment]
sure...

**Comment by aashish24** [comment]
@doutriaux1 did I say that you are awesome!!

**Pull request merged**
