### PR TITLE
Add flake8 test for cdms2.

### PR DESCRIPTION
**Pull request by dlonie**
The test currently fails. The code needs to be cleaned up before merging.

@doutriaux1 @aashish24

### CODE REVIEW

**Comment by dlonie** [comment]
It works \o/ https://open.cdash.org/testDetails.php?test=347717306&build=3872951

**Comment by aashish24** [comment]
@dlonie @doutriaux1  this is great stuff!!!! I think it will really improve our code quality and bring UV-CDAT to new heights.

**Comment by aashish24** [comment]
@doutriaux1 I am assuming that you will fix the styling issues.

**Comment by aashish24** [comment]
@doutriaux1 can we start fixing the styles this week?

**Pull request closed without merging**
