### PR TITLE
Enable Matplotlib in default build

### PR DESCRIPTION
**Pull request by sankhesh**
This addresses issue #1406

### CODE REVIEW

**Comment by sankhesh** [comment]
@aashish24 @doutriaux1 Please review

**Comment by aashish24** [comment]
LGTM but @doutriaux1 should approve. .

**Comment by doutriaux1** [comment]
@sankhesh that's a great start I can approve. But do you want to do basemap in a separate PR or do you want to add it in this one?

**Comment by sankhesh** [comment]
@doutriaux1 Let me add basemap in a separate PR.

**Pull request merged**
