### PR TITLE
Newdiagtest

### PR DESCRIPTION
**Pull request by painter1**
Add a new file for testing diagnostics.

### CODE REVIEW

**Comment by doutriaux1** [comment]
@painter1 is it still working off of the old "minimal" set of test data? or de we need to pupload new ones?

**Comment by painter1** [comment]
Yes, it's using the same test data.  It's "minimal", but sufficient.

**Comment by doutriaux1** [comment]
```
doutriaux1@maryam:[~/build]:[5069]> ctest -R diags_test_01 -VV
UpdateCTestConfiguration  from :/Users/doutriaux1/build/DartConfiguration.tcl
Parse Config file:/Users/doutriaux1/build/DartConfiguration.tcl
UpdateCTestConfiguration  from :/Users/doutriaux1/build/DartConfiguration.tcl
Parse Config file:/Users/doutriaux1/build/DartConfiguration.tcl
Test project /Users/doutriaux1/build
Constructing a list of tests
Done constructing a list of tests
Checking test dependency graph...
Checking test dependency graph end
test 377
    Start 377: diags_test_01

377: Test command: /lgm/uvcdat/2015-03-20/bin/python "/git/uvcdat/testing/metrics/diagtest01.py" "/Users/doutriaux1/uvcmetrics_test_data"
377: Test timeout computed to be: 1500
377: Test 1: Sample Diagnostic ... 
377: Traceback (most recent call last):
377:   File "/git/uvcdat/testing/metrics/diagtest01.py", line 39, in <module>
377:     datafiles1 = dirtree_datafiles( opts1, pathid='model' )
377: TypeError: __init__() got an unexpected keyword argument 'pathid'
1/1 Test #377: diags_test_01 ....................***Failed    1.24 sec

0% tests passed, 1 tests failed out of 1

Total Test time (real) =   1.25 sec

The following tests FAILED:
	377 - diags_test_01 (Failed)
Errors while running CTest
```

**Comment by doutriaux1** [comment]
```
doutriaux1@maryam:[~/build]:[5071]> ctest -R diags_test_02 -VV
UpdateCTestConfiguration  from :/Users/doutriaux1/build/DartConfiguration.tcl
Parse Config file:/Users/doutriaux1/build/DartConfiguration.tcl
UpdateCTestConfiguration  from :/Users/doutriaux1/build/DartConfiguration.tcl
Parse Config file:/Users/doutriaux1/build/DartConfiguration.tcl
Test project /Users/doutriaux1/build
Constructing a list of tests
Done constructing a list of tests
Checking test dependency graph...
Checking test dependency graph end
test 378
    Start 378: diags_test_02

378: Test command: /lgm/uvcdat/2015-03-20/bin/python "/git/uvcdat/testing/metrics/diagtest02.py" "--datadir=/Users/doutriaux1/uvcmetrics_test_data" "--baseline=/Users/doutriaux1/build/uvcdat-testdata/baselines/metrics/metrics/"
378: Test timeout computed to be: 1500
378: UV-CDAT Diagnostics, command-line version
378: Added set:  {'climos': 'no', 'end': None, 'name': None, 'filter': None, 'start': None, 'path': '/Users/doutriaux1/uvcmetrics_test_data/cam_output', 'type': 'model'}
378: Added set:  {'climos': 'yes', 'end': None, 'name': None, 'filter': "f_startswith('NCEP')", 'start': None, 'path': '/Users/doutriaux1/uvcmetrics_test_data/obs_atmos', 'type': 'obs'}
378: Enabling NetCDF compression on output files
378: filt:  None
378: INFO:  file /Users/doutriaux1/uvcmetrics_test_data/cam_output/c_t_b30.009.cam2.h0.0600-01.nc has an axis bound with no bounds.
378: An attempt will be made to compute bounds, but that is unreliable compared to bounds provided by the data file.
378: INFO:  file /Users/doutriaux1/uvcmetrics_test_data/cam_output/c_t_b30.009.cam2.h0.0600-01.nc has an axis lev with no bounds.
378: An attempt will be made to compute bounds, but that is unreliable compared to bounds provided by the data file.
378: There will be no more bad data warnings from constructing this filetable.
378: filt:  f_startswith('NCEP')
378: WARNING - no files found at /Users/doutriaux1/uvcmetrics_test_data/obs_atmos with filter f_startswith("NCEP")
378: using seasons= ['ANN']
378: plot set 5 - Horizontal Contour Plots of Seasonal Means
378: WARNING: Couldn't find any of the requested variables: ['T']
378: among ['AODVIS', 'CLDHGH_ISCCP', 'CLDHGH_TAU1.3-9.4_MODIS', 'CLDHGH_TAU1.3_MODIS', 'CLDHGH_TAU9.4_MODIS', 'CLDHGH_VISIR', 'CLDLOW_ISCCP', 'CLDLOW_TAU1.3-9.4_MISR', 'CLDLOW_TAU1.3_MISR', 'CLDLOW_TAU9.4_MISR', 'CLDLOW_VISIR', 'CLDMED_ISCCP', 'CLDMED_VISIR', 'CLDTOT_ISCCP', 'CLDTOT_TAU1.3-9.4_ISCCP', 'CLDTOT_TAU1.3-9.4_MISR', 'CLDTOT_TAU1.3-9.4_MODIS', 'CLDTOT_TAU1.3_ISCCP', 'CLDTOT_TAU1.3_MISR', 'CLDTOT_TAU1.3_MODIS', 'CLDTOT_TAU9.4_ISCCP', 'CLDTOT_TAU9.4_MISR', 'CLDTOT_TAU9.4_MODIS', 'CLDTOT_VISIR', 'CLISCCP', 'CLMISR', 'LHFLX', 'PRECT', 'QFLX', 'RESTOM', 'TGCLDLWP', 'TREFHT']
378: total number of (compound) diagnostic plots generated = 0
378: ERROR: In /Users/doutriaux1/build/build/VTK/IO/Image/vtkPNGReader.cxx, line 44
378: vtkPNGReader (0x7f9de8601200): Unable to open file /var/folders/nv/3xl0t1xx4yxb6tyd0yqdm238001cpd/T/tmpMOohpz/set5_Global_ANN_T-combined.png
378: 
378: ERROR: In /Users/doutriaux1/build/build/VTK/Imaging/Core/vtkImageExtractComponents.cxx, line 239
378: vtkImageExtractComponents (0x7f9de8611fc0): Execute: Component 1 is not in input.
378: 
378: Test 2: Diagnostic contour plots ...  Found Baselines:
378: - /Users/doutriaux1/build/uvcdat-testdata/baselines/metrics/metrics/set5_Global_ANN_T-combined.png
378: ERROR: In /Users/doutriaux1/build/build/VTK/IO/Image/vtkPNGReader.cxx, line 44
378: vtkPNGReader (0x7f9de8601200): Unable to open file /Users/doutriaux1/build/uvcdat-testdata/baselines/metrics/metrics/set5_Global_ANN_T-combined.png
378: 
378: ERROR: In /Users/doutriaux1/build/build/VTK/Imaging/Core/vtkImageExtractComponents.cxx, line 239
378: vtkImageExtractComponents (0x7f9de8612030): Execute: Component 1 is not in input.
378: 
378: ERROR: In /Users/doutriaux1/build/build/VTK/Imaging/Core/vtkImageDifference.cxx, line 221
378: vtkImageDifference (0x7f9de884b600): Execute: All ScalarTypes must be unsigned char
378: 
378: Comparing '/var/folders/nv/3xl0t1xx4yxb6tyd0yqdm238001cpd/T/tmpMOohpz/set5_Global_ANN_T-combined.png' to '/Users/doutriaux1/build/uvcdat-testdata/baselines/metrics/metrics/set5_Global_ANN_T-combined.png'...diff=1000.000000, New best!
378: All baselines failed! Lowest error (1000.000000) exceeds threshold (10.000000).
378: Saving image diff at '/var/folders/nv/3xl0t1xx4yxb6tyd0yqdm238001cpd/T/tmpMOohpz/set5_Global_ANN_T-combined_diff.png'.
378: Warning: In /Users/doutriaux1/build/build/VTK/IO/Image/vtkPNGWriter.cxx, line 215
378: vtkPNGWriter (0x7f9de8622970): PNGWriter only supports unsigned char and unsigned short inputs
378: 
378: <DartMeasurement name="ImageError" type="numeric/double">1000.000000</DartMeasurement>
378: <DartMeasurementFile name="TestImage" type="image/png">/var/folders/nv/3xl0t1xx4yxb6tyd0yqdm238001cpd/T/tmpMOohpz/set5_Global_ANN_T-combined.png</DartMeasurementFile>
378: <DartMeasurementFile name="DifferenceImage" type="image/png">/var/folders/nv/3xl0t1xx4yxb6tyd0yqdm238001cpd/T/tmpMOohpz/set5_Global_ANN_T-combined_diff.png</DartMeasurementFile>
378: <DartMeasurementFile name="ValidImage" type="image/png">/Users/doutriaux1/build/uvcdat-testdata/baselines/metrics/metrics/set5_Global_ANN_T-combined.png</DartMeasurementFile>
378: Graphics file /var/folders/nv/3xl0t1xx4yxb6tyd0yqdm238001cpd/T/tmpMOohpz/set5_Global_ANN_T-combined.png match difference: -1
378: Traceback (most recent call last):
378:   File "/git/uvcdat/testing/metrics/diagtest02.py", line 75, in <module>
378:     close1 = closeness( varname, filename, pathout, baselinepath, rtol, atol )
378:   File "/git/uvcdat/testing/metrics/diagtest02.py", line 32, in closeness
378:     f = cdms2.open( fname )
378:   File "/lgm/uvcdat/2015-03-20/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cdms2/dataset.py", line 221, in openDataset
378:     if not os.path.exists(path): return CdmsFile(path,mode)
378:   File "/lgm/uvcdat/2015-03-20/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cdms2/dataset.py", line 890, in __init__
378:     raise CDMSError, 'Cannot open file %s (%s)'%(path,err)
378: cdms2.error.CDMSError: Cannot open file /var/folders/nv/3xl0t1xx4yxb6tyd0yqdm238001cpd/T/tmpMOohpz/T_ANN_at_850_mbar_(1)_None.nc (No error)
1/1 Test #378: diags_test_02 ....................***Failed    2.39 sec
File "/var/folders/nv/3xl0t1xx4yxb6tyd0yqdm238001cpd/T/tmpMOohpz/set5_Global_ANN_T-combined.png" not found.
File "/var/folders/nv/3xl0t1xx4yxb6tyd0yqdm238001cpd/T/tmpMOohpz/set5_Global_ANN_T-combined_diff.png" not found.
File "/Users/doutriaux1/build/uvcdat-testdata/baselines/metrics/metrics/set5_Global_ANN_T-combined.png" not found.

0% tests passed, 1 tests failed out of 1

Total Test time (real) =   2.41 sec

The following tests FAILED:
	378 - diags_test_02 (Failed)
Errors while running CTest
```

**Comment by doutriaux1** [comment]
@painter1 @aashish24 my uvcmetrics build directory says:
```
doutriaux1@maryam:[~/build/build/UVCMETRICS]:[master]:[4928]> git status
On branch master
Your branch is up-to-date with 'origin/master'.

nothing to commit, working directory clean
```
shouldn't we be fetching some other tag?

My uvcmterics_pkg.cmake says:
```
set (nm UVCMETRICS)
string(TOUPPER ${nm} uc_nm)
set(${uc_nm}_VERSION ${${nm}_TAG})
set(UVCMETRICS_URL ${LLNL_URL})
set(UVCMETRICS_ZIP uvcmetrics-${UVCMETRICS_VERSION}.zip)
#set(UVCMETRICS_SOURCE ${UVCMETRICS_URL}/${UVCMETRICS_ZIP})
set(UVCMETRICS_SOURCE ${GIT_PROTOCOL}github.com/UV-CDAT/uvcmetrics.git )
set(UVCMETRICS_MD5)
set(UVCMETRICS_BRANCH uvcdat-2.2.0)

add_cdat_package(UVCMETRICS "" "" ON)
```

**Comment by doutriaux1** [comment]
just to be sure my .git/config says:
```
[core]
    repositoryformatversion = 0
    filemode = true
    bare = false
    logallrefupdates = true
    ignorecase = true
    precomposeunicode = true
[remote "origin"]
    url = git://github.com/UV-CDAT/uvcmetrics.git
    fetch = +refs/heads/*:refs/remotes/origin/*
[branch "master"]
    remote = origin
    merge = refs/heads/master
```

**Comment by doutriaux1** [comment]
now, after installing 2.2.0 I get:
```
doutriaux1@maryam:[~/build]:[4907]> ctest -R diags_test_02 -VV
UpdateCTestConfiguration  from :/Users/doutriaux1/build/DartConfiguration.tcl
Parse Config file:/Users/doutriaux1/build/DartConfiguration.tcl
UpdateCTestConfiguration  from :/Users/doutriaux1/build/DartConfiguration.tcl
Parse Config file:/Users/doutriaux1/build/DartConfiguration.tcl
Test project /Users/doutriaux1/build
Constructing a list of tests
Done constructing a list of tests
Checking test dependency graph...
Checking test dependency graph end
test 378
    Start 378: diags_test_02

378: Test command: /lgm/uvcdat/2015-03-20/bin/python "/git/uvcdat/testing/metrics/diagtest02.py" "--datadir=/Users/doutriaux1/uvcmetrics_test_data" "--baseline=/Users/doutriaux1/build/uvcdat-testdata/baselines/metrics/metrics/"
378: Test timeout computed to be: 1500
378: Traceback (most recent call last):
378:   File "/lgm/uvcdat/2015-03-20/Library/Frameworks/Python.framework/Versions/2.7/bin/diags", line 40, in <module>
378:     from metrics.fileio.filetable import *
378:   File "/lgm/uvcdat/2015-03-20/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/metrics/fileio/__init__.py", line 3, in <module>
378:     import filetable
378:   File "/lgm/uvcdat/2015-03-20/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/metrics/fileio/filetable.py", line 8, in <module>
378:     from metrics.frontend.options import Options
378:   File "/lgm/uvcdat/2015-03-20/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/metrics/frontend/__init__.py", line 6, in <module>
378:     vcs_tmp_canvas.scriptrun(os.path.join(sys.prefix,"share","uvcmetrics.json"))
378:   File "/lgm/uvcdat/2015-03-20/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/vcs/Canvas.py", line 5359, in scriptrun
378:     vcs.scriptrun(aFile,*args,**kargs)
378:   File "/lgm/uvcdat/2015-03-20/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/vcs/utils.py", line 565, in scriptrun
378:     f=open(script)
378: IOError: [Errno 2] No such file or directory: '/lgm/uvcdat/2015-03-20/Library/Frameworks/Python.framework/Versions/2.7/share/uvcmetrics.json'
378: Test 2: Diagnostic contour plots ... 
378: Traceback (most recent call last):
378:   File "/git/uvcdat/testing/metrics/diagtest02.py", line 59, in <module>
378:     raise DiagError("diags run failed")
378: metrics.common.utilities.DiagError: diags run failed
1/1 Test #378: diags_test_02 ....................***Failed    1.62 sec

0% tests passed, 1 tests failed out of 1

Total Test time (real) =   1.64 sec

The following tests FAILED:
	378 - diags_test_02 (Failed)
Errors while running CTest
```
@painter1 didn't we already fixed that jsn thing once? Is it not in 2.2.0 tag? @chaosphere2112 you get that one too right?

**Comment by doutriaux1** [comment]
@painter1 installing from "devel" i get:
```
doutriaux1@maryam:[~/build]:[4888]> ctest -R diags_test_02 -VV
UpdateCTestConfiguration  from :/Users/doutriaux1/build/DartConfiguration.tcl
Parse Config file:/Users/doutriaux1/build/DartConfiguration.tcl
UpdateCTestConfiguration  from :/Users/doutriaux1/build/DartConfiguration.tcl
Parse Config file:/Users/doutriaux1/build/DartConfiguration.tcl
Test project /Users/doutriaux1/build
Constructing a list of tests
Done constructing a list of tests
Checking test dependency graph...
Checking test dependency graph end
test 378
    Start 378: diags_test_02

378: Test command: /lgm/uvcdat/2015-03-20/bin/python "/git/uvcdat/testing/metrics/diagtest02.py" "--datadir=/Users/doutriaux1/uvcmetrics_test_data" "--baseline=/Users/doutriaux1/build/uvcdat-testdata/baselines/metrics/metrics/"
378: Test timeout computed to be: 1500
378: UV-CDAT Diagnostics, command-line version
378: Added set:  {'climos': 'no', 'end': None, 'name': None, 'filter': None, 'start': None, 'path': '/Users/doutriaux1/uvcmetrics_test_data/cam_output', 'type': 'model'}
378: Added set:  {'climos': 'yes', 'end': None, 'name': None, 'filter': "f_startswith('NCEP')", 'start': None, 'path': '/Users/doutriaux1/uvcmetrics_test_data/obs_atmos', 'type': 'obs'}
378: Enabling NetCDF compression on output files
378: filt:  None
378: INFO:  file /Users/doutriaux1/uvcmetrics_test_data/cam_output/c_t_b30.009.cam2.h0.0600-01.nc has an axis bound with no bounds.
378: An attempt will be made to compute bounds, but that is unreliable compared to bounds provided by the data file.
378: INFO:  file /Users/doutriaux1/uvcmetrics_test_data/cam_output/c_t_b30.009.cam2.h0.0600-01.nc has an axis lev with no bounds.
378: An attempt will be made to compute bounds, but that is unreliable compared to bounds provided by the data file.
378: There will be no more bad data warnings from constructing this filetable.
378: filt:  f_startswith('NCEP')
378: WARNING - no files found at /Users/doutriaux1/uvcmetrics_test_data/obs_atmos with filter f_startswith("NCEP")
378: using seasons= ['ANN']
378: plot set 5 - Horizontal Contour Plots of Seasonal Means
378: WARNING: Couldn't find any of the requested variables: ['T']
378: among ['AODVIS', 'CLDHGH_ISCCP', 'CLDHGH_TAU1.3-9.4_MODIS', 'CLDHGH_TAU1.3_MODIS', 'CLDHGH_TAU9.4_MODIS', 'CLDHGH_VISIR', 'CLDLOW_ISCCP', 'CLDLOW_TAU1.3-9.4_MISR', 'CLDLOW_TAU1.3_MISR', 'CLDLOW_TAU9.4_MISR', 'CLDLOW_VISIR', 'CLDMED_ISCCP', 'CLDMED_VISIR', 'CLDTOT_ISCCP', 'CLDTOT_TAU1.3-9.4_ISCCP', 'CLDTOT_TAU1.3-9.4_MISR', 'CLDTOT_TAU1.3-9.4_MODIS', 'CLDTOT_TAU1.3_ISCCP', 'CLDTOT_TAU1.3_MISR', 'CLDTOT_TAU1.3_MODIS', 'CLDTOT_TAU9.4_ISCCP', 'CLDTOT_TAU9.4_MISR', 'CLDTOT_TAU9.4_MODIS', 'CLDTOT_VISIR', 'CLISCCP', 'CLMISR', 'LHFLX', 'PRECT', 'QFLX', 'RESTOM', 'TGCLDLWP', 'TREFHT']
378: total number of (compound) diagnostic plots generated = 0
378: ERROR: In /Users/doutriaux1/build/build/VTK/IO/Image/vtkPNGReader.cxx, line 44
378: vtkPNGReader (0x7ff54b120880): Unable to open file /var/folders/nv/3xl0t1xx4yxb6tyd0yqdm238001cpd/T/tmp1_LEho/set5_Global_ANN_T-combined.png
378: 
378: ERROR: In /Users/doutriaux1/build/build/VTK/Imaging/Core/vtkImageExtractComponents.cxx, line 239
378: vtkImageExtractComponents (0x7ff548c00da0): Execute: Component 1 is not in input.
378: 
378: Test 2: Diagnostic contour plots ...  Found Baselines:
378: - /Users/doutriaux1/build/uvcdat-testdata/baselines/metrics/metrics/set5_Global_ANN_T-combined.png
378: ERROR: In /Users/doutriaux1/build/build/VTK/IO/Image/vtkPNGReader.cxx, line 44
378: vtkPNGReader (0x7ff548c00d40): Unable to open file /Users/doutriaux1/build/uvcdat-testdata/baselines/metrics/metrics/set5_Global_ANN_T-combined.png
378: 
378: ERROR: In /Users/doutriaux1/build/build/VTK/Imaging/Core/vtkImageExtractComponents.cxx, line 239
378: vtkImageExtractComponents (0x7ff548ca8cb0): Execute: Component 1 is not in input.
378: 
378: ERROR: In /Users/doutriaux1/build/build/VTK/Imaging/Core/vtkImageDifference.cxx, line 221
378: vtkImageDifference (0x7ff54a067e00): Execute: All ScalarTypes must be unsigned char
378: 
378: Comparing '/var/folders/nv/3xl0t1xx4yxb6tyd0yqdm238001cpd/T/tmp1_LEho/set5_Global_ANN_T-combined.png' to '/Users/doutriaux1/build/uvcdat-testdata/baselines/metrics/metrics/set5_Global_ANN_T-combined.png'...diff=1000.000000, New best!
378: All baselines failed! Lowest error (1000.000000) exceeds threshold (10.000000).
378: Saving image diff at '/var/folders/nv/3xl0t1xx4yxb6tyd0yqdm238001cpd/T/tmp1_LEho/set5_Global_ANN_T-combined_diff.png'.
378: Warning: In /Users/doutriaux1/build/build/VTK/IO/Image/vtkPNGWriter.cxx, line 215
378: vtkPNGWriter (0x7ff548f33f70): PNGWriter only supports unsigned char and unsigned short inputs
378: 
378: <DartMeasurement name="ImageError" type="numeric/double">1000.000000</DartMeasurement>
378: <DartMeasurementFile name="TestImage" type="image/png">/var/folders/nv/3xl0t1xx4yxb6tyd0yqdm238001cpd/T/tmp1_LEho/set5_Global_ANN_T-combined.png</DartMeasurementFile>
378: <DartMeasurementFile name="DifferenceImage" type="image/png">/var/folders/nv/3xl0t1xx4yxb6tyd0yqdm238001cpd/T/tmp1_LEho/set5_Global_ANN_T-combined_diff.png</DartMeasurementFile>
378: <DartMeasurementFile name="ValidImage" type="image/png">/Users/doutriaux1/build/uvcdat-testdata/baselines/metrics/metrics/set5_Global_ANN_T-combined.png</DartMeasurementFile>
378: Graphics file /var/folders/nv/3xl0t1xx4yxb6tyd0yqdm238001cpd/T/tmp1_LEho/set5_Global_ANN_T-combined.png match difference: -1
378: Traceback (most recent call last):
378:   File "/git/uvcdat/testing/metrics/diagtest02.py", line 75, in <module>
378:     close1 = closeness( varname, filename, pathout, baselinepath, rtol, atol )
378:   File "/git/uvcdat/testing/metrics/diagtest02.py", line 32, in closeness
378:     f = cdms2.open( fname )
378:   File "/lgm/uvcdat/2015-03-20/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cdms2/dataset.py", line 221, in openDataset
378:     if not os.path.exists(path): return CdmsFile(path,mode)
378:   File "/lgm/uvcdat/2015-03-20/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cdms2/dataset.py", line 890, in __init__
378:     raise CDMSError, 'Cannot open file %s (%s)'%(path,err)
378: cdms2.error.CDMSError: Cannot open file /var/folders/nv/3xl0t1xx4yxb6tyd0yqdm238001cpd/T/tmp1_LEho/T_ANN_at_850_mbar_(1)_None.nc (No error)
1/1 Test #378: diags_test_02 ....................***Failed    2.46 sec
File "/var/folders/nv/3xl0t1xx4yxb6tyd0yqdm238001cpd/T/tmp1_LEho/set5_Global_ANN_T-combined.png" not found.
File "/var/folders/nv/3xl0t1xx4yxb6tyd0yqdm238001cpd/T/tmp1_LEho/set5_Global_ANN_T-combined_diff.png" not found.
File "/Users/doutriaux1/build/uvcdat-testdata/baselines/metrics/metrics/set5_Global_ANN_T-combined.png" not found.

0% tests passed, 1 tests failed out of 1

Total Test time (real) =   2.47 sec

The following tests FAILED:
	378 - diags_test_02 (Failed)
Errors while running CTest
```

**Comment by painter1** [comment]
Charles, could you give me a directory listing of /Users/doutriaux1/uvcmetrics_test_data/* ?  Thanks.

**Comment by doutriaux1** [comment]
doutriaux1@maryam:[vcs]:[me]:[6550]> ll ~/uvcmetrics_test_data/

total 0

drwxr-xr-x  74 doutriaux1  45773   2.5K Aug 27  2014 acme_hires_land

drwxr-xr-x   4 doutriaux1  45773   136B Aug  8  2014 acme_lores_atm_climo

drwxr-xr-x  10 doutriaux1  45773   340B Aug 14  2014 acme_lores_cam_climo

drwxr-xr-x  19 doutriaux1  45773   646B Aug 14  2014 acme_lores_clm_climo

drwxr-xr-x  14 doutriaux1  45773   476B Aug 27  2014 acme_lores_land

drwxr-xr-x  26 doutriaux1  45773   884B Aug 27  2014 cam_output

drwxr-xr-x  17 doutriaux1  45773   578B Aug 14  2014 obs

drwxr-xr-x  20 doutriaux1  45773   680B Aug 27  2014 obs_atmos

**Comment by painter1** [comment]
What's one level down, especially in obs_atmos?

**Comment by doutriaux1** [comment]
doutriaux1@maryam:[vcs]:[boxfill_bug_branch_clean_up+1]:[6611]> ll ~/uvcmetrics_test_data/obs_atmos/

total 2304

-rw-r--r--  1 doutriaux1  45773    22K Aug 27  2014 c_CRU_ANN_climo.nc

-rw-r--r--  1 doutriaux1  45773    22K Aug 27  2014 c_CRU_DJF_climo.nc

-rw-r--r--  1 doutriaux1  45773    22K Aug 27  2014 c_CRU_JJA_climo.nc

-rw-r--r--  1 doutriaux1  45773    70K Aug 27  2014 c_t_NCEP_01_climo.nc

-rw-r--r--  1 doutriaux1  45773    70K Aug 27  2014 c_t_NCEP_02_climo.nc

-rw-r--r--  1 doutriaux1  45773    70K Aug 27  2014 c_t_NCEP_03_climo.nc

-rw-r--r--  1 doutriaux1  45773    70K Aug 27  2014 c_t_NCEP_04_climo.nc

-rw-r--r--  1 doutriaux1  45773    70K Aug 27  2014 c_t_NCEP_05_climo.nc

-rw-r--r--  1 doutriaux1  45773    70K Aug 27  2014 c_t_NCEP_06_climo.nc

-rw-r--r--  1 doutriaux1  45773    70K Aug 27  2014 c_t_NCEP_07_climo.nc

-rw-r--r--  1 doutriaux1  45773    70K Aug 27  2014 c_t_NCEP_08_climo.nc

-rw-r--r--  1 doutriaux1  45773    70K Aug 27  2014 c_t_NCEP_09_climo.nc

-rw-r--r--  1 doutriaux1  45773    70K Aug 27  2014 c_t_NCEP_10_climo.nc

-rw-r--r--  1 doutriaux1  45773    70K Aug 27  2014 c_t_NCEP_11_climo.nc

-rw-r--r--  1 doutriaux1  45773    70K Aug 27  2014 c_t_NCEP_12_climo.nc

-rw-r--r--  1 doutriaux1  45773    71K Aug 27  2014 c_t_NCEP_ANN_climo.nc

-rw-r--r--  1 doutriaux1  45773    70K Aug 27  2014 c_t_NCEP_DJF_climo.nc

-rw-r--r--  1 doutriaux1  45773    70K Aug 27  2014 c_t_NCEP_JJA_climo.nc

**Comment by painter1** [comment]
The problem is that the desired file, NCEP_ANN_climo.nc, doesn't exist.
How did that prefix "c_t_" (and "c_" for CRU) get in there?  If there's a good reason, I will change my test code to look for it.  But NCEP_ANN_climo.nc is the usual name for this file.  So the test problem will be easier to understand if that's the file name.

**Comment by painter1** [comment]
Charles, what do you have in the obs directory?  Maybe the names are different.

**Comment by doutriaux1** [comment]
doutriaux1@maryam:[uvcdat-testdata]:[boxfill_bug_branch_clean_up]:[6600]> ll ~/uvcmetrics_test_data/obs

total 106424

-rw-r--r--  1 doutriaux1  45773   3.4M Aug 14  2014 NCEP_01_climo.nc

-rw-r--r--  1 doutriaux1  45773   3.4M Aug 14  2014 NCEP_02_climo.nc

-rw-r--r--  1 doutriaux1  45773   3.4M Aug 14  2014 NCEP_03_climo.nc

-rw-r--r--  1 doutriaux1  45773   3.4M Aug 14  2014 NCEP_04_climo.nc

-rw-r--r--  1 doutriaux1  45773   3.4M Aug 14  2014 NCEP_05_climo.nc

-rw-r--r--  1 doutriaux1  45773   3.4M Aug 14  2014 NCEP_06_climo.nc

-rw-r--r--  1 doutriaux1  45773   3.4M Aug 14  2014 NCEP_07_climo.nc

-rw-r--r--  1 doutriaux1  45773   3.4M Aug 14  2014 NCEP_08_climo.nc

-rw-r--r--  1 doutriaux1  45773   3.4M Aug 14  2014 NCEP_09_climo.nc

-rw-r--r--  1 doutriaux1  45773   3.4M Aug 14  2014 NCEP_10_climo.nc

-rw-r--r--  1 doutriaux1  45773   3.4M Aug 14  2014 NCEP_11_climo.nc

-rw-r--r--  1 doutriaux1  45773   3.4M Aug 14  2014 NCEP_12_climo.nc

-rw-r--r--  1 doutriaux1  45773   3.7M Aug 14  2014 NCEP_ANN_climo.nc

-rw-r--r--  1 doutriaux1  45773   3.7M Aug 14  2014 NCEP_DJF_climo.nc

-rw-r--r--  1 doutriaux1  45773   3.7M Aug 14  2014 NCEP_JJA_climo.nc

**Comment by painter1** [comment]
I've pushed a new version of diagtest02.py which will work even if you stick a prefix before the filenames.

**Comment by doutriaux1** [comment]
@mcenerney1 did you test this? I hadn't had a chance to test @painter1 latest changes but before that it didn't pass crest for me

**Pull request merged**
