### PR TITLE
Revert commit that break dv3d_ tests

### PR DESCRIPTION
**Pull request by danlipsa**
The commit is 9404c34157ededc830a4287d35e6082e55edf6bf

### CODE REVIEW

**Comment by danlipsa** [comment]
@doutriaux1 @aashish24 Reverting the listed commit fixes the dv3d_ tests. Please review.

**Comment by doutriaux1** [comment]
@danlipsa the new GUI actually needs this. @sampsonbryce @chaosphere2112 do you mind fixing the places where dv3d calls this? Or we can merge this and you guys can fix it later.

**Comment by chaosphere2112** [comment]
@danlipsa @doutriaux1 I'll push a fix to dv3d, I know the root of the problem.

**Comment by danlipsa** [comment]
@chaosphere2112 Thanks! I will close this then.

**Comment by aashish24** [comment]
@chaosphere2112 could you please elaborate why this change was required? Also, I am wondering how did we merge this one? Did we not tests?

**Comment by chaosphere2112** [comment]
@aashish24 The "required" change was fixing the way VCS addons were handled (I use a histogram in the new GUI). My intern took the DV3D fix into his own hands to fix what looked like a hole in the API from when it was integrated (and indeed, was). @doutriaux1 got a little merge-happy (and thought I had run tests, which I had not), so that's how it got merged.

There were actually an existing host of problems related to this; any time you plotted a 3D graphics method, it used the *exact same* graphics method object, even when plotted on multiple canvases. This meant that modifications to the first canvas (like panning the camera) would effect the second canvas. While this could be useful in some circumstances, it totally breaks the existing beliefs about how UV-CDAT works. I'm fixing that problem now, as part of fixing these tests (which were badly written, and depended on examining things in `canvas.backend`, which is a no-fly zone for API compatibility as far as I'm concerned).

**Comment by ThomasMaxwell** [comment]
dv3d was designed such that navigation commands (pan, zoom, rotate, etc) would be synchronized across all cells.   Having to adjust the camera independently in each cell is extremely awkward when doing 3D visualization.

**Pull request closed without merging**
