### PR TITLE
1487 isoline labels

### LINKED ISSUE #1487: isoline labels still defective
I just bult UVCDAT from master and the isoline labels now work. The spacing is still broken but something needs to be fixed about the round-off.
isoline_example

### PR DESCRIPTION
**Pull request by sankhesh**
Fixes #1487

### CODE REVIEW

**Comment by sankhesh** [comment]
@doutriaux1 @aashish24

**Comment by doutriaux1** [comment]
@sankhesh the son files needs update. Did you flake8ed them? Did you add options and hence need to update son files?

**Comment by doutriaux1** [comment]
@sankhesh mac failure?

**Comment by sankhesh** [comment]
@doutriaux1 

Seems like the mac build did not update the testdata repository and hence cannot find the baseline. It should be fixed when the branches are merged.

**Comment by doutriaux1** [comment]
ok seems like the failing test are due to master baseline having diverged too much since your original baseline (I need to fix the bots for this) approving. But we still need a fix for the near zeroes labels being some big fat string. We can't the release w/o this.

**Comment by durack1** [comment]
@aashish24 @doutriaux1 @sankhesh the [new baseline has not been merged](https://github.com/UV-CDAT/uvcdat-testdata/pull/65) so this is now causing test failures across the suite

@aashish24 want to approve https://github.com/UV-CDAT/uvcdat-testdata/pull/65?

**Comment by durack1** [comment]
@sankhesh it looks like the very small values (-4.4e-16) are still being plotted in some recent tests on `garant`. The `RH6` machines are skipping this test currently: https://open.cdash.org/testDetails.php?test=376877973&build=4029199 and https://open.cdash.org/testDetails.php?test=376878238&build=4029197

**Comment by sankhesh** [comment]
@durack1  Yes. That is supposed to happen until UV-CDAT/VTK#9 is merged. Care to merge it in? 
I can merge UV-CDAT/VTK#9, UV-CDAT/uvcdat-testdata#65 and that will fix all these issues. But that would be bad practice since I'm the original author :disappointed: .

**Comment by durack1** [comment]
@sankhesh https://github.com/UV-CDAT/VTK/pull/9 is now merged, but I don't have merge privileges for https://github.com/UV-CDAT/uvcdat-testdata/pull/65 - so have polled @chaosphere2112 to merge this..

@aashish24 @doutriaux1 you could also merge https://github.com/UV-CDAT/uvcdat-testdata/pull/65 in?

**Pull request merged**
