### PR TITLE
Altered some tests to ensure geometry

### PR DESCRIPTION
**Pull request by chaosphere2112**
Should *hopefully* fix issues that garant and @doutriaux1 have been having with automatic window sizing and some tests.

### CODE REVIEW

**Comment by aashish24** [comment]
thanks @chaosphere2112 for taking care of this quickly!

**Comment by chaosphere2112** [comment]
@aashish24 @doutriaux1 @jbeezley So, [this](https://open.cdash.org/testDetails.php?test=393068095&build=4107947) is what's busted still. The PNG is coming out in the correct dimensions now, but the labels are all wrong and the plot is misshapen.

**Comment by chaosphere2112** [comment]
@doutriaux1 @aashish24 Seems to have finally passed `test_vcs_click_info` on garant!

**Comment by aashish24** [comment]
It did it!! :+1: LGTM Thanks @chaosphere2112 this is awesome.

**Pull request merged**
