### PR TITLE
Issue788 durack1 remove deprecated folders and files

### LINKED ISSUE #788: Remove/update deprecated files
I've just pulled down the 2.0.0 source and noted the files TODO.txt and Changes.txt which don't appear to be relevant to the latest master repo - should these be removed/updated?

### PR DESCRIPTION
**Pull request by durack1**
Fix #788 - remove deprecated folders and files

Starting with files and will continue with `tests`, `docs` and `esg` subdirs..

Resolving the duplication and obsolete files in `images` and `resources` will be resolved by @doutriaux1 in #1353

The issue of updating the license info will be dealt with in #1354

### CODE REVIEW

**Comment by durack1** [comment]
@aashish24 when I looked at this last night it seemed to indicate a cmake build problem - wanna take a peek here?

**Comment by aashish24** [comment]
This is weird. @jbeezley, any suggestion?

**Comment by durack1** [comment]
@aashish24 yep, from a quick check it still seems to be throwing that same error.. Would the deletion of the `docs` subdir trigger this? I don't see how..?

**Comment by durack1** [comment]
@aashish24 @jbeezley any ideas what's going wrong here?

**Comment by jbeezley** [comment]
```
CMake Error at /usr/share/cmake-2.8/Modules/CPack.cmake:395 (message):
  CPack package description file:
  "/home/buildbot/buildbot/uvcdat-garant-linux-release/source/docs/README.txt"
  could not be found.
Call Stack (most recent call first):
  /usr/share/cmake-2.8/Modules/CPack.cmake:399 (cpack_check_file_exists)
  CMakeLists.txt:810 (include)


CMake Error at /usr/share/cmake-2.8/Modules/CPack.cmake:395 (message):
  CPack license resource file:
  "/home/buildbot/buildbot/uvcdat-garant-linux-release/source/docs/Legal.txt"
  could not be found.
Call Stack (most recent call first):
  /usr/share/cmake-2.8/Modules/CPack.cmake:400 (cpack_check_file_exists)
  CMakeLists.txt:810 (include)
```
It is looking for `docs/README.txt` and `docs/Legal.txt`.  I don't know enough about CPack to say why or if it is possible override the path to these files, but I would guess if you added them back, it would probably work.

**Comment by doutriaux1** [comment]
@durack1 you yanked too many files, please try to build before submitting PR. You need to restore (at least) the two files that @jbeezley mentioned. Actually I would create a symbolic link for te README file to the official README.

**Comment by durack1** [comment]
@doutriaux1 is the [esg](https://github.com/UV-CDAT/uvcdat/tree/issue788_durack1_removeDeprecatedFoldersAndFiles/esg) subdir still required?

**Comment by durack1** [comment]
@jbeezley it seems that there are just two [VCS/VTK issues](https://open.cdash.org/viewTest.php?onlyfailed&buildid=3833548) only occurring on the `test-laptop` setup

**Comment by jbeezley** [comment]
I have seen these resize errors from time to time.  I suspect there is a race condition popping up.  It can be tricky to determine when a resize event is done rendering.  I have no idea at all if this is related, but there was a bug in VTK-Web fixed recently that went to [great lengths](https://github.com/Kitware/VTK/commit/39fedcd67301c7975fc44dcd910d7cf1f23dc031) to handle window resizes on X11.

**Comment by durack1** [comment]
@jbeezley will #1348 that @dlonie proposed pull across these changes into the UV-CDAT/master? It'd be nice to get these tests behaving properly..

**Comment by dlonie** [comment]
I see Chris's commit does get pulled in by that branch, but it gets reverted:

```
commit 30eedf071db7252b956a0364f40af2bb98abe149
Author: Chris Harris <chris.harris@kitware.com>
Date:   Thu Apr 9 10:06:34 2015 -0400

    Revert "Wait for resize notification in SetSize(...)"
    
    Fix in vtkWeb code instead.
    
    This reverts commit 39fedcd67301c7975fc44dcd910d7cf1f23dc031.
```

Not sure what's up with that.

**Comment by jbeezley** [comment]
Yeah, I think it caused other problems, so he fixed the issue in the vtkWeb python source.  I linked the patch just to emphasize that syncing resizes is not easy in general.  I doubt it would have helped here anyway.

I'm not sure it is worth trying to fix this until we have cleaned up the vtk pipeline in the vcs code.  We could probably add an explicit sleep after the resize but before the screenshot is taken to reduce the chance that it happens.

**Comment by durack1** [comment]
@doutriaux1 I think this is ready to go - can you review please?
@aashish24 to attempt to catch some problems with timeouts in travis builds I edited `.travis.yml` to include `travis_wait` to deal with timeouts due to download delays. Can you check to make sure this is ok? I wonder if `cmake` is smart enough to recover dropped connections when downloading source? If there's a flag to enable this, it might make travis tests more stable
@chaosphere2112 I added a `time.sleep(2)` to your `testing/vcs/vtk_ui/test_vtk_ui_manager_resize.py` file - can you check this is ok before the PR is merged..?

**Comment by durack1** [comment]
@doutriaux1 I think this is ready to go - can you review please?
@chaosphere2112 I added a `time.sleep(2)` to your `testing/vcs/vtk_ui/test_vtk_ui_manager_resize.py` file - can you check this is ok before the PR is merged..?

**Comment by doutriaux1** [comment]
@durack1 why did you add a time.sleep? Was it failing for you?

**Comment by doutriaux1** [comment]
@chaosphere2112 while we are on the vtk_ui thing. I was wondering if there's anyway to make these test run in "background" mode, they keep poping up and make my windows loose focus, very annoying.
Same for dv3d.

**Comment by durack1** [comment]
@doutriaux1 yep, the test appeared to be checking for the resize before it was completed - see the dialogue above for more info.. The sleep statement seems to have resolved the race condition, at least in this PR..

**Comment by chaosphere2112** [comment]
"Due to #1148, have to render on screen when resizing"

@dlonie, any progress with [the bug](http://www.vtk.org/Bug/view.php?id=15384)? If not, then, nope, sorry Charles.

**Comment by chaosphere2112** [comment]
If the test is passing with the sleep, then that's fine with me. I assume that the size stored in the object is the size that it's shrinking to, not the size that it's literally currently at; I could restructure that test a bit to listen to the notifications of window resizing, perhaps. That might be a bit easier/better.

**Comment by durack1** [comment]
@chaosphere2112 if you want to deal with this I can pull my edit out of this PR, up to you..

**Comment by chaosphere2112** [comment]
Nah, let's go with this for now. No need to fix something that's already been fixed.

**Comment by durack1** [comment]
@doutriaux1 has something broken in `master`, it seems like a [heap of `vcs` and `vtk` errors have appeared](https://open.cdash.org/viewTest.php?onlyfailed&buildid=3856899)

**Comment by dlonie** [comment]
@chaosphere2112 Looks like that issue is still open.

@durack1 Merge uvcdat's current master into this branch, or rebase onto it. There are changes needed to work with the current uvcdat VTK fork.

**Comment by durack1** [comment]
@chaosphere2112 it seems like the canvas is inheriting something along the [right hand side pixel column](https://open.cdash.org/testDetails.php?test=345358793&build=3861277), and only for the `test-laptop` config..

**Comment by durack1** [comment]
@doutriaux1 can you check and merge this, it'll solve the [vcs test problem](https://open.cdash.org/testDetails.php?test=345370187&build=3861303) in #1380

**Comment by durack1** [comment]
@doutriaux1 can you check and merge this, it'll solve the vcs test problem which appeared the previous build in #1380 (I've added the `sleep(1)` back into  #1380 to get it passing

**Comment by durack1** [comment]
@doutriaux1 I've finished up with this, please go ahead and checkout and then build on top of this PR.. As noted in #1353 there is a bit more cleanup to do..

**Comment by aashish24** [comment]
:+1: for doing this awesome stuff...

**Comment by durack1** [comment]
@aashish24 if you can comment on #1353, not sure there are standard directory names/conventions that should be considered when renaming/moving/removing things..

**Comment by durack1** [comment]
@aashish24 if you can comment on #1353 that would be helpful. I'm not sure if there are standard directory names/conventions that should be considered when renaming/moving/removing things.. In particular I'm thinking about the eventual creation of Mac OS X *.dmg files with their standard `Contents`, `Resources` etc subdirs..

**Comment by durack1** [comment]
@doutriaux1 can you wedge this through tomorrow?

**Comment by durack1** [comment]
@doutriaux1 pinging you on this one..

**Comment by durack1** [comment]
@doutriaux1 just pinging you on this..

**Comment by aashish24** [comment]
@doutriaux1 this seems to be a useful branch. I think we should really merge (and if needed update it). what you think?

**Comment by doutriaux1** [comment]
some of the deleted files need to stay (licences, legal etc..) I need to carefully review it (and update it), can't merge now. We can clause and do it from scratch later if you want.

**Comment by durack1** [comment]
@aashish24 @doutriaux1 as noted up the top of the PR:

Resolving the duplication and obsolete files in images and resources will be resolved by @doutriaux1 in #1353

The issue of updating the license info will be dealt with in #1354 (this requires regeneration, as the UC license is not longer active for LLNS)

So I think this PR is ok to merge..

**Comment by doutriaux1** [comment]
I'm not sure if the esg module is no longer used, I need to ask ESGF people. Too many uncertainties. This really needs to be redone from scratch by me. Closing. Sorry.

**Pull request closed without merging**
