### PR TITLE
Fix flake8 warnings and a test generated file

### PR DESCRIPTION
**Pull request by danlipsa**

### CODE REVIEW

**Comment by danlipsa** [comment]
https://github.com/UV-CDAT/uvcdat-testdata/pull/136

**Comment by danlipsa** [comment]
@doutriaux1 I missed a baseline and @aashish24 did not flake8 :smile: Please review.

**Comment by doutriaux1** [comment]
@aashish24 I will hold that flake8 mistake as my `escape from prison` card against you :wink:

**Comment by aashish24** [comment]
@danlipsa I fixed these in my other branch (vector scale one), I will rebase. 

@doutriaux1 :laughing:

**Pull request merged**
