### PR TITLE
issue1579 durack1 update netcdf 4.3.3.1 to 4.4.0

### PR DESCRIPTION
**Pull request by durack1**
Test update for netcdf-c 4.4.0-rc4

@aashish24 @doutriaux1 this is a placeholder - **please do not merge until the final `4.4.0` release is out and this PR is updated**

### CODE REVIEW

**Comment by aashish24** [comment]
@durack1 let's do it post 2.4

**Comment by durack1** [comment]
@aashish24 @doutriaux1 yep it's still in `RC` so 2.4+ is certainly where it should be merged..

**Comment by durack1** [comment]
This also needs a bump to the `hdf` libraries - so will update the sources and add that in

**Comment by durack1** [comment]
@doutriaux1 looks like the `macbots` are in trouble again..

**Comment by durack1** [comment]
@doutriaux1 I'd be inclined to update `zlib` from the confusing arrangement where there are [4 versions being built depending on the system](https://github.com/UV-CDAT/uvcdat/blob/master/CMake/cdat_modules/zlib_pkg.cmake#L1-L13) or using the system `zlib` to `1.2.8` the latest release

**Comment by durack1** [comment]
@doutriaux1 as discussed this brings us right up-to-date with netcdf and hdf (my comment above regarding `zlib` is redundant) - this is now a complete PR, so please review and merge

**Comment by aashish24** [comment]
@durack1 do you want to update it to netcdf 4.4.0 since its out now?

**Comment by aashish24** [comment]
@durack1 also, would be good to know why we are bringing new changes..

**Comment by durack1** [comment]
@aashish24 take a look at the PR it is indeed the final release and has been for quite sometime

**Comment by aashish24** [comment]
I see so you did update to 4.4.0 as we didn't see it in the commit. What is the major change / advantage?

**Comment by durack1** [comment]
Yep, 4.4.0 is in.. For changes take a peek at #1579 and the links listed

**Comment by durack1** [comment]
@aashish24 #1398 (amongst other standing issues) are likely also fixed - as noted above

**Comment by doutriaux1** [comment]
@durack1 the commit seems to be from nov 18th 4.4.0 has been out post this. Are you 100% sure it is the correct tarball?

**Comment by durack1** [comment]
@doutriaux1 [`netcdf-c 4.4.0`](https://github.com/Unidata/netcdf-c/releases/tag/v4.4.0) was released on 13th Jan and the tarball was uploaded on 14th Jan
```
[durack1@aims4 ~]$ ls -alh netcdf-c-4.4.0.*
-rw-r--r-- 1 durack1 climate 17M Jan 14 16:56 netcdf-c-4.4.0.tar.gz
```
And the [md5 matches the final too](https://github.com/UV-CDAT/uvcdat/blob/issue1579_durack1_UpdateNetcdf4.3.3.1To4.4.0/CMake/cdat_modules/netcdf_pkg.cmake#L6):
```
[durack1@aims4 ~]$ md5sum netcdf-c-4.4.0.tar.gz
4e3d3b05ab53d0ae6036a1a0fe1506e5  netcdf-c-4.4.0.tar.gz
```

The commit that matters is dated 14th Jan https://github.com/UV-CDAT/uvcdat/commit/54ca62b7f289db0eb3a2726ae08252a0e7e71e0b

**Comment by durack1** [comment]
@doutriaux1 looks like macbots need a reboot/reconfigure/restart they've been hanging for weeks

**Comment by doutriaux1** [comment]
they have not been hanging for weeks but they hang after each PR... crap mac software... I need to invest time into fixing this properly...

**Comment by durack1** [comment]
@doutriaux1 this appears to build on all completed bots - the travis failure above was due to a tarball download time out - so good to merge I think.. As noted, it would also be good to check if #1398 is fixed with `4.4.0` their internal issue was closed https://github.com/Unidata/netcdf-c/issues/128

**Comment by durack1** [comment]
@doutriaux1 @aashish24 it would be great to get this PR merged.. Can you folks take a look at it tomorrow?

**Comment by aashish24** [comment]
> @doutriaux1 @aashish24 it would be great to get this PR merged.. Can you folks take a look at it tomorrow

Yes, I will look into it tomorrow @durack1

**Comment by durack1** [comment]
@aashish24 @doutriaux1 ping!

**Comment by durack1** [comment]
@doutriaux1 @aashish24 can this please be reviewed pronto? It's been sitting in the queue for too long now

**Comment by durack1** [comment]
@doutriaux1 what's going on with the `bots` none of them are working any more

**Comment by durack1** [comment]
@dnadeau4 please test this PR and merge if it's all ok.
I'm uncertain why @aashish24 and @doutriaux1 have not reviewed this already.

**Comment by dnadeau4** [comment]
All cdms2 test passed with netCDF 4.4.0  Somehow I cannot click "Merge Pull Request".   @doutriaux1 did you change something in the "github" configuration?

**Comment by doutriaux1** [comment]
@durack1 `pronto`? Really? Are you our project manager now? We got many many fires going on right now and the last thing we need to need is add oil on the fire by merging something that has not been carefully reviewed. I apologize we could not get to this `pronto`. We'll try to work longer hours in the future...

**Comment by durack1** [comment]
@doutriaux1 if you can add it to the review queue that would be great. @dnadeau4 has also taken a look and tested in his env

**Comment by durack1** [comment]
@doutraux1 the `garant` failure is due to a missing baseline https://open.cdash.org/testDetails.php?test=425699817&build=4261331 - nothing to do with the PR

**Comment by durack1** [comment]
@doutriaux1 @aashish24 @dnadeau4 is there a reason that this is being held up? It seems like it's good to go..?

**Comment by doutriaux1** [comment]
yes there is, I do not have time to properly get to it, everytime I build it, something comes up and I forget and then I need to build it again the next time, etc...

**Comment by durack1** [comment]
@doutriaux1 ok great good to know.. I was wondering if there was something with the PR that needed attention.. If it's just time then good to know it's still in the queue..

**Comment by aashish24** [comment]
@durack1 @doutriaux1 if CI is happy, lets get this merged in.

**Comment by durack1** [comment]
@aashish24 I'll defer to @doutriaux1 for this

**Comment by doutriaux1** [comment]
@aashish24 I'm neither happy or not with it. I really need to look at it carefully first, sorry @durack1 I know you want it bad. Maybe Thursday I can take a close look at it.

**Comment by aashish24** [comment]
> Maybe Thursday I can take a close look at it.

thanks @doutriaux1

**Comment by aashish24** [comment]
@durack1 talked to @doutriaux1 we will look into it past 2.4.1.

**Pull request closed without merging**
