### PR TITLE
BUG #1770: Display meshfill template elements through renderTemplate.

### PR DESCRIPTION
**Pull request by danlipsa**
This deletes some displays which reduces memory leaks.

### CODE REVIEW

**Comment by danlipsa** [comment]
Baselines in
https://github.com/UV-CDAT/uvcdat-testdata/pull/146

**Comment by danlipsa** [comment]
@doutriaux1 @aashish24 @chaosphere2112 Please review.
A question for uvcdat old-timers: Why is template.plot (and maybe other parts of the code) storing stuff in vcs.elements? I printed vcs.elements before and after doing a plot:
Before calling Canvas.plot
====================
list: 28
projection: 10
texttable: 9
textorientation: 63
textcombined: 0
line: 17
marker: 9
fillarea: 1
font: 16
fontNumber: 16
boxfill: 9
isofill: 9
isoline: 9
meshfill: 7
3d_scalar: 2
3d_dual_scalar: 1
3d_vector: 1
template: 77
taylordiagram: 1
1d: 13
vector: 1
yxvsx: 1
xyvsy: 1
xvsy: 1
scatter: 1
colormap: 22
display: 1

After calling plot with my fix:
===========
list: 28
projection: 10
texttable: 21
textorientation: 75
textcombined: 12
line: 17
marker: 9
fillarea: 1
font: 16
fontNumber: 16
boxfill: 9
isofill: 9
isoline: 9
meshfill: 8
3d_scalar: 2
3d_dual_scalar: 1
3d_vector: 1
template: 77
taylordiagram: 1
1d: 13
vector: 1
yxvsx: 1
xyvsy: 1
xvsy: 1
scatter: 1
colormap: 22
display: 2

After calling plot without my fix:
========================
list: 28
projection: 10
texttable: 21
textorientation: 75
textcombined: 12
line: 17
marker: 9
fillarea: 1
font: 16
fontNumber: 16
boxfill: 9
isofill: 9
isoline: 9
meshfill: 8
3d_scalar: 2
3d_dual_scalar: 1
3d_vector: 1
template: 77
taylordiagram: 1
1d: 13
vector: 1
yxvsx: 1
xyvsy: 1
xvsy: 1
scatter: 1
colormap: 22
display: 8

**Comment by danlipsa** [comment]
Note texttable, textorientation, textcombined is increasing and also display is at 2 not at 1.

**Comment by chaosphere2112** [comment]
@danlipsa This is the memory leak I referred to in @durack1's issues. @doutriaux1 was going to take a look at it

**Comment by durack1** [comment]
@danlipsa #1424 is what @chaosphere2112 was talking about.. I'd be more than happy to kick the tires on a branch here, my [plot slowdowns](https://github.com/UV-CDAT/uvcdat/issues/1424#issuecomment-230538517) and [memory usage](https://github.com/UV-CDAT/uvcdat/issues/1424#issuecomment-230850902) (~100GB for a ~6800 loop) is pretty extreme

**Comment by sankhesh** [comment]
Do: test

**Comment by sankhesh** [comment]
Do: test

**Comment by danlipsa** [comment]
@doutriaux1 @aashish24 This has been ready for a while. Please review.
https://open.cdash.org/viewTest.php?onlyfailed&buildid=4463184

**Comment by danlipsa** [comment]
Do: test

**Comment by danlipsa** [comment]
@sankhesh buildbot does not seem to pickup uvcdat-testdata. I know it should be done by make, but it does not seem to happen in the latest cdath results on this PR. Is there a way to see the SHA for the test data?

**Comment by doutriaux1** [comment]
@danlipsa I have a lot of failed tests due to image sizes being different on my mac see: https://open.cdash.org/viewTest.php?onlyfailed&buildid=4475287

Some of them are due to conda env not being activated properly (I think it is because I was also messing with my conda envs as I was running the test suite)

**Comment by doutriaux1** [comment]
anyway issues not related to your changes so merged.

**Pull request merged**
