### PR TITLE
Fix for #1517

### LINKED ISSUE #1517: Background for Querying Popup missing
When I click on a plot, it's supposed to present a beige background popup with point data on it. Instead, the point data shows up without a background, and the errors below show up in the console. This happens in both the GUI and the command line.

screen shot 2015-09-03 at 2 44 09 pm

```
ERROR: In /Users/fries2/build/build/VTK/Rendering/Core/vtkTextActor.cxx, line 893
vtkTextActor (0x7fb027ee0c50): No render window available: cannot determine DPI.

ERROR: In /Users/fries2/build/build/VTK/Rendering/Core/vtkTextActor.cxx, line 158
vtkTextActor (0x7fb027ee0c50): UpdateRectangle failed to do so

ERROR: In /Users/fries2/build/build/VTK/Filters/Sources/vtkPlaneSource.cxx, line 104
vtkPlaneSource (0x7fb027eb8ca0): Bad plane coordinate system

ERROR: In /Users/fries2/build/build/VTK/Common/ExecutionModel/vtkExecutive.cxx, line 784
vtkCompositeDataPipeline (0x7fb027ebd430): Algorithm vtkPlaneSource(0x7fb027eb8ca0) returned failure for request: vtkInformation (0x7fb027eac630)
  Debug: Off
  Modified Time: 279339
  Reference Count: 1
  Registered Events: (none)
  Request: REQUEST_DATA
  ALGORITHM_AFTER_FORWARD: 1
  FORWARD_DIRECTION: 0
  FROM_OUTPUT_PORT: 0
```

### PR DESCRIPTION
**Pull request by chaosphere2112**
Fixes #1517 by moving the AddRenderer call in backend.leftButtonPressEvent before actors get added; the issue was because we were querying the text actor's bounding box information, which requires it to be in a render chain (apparently a new requirement vs older versions of vtk). Added a test to (hopefully) keep this feature working reliably in the future. Goes with UV-CDAT/uvcdat-testdata#63.

### CODE REVIEW

**Comment by chaosphere2112** [comment]
@doutriaux1 @aashish24

**Comment by aashish24** [comment]
@chaosphere2112 not sure why the machines didn't pick up your test data (did you push it after you push your source code?) but the changes looks good to me. Let me update this branch with master and see if we can get a greener dashboard.

**Comment by doutriaux1** [comment]
@aashish24 this was due to the bot server, because now it merges master into the branch, hence we end up in an "detached mode" and uvcdat/cmake couldn't figure out where it came from. The server is now fixed if @chaosphere2112 pushes an update it should pick up the test properly.

**Comment by aashish24** [comment]
Thanks. LGTM :+1:

**Pull request merged**
