### PR TITLE
Updated packages reference

### PR DESCRIPTION
**Pull request by aashish24**
For the uvcmetrics, I have followed what is suggested by Jeff
and Brian.

### CODE REVIEW

**Comment by doutriaux1** [comment]
Aashish the PACKAGE_MD5 is used to generate the file that says which version of which package have been generated, can you please make sure this is still correct? Thanks

**Comment by doutriaux1** [comment]
also where o you set the _BRANCH tags in the .pkg files? Did you edit them earlier? I don't see them in the list of changed files.

**Comment by aashish24** [comment]
PACKAGE_MD5 for these packages are used just as it a branch name. I run a grep and I couldn't find any other use. Do you not see VISTRAILS_BRANCH and PARAVIEW_BRANCH?

**Comment by aashish24** [comment]
Going once.. going twice... going...  -:)

**Comment by doutriaux1** [comment]
@aashish24 this bit will be broken:
in CMakeLists.txt
```
  if(CDAT_BUILD_${uc_package})
      message("[INFO] Package --- ${package}/${uc_package}/${${uc_package}_VERSION} --- will be built")
    list(APPEND packages_info "${package} ${${uc_package}_VERSION} ${${uc_package}_SOURCE} ${${uc_package}_MD5}\n")
    include("${lc_package}_external")
  endif()
endforeach()
file(WRITE ${PARTS_BUILT_INFO} ${packages_info})
```

**Comment by doutriaux1** [comment]
https://github.com/UV-CDAT/uvcdat/blob/update_references_for_master/CMakeLists.txt#L612

**Comment by aashish24** [comment]
Thanks. I can push a fix for it. Basically, we can do a check and then construct the pacakge info.

**Comment by aashish24** [comment]
Pushed a fix. Please review again @doutriaux1

**Comment by doutriaux1** [comment]
lgtm building on my system and then merging.

**Comment by aashish24** [comment]
Great.. once this goes in, I can update the VTK as well.

**Comment by doutriaux1** [comment]
i don't know if that's yours and something that went into master (merged master locally in before running your PR), but now this happens:
```
doutriaux1@omar:[build_test_up_ref]:[33531]> source install/bin/setup_runtime.sh 
(uvcdat)doutriaux1@omar:[build_test_up_ref]:[33526]> 
```
sourcing messes up my prompt. Not quite sure what's going on here. Let me build pure master and if also happens then I can at least approve this.

**Comment by doutriaux1** [comment]
i really don't see how this could mess my prompt, it must be something that went into master.

**Comment by doutriaux1** [comment]
ok commit b0d52306befd855bc333f7c2884448cbacd7f1b8 introduces this prompt change! merging this but going to promptly (haha) ask to reverse that prompt change, who approved this?

**Pull request merged**
