### PR TITLE
Viridis latest

### PR DESCRIPTION
**Pull request by doutriaux1**
goes with https://github.com/UV-CDAT/uvcdat-testdata/pull/154

@aashish24 @danlipsa @chaosphere2112 please review passes all test on my mac and linux boxes

### CODE REVIEW

**Comment by doutriaux1** [comment]
if you're not convinced take a look at: https://youtu.be/xAoljeRJ3lU

**Comment by chaosphere2112** [comment]
https://github.com/UV-CDAT/uvcdat-testdata/blob/863c2bcf25b2a344d7447fc04ce8912513a63533/baselines/vcs/test_fewer_colors_than_levels.png This one is less good. Can you update that test to use colors from a wider selection of viridis?

**Comment by doutriaux1** [comment]
@chaosphere2112 I checked the colors are different. Feel free to update the test and baselines, the test does what it's supposed to do, as far as I'm concerned that's good enough, I don't really care if the output of the test "look good or not"

**Comment by aashish24** [comment]
@doutriaux1 thanks for pushing this change. Could you please squash commits (the duplicate ones?).

**Comment by doutriaux1** [comment]
@aashish24 no the squash when merging these days.

**Comment by doutriaux1** [comment]
travis does not seem to be checking out the matching baseline branch

**Comment by doutriaux1** [comment]
I see in the travis log:
```
[100%] Updating uvcdat-testdata repo.
Cloning "git://github.com/UV-CDAT/uvcdat-testdata.git" into "/home/travis/build/UV-CDAT/_build/uvcdat-testdata"...
Cloning into '/home/travis/build/UV-CDAT/_build/uvcdat-testdata'...
[INFO] Trying to find matching branch on baseline repo
The current source directory at '/home/travis/build/UV-CDAT/uvcdat' is not on a named branch. Using the 'master' branch of the testdata repo.
Testing if remote branch 'origin/master' exists...
Remote branch exists.
Testing if local branch 'master' exists...
Local branch exists.
Checking out branch 'master' in repo '/home/travis/build/UV-CDAT/_build/uvcdat-testdata'.
Updating "/home/travis/build/UV-CDAT/_build/uvcdat-testdata:master" from "git://github.com/UV-CDAT/uvcdat-testdata.git:master"...
Already up-to-date.
```

**Comment by doutriaux1** [comment]
I think travis checks out a commit not a branch? I'll look into this.

**Comment by aashish24** [comment]
@doutriaux1 let us know again when we should look into reviewing this branch (as I see that last commit us using the old colormap for some baselines).

**Comment by aashish24** [comment]
@sankhesh let's disable the content check until we discuss the software process with the team.

**Comment by danlipsa** [comment]
Do: test

**Comment by sankhesh** [comment]
Do: test

**Comment by sankhesh** [comment]
**FYI**: Content checks still fail but I've set it to ignore the failures and run tests.

**Comment by doutriaux1** [comment]
the `green` link to cdash is broken (details link)

**Comment by sankhesh** [comment]
Hmm. It works for me. Goes to [CDash](https://open.cdash.org/index.php?compare1=63&filtercount=2&field1=buildname%2Fstring&project=UV-CDAT&field2=buildstarttime%2Fdate&showfilters=0&limit=100&compare2=83&value1=0faa5b60&showfeed=0&value2=20160825T102327)

**Comment by doutriaux1** [comment]
@sankhesh I guess I was expecting it to take me to: https://open.cdash.org/buildSummary.php?buildid=4519827

**Comment by danlipsa** [comment]
@doutriaux1 14 tests fail on buildbot. See the CDash link from buildbot.
You might need additional baselines for the line stipple ones.

**Comment by doutriaux1** [comment]
@danlipsa changing default to use all colors:  https://open.cdash.org/viewTest.php?onlyfailed&buildid=4521825

**Comment by danlipsa** [comment]
@doutriaux1 Nice! Once you change all the baselines, I can do another pass through all images.

**Comment by doutriaux1** [comment]
@danlipsa baselines uploaded. sources as well. Ready for another round of review.

**Comment by danlipsa** [comment]
@doutriaux1 
- All basic_boxfill did not switch to viridis and have wrong colors and the bottom and top margins
- Same for basic_isofill
Something seems to have gone wrong with updating the baselines.
See for instance 
https://github.com/UV-CDAT/uvcdat-testdata/blob/914a99a82c57e67d80793d0823d71b07c5fd3274/baselines/vcs/test_vcs_basic_boxfill.png

**Comment by aashish24** [comment]
I see sorry on the data PR, I got it otherway. So now by default we will be using the full range :+1:  for that.

**Comment by aashish24** [comment]
Are we going to take out constant colors from other colormaps?

**Comment by doutriaux1** [comment]
no it would break too many scripts. Lots of history scripts using `242` as `red` for example or `1` as `black`

**Comment by aashish24** [comment]
> no it would break too many scripts. Lots of history scripts using 242 as red for example or 1 as black

roger that

**Comment by doutriaux1** [comment]
@danlipsa the test_vcs_basic_gmpy sets the colormap to `rainbow` so it's normal that they do not use `viridis` also the new default range is 0/255 hence the weird colors on the edges. Do you prefer I turn off the rainbow colormap or sets the colors to use 16/240 as before?

**Comment by doutriaux1** [comment]
well it's called `basic` so it should stay basic and use the default colormap. I went for this solution.

**Comment by doutriaux1** [comment]
@danlipsa @aashish24 I think we're good. Still not sure why travis fails some baselines. I'll look at the cdash. But at least it's checking out the correct branches.

**Comment by danlipsa** [comment]
Do: test

**Comment by danlipsa** [comment]
> well it's called basic so it should stay basic and use the default colormap. I went for this solution.
@doutriaux1 Sounds good. Sorry for the delay, I was out yesterday.

**Comment by danlipsa** [comment]
> no it would break too many scripts. Lots of history scripts using 242 as red for example or 1 as black
@doutriaux1 @aashish24 Maybe we should provide an API to access additional (annotation) colors associated with a a color map. This way, we can have annotation colors for new color maps that fill all 256 positions such as viridis. We can do this in a separate PR. We can use the colors stored in 1-15 and 241-256 for old color maps.

**Comment by doutriaux1** [comment]
@danlipsa we do not need these reserved color anymore user can simply specify `red` I'm not sure I understand your API comment.

**Comment by doutriaux1** [comment]
anyhow let's merge this please if you're happy with it.

**Comment by danlipsa** [comment]
@doutriaux1 The API would be useful because for a particular colormap you don't know if red would be a good color to use. Red might be a color used in the color map, so it won't be good for annotations.

**Comment by danlipsa** [comment]
@doutriaux1 That was the reason why it was useful to have reserved colors for each color maps. Annotations have to be done with different colors for different color maps.

**Comment by danlipsa** [comment]
@doutriaux1 Another pass:
basic_aeqd
basic_vector_45_2
colormaps_source_boxfill_canvas
colormaps_source_boxfill_gm
colormaps_source_boxfill_vcs
legend_boxfill_horizontal_ext1_n_ext2_n
legend_boxfill_horizontal_ext1_n_ext2_y
legend_boxfill_horizontal_ext1_y_ext2_n
legend_boxfill_horizontal_ext1_y_ext2_y
legend_boxfill_vertical_ext1_n_ext2_y
legend_boxfill_vertical_ext1_y_ext2_n
legend_boxfill_vertical_ext1_y_ext2_y
set_colormap
have the annotation colors showing up. 

colormaps_source_isofill_canvas
colormaps_source_isofill_gm
colormaps_source_isofill_vcs
colormaps_source_meshfill_canvas
colormaps_source_meshfill_gm
colormaps_source_meshfill_vcs
looks different - has white at left side of the color map compared with dark blue



I think, this should never happen, even if the user chooses one of the old color maps. Maybe we should have a flag: old style (15-240) or new style (0-255) color map. This way we can do the right thing regardless of the type of color map. Also, adding the API to get additional colors for each color map - as I suggested in my previous post would help.

**Comment by doutriaux1** [comment]
@danlipsa but you would think annotation would be done using a separate textobject. This object can have its own colormap.

**Comment by danlipsa** [comment]
@doutriaux1 Colors for annotations have to work with (be somewhat different than) the existing picture = existing color map. Otherwise you could have a red text over a red part of the picture. That is why they have to be somehow associated with an existing color map. I assume that is why they were stored in the past in 0-16 240-256 of each color map. VTK attenuates this problem using shaded text. Not sure if vcs has this concept. Maybe this is the easiest way to deal with this.

**Comment by danlipsa** [comment]
@doutriaux1 There are 22 tests failing on buildbot:
https://open.cdash.org/index.php?compare1=63&filtercount=2&field1=buildname%2Fstring&project=UV-CDAT&field2=buildstarttime%2Fdate&showfilters=0&limit=100&compare2=83&value1=1f65a28f&showfeed=0&value2=20160830T135522

**Comment by danlipsa** [comment]
This is a test comment for buildbot

**Comment by doutriaux1** [comment]
Both will fail because we need to remove .uv-cdat
 From  $home . I was going to fix this in another PR but let me fix it in here then

**Comment by doutriaux1** [comment]
@danlipsa ok I pushed the fixes to not overwrite our default if they are redefined in .uvcdat directory.

**Comment by danlipsa** [comment]
Do: test

**Comment by danlipsa** [comment]
@doutriaux1 Nice, only 3 failures: 2 stipple offset test failures and one font size and we are good.
https://open.cdash.org/index.php?compare1=63&filtercount=2&field1=buildname%2Fstring&project=UV-CDAT&field2=buildstarttime%2Fdate&showfilters=0&limit=100&compare2=83&value1=c4ac10eb&showfeed=0&value2=20160831T094724

**Comment by doutriaux1** [comment]
@danlipsa do you mind adding these new baselines? I do not have access to karma

**Comment by danlipsa** [comment]
@doutriaux1 You should see the same thing on your local linux machine. That is the idea at least. Let me know, if you don't, I can add the baselines - I'll just copy them from cdash.

**Comment by doutriaux1** [comment]
a green Linux on travis! Yeah! https://travis-ci.org/UV-CDAT/uvcdat/jobs/156546414

**Comment by danlipsa** [comment]
Do: test

**Comment by danlipsa** [comment]
@doutriaux1 Green buildbot. :+1:  Ready to merge.

**Pull request merged**
