### PR TITLE
should address part of #729

### PR DESCRIPTION
**Pull request by doutriaux1**
@chaosphere2112 @dlonie @aashish24 this is an improved version that should make the GUI experience more pleasant for @potter2
no baseline

### CODE REVIEW

**Comment by aashish24** [comment]
@doutriaux1 what we should expect? How do I verify?

**Comment by doutriaux1** [comment]
@aashish24 it just adds a few predefined nethods, all the a_ are editable copy of default. Also added a few default with projection enabled to make it easier.

**Comment by doutriaux1** [comment]
@aashish24 just a friendly ping

**Comment by potter2** [comment]
When can I get a binary, or the instructions to build it on 10.10?

On 2/25/15 6:43 PM, Aashish Chaudhary wrote:
>
> Merged #1052 <https://github.com/UV-CDAT/uvcdat/pull/1052>.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/UV-CDAT/uvcdat/pull/1052#event-242222578>.
>

-- 
Gerald (Jerry) Potter
NASA Goddard Space Flight Center
E-mail  gerald.potter@nasa.gov
Office  28:S241
Phone    707.315.8314
Analysis and Data Consultant
Department      GSFC:606.2

**Comment by williams13** [comment]
Charles ma have something today… We’ll keep you posted.

**Pull request merged**
