### PR TITLE
Uvcmetrics devel

### PR DESCRIPTION
**Pull request by doutriaux1**
getting uvcmetrics in line with repo not just uvcdat-2.4.0 tag point and updates baselines (and their new file names) along with it.  goes with https://github.com/UV-CDAT/uvcdat-testdata/pull/105

### CODE REVIEW

**Comment by doutriaux1** [comment]
@mcenerney1 @isubsmith @painter1 please review and approve

**Comment by doutriaux1** [comment]
@aashish24 @mcenerney1 @painter1 @danlipsa ready to be merged in, needed in preparation of uvcdat 2.4.1 goes with: https://github.com/UV-CDAT/uvcdat-testdata/pull/105

**Comment by aashish24** [comment]
Thanks @doutriaux1 I was going to ping you on 2.4.1. Looks like garant is failing.

**Comment by doutriaux1** [comment]
hum looks like anti-aliasing is on in the test suite... let me look into this

**Comment by doutriaux1** [comment]
@aashish24 @sankhesh @danlipsa @chaosphere2112 I think this is our 2.4.1 candidate please review I would like to release tomorrow.

**Pull request merged**
