### PR TITLE
Revert "Fix #1539 - Update iPython 3.0.0 to 4.0.0"

### LINKED ISSUE #1539: Update iPython to 4.1.2
We are a full release behind iPython latest (3.0.0 vs 4.0.0).

@doutriaux1 want to assign me as a 2.4 milestone?

### PR DESCRIPTION
**Pull request by doutriaux1**
This reverts commit 683596cbfb15a2a7c9102e4e8dee39aa28ce2601.

@aashish24 this should bring us back to ipython 3.0

ipython 4.0 `appears` to work but when on lab networks it fails at load time because we need to bring in many many more `silent` dependencies that pip auto-downloads (except inside the lab)

### CODE REVIEW

**Comment by durack1** [comment]
@doutriaux1 @aashish24 FYI the latest release of `ipython3.2.2` source up on $LLNL_URL, the md5 is `69a99f1b0afc78acdd0443b62d10d52b`

**Comment by doutriaux1** [comment]
@aashish24 merging in a few hours if I didin't hear from you so @williams13 can test in the morning

**Comment by aashish24** [comment]
LGTM :+1:

**Comment by doutriaux1** [comment]
Thx

**Pull request merged**
