### PR TITLE
Vtk ui test coverage

### PR DESCRIPTION
**Pull request by chaosphere2112**
Fully rebased PR that replaces #1304 to make this all nice and mergeable.

### CODE REVIEW

**Comment by chaosphere2112** [comment]
Goes with UV-CDAT/uvcdat-testdata#55

**Comment by chaosphere2112** [comment]
@jbeezley or @aashish24 Can someone kick the build off on garant? I accidentally submitted this PR before the one on uvcdat-testdata (my remotes weren't what I thought they were).

**Comment by chaosphere2112** [comment]
@aashish24 @jbeezley @doutriaux1 This branch is ready to merge.

**Comment by doutriaux1** [comment]
hum... I rebased with master into this and tried. I get this:
https://open.cdash.org/viewTest.php?onlyfailed&buildid=3937105
Not sure why. 

I'm worried about the matlplotlib. I need to test again master....

**Pull request merged**
