### PR TITLE
Merge colorpicker changes into release

### PR DESCRIPTION
**Pull request by chaosphere2112**

### CODE REVIEW

**Comment by chaosphere2112** [comment]
@aashish24 This merges my PR and Remi's into release

**Comment by aashish24** [comment]
? no reviews?

**Comment by chaosphere2112** [comment]
I just merged over from master; it was code that was already reviewed, and both Remi and I had aimed at the wrong branch.

**Comment by chaosphere2112** [comment]
that said, we can back out the changes. I just figured it wasn't a big deal.

**Comment by aashish24** [comment]
no problem. okay, but create a new branch, so that the we have a proper name of the branch.

**Comment by chaosphere2112** [comment]
:confused: You want me to do what exactly?

**Comment by aashish24** [comment]
On the top it says: 
	chaosphere2112  merged 3 commits into release from master 27 minutes ago

which means that you are directly merging from master into release. Intstead you would do: 

> git checkout bring_fix_foo origin/master
> git push origin HEAD

and then will do a pull request on that. In that way we know (without github interface) what change you bought in in git log  or gitk --first-parent

**Comment by chaosphere2112** [comment]
ah, gotcha.

**Comment by chaosphere2112** [comment]
Will do!

**Comment by aashish24** [comment]
thanks :+1:

**Pull request merged**
