### PR TITLE
Animations will properly resume when resizing

### PR DESCRIPTION
**Pull request by chaosphere2112**
Addresses the buggy part of #1629; performance fix will be a separate PR (I know the source of the issue, there will be an extensive writeup as part of that PR, which I hope to have up by end of day today).

### CODE REVIEW

**Comment by aashish24** [comment]
@chaosphere2112 I will review it today.

**Comment by aashish24** [comment]
@chaosphere2112 I was able to reproduce the bug now working on testing your code.

**Comment by aashish24** [comment]
@chaosphere2112 LGTM :+1: I see failures on dashboards but it does not seem to related to this branch.

**Comment by aashish24** [comment]
Ship it!

**Comment by jbeezley** [comment]
It looks like garant has been failing since about 9/23 (that was the last nightly to pass).  Looking back through cdash, my guess is that #1563 is the cause.

FWIW, the output image looks something like the resizing bug that occurs in cdatweb.  The axes and text don't look like they have redrawn yet.  Another thing I noticed is that this test is much faster on garant than on the other dashboard machines (1.5s vs 5-10s).

**Comment by aashish24** [comment]
@jbeezley the axes looks right on my Ubuntu box when I merged Sam's branch into master. Can you post your screen captures?

**Comment by jbeezley** [comment]
Yes, it doesn't have anything to do with these changes.  Like I said, it has shown up on the nightlies for over a month.  For example here: https://open.cdash.org/testDetails.php?test=383120267&build=4070878

**Comment by aashish24** [comment]
> Yes, it doesn't have anything to do with these changes. Like I said, it has shown up on the nightlies for over a month. For example here: https://open.cdash.org/testDetails.php?test=383120267&build=4070878

Ah, thanks, I misunderstood what you said earlier. That test has been failing for sometime. @doutriaux1 are you going to look at it? Do you think its a more general issue like what @jbeezley is talking about?

**Comment by doutriaux1** [comment]
@chaosphere2112 looks like we need to tell test_vcs_click_info an actual size of screen to use, my guess is that on garant VTK is actually able to get the screensize (unlike on most other machines) and uses it to set a different value.

**Comment by chaosphere2112** [comment]
@doutriaux1 That would make sense... I can do that.

**Comment by aashish24** [comment]
> @chaosphere2112 looks like we need to tell test_vcs_click_info an actual size of screen to use, my guess is that on garant VTK is actually able to get the screensize (unlike on most other machines) and uses it to set a different value.

or may be its getting a different size since I don't know how VTK would behave differently.

**Comment by chaosphere2112** [comment]
@aashish24 It's been very odd. I've got installs where it correctly determines the size and ones where it doesn't (different OSX versions, mostly).

**Comment by aashish24** [comment]
> @aashish24 It's been very odd. I've got installs where it correctly determines the size and ones where it doesn't (different OSX versions, mostly).

The VTK API returns a pointer so unless the API changed, I don't know how it can return a number. But I haven't look at the code recently.

**Comment by chaosphere2112** [comment]
```
In [1]: import vtk

In [2]: w = vtk.vtkRenderWindow()

In [3]: w.GetScreenSize()
Out[3]: (2560, 1600)

In [4]: w.GetDPI()
Out[4]: 72
```

**Comment by jbeezley** [comment]
On garant:
```python
In [1]: import vtk

In [2]: w = vtk.vtkRenderWindow()

In [3]: w.GetScreenSize()
Out[3]: '_000000000116fac0_p_void'

In [4]: w.GetDPI()
Out[4]: 72
```

**Comment by jbeezley** [comment]
That's with VTK commit [6d67334](https://github.com/UV-CDAT/VTK/commit/6d6733477f60dc57236ce8f09e8db9429056fcd9).

**Comment by chaosphere2112** [comment]
I'm on https://github.com/UV-CDAT/VTK/commit/ec6c6ab9e982f4c585ca04ea98271fbe6baa819a

**Comment by jbeezley** [comment]
Yeah, that was an old build.  But using the latest https://github.com/UV-CDAT/VTK/commit/ec6c6ab9e982f4c585ca04ea98271fbe6baa819a, I still get
```python
In [3]: w.GetScreenSize()
Out[3]: '_000000000116fac0_p_void'
```

**Comment by jbeezley** [comment]
This was supposedly fixed in https://github.com/UV-CDAT/VTK/commit/0541472e57a124f9b87ce6f019d107102ece2d01.  Maybe some other render window classes need the type hinting added.

**Comment by jbeezley** [comment]
For the record, that is using `XOpenGLRenderWindow` on Ubuntu 14.04.
```
$ glxinfo | head
name of display: :0
display: :0  screen: 0
direct rendering: Yes
server glx vendor string: NVIDIA Corporation
server glx version string: 1.4

$ modinfo nvidia
filename:       /lib/modules/3.16.0-34-generic/kernel/drivers/video/nvidia.ko
alias:          char-major-195-*
version:        346.47
supported:      external
license:        NVIDIA
alias:          pci:v000010DEd00000E00sv*sd*bc04sc80i00*
alias:          pci:v000010DEd00000AA3sv*sd*bc0Bsc40i00*
alias:          pci:v000010DEd*sv*sd*bc03sc02i00*
alias:          pci:v000010DEd*sv*sd*bc03sc00i00*
depends:        drm
vermagic:       3.16.0-34-generic SMP mod_unload modversions
parm:           NVreg_Mobile:int
parm:           NVreg_ResmanDebugLevel:int
parm:           NVreg_RmLogonRC:int
parm:           NVreg_ModifyDeviceFiles:int
parm:           NVreg_DeviceFileUID:int
parm:           NVreg_DeviceFileGID:int
parm:           NVreg_DeviceFileMode:int
parm:           NVreg_RemapLimit:int
parm:           NVreg_UpdateMemoryTypes:int
parm:           NVreg_InitializeSystemMemoryAllocations:int
parm:           NVreg_UsePageAttributeTable:int
parm:           NVreg_MapRegistersEarly:int
parm:           NVreg_RegisterForACPIEvents:int
parm:           NVreg_CheckPCIConfigSpace:int
parm:           NVreg_EnablePCIeGen3:int
parm:           NVreg_EnableMSI:int
parm:           NVreg_MemoryPoolSize:int
parm:           NVreg_RegistryDwords:charp
parm:           NVreg_RmMsg:charp
parm:           NVreg_AssignGpus:charp

$ Xorg -version
X.Org X Server 1.16.0
Release Date: 2014-07-16
X Protocol Version 11, Revision 0
Build Operating System: Linux 3.2.0-70-generic x86_64 Ubuntu
Current Operating System: Linux garant 3.16.0-34-generic #47~14.04.1-Ubuntu SMP Fri Apr 10 17:49:16 UTC 2015 x86_64
Kernel command line: BOOT_IMAGE=/boot/vmlinuz-3.16.0-34-generic root=UUID=f6b13ce7-4323-498a-a545-0b6a9c5b7b3b ro quiet splash nouveau.blacklist=1 vt.handoff=7
Build Date: 12 February 2015  11:11:26PM
xorg-server 2:1.16.0-1ubuntu1.2~trusty2 (For technical support please see http://www.ubuntu.com/support)
Current version of pixman: 0.30.2
```

**Comment by aashish24** [comment]
> This was supposedly fixed in UV-CDAT/VTK@0541472. Maybe some other render window classes need the type hinting added.

@jbeezley that sounds like a possibility. On my ubuntu as well I am getting a pointer but may for Mac, we have the type hinting set. @dlonie care to look into it?

**Comment by dlonie** [comment]
Sure enough, looks like the hints file is missing a definition for `vtkXOpenGLRenderWindow`. Funny, as that's the most frequently used window implementation.

Actually, on second look, it's a typo. There are hints provided for `vtkXRenderWindow` at the bottom of the file, but that class doesn't exist. It should be `vtkXOpenGLRenderWindow`.

@jbeezley Can you try patching the hints file on your local build to correct the name and see if that fixes it? I can prepare a patch if that fixes it.

**Comment by jbeezley** [comment]
Sure.

**Comment by jbeezley** [comment]
Yup, that fixed it.
```diff
diff --git a/Wrapping/Tools/hints b/Wrapping/Tools/hints
index c36c49e..78a6dfe 100644
--- a/Wrapping/Tools/hints
+++ b/Wrapping/Tools/hints
@@ -282,7 +282,7 @@ vtkWindowLevelLookupTable             GetMaximumTableValue              307  4
 vtkWindowLevelLookupTable             GetMinimumTableValue              307  4
 vtkXImageWindow                       GetPosition                       304  2
 vtkXImageWindow                       GetSize                           304  2
-vtkXRenderWindow                      GetPosition                       304  2
-vtkXRenderWindow                      GetScreenSize                     304  2
-vtkXRenderWindow                      GetSize                           304  2
+vtkXOpenGLRenderWindow                GetPosition                       304  2
+vtkXOpenGLRenderWindow                GetScreenSize                     304  2
+vtkXOpenGLRenderWindow                GetSize                           304  2
 vtkXYPlotActor                        GetPlotColor                      307  3
```

**Comment by dlonie** [comment]
UV-CDAT/VTK#11

**Pull request merged**
