### PR TITLE
1338 isoline labels

### PR DESCRIPTION
**Pull request by sankhesh**
Takes over from #1459

### CODE REVIEW

**Comment by sankhesh** [comment]
@aashish24 

Please review

**Comment by aashish24** [comment]
Thanks @sankhesh!

**Comment by aashish24** [comment]
@sankhesh there should be a data branch as well I guess that we need to merge?

**Comment by aashish24** [comment]
Eventually we need to get rid of fitTOViewport and I hope that we can have classes for each plot; each with its own Renderer. But for now it looks good to me.

**Comment by aashish24** [comment]
+2 :+1:

**Pull request merged**
