### PR TITLE
grid var name hadn't been renamed everywhere...

### LINKED ISSUE #1245: Error on meshfill
Hey all; clean build on release branch, all tests pass. Ran into this issue:

```python
import vcs, cdms2, os
x = vcs.init()
f = cdms2.open(os.path.join(vcs.prefix, "sample_data", "clt.nc"))
s = f("clt")
x.meshfill(s)
```

barfs out this:

```
----> 1 x.meshfill(s)

/Users/fries2/bin/uvcdat/2.2-rc1/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/vcs/Canvas.pyc in meshfill(self, *args, **parms)
   1490 """
   1491         arglist=_determine_arg_list('meshfill',args)
-> 1492         return self.__plot(arglist, parms)
   1493 
   1494     #############################################################################

/Users/fries2/bin/uvcdat/2.2-rc1/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/vcs/Canvas.pyc in __plot(self, arglist, keyargs)
   2730                     ys=arglist[0].getAxis(-2)
   2731                     if xs.isLongitude() and ys.isLatitude() and isinstance(inGrid,cdms2.grid.TransientRectGrid):
-> 2732                         arglist[1]=MV2.array(g.getMesh())
   2733                         if not 'wrap' in keyargs.keys():
   2734                             keyargs['wrap']=[0.,360.]

UnboundLocalError: local variable 'g' referenced before assignment
```

@doutriaux1 I'm assigning to you.

### PR DESCRIPTION
**Pull request by doutriaux1**
fix #1245 
@chaosphere2112 please review

### CODE REVIEW

**Comment by doutriaux1** [comment]
goes with: 
https://github.com/UV-CDAT/uvcdat-testdata/pull/43

**Comment by aashish24** [comment]
LGTM but someone else should approve it (I didn't built it)

**Comment by chaosphere2112** [comment]
@doutriaux1 I'm having some issues getting a working environment up at home; I'll try and get one assembled today to test this.

**Comment by chaosphere2112** [comment]
@doutriaux1 Passes all tests for me; https://open.cdash.org/viewTest.php?onlypassed&buildid=3794971

**Pull request merged**
