### PR TITLE
Improve testing by moving common code to testing module

### PR DESCRIPTION
**Pull request by aashish24**

### CODE REVIEW

**Comment by aashish24** [comment]
Not ready to be merged but any feedback is welcome. @doutriaux1 @sankhesh @danlipsa @chaosphere2112

**Comment by aashish24** [comment]
The core idea is to provide a regression testing module that provide api that is needed for most of the vcs regression testing. This work reduces the testing code to 20 - 60% in most of the cases.

**Comment by aashish24** [comment]
Data: https://github.com/UV-CDAT/uvcdat-testdata/pull/132

**Comment by doutriaux1** [comment]
@aashish24 I like this so far, I just gave it a quick glance but I like the concept.

**Comment by aashish24** [comment]
thanks @doutriaux1. This branch is ready for review now.

**Comment by aashish24** [comment]
@danlipsa @doutriaux1 would it be possible to get it merged soon so that I don't need to keep upto date with master?

**Comment by doutriaux1** [comment]
ok let em build this on my mac an run the test suite on it.

**Comment by doutriaux1** [comment]
@aashish24 sorry my mac is very very slow.... still building

**Comment by danlipsa** [comment]
@aashish24 it is fine by me. Let me know if I should build/test this on my mac as well.

**Comment by doutriaux1** [comment]
@danlipsa I'm building on mac, if you have a different flavor of linux from @aashish24 that would be great as well

**Comment by danlipsa** [comment]
@doutriaux1 I have ubuntu 14.04. @aashish24 ?

**Comment by doutriaux1** [comment]
actually I can run a "mesa" build on my ubuntu 16 as well

**Comment by doutriaux1** [comment]
@aashish24 LOTS of failures on my mac: https://open.cdash.org/viewTest.php?onlyfailed&buildid=4364585

**Comment by doutriaux1** [comment]
@aashish24 I think it's a mix from @chaosphere2112 PR that went in and also some test seem to generate pictures at different output sizes, make sure they all set the output picture size. Otherwise it picks whatever the screen is.

**Comment by danlipsa** [comment]
@aashish24 I run your branch on my machine. You need to rebase uvcdat-testdata. Also most test fail because they cannot find testing.regression.
Here is an example:
[~/projects/uvcdat/build]$ "/home/danlipsa/projects/uvcdat/build/install/bin/python" "/home/danlipsa/projects/uvcdat/src/testing/vcs/test_vcs_gms_patterns_hatches.py" "--gm_type=meshfill" "--fill_style=hatch" "--lon1=0" "--lon2=360" "--source=/home/danlipsa/projects/uvcdat/build/uvcdat-testdata/baselines/vcs/test_vcs_meshfill_hatch_SH_0_360.png" "--threshold=45"
Traceback (most recent call last):
  File "/home/danlipsa/projects/uvcdat/src/testing/vcs/test_vcs_gms_patterns_hatches.py", line 1, in <module>
    import argparse, os, sys, cdms2, vcs, testing.regression as regression
ImportError: No module named testing.regression
[~/projects/uvcdat/build]$ find . -name regression.py
./build/Python/Lib/sqlite3/test/regression.py
./install/lib/python2.7/sqlite3/test/regression.py
[~/projects/uvcdat/build]$ echo $PYTHONPATH 
/home/danlipsa/projects/uvcdat/build/install/lib/python2.7/site-packages:/home/danlipsa/projects/uvcdat/build/install/Externals/lib/python2.7/site-packages:

**Comment by aashish24** [comment]
@danlipsa thanks. make sure that you delete CDAT-prefix and then do the installation. I will look into the test data branch. Thanks.

**Comment by danlipsa** [comment]
@aashish24 Thanks, that fixed the problem with the import. I am running through the tests right now.

**Comment by danlipsa** [comment]
These are the failures:
	 40 - flake8_vcs (Failed)
	 54 - test_vcs_read_old_scr_2 (Failed)
	118 - test_vcs_boxfill_10x10_numpy (Failed)
	358 - test_vcs_boxfill_lev1_lev2 (Failed)
	421 - test_vcs_click_info (Failed)
	422 - test_vcs_click_info_mollweide_boxfill (Failed)
	423 - test_vcs_click_info_meshfill (Failed)
	424 - test_vcs_click_info_robinson_meshfill (Failed)
	430 - test_vcs_no_continents (Failed)
	431 - test_vtk_ui_button_draw (Failed)
	432 - test_vtk_ui_button_action (Failed)
	433 - test_vtk_ui_button_corner_radius (Failed)
	434 - test_vtk_ui_button_dimensions (Failed)
	435 - test_vtk_ui_button_states (Failed)
	436 - test_vtk_ui_button_click (Failed)
	437 - test_vtk_ui_button_font (Failed)
	438 - test_vtk_ui_button_alignment (Failed)
	439 - test_vtk_ui_button_image (Failed)
	440 - test_vtk_ui_button_tooltip_show (Failed)
	441 - test_vtk_ui_button_tooltip_hide (Failed)
	442 - test_vtk_ui_button_state_advance (Failed)
	443 - test_vtk_ui_toggle_button_get_text (Failed)
	444 - test_vtk_ui_handle_appearance (Failed)
	445 - test_vtk_ui_handle_normalize (Failed)
	446 - test_vtk_ui_handle_sizing (Failed)
	447 - test_vtk_ui_handle_interaction (Failed)
	448 - test_vtk_ui_textbox_highlight (Failed)
	449 - test_vtk_ui_textbox_appearance (Failed)
	450 - test_vtk_ui_textbox_blank_text (Failed)
	451 - test_vtk_ui_textbox_cursor (Failed)
	452 - test_vtk_ui_textbox_typing (Failed)
	453 - test_vtk_ui_textbox_coordinate_editing (Failed)
	454 - test_vtk_ui_textbox_detach (Failed)
	455 - test_vtk_ui_label_top (Failed)
	456 - test_vtk_ui_label_y (Failed)
	457 - test_vtk_ui_label_behaviors (Failed)
	458 - test_vtk_ui_label_bounds (Failed)
	459 - test_vtk_ui_label_detach (Failed)
	460 - test_vtk_ui_label_font_attrs (Failed)
	461 - test_vtk_ui_label_left (Failed)
	462 - test_vtk_ui_label_render (Failed)
	463 - test_vtk_ui_label_show_hide (Failed)
	464 - test_vtk_ui_label_text (Failed)
	465 - test_vtk_ui_label_x (Failed)
	466 - test_vtk_ui_contrasting_colors (Failed)
	467 - test_vtk_ui_hsv_rgb (Failed)
	468 - test_vtk_ui_set_font (Failed)
	469 - test_vtk_ui_text_dimensions (Failed)
	470 - test_vtk_ui_white_or_black (Failed)
	471 - test_vtk_ui_toolbar_in_toolbar_open (Failed)
	472 - test_vtk_ui_toolbar_in_toolbar_closed (Failed)
	473 - test_vtk_ui_toolbar_label (Failed)
	474 - test_vtk_ui_toolbar_open (Failed)
	475 - test_vtk_ui_toolbar_close (Failed)
	476 - test_vtk_ui_slider_value_func (Failed)
	477 - test_vtk_ui_slider_values (Failed)
	478 - test_vtk_ui_slider_appearance (Failed)
	479 - test_vtk_ui_slider_callbacks (Failed)
	480 - test_vtk_ui_slider_place (Failed)
	481 - test_vtk_ui_slider_jumps (Failed)
	482 - test_vtk_ui_manager_resize (Failed)
	483 - test_vtk_ui_behavior_keyable (Failed)
	484 - test_vtk_ui_widget_init (Failed)
	485 - test_vtk_ui_widget_show_hide (Failed)
	486 - test_vtk_ui_widget_subscribe_unsubscribe (Failed)
	487 - test_vtk_ui_widget_detach (Failed)
	562 - diags_test_02 (Failed)
	563 - diags_test_03 (Failed)
	564 - diags_test_04 (Failed)
	565 - diags_test_41 (Failed)
	566 - diags_test_05 (Failed)
	567 - diags_test_06 (Failed)
	568 - diags_test_07 (Failed)
	569 - diags_test_08 (Failed)
	570 - diags_test_09 (Failed)
	571 - diags_test_10 (Failed)
	572 - diags_test_11 (Failed)
	573 - diags_test_12 (Failed)
	574 - diags_test_13 (Failed)
	575 - diags_test_15 (Failed)

**Comment by aashish24** [comment]
@doutriaux1 @danlipsa I have resolved all of the failing tests issues. I am running the tests locally but it would be great if you guys can test the branch again. 

@sankhesh looking forward to the bots on github

**Comment by aashish24** [comment]
I only have these tests failing now (and none of them are related to my changes). 

	550 - CDMS_Test_multiple_formats (Failed)
	562 - diags_test_02 (Failed)
	563 - diags_test_03 (Failed)
	564 - diags_test_04 (Failed)
	565 - diags_test_41 (Failed)
	566 - diags_test_05 (Failed)
	567 - diags_test_06 (Failed)
	568 - diags_test_07 (Failed)
	569 - diags_test_08 (Failed)
	570 - diags_test_09 (Failed)
	571 - diags_test_10 (Failed)
	572 - diags_test_11 (Failed)
	573 - diags_test_12 (Failed)
	574 - diags_test_13 (Failed)
	575 - diags_test_15 (Failed

**Comment by doutriaux1** [comment]
ok sounds good. I'll test on my mac now then.

**Comment by aashish24** [comment]
@doutriaux1 @danlipsa overall I reduced 20% number of lines of repeated testing code. 

```
# (before-after)/before
In [9]: (7898-6286)/7898.0
Out[9]: 0.20410230438085591
```

**Comment by doutriaux1** [comment]
that's really neat! Thanks.

**Comment by danlipsa** [comment]
@aashish24 your click_info baseline files are wrong. They are missing the yellow box showing the information. Not sure why - maybe you modified the test file in a way where it does not show the info? Search for click_info in the list of baselines you modified.

**Comment by aashish24** [comment]
@danlipsa thanks for catching this. The baselines were indeed wrong. I fixed the baselines in the corresponding testdata branch.

**Comment by doutriaux1** [comment]
@aashish24 I confirm see: https://open.cdash.org/viewTest.php?onlyfailed&buildid=4371882

**Comment by doutriaux1** [comment]
@aashish24 re-running now that you updated the baselines. WIll let you know.

**Comment by doutriaux1** [comment]
@aashish24 it seems to be still failing, will post cdash link when done:
```
        Start 118: test_vcs_boxfill_10x10_numpy
        Start 139: test_vcs_meshfill_regular_grid
        Start 356: test_vcs_first_png_blank
        Start 358: test_vcs_boxfill_lev1_lev2
  5/577 Test  #49: test_vcs_meshfill_vertices ..............................***Failed   12.75 sec
  6/577 Test #108: test_vcs_iso_celine_part2 ...............................   Passed   12.75 sec
  7/577 Test #113: test_vcs_boxfill_decreasing_latitude ....................   Passed   12.74 sec
        Start 359: test_vcs_boxfill_lev1_lev2_ext1
        Start 360: test_vcs_boxfill_lev1_lev2_ext2
        Start 361: test_vcs_boxfill_lev1_lev2_ext1_ext2
  8/577 Test #118: test_vcs_boxfill_10x10_numpy ............................***Failed    5.63 sec
  9/577 Test #139: test_vcs_meshfill_regular_grid ..........................   Passed    5.63 sec
 10/577 Test #358: test_vcs_boxfill_lev1_lev2 ..............................   Passed    5.63 sec
 11/577 Test #356: test_vcs_first_png_blank ................................   Passed    5.83 sec
        Start 362: test_vcs_hatches_patterns
        Start 409: test_vcs_patterns
        Start 421: test_vcs_click_info
        Start 422: test_vcs_click_info_mollweide_boxfill
 12/577 Test #361: test_vcs_boxfill_lev1_lev2_ext1_ext2 ....................   Passed    5.84 sec
        Start 423: test_vcs_click_info_meshfill
 13/577 Test #360: test_vcs_boxfill_lev1_lev2_ext2 .........................   Passed    6.05 sec
 14/577 Test #359: test_vcs_boxfill_lev1_lev2_ext1 .........................   Passed    6.05 sec
        Start 424: test_vcs_click_info_robinson_meshfill
        Start 408: test_vcs_animate_isoline_text_labels_colored
 15/577 Test #114: test_vcs_meshfill_no_wrapping ...........................   Passed   24.50 sec
        Start 407: test_vcs_animate_isoline_text_labels
 16/577 Test #422: test_vcs_click_info_mollweide_boxfill ...................***Failed    6.54 sec
        Start 404: test_vcs_animate_boxfill
 17/577 Test #421: test_vcs_click_info .....................................***Failed    6.85 sec
 18/577 Test #423: test_vcs_click_info_meshfill ............................***Failed    6.23 sec
        Start 403: test_vcs_animate_isofill
        Start 406: test_vcs_animate_isoline_colored
 19/577 Test #362: test_vcs_hatches_patterns ...............................   Passed    7.55 sec
 20/577 Test #424: test_vcs_click_info_robinson_meshfill ...................***Failed    6.52 sec
        Start 405: test_vcs_animate_isoline
        Start 392: test_vcs_animate_projected_boxfill_robinson
 21/577 Test #409: test_vcs_patterns .......................................   Passed   14.74 sec
```

**Comment by aashish24** [comment]
thanks @doutriaux1 make sure that you fetch and reset for baselines "improve_testing_somemore"

**Comment by aashish24** [comment]
@doutriaux1 weird. What SHA you have for uvcdat-testdata, mine is below:

[chaudhary@einstein uvcdat-testdata (improve_testing_somemore)]$ git log -n1
commit 1d09e7b04908c4ec209a801a88e7432ab3411d7d
Author: Aashish Chaudhary <aashish.chaudhary@kitware.com>
Date:   Wed May 18 10:56:02 2016 -0400

    Updated to use correct baselines
[chaudhary@einstein uvcdat-testdata (improve_testing_somemore)]$

**Comment by aashish24** [comment]
test_vcs_boxfill_10x10_numpy has a legitimate failure as the baseline size was slightly different. Not sure why my run didn't catch that. I pushed the correct size baseline. All other tests are passing for me (in the list above)

**Comment by doutriaux1** [comment]
@aashish24 currently it is running against:```
doutriaux1@sofia:[uvcdat-testdata]:[improve_testing_somemore]:[4263]> git log -n1
commit 1d09e7b04908c4ec209a801a88e7432ab3411d7d
Author: Aashish Chaudhary <aashish.chaudhary@kitware.com>
Date:   Wed May 18 10:56:02 2016 -0400

    Updated to use correct baselines
doutriaux1@sofia:[uvcdat-testdata]:[improve_testing_somemore]:[4257]> 
```

**Comment by danlipsa** [comment]
@aashish24 test_vcs_monotonic_decreasing_yxvsx_default.png has some points along the line that where not present in the original image. Do you know why?

**Comment by aashish24** [comment]
@doutriaux1 please try this SHA:

[chaudhary@einstein uvcdat-testdata (improve_testing_somemore)]$ git log -n1
commit 98599d5053a733f65990e34d06fada5728830a7a
Author: Aashish Chaudhary <aashish.chaudhary@kitware.com>
Date:   Wed May 18 11:04:33 2016 -0400

    Updated baseline to match the correct size

**Comment by aashish24** [comment]
@danlipsa I just saw test_vcs_monotonic_decreasing_yxvsx_default.png too. Let me have a look.

**Comment by aashish24** [comment]
@danlipsa I just looked. My change should not have caused it but I am looking for suggestions.

**Comment by aashish24** [comment]
@doutriaux1 vcs_click_info is failing because of dimension issues. I will push a fix.

**Comment by danlipsa** [comment]
@aashish24 strange. I just run the test on my branch and it generates the (smaller) image without the dots. I would say to file an issue for this, if we think it is small enough to let it through.

**Comment by aashish24** [comment]
okay thanks @danlipsa I will file the issue.

**Comment by aashish24** [comment]
Ref: https://github.com/UV-CDAT/uvcdat/issues/1976

**Comment by aashish24** [comment]
I am running the tests again, this time I think I should have it. It seems to me that in parallel build, I didn't get these errors (weird).

**Comment by aashish24** [comment]
should be all good now crossing my finget

**Comment by aashish24** [comment]
@danlipsa @doutriaux1 please try again.

**Comment by danlipsa** [comment]
54 - test_vcs_read_old_scr_2 (Failed)
	421 - test_vcs_click_info (Failed)
	422 - test_vcs_click_info_mollweide_boxfill (Failed)
	423 - test_vcs_click_info_meshfill (Failed)
	424 - test_vcs_click_info_robinson_meshfill (Failed)
	562 - diags_test_02 (Failed)
	563 - diags_test_03 (Failed)
	564 - diags_test_04 (Failed)
	565 - diags_test_41 (Failed)
	566 - diags_test_05 (Failed)
	567 - diags_test_06 (Failed)
	568 - diags_test_07 (Failed)
	569 - diags_test_08 (Failed)
	570 - diags_test_09 (Failed)
	571 - diags_test_10 (Failed)
	572 - diags_test_11 (Failed)
	573 - diags_test_12 (Failed)
	574 - diags_test_13 (Failed)
	575 - diags_test_15 (Failed)

This is uvctest-data
[~/projects/uvcdat/build/uvcdat-testdata (improve_testing_somemore %=)]$ git log
commit 426733695eb93d08904a6be993496ff45ad58d52
Author: Aashish Chaudhary <aashish.chaudhary@kitware.com>
Date:   Wed May 18 11:04:33 2016 -0400

    Updated baseline to match the correct size

**Comment by aashish24** [comment]
test_vcs_click_info is failing because it has to be in the foreground and width and height are not set. I tried to set geometry afterwards but looks like I found a bug. I will try to pass the geometry in the init call and see if that produces consistent behavior.

**Comment by aashish24** [comment]
@danlipsa I made the size of click tests to a fixed size. Can you try again please?

**Comment by danlipsa** [comment]
@aashish24 Those pass now, but it seems that you changed something else. I have 114 tests that fail - the size of the generated image is different - unless I did something wrong.
Here are the first few:

	  3 - testEsmfRegridRegion (Failed)
	 42 - test_vcs_boxfill_polar (Failed)
	 46 - test_vcs_fillarea_transparency (Failed)
	 49 - test_vcs_meshfill_vertices (Failed)
	 54 - test_vcs_read_old_scr_2 (Failed)
	 92 - test_vcs_remove_marker_none_1d (Failed)
	 95 - test_vcs_monotonic_decreasing_yxvsx_default (Failed)
	 96 - test_vcs_taylor_template_ctl (Failed)
	 97 - test_vcs_taylor_2quads (Failed)
	 98 - test_vcs_gen_meshfill (Failed)
	 99 - test_vcs_setcolormap (Failed)
	100 - test_vcs_1d_in_boxfill (Failed)
	101 - test_vcs_1d_missing (Failed)
	103 - test_vcs_1D_datawc (Failed)
	104 - test_vcs_1D_datawc_missing (Failed)
	105 - test_vcs_wmo_marker (Failed)
	106 - test_vcs_wmo_markers (Failed)
	107 - test_vcs_iso_celine_part1 (Failed)
	108 - test_vcs_iso_celine_part2 (Failed)
	109 - test_vcs_markers (Failed)
	113 - test_vcs_boxfill_decreasing_latitude (Failed)
	114 - test_vcs_meshfill_no_wrapping (Failed)
	116 - test_vcs_meshfill_zoom (Failed)

**Comment by doutriaux1** [comment]
@aashish24 same here on mac, more failures now:

https://open.cdash.org/viewTest.php?onlyfailed&buildid=4371882

**Comment by aashish24** [comment]
@danlipsa @doutriaux1 my bad, i relied on something from vcs which wasn't quite right. I will push a fix for vcs in a separate branch. In the mean time if you checkout the current SHA you should see only these tests failing: https://open.cdash.org/viewTest.php?onlyfailed&buildid=4372388

This should be the SHA: 
[chaudhary@einstein src.git (improve_testing_somemore)]$ git log -n1
commit 9c121a20f2121a0fcca665123d50b27553f176a0
Author: Aashish Chaudhary <aashish.chaudhary@kitware.com>
Date:   Wed May 18 21:19:46 2016 -0400

    Fixed failing test because of incorrect capture window size
[chaudhary@einstein src.git (improve_testing_somemore)]$

**Comment by danlipsa** [comment]
@aashish24 Now it is good. These are the only failing tests.
	 54 - test_vcs_read_old_scr_2 (Failed)
	562 - diags_test_02 (Failed)
	563 - diags_test_03 (Failed)
	564 - diags_test_04 (Failed)
	565 - diags_test_41 (Failed)
	566 - diags_test_05 (Failed)
	567 - diags_test_06 (Failed)
	568 - diags_test_07 (Failed)
	569 - diags_test_08 (Failed)
	570 - diags_test_09 (Failed)
	571 - diags_test_10 (Failed)
	572 - diags_test_11 (Failed)
	573 - diags_test_12 (Failed)
	574 - diags_test_13 (Failed)
	575 - diags_test_15 (Failed)

**Comment by aashish24** [comment]
thanks @danlipsa finally 😌  @doutriaux1 okay to merge?

**Comment by doutriaux1** [comment]
sorry lots of fires this morning, let me run it on my mac just to be safe.

**Comment by doutriaux1** [comment]
https://open.cdash.org/viewTest.php?onlyfailed&buildid=4373515

**Comment by aashish24** [comment]
@doutriaux1 looks like you have an older copy of regression.py. If you look at the code here; https://github.com/UV-CDAT/uvcdat/blob/9c121a20f2121a0fcca665123d50b27553f176a0/Packages/testing/regression.py you will see that init takes arguments. Can you make sure that you have latest code installed (and the baseline).

**Comment by danlipsa** [comment]
@doutriaux1 Lets merge this in, otherwise nothing can get merged - this has lots of changes! Seems it is ready.

**Comment by doutriaux1** [comment]
failed on my mac yesterday, but I'm off (officially today) I trust you @danlipsa go ahead and merge

**Pull request merged**
