### PR TITLE
Sync master

### PR DESCRIPTION
**Pull request by aashish24**

### CODE REVIEW

**Comment by aashish24** [comment]
@dlonie @chaosphere2112 @doutriaux1 please review.

**Comment by aashish24** [comment]
@chaosphere2112 is there anything we have to pick up from master into release (so the other way round).

**Comment by chaosphere2112** [comment]
@aashish24 Nope, I don't think so. Here are the commits in Master that aren't in release currently:

| Developer | Commit Message                                | SHA       |
|-----------|-----------------------------------------------|----------|
| aashish24 | Merge remote-tracking branch 'origin/release' |  cdf05a4 |
| aashish24 | Merge pull request #1262 from UV-CDAT/update_master … |  df355f9 |
| dlonie | Add checkFuzzyBoolean representation. … | 63f64f1 |
| dlonie | Add vcsvtk.Pipeline interface, ported VTKPlots.plot2D to use it. … | 7416eab |
| dlonie | Add vectorpipeline plots to vcsvtk submodule. | 8090db5 |
| dlonie | Add Pipeline1D. |  5798113 |
| doutriaux1 | Merge pull request #1229 from dlonie/vtk-refactor … |  538cf4b |


@dlonie's should all be the VTK refactor (along with @doutriaux1's), and it looks like yours are a merge to master from release previously.

**Comment by doutriaux1** [comment]
@aashish24 I think we're good.

**Comment by dlonie** [comment]
LGTM, tests pass.

+1

**Comment by aashish24** [comment]
Thanks guys 😊

**Comment by doutriaux1** [comment]
@aashish24 just approved a branch from @jbeezley care to add it?

**Comment by huiwanpnnl** [comment]
I can do it afterwards.. no worries...this is @aashish24

**Pull request merged**
