### PR TITLE
Dummy change to test GitRobot + Buildbot

### PR DESCRIPTION
**Pull request by sankhesh**

### CODE REVIEW

**Comment by sankhesh** [comment]
Do: test

**Comment by kwrobot01** [comment]
*Warning*: Requests to test ignored; user lacks testing privileges:  
@sankhesh: test   

**SERVER ERROR**: project uvcdat directory not available! @sankhesh

**Comment by sankhesh** [comment]
Do: test

**Comment by kwrobot01** [comment]
**SERVER ERROR**: project uvcdat directory not available! @sankhesh

**Comment by kwrobot01** [comment]
*Error*: Failed to fetch the commit from the repository UV-CDAT/uvcdat!

**Comment by kwrobot01** [comment]
Basic content checks passed!

Branch-at: a579480292811525fc529149e23f441009cebc14  
Acked-by: @kwrobot01

**Comment by sankhesh** [comment]
Do: test

**Comment by sankhesh** [comment]
Do: test

**Comment by kwrobot01** [comment]
Testing commands handed to buildbot.

Branch-at: a579480292811525fc529149e23f441009cebc14

**Comment by sankhesh** [comment]
Do: test

**Comment by kwrobot01** [comment]
Testing commands handed to buildbot.

Branch-at: a579480292811525fc529149e23f441009cebc14

**Comment by sankhesh** [comment]
Do: test

**Comment by sankhesh** [comment]
Do: test

**Comment by kwrobot01** [comment]
Testing commands handed to buildbot.

Branch-at: a579480292811525fc529149e23f441009cebc14

**Comment by sankhesh** [comment]
Do: test

**Comment by kwrobot01** [comment]
Testing commands handed to buildbot.

Branch-at: a579480292811525fc529149e23f441009cebc14

**Comment by sankhesh** [comment]
Do: test

**Comment by kwrobot01** [comment]
Testing commands handed to buildbot.

Branch-at: a579480292811525fc529149e23f441009cebc14

**Comment by sankhesh** [comment]
Do: test

**Comment by kwrobot01** [comment]
Testing commands handed to buildbot.

Branch-at: a579480292811525fc529149e23f441009cebc14

**Comment by sankhesh** [comment]
Do: test

**Comment by kwrobot01** [comment]
Testing commands handed to buildbot.

Branch-at: a579480292811525fc529149e23f441009cebc14

**Comment by sankhesh** [comment]
Do: test

**Comment by kwrobot01** [comment]
Testing commands handed to buildbot.

Branch-at: a579480292811525fc529149e23f441009cebc14

**Comment by sankhesh** [comment]
Do: test

**Comment by kwrobot01** [comment]
Testing commands handed to buildbot.

Branch-at: a579480292811525fc529149e23f441009cebc14

**Comment by sankhesh** [comment]
Do: test

**Comment by kwrobot01** [comment]
Testing commands handed to buildbot.

Branch-at: a579480292811525fc529149e23f441009cebc14

**Comment by sankhesh** [comment]
Do: test

**Comment by kwrobot01** [comment]
Testing commands handed to buildbot.

Branch-at: a579480292811525fc529149e23f441009cebc14

**Comment by kwrobot01** [comment]
Your merge request has been queued for testing. You may view the test results on [CDash](https://open.cdash.org/index.php?compare1=63&filtercount=2&field1=buildname%2Fstring&project=UV-CDAT&field2=buildstarttime%2Fdate&showfilters=0&limit=100&compare2=83&value1=a5794802&showfeed=0&value2=20160715T125907) or [Buildbot](https://kwrobot02:8011/grid?branch=buildbot_test&category=uvcdat-expected).

Branch-at: a579480292811525fc529149e23f441009cebc14

**Comment by sankhesh** [comment]
Do: test

**Comment by kwrobot01** [comment]
Testing commands handed to buildbot.

Branch-at: a579480292811525fc529149e23f441009cebc14

**Comment by kwrobot01** [comment]
Your merge request has been queued for testing. You may view the test results on [CDash](https://open.cdash.org/index.php?compare1=63&filtercount=2&field1=buildname%2Fstring&project=UV-CDAT&field2=buildstarttime%2Fdate&showfilters=0&limit=100&compare2=83&value1=a5794802&showfeed=0&value2=20160715T231535) or [Buildbot](https://kwrobot02:8011/grid?branch=buildbot_test&category=uvcdat-expected).

Branch-at: a579480292811525fc529149e23f441009cebc14

**Comment by sankhesh** [comment]
Do: test

**Comment by kwrobot01** [comment]
Testing commands handed to buildbot.

Branch-at: a579480292811525fc529149e23f441009cebc14

**Comment by kwrobot01** [comment]
Your merge request has been queued for testing. You may view the test results on [CDash](https://open.cdash.org/index.php?compare1=63&filtercount=2&field1=buildname%2Fstring&project=UV-CDAT&field2=buildstarttime%2Fdate&showfilters=0&limit=100&compare2=83&value1=a5794802&showfeed=0&value2=20160715T231847) or [Buildbot](https://kwrobot02:8011/grid?branch=buildbot_test&category=uvcdat-expected).

Branch-at: a579480292811525fc529149e23f441009cebc14

**Comment by sankhesh** [comment]
Do: test

**Comment by sankhesh** [comment]
Do: test

**Comment by kwrobot01** [comment]
Testing commands handed to buildbot.

Branch-at: a579480292811525fc529149e23f441009cebc14

**Comment by kwrobot01** [comment]
Your merge request has been queued for testing. You may view the test results on [CDash](https://open.cdash.org/index.php?compare1=63&filtercount=2&field1=buildname%2Fstring&project=UV-CDAT&field2=buildstarttime%2Fdate&showfilters=0&limit=100&compare2=83&value1=a5794802&showfeed=0&value2=20160715T232827) or [Buildbot](https://kwrobot02:8011/grid?branch=buildbot_test&category=uvcdat-expected).

Branch-at: a579480292811525fc529149e23f441009cebc14

**Comment by sankhesh** [comment]
Do: test

**Comment by kwrobot01** [comment]
Testing commands handed to buildbot.

Branch-at: a579480292811525fc529149e23f441009cebc14

**Comment by kwrobot01** [comment]
Your merge request has been queued for testing. You may view the test results on [CDash](https://open.cdash.org/index.php?compare1=63&filtercount=2&field1=buildname%2Fstring&project=UV-CDAT&field2=buildstarttime%2Fdate&showfilters=0&limit=100&compare2=83&value1=a5794802&showfeed=0&value2=20160717T222344) or [Buildbot](https://kwrobot02:8011/grid?branch=buildbot_test&category=uvcdat-expected).

Branch-at: a579480292811525fc529149e23f441009cebc14

**Comment by kwrobot01** [comment]
Testing commands handed to buildbot.

Branch-at: a579480292811525fc529149e23f441009cebc14

**Comment by kwrobot01** [comment]
Your merge request has been queued for testing. You may view the test results on [CDash](https://open.cdash.org/index.php?compare1=63&filtercount=2&field1=buildname%2Fstring&project=UV-CDAT&field2=buildstarttime%2Fdate&showfilters=0&limit=100&compare2=83&value1=a5794802&showfeed=0&value2=20160717T222624) or [Buildbot](https://kwrobot02:8011/grid?branch=buildbot_test&category=uvcdat-expected).

Branch-at: a579480292811525fc529149e23f441009cebc14

**Comment by sankhesh** [comment]
Do: test

**Comment by kwrobot01** [comment]
Testing commands handed to buildbot.

Branch-at: a579480292811525fc529149e23f441009cebc14

**Comment by kwrobot01** [comment]
Your merge request has been queued for testing. You may view the test results on [CDash](https://open.cdash.org/index.php?compare1=63&filtercount=2&field1=buildname%2Fstring&project=UV-CDAT&field2=buildstarttime%2Fdate&showfilters=0&limit=100&compare2=83&value1=a5794802&showfeed=0&value2=20160717T225603) or [Buildbot](https://kwrobot02:8011/grid?branch=buildbot_test&category=uvcdat-expected).

Branch-at: a579480292811525fc529149e23f441009cebc14

**Comment by sankhesh** [comment]
Do: test

**Comment by kwrobot01** [comment]
*Error*: Failed to fetch the commit from the repository UV-CDAT/uvcdat!

**Comment by sankhesh** [comment]
Do: test

**Comment by kwrobot01** [comment]
*Error*: Failed to fetch the commit from the repository UV-CDAT/uvcdat!

**Comment by sankhesh** [comment]
Do: test

**Comment by kwrobot01** [comment]
*Error*: Failed to fetch the commit from the repository UV-CDAT/uvcdat:refs/check/pr/2060/heads/1:d3a169cd32075148ece32b217076033f1252b55f!

**Comment by sankhesh** [comment]
Do: test

**Comment by kwrobot01** [comment]
Basic content checks failed!

```
commit d3a169cd adds bad whitespace:
cmake.txt:24: trailing whitespace.
+if ( ${CONDA} STREQUAL "CONDA-NOTFOUND" ) 
cmake.txt:29: trailing whitespace.
+if ( ${ACTIVATE} STREQUAL "ACTIVATE-NOTFOUND" ) 

```

Changes since last check: [compare](https://github.com/UV-CDAT/uvcdat/compare/a579480292811525fc529149e23f441009cebc14...d3a169cd32075148ece32b217076033f1252b55f)

Branch-at: d3a169cd32075148ece32b217076033f1252b55f  
Rejected-by: @kwrobot01

**Comment by sankhesh** [comment]
Do: test

**Comment by kwrobot01** [comment]
*Error*: Failed to fetch the commit from the repository UV-CDAT/uvcdat:refs/check/pr/2060/heads/2:a15b40a90246c3204ad4fdff2e399a88b35bf901!

**Comment by sankhesh** [comment]
Do: test

**Comment by kwrobot01** [comment]
Basic content checks passed!

Changes since last check: [compare](https://github.com/UV-CDAT/uvcdat/compare/a579480292811525fc529149e23f441009cebc14...a15b40a90246c3204ad4fdff2e399a88b35bf901)

Branch-at: a15b40a90246c3204ad4fdff2e399a88b35bf901  
Acked-by: @kwrobot01

**Comment by sankhesh** [comment]
Do: test

**Comment by kwrobot01** [comment]
*Error*: Failed to fetch the commit from the repository UV-CDAT/uvcdat:refs/check/pr/2060/heads/3:fd98ae2ddc94ed8b14223c041bf0a9cdfae770d6!

**Comment by sankhesh** [comment]
Do: test

**Comment by kwrobot01** [comment]
Basic content checks failed!

```
commit fd98ae2d adds bad whitespace:
CMake/cdat_modules/cdat_pkg1.cmake:13: trailing whitespace.
+if (NOT ${res} EQUAL 0) 
CMake/cdat_modules/cdat_pkg1.cmake:34: new blank line at EOF.

```

Changes since last check: [compare](https://github.com/UV-CDAT/uvcdat/compare/a15b40a90246c3204ad4fdff2e399a88b35bf901...fd98ae2ddc94ed8b14223c041bf0a9cdfae770d6)

Branch-at: fd98ae2ddc94ed8b14223c041bf0a9cdfae770d6  
Rejected-by: @kwrobot01

**Comment by sankhesh** [comment]
Do: test

**Comment by kwrobot01** [comment]
Testing commands handed to buildbot.

Branch-at: fd98ae2ddc94ed8b14223c041bf0a9cdfae770d6

**Comment by kwrobot01** [comment]
Your merge request has been queued for testing. You may view the test results on [CDash](https://open.cdash.org/index.php?compare1=63&filtercount=2&field1=buildname%2Fstring&project=UV-CDAT&field2=buildstarttime%2Fdate&showfilters=0&limit=100&compare2=83&value1=fd98ae2d&showfeed=0&value2=20160717T235323) or [Buildbot](https://kwrobot02:8011/grid?branch=buildbot_test&category=uvcdat-expected).

Branch-at: fd98ae2ddc94ed8b14223c041bf0a9cdfae770d6

**Comment by sankhesh** [comment]
Do: test

**Comment by kwrobot01** [comment]
*Error*: Failed to fetch the commit from the repository UV-CDAT/uvcdat:refs/check/pr/2060/heads/5:af985439803f99c4af4f68ec8d63affb9dc47202!

**Comment by sankhesh** [comment]
Do: test

**Comment by kwrobot01** [comment]
*Error*: Failed to fetch the commit from the repository UV-CDAT/uvcdat:refs/check/pr/2060/heads/5:af985439803f99c4af4f68ec8d63affb9dc47202!

**Comment by sankhesh** [comment]
Do: test

**Comment by kwrobot01** [comment]
Basic content checks passed!

Changes since last check: [compare](https://github.com/UV-CDAT/uvcdat/compare/fd98ae2ddc94ed8b14223c041bf0a9cdfae770d6...af985439803f99c4af4f68ec8d63affb9dc47202)

Branch-at: af985439803f99c4af4f68ec8d63affb9dc47202  
Acked-by: @kwrobot01

**Comment by sankhesh** [comment]
Do: test

**Comment by kwrobot01** [comment]
Testing commands handed to buildbot.

Branch-at: af985439803f99c4af4f68ec8d63affb9dc47202

**Comment by kwrobot01** [comment]
Your merge request has been queued for testing. You may view the test results on [CDash](https://open.cdash.org/index.php?compare1=63&filtercount=2&field1=buildname%2Fstring&project=UV-CDAT&field2=buildstarttime%2Fdate&showfilters=0&limit=100&compare2=83&value1=af985439&showfeed=0&value2=20160718T001645) or [Buildbot](https://kwrobot02:8011/grid?branch=buildbot_test&category=uvcdat-expected).

Branch-at: af985439803f99c4af4f68ec8d63affb9dc47202

**Comment by sankhesh** [comment]
Do: test

**Comment by sankhesh** [comment]
Do: test

**Comment by kwrobot01** [comment]
Testing commands handed to buildbot.

Branch-at: af985439803f99c4af4f68ec8d63affb9dc47202

**Comment by kwrobot01** [comment]
Your merge request has been queued for testing. You may view the test results on [CDash](https://open.cdash.org/index.php?compare1=63&filtercount=2&field1=buildname%2Fstring&project=UV-CDAT&field2=buildstarttime%2Fdate&showfilters=0&limit=100&compare2=83&value1=af985439&showfeed=0&value2=20160718T092417) or [Buildbot](https://kwrobot02:8011/grid?branch=buildbot_test&category=uvcdat-expected).

Branch-at: af985439803f99c4af4f68ec8d63affb9dc47202

**Comment by sankhesh** [comment]
Do: test

**Comment by kwrobot01** [comment]
Basic content checks passed!

Changes since last check: [compare](https://github.com/UV-CDAT/uvcdat/compare/fd98ae2ddc94ed8b14223c041bf0a9cdfae770d6...af985439803f99c4af4f68ec8d63affb9dc47202)

Branch-at: af985439803f99c4af4f68ec8d63affb9dc47202  
Acked-by: @kwrobot01

**Comment by sankhesh** [comment]
Do: test

**Comment by kwrobot01** [comment]
Testing commands handed to buildbot.

Branch-at: af985439803f99c4af4f68ec8d63affb9dc47202

**Comment by kwrobot01** [comment]
Your merge request has been queued for testing. You may view the test results on [CDash](https://open.cdash.org/index.php?compare1=63&filtercount=2&field1=buildname%2Fstring&project=UV-CDAT&field2=buildstarttime%2Fdate&showfilters=0&limit=100&compare2=83&value1=af985439&showfeed=0&value2=20160718T092935) or [Buildbot](https://kwrobot02:8011/grid?branch=buildbot_test&category=uvcdat-expected).

Branch-at: af985439803f99c4af4f68ec8d63affb9dc47202

**Comment by sankhesh** [comment]
Do: test

**Comment by kwrobot01** [comment]
Testing commands handed to buildbot.

Branch-at: af985439803f99c4af4f68ec8d63affb9dc47202

**Comment by kwrobot01** [comment]
Your merge request has been queued for testing. You may view the test results on [CDash](https://open.cdash.org/index.php?compare1=63&filtercount=2&field1=buildname%2Fstring&project=UV-CDAT&field2=buildstarttime%2Fdate&showfilters=0&limit=100&compare2=83&value1=af985439&showfeed=0&value2=20160718T093127) or [Buildbot](https://kwrobot02:8011/grid?branch=buildbot_test&category=uvcdat-expected).

Branch-at: af985439803f99c4af4f68ec8d63affb9dc47202

**Comment by sankhesh** [comment]
Do: test

**Comment by sankhesh** [comment]
Do: test

**Pull request closed without merging**
