### PR TITLE
Update vtk proj4 9 2

### PR DESCRIPTION
**Pull request by danlipsa**
This is using a VTK branch not commited into master so do not merge yet.

### CODE REVIEW

**Comment by danlipsa** [comment]
https://github.com/UV-CDAT/uvcdat-testdata/pull/108

**Comment by danlipsa** [comment]
https://github.com/Kitware/VTK/pull/29

**Comment by danlipsa** [comment]
@doutriaux1 Is cont-int/LLNL/Linux-RH6 (FULL) working? Because it says: 'checking whether the C compiler works...  no' I would think it is a problem with the machine. Are there any mac buildbots left?

**Comment by danlipsa** [comment]
@aashish24 @doutriaux1 Please review. I think this is a step in the right direction with aeqd and no other projection seems worst than it was. Some of the aeqd tests look a lot better some don't. Given that aeqd was completely broken in the past I would say to merge this and do another pass through the aeqd tests in the future. I think we can improve how they look.

**Comment by danlipsa** [comment]
@aashish24 We need to merge proj4 upgrade branch into VTK first before we can merge this. See
https://gitlab.kitware.com/vtk/vtk/merge_requests/1207

**Comment by doutriaux1** [comment]
@danlipsa looks like xfvb needs a restart on RH6 (FULL) and bots are down after one build as usual...

**Comment by doutriaux1** [comment]
@danlipsa are you using Kitware/VTK? I thought we were supposed to use UV-CDAT/VTK so we do not have to wait for Kitware/VTK.

**Comment by aashish24** [comment]
> @aashish24 We need to merge proj4 upgrade branch into VTK first before we can merge this. See
> https://gitlab.kitware.com/vtk/vtk/merge_requests/1207

Reviewed it and +2 it. @doutriaux1 once this goes into master, we will merge master into UVCDAT/VTK:uvcdat-master.

**Comment by danlipsa** [comment]
@aashish24 I get conflicts merging VTK master into uvcdat-master. I'll let you do this merge as you have managed the commits into both. @aashish24 @doutriaux1 In the future I would suggest always merge things into VTK master before we use a certain SHA into uvcdat. Having a separate branch and merging things into both VTK master and uvcdat-master can lead to conflicts and makes it more difficult to update VTK. Note that ParaView used a separate branch in the past but it got rid of it and now it uses directly a certain SHA from VTK.
If there are no changes in uvcdat that are not merged in VTK I would suggest updating uvcdat-master to VTK master.

**Comment by doutriaux1** [comment]
@danlipsa things got really bad on my ubunut see:
https://open.cdash.org/testDetails.php?test=420823075&build=4239089

**Comment by danlipsa** [comment]
@doutriaux1 this looks like the old proj4. Make sure the VTK got updated: remove VTK-prefix and build/VTK-build

**Comment by aashish24** [comment]
> @aashish24 I get conflicts merging VTK master into uvcdat-master. I'll let you do this merge as you have managed the commits into both.

You got merge conflict because I pull in one fix from UV-CDAT to VTK. I will fix the conflict as its a easy one. We pretty much have all the changes in VTK master except the FFPEG one. If we keep merging changes to VTK propoer, we won't have these conflicts.

**Comment by doutriaux1** [comment]
I'm pretty sure it was a fresh build, but I will double check

**Comment by danlipsa** [comment]
@aashish24 OK, so after we merge everything into VTK we can just update uvcdat-master to the latest VTK isn't it?

**Comment by danlipsa** [comment]
@doutriaux1 I will try running the tests on my mac as well.

**Comment by aashish24** [comment]
> aashish24 OK, so after we merge everything into VTK we can just update uvcdat-master to the latest VTK isn't it?

Right that is the idea. The only part thats not in VTK proper is the FFMPEG code. The reason I am afraid to bring it in VTK is because I am not 100% sure why the code was written the way it was written but somehow was working. I guess I will take the risk and push a VTK PR and see what happens. In the mean time, what I am going to do is reset UVCDAT/uvcdat-master to VTK master and bring in my change on top of it.

**Comment by danlipsa** [comment]
@doutriaux1 @aashish24 All tests pass on my ubuntu, also cdat-web works. I'll run the tests at home on my mac.

**Comment by doutriaux1** [comment]
@danlipsa running this one more time on my mac just to be sure.

**Comment by danlipsa** [comment]
@doutriaux1 I run this on my mac. Looks good besides expected (and anoying) small differences in some aeqd new images. vcs_mintics has more differences but think this is a test @chaosphere2112 just added. I added the file on linux as it was missing.

**Comment by danlipsa** [comment]
@aashish24 I can remove the gdal stuff. Do need that saved in a patch file?

**Comment by aashish24** [comment]
> @aashish24 I can remove the gdal stuff. Do need that saved in a patch file?

Yes, thanks. A patch would work (just in case).

**Comment by danlipsa** [comment]
@aashish24 Here is the patch:
[gdal-patch.txt](https://github.com/UV-CDAT/uvcdat/files/163788/gdal-patch.txt)

**Comment by danlipsa** [comment]
@doutriaux1 @aashish24 This is ready to merge!

**Comment by aashish24** [comment]
LGTM :+1:

**Pull request merged**
