### PR TITLE
issue1538 durack1 update Cython 0.23.3 to 0.23.4

### LINKED ISSUE #1538: Update Cython to 0.23.3
We are a couple of patches behind Cython latest (0.22.1 vs 0.23.2).

@doutriaux1 want to assign me as a 2.4 milestone?

### PR DESCRIPTION
**Pull request by durack1**
Fix #1538 - Update Cython 0.23.3 to 0.23.4

### CODE REVIEW

**Comment by doutriaux1** [comment]
failed on mc full

**Comment by durack1** [comment]
@doutriaux1 looks to me like [it never even got to `ctest`](http://aims4.llnl.gov:9981/master/macbot2.llnl.gov:9982/UV-CDAT/uvcdat/53876051b64b9966984561541a23642eadbe3f43/make__-j4)

It seems your `--old-and-unmanageable` kludge tripped things over:
```
CMake Error at /Users/doutriaux1/bot/build/Cython-prefix/src/Cython-stamp/Cython-install.cmake:56 (message):
  CTEST_FULL_OUTPUT
   Command failed: 1
   '/Users/doutriaux1/bot/build/install/bin/python' 'setup.py' 'install' '--old-and-unmanageable'
   From /Users/doutriaux1/bot/build/Cython-prefix/src/Cython-stamp/Cython-install-out.log
  -------------------------------------------------
  Unable to find pgen, not compiling formal grammar.
  -------------------------------------------------
   From /Users/doutriaux1/bot/build/Cython-prefix/src/Cython-stamp/Cython-install-err.log
  -------------------------------------------------
  usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: setup.py --help [cmd1 cmd2 ...]
     or: setup.py --help-commands
     or: setup.py cmd --help
  error: option --old-and-unmanageable not recognized
```

**Comment by durack1** [comment]
@doutriaux1 looks like 1 of the 2 `crunchy` issues is the [UV-CDAT logo on the test file and not the baseline](https://open.cdash.org/testDetails.php?test=386882585&build=4080823)

**Comment by durack1** [comment]
@doutriaux1 does [`cython_deps.cmake`](https://github.com/UV-CDAT/uvcdat/blob/master/CMake/cdat_modules/cython_deps.cmake#L1) need `setuptools_pkg` added?

**Comment by durack1** [comment]
@doutriaux1 looks like the 'macbots' are all hanging.. Wanna reboot/refresh them?

**Comment by durack1** [comment]
@doutriaux1 looks like all the `macbots` have hung, wanna reboot/refresh them?

**Comment by durack1** [comment]
@doutriaux1 looks like all the `macbots` have hung, wanna reboot/refresh them?

**Comment by durack1** [comment]
@doutriaux1 this now looks good, only [`crunchy` failed and the error is the standard](https://open.cdash.org/viewTest.php?onlyfailed&buildid=4085633):
```
The following tests FAILED:
	 88 - vcs_test_background_mode_rotate (Failed)
```

**Pull request merged**
