### PR TITLE
Issue 1734 non contiguous levs

### PR DESCRIPTION
**Pull request by doutriaux1**
@sankhesh @aashish24 @chaosphere2112 please review

### CODE REVIEW

**Comment by doutriaux1** [comment]
goes with: https://github.com/UV-CDAT/uvcdat-testdata/pull/95

**Comment by aashish24** [comment]
@doutriaux1 this will some time to review.. more than minor change of code.. 

@danlipsa it would be nice if you can look into this branch as well.

**Comment by doutriaux1** [comment]
@aashish24 it is really minor, I just unified the function call, it was the same function called from isofill/boxfill/meshfill so I moved it to the mother class instead.

**Comment by aashish24** [comment]
ah..thanks @doutriaux1 looking into it..

**Comment by aashish24** [comment]
@doutriaux1 looks good to me.. crunchy is having some serious issues.. can you have a look at it? 

Thanks

**Pull request merged**
