### PR TITLE
Add nc_del_attr to Cdunif to allow attribute removal in netCDF files

### PR DESCRIPTION
**Pull request by dnadeau4**
Allow to delete Global Attributes or Variable attributes when calling del(f.attribute) or delattr(f, attribute).   Cdunifmodule "set_attribute" function is called with a null pointer "0x00" which is different than Py_None.   Without this change deleting an attribute with a "del" or "delattr" call was crashing the program with a segmentation fault.

### CODE REVIEW

**Comment by doutriaux1** [comment]
@dnadeau4 can you please add a test case? Thanks!
```python
import cdms2, MV
f = cdms2.open("test.nc","w")
s = MV2.ones((20,20))
s.id="test"
s.test_attribute = "some variable attribute"
f.test_attribute = "some file attribute"
f.write(s)
f.close()
f = cdms2.open("test.nc","r+")
del(f.some_attribute)
s=f["test"]
del(s.some_attribute)
f.close()
f = cdms2.open("test.nc")
assert(hasattr(f,"some_attribute") is False)
s=f["test"]
assert(hasattr(s,"some_attribute") is False)
```

**Comment by dnadeau4** [comment]
I added the test.

**Comment by durack1** [comment]
@dnadeau4 it would be a good idea to merge these changes into the existing branch `issue1579_durack1_UpdateNetcdf4.3.3.1To4.4.0` - this branch includes the new `netcdf 4.4.0` final release..

**Comment by doutriaux1** [comment]
@durack1 totally different issue, one issue per branch. The NetCDF4 needs testing first.

**Comment by durack1** [comment]
@doutriaux1 not sure I agree with you. In `4.4.0` https://github.com/Unidata/netcdf-c/issues/128 is fixed, and these changes will likely impact the operation of `Cdunif`

**Comment by dnadeau4** [comment]
@doutriaux1 How come you did not merge it yet?  I did add the test and I tried it.    Thanks for providing a template.

**Comment by doutriaux1** [comment]
my bad, didn't see that you had a test in!

**Pull request merged**
