### PR TITLE
Orthographic

### PR DESCRIPTION
**Pull request by danlipsa**

### CODE REVIEW

**Comment by danlipsa** [comment]
Data in:
https://github.com/UV-CDAT/uvcdat-testdata/pull/137

**Comment by danlipsa** [comment]
@doutriaux1 @aashish24 Please review. Note that labels are wrong for mercator and orthographic projections as proj4 returns infinity for certain combination of values. We can fix the labels in a different PR.

**Comment by aashish24** [comment]
@danlipsa this is great. If is possible, can we fix the legend as well in the same branch since in the new baselines legend look more wrong now.

**Comment by danlipsa** [comment]
@aashish24 @doutriaux1 Looking at the code, I would fix the tics/labels in a more general way, fixing it in a simple/specific way is not easy to do. The problem is that the code assumes that the outline of the data in lon/lat space results in an outline in projected space. This is not true for mercator and orthographic projections. I want to fix this by getting the proper outline - where data is not projected to infinity and passing that to the vcs routine that computes the location of the ticks/labels. I think this would affect many baselines so I would do it in a separate PR.

**Comment by danlipsa** [comment]
@aashish24 @doutriaux1 This also seems to be a big/disruptive change, so we have to decide if we want it for this release.

**Comment by danlipsa** [comment]
@aashish24 @doutriaux1 I'll look some more. Maybe I can do something simple for mercator. Oblique orthographic is a tough case, as the outline is not on geodesics.

**Comment by danlipsa** [comment]
For future reference:
an oblique orthographic projection:
test_vcs_boxfill_orthographic
the points hidden from the lon / lat data
hidden

**Comment by aashish24** [comment]
> Maybe I can do something simple for mercator.

Sounds good to me. 

We can handle oblique one in the next PR.

**Comment by danlipsa** [comment]
@aashish24 @doutriaux1 I fixed the labels for mercator and the labels for orthographic look a lot better. There are also some aeqd labels that were fixed in the process. Please review - you'll have to download the baselines to see all of them: 49 changed :smile:

**Comment by doutriaux1** [comment]
@danlipsa ubuntu results at: https://open.cdash.org/viewTest.php?onlyfailed&buildid=4385602

```
The following tests FAILED:
	 49 - test_vcs_boxfill_orthographic_45 (Failed)
	 50 - test_vcs_boxfill_orthographic_90 (Failed)
	 87 - test_vcs_background_mode_rotate (Failed)
	286 - test_vcs_basic_isofill_masked_aeqd_proj (Failed)
	362 - test_vcs_isoline_width_stipple (Failed)
	460 - test_vcs_line_patterns (Failed)
```

**Comment by danlipsa** [comment]
>   49 - test_vcs_boxfill_orthographic_45 (Failed)
>    50 - test_vcs_boxfill_orthographic_90 (Failed)
I added the missing test file

     87 - test_vcs_background_mode_rotate (Failed)
seg fault - not sure what this is.
    286 - test_vcs_basic_isofill_masked_aeqd_proj (Failed)
this seems to have the old baseline.
    362 - test_vcs_isoline_width_stipple (Failed)
    460 - test_vcs_line_patterns (Failed)
the stipples look like they are shifted. However on both my linux and my mac the are like in the baselines. Should we add an alternate baseline? I think that would be ok as long as this shifting is deterministic and we have only two versions.

**Comment by danlipsa** [comment]
@doutriaux1 All tests pass on both my mac and my linux box.

**Comment by doutriaux1** [comment]
@danlipsa I updated the branch, but I'm not sure anything is going to pass any longer since @aashish24 merged his vector branch in. Do you mind double checking the baselines? I'm rebuilding this from scratch on my Ubuntu.

**Comment by danlipsa** [comment]
@doutriaux1 I will rebase and push a new version.

**Comment by doutriaux1** [comment]
@danlipsa see:   https://open.cdash.org/viewTest.php?onlydelta&buildid=4390366
It was probably ran before you get your updated baselines in. Let me know when you want me to re-run ctest.

**Comment by doutriaux1** [comment]
@danlipsa ok now I get: https://open.cdash.org/viewTest.php?onlyfailed&buildid=4390515

I don't think any failure is related to your branch any more, correct?

**Comment by danlipsa** [comment]
@doutriaux1 That is right. I just merged a fix for test_vcs_png_window_resize. This should be ready to merge. Make sure you merge the data as well.

**Comment by danlipsa** [comment]
Or I can merge if you prefer.

**Pull request merged**
