### PR TITLE
Updated VTK to use current uvcdat-master

### PR DESCRIPTION
**Pull request by aashish24**
uvcdat-master is synced up with VTK/master

### CODE REVIEW

**Comment by aashish24** [comment]
@danlipsa you can merge your branches into this branch.

**Comment by danlipsa** [comment]
@aashish24 Do you need to update uvcdat-master to point to the latest VTK or should I do that?

**Comment by doutriaux1** [comment]
@aashish24 , @danlipsa is right uvcdat-master is 22 commits ahead, 2295 commits behind Kitware:master.

**Comment by doutriaux1** [comment]
@aashish24 looks like https://github.com/UV-CDAT/uvcdat/compare/update_vtk merged into `master` not `uvcdat-master`, should we use `master` from now on, sounds like a better idea no?

**Comment by doutriaux1** [comment]
actually master is 3645 commits behind Kitware:master so I'm lost I'm not sure what you did @aashish24

**Comment by aashish24** [comment]
@doutriaux1 @danlipsa sorry since I didn't force push the uvcdat-master, when my script pushed it, it got rejected and I didn't see that. the uvcdat-master in UVCDAT/vtk should be on correct sha now. 

The reason, we don't want to use master because we want consistency across all repos (use uvcdat-master) or else if other repo's master get's updated things may break.

**Comment by aashish24** [comment]
@doutriaux1 @danlipsa this should be ready for review.

**Comment by doutriaux1** [comment]
thanks @aashish24

**Comment by aashish24** [comment]
@doutriaux1 I updated (rebased) this branch to trigger rebuild.

**Comment by danlipsa** [comment]
@aashish24 Would it make sense to use a certain SHA1 instead of uvcdat-master? This way you could go back to a previous uvcdat SHA-1 and have reproducible behavior. With current behavior you always use uvcdat-master, whatever that may be at the moment.

**Comment by doutriaux1** [comment]
@danlipsa we only use uvcdat-master for in-between releases, when we release we point to a sha1or more exactly to a tag point (same thing anyway)

**Comment by danlipsa** [comment]
I'll update VTK in the update proj4 PR, so I'll close this one.

**Comment by danlipsa** [comment]
@doutriaux1 I agree that we have reproducibility for releases because we tag external modules such as VTK. However in between releases we don't as, for VTK, we always point to the latest VTK master. This is something that we may want to add in the future. I don't think it will cost us anything. We just point to a certain SHA1 instead of the top of a branch.

**Pull request closed without merging**
