### PR TITLE
Fix travis

### PR DESCRIPTION
**Pull request by doutriaux1**
work in progress, mainly for @danlipsa

### CODE REVIEW

**Comment by danlipsa** [comment]
@doutriaux1 Any change we get the hdf5 fix in master first? Which is the commit? I can try it out. Thanks!

**Comment by doutriaux1** [comment]
@danlipsa this is ready for Linux, I need to tweak for Mac.

**Comment by doutriaux1** [comment]
@danlipsa it runs on Linux and Mac now. We can improve from here

**Comment by aashish24** [comment]
@doutriaux1 can we update this branch sometime soon? I talked to Dan and I believe this branch has a bug fix which is not travis related. @danlipsa can you elaborate?

**Comment by doutriaux1** [comment]
this branch is dead it was merged as part of the viridis default colormap. Closing.

**Comment by aashish24** [comment]
thanks @doutriaux1 I didn't see that but I didn't track viridis as closely since you and @danlipsa were having too much fun!

**Pull request closed without merging**
