### PR TITLE
Issue885 durack1 numpy192

### PR DESCRIPTION
**Pull request by durack1**
@doutriaux1 @aashish24 let's see if this passes the travis test and merge it as a 2.2 milestone

### CODE REVIEW

**Comment by doutriaux1** [comment]
this one breaks:
variable.mean()
I'm trying to figure out why exactly. I think it's the way we inherit from numpy...
```
In [2]: s.mean()
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-2-115fb75d3a77> in <module>()
----> 1 s.mean()

/export/doutriaux1/build/install/lib/python2.7/site-packages/numpy/ma/core.pyc in mean(self, axis, dtype, out)
   4774         """
   4775         if self._mask is nomask:
-> 4776             result = super(MaskedArray, self).mean(axis=axis, dtype=dtype)
   4777         else:
   4778             dsum = self.sum(axis=axis, dtype=dtype)

/export/doutriaux1/build/install/lib/python2.7/site-packages/numpy/core/_methods.pyc in _mean(a, axis, dtype, out, keepdims)
     67     if isinstance(ret, mu.ndarray):
     68         ret = um.true_divide(
---> 69                 ret, rcount, out=ret, casting='unsafe', subok=False)
     70     elif hasattr(ret, 'dtype'):
     71         ret = ret.dtype.type(ret / rcount)

/export/doutriaux1/build/install/lib/python2.7/site-packages/numpy/ma/core.pyc in __array_wrap__(self, obj, context)
   2892                 return masked
   2893             else:
-> 2894                 result._mask = m
   2895                 result._sharedmask = False
   2896         #....

AttributeError: 'numpy.ndarray' object has no attribute '_mask'

In [3]: numpy.ma.mean(s)
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-3-4b33150f59ce> in <module>()
----> 1 numpy.ma.mean(s)

/export/doutriaux1/build/install/lib/python2.7/site-packages/numpy/ma/core.pyc in __call__(self, a, *args, **params)
   6080         method = getattr(a, method_name, None)
   6081         if method is not None:
-> 6082             return method(*args, **params)
   6083         # Still here ? Then a is not a MaskedArray
   6084         method = getattr(MaskedArray, method_name, None)

/export/doutriaux1/build/install/lib/python2.7/site-packages/numpy/ma/core.pyc in mean(self, axis, dtype, out)
   4774         """
   4775         if self._mask is nomask:
-> 4776             result = super(MaskedArray, self).mean(axis=axis, dtype=dtype)
   4777         else:
   4778             dsum = self.sum(axis=axis, dtype=dtype)

/export/doutriaux1/build/install/lib/python2.7/site-packages/numpy/core/_methods.pyc in _mean(a, axis, dtype, out, keepdims)
     67     if isinstance(ret, mu.ndarray):
     68         ret = um.true_divide(
---> 69                 ret, rcount, out=ret, casting='unsafe', subok=False)
     70     elif hasattr(ret, 'dtype'):
     71         ret = ret.dtype.type(ret / rcount)

/export/doutriaux1/build/install/lib/python2.7/site-packages/numpy/ma/core.pyc in __array_wrap__(self, obj, context)
   2892                 return masked
   2893             else:
-> 2894                 result._mask = m
   2895                 result._sharedmask = False
   2896         #....

AttributeError: 'numpy.ndarray' object has no attribute '_mask'
```

**Comment by durack1** [comment]
Glad you have the test cases in place.. Otherwise we'd be in a bit of trouble with these updates and PRs..

**Comment by durack1** [comment]
@doutriaux1 I note that numpy 1.9.2rc1 is now out.. What is the timeline you'd expect to get this updated? If it's helpful I'll keep and eye on the 1.9.2 releases and update sources when the final release is available

**Comment by durack1** [comment]
@doutriaux1 1.9.2 is out, so sources have been updated..

**Comment by durack1** [comment]
@doutriaux1 this is tripping things over more than before - it seems like cython-numpy interactions have changed.. Certainly a 2.3+ item..

**Comment by durack1** [comment]
@doutriaux1 want to label this a 2.3 milestone?

**Comment by aashish24** [comment]
@durack1 done@

**Comment by aashish24** [comment]
@durack1 @doutriaux1 can we close this merge request?

**Pull request closed without merging**
