### PR TITLE
System python

### PR DESCRIPTION
**Pull request by dlonie**
@jbeezley @aashish24 @doutriaux1 

This branch is an update of @cjh1's branch to add CDAT_USE_SYSTEM_PYTHON. I've tested it out locally and it looks like things are working, but it should really get some broader testing before merging (esp. on macs, and the ESMF tests, which always fail for me).

### CODE REVIEW

**Comment by dlonie** [comment]
Merged master in and fixed up some tests.

After merging master in, a few tests are failing due to a missing UVCDAT logo. Not sure what happened there?

**Comment by doutriaux1** [comment]
@aashish24 is everything that went into 2.1.0 is in master? I thought you said some fixes went directly to release but not master. Am I mistaken?

**Comment by aashish24** [comment]
Everything that is in release is in  master. The failures may be related to a missing data branch. 

let's try to get the system python merge in. I need it badly for the next week.

**Comment by aashish24** [comment]
@dlonie can you resolve the conflict and push again. I would like to get it merged today. I will push a fix for the failing images.

**Comment by dlonie** [comment]
Will do.

**Comment by dlonie** [comment]
Updated -- ctest results here: https://www.cdash.org/buildSummary.php?buildid=3655532

The build failures are for contributed packages. Looks like they might need to be patched upstream?

**Comment by aashish24** [comment]
no they are failiing because on your system your esmf is not built or has some issue with fortran. Don't worry about those. Looks like all other ones are failing because of logo. @doutriaux1 that should be the this branch. Can we merge this one please?

**Comment by doutriaux1** [comment]
@aashish24 will try it today. Did you close it by accident?

**Comment by doutriaux1** [comment]
oh I see the other PR, nevermind

**Pull request closed without merging**
