### PR TITLE
All vcs docstrings updated

### PR DESCRIPTION
**Pull request by chaosphere2112**
After much git-foo, this is now ready to be examined and merged.

### CODE REVIEW

**Comment by danlipsa** [comment]
@chaosphere2112 @embrown Please fix the buildbot errors above.

**Comment by chaosphere2112** [comment]
Do: check

**Comment by embrown** [comment]
Do: check

**Comment by chaosphere2112** [comment]
Do: check

**Comment by doutriaux1** [comment]
superseded by #2117

**Pull request closed without merging**
