### PR TITLE
System dependent outline

### PR DESCRIPTION
**Pull request by danlipsa**

### CODE REVIEW

**Comment by danlipsa** [comment]
Baselines changes in:
https://github.com/UV-CDAT/uvcdat-testdata/pull/150

**Comment by danlipsa** [comment]
@doutriaux1 @aashish24 This fixes the system dependent showing of the top/bottom line for the outline. This was caused by the parallel projection parallelepiped having the same coordinates as the dataset outline. There is still system dependent label placement for isofill/isoline. Please review.

**Comment by danlipsa** [comment]
@doutriaux1 @aashish24 The following tests fail on mac and linux - I have alternate baselines only for isofill/isoline + labels.
Linux
28 tests failed

Total Test time (real) =  58.98 sec

The following tests FAILED:
	 13 - testWrite (Failed)
	 62 - test_vcs_read_old_scr_2 (Failed)
	 73 - test_vcs_verify_boxfill_basics (Failed)
	121 - test_vcs_boxfill_decreasing_latitude (Failed)
	122 - test_vcs_meshfill_no_wrapping (Failed)
	413 - test_vcs_isofill_level0 (Failed)
	414 - test_vcs_isofill_level1 (Failed)
	415 - test_vcs_isofill_level2 (Failed)
	469 - test_vcs_matplotlib_colormap (Failed)
	549 - dv3d_vector_test (Failed)
	550 - dv3d_slider_test (Failed)
	551 - Hovmoller_volume_test (Failed)
	552 - dv3d_volume_test (Failed)
	553 - dv3d_constituents_test (Failed)
	554 - dv3d_surface_test (Failed)
	555 - dv3d_hovmoller_test (Failed)
	580 - cdms2_test_createcopy_lose_dtype (Failed)
	581 - CDMS_Test_01 (Failed)
	582 - CDMS_Test_02 (Failed)
	583 - CDMS_Test_03 (Failed)
	584 - CDMS_Test_04 (Failed)
	590 - CDMS_Test_10 (Failed)
	598 - CDMS_Test_18 (Failed)
	599 - CDMS_Test_20 (Failed)
	602 - CDMS_Test_write_compressed (Failed)
	606 - CDMS_Test_pack (Failed)
	609 - CDMS_Test_write_extended_dimension (Failed)
	610 - CDMS_Test_del_attributes (Failed)

**Comment by aashish24** [comment]
@danlipsa the changes looks reasonable to me and looke like you deleted the extra baselines as they are no longer needed?

**Comment by danlipsa** [comment]
@aashish24 @doutriaux1 Indeed, the extra baseline is no longer needed for that extra line on the top. We still need an extra baseline for isoline/isofill + labels. I am not sure why we get different label position on different platform.

**Comment by danlipsa** [comment]
These are the mac os x failed tests:
26 tests failed

The following tests FAILED:
	  3 - testMPIGrid (Failed)
	  4 - testAccuracy (Failed)
	  5 - testMarvel (Failed)
	  6 - testUnits (Failed)
	  7 - testRaynaud (Failed)
	  8 - testDateline (Failed)
	  9 - testEsmfInit4Pes (Failed)
	 17 - testMpi10Pes (Failed)
	 18 - testRemoteGet8Pes (Failed)
	 20 - testConserv (Failed)
	 21 - testEsmfVsLibcf (Failed)
	 22 - testEsmfInterface1 (Failed)
	 23 - testEsmfInterface2Pes (Failed)
	 24 - testDistArray6Pes (Failed)
	 25 - testGhostedDistArray6Pes (Failed)
	 26 - testEsmfGridToMeshRegridCsrv (Failed)
	 28 - testEsmf3DSmallesmf2Pes (Failed)
	 31 - testEsmfSmall2Pes (Failed)
	 32 - testEsmfSmall4Pes (Failed)
	 33 - testEsmfSmall8Pes (Failed)
	 35 - testTasRegrid2Pes (Failed)
	 46 - testEsmfSalinity2Pes (Failed)
	 47 - testEsmfSalinity4Pes (Failed)
	 48 - testEsmfSalinity8Pes (Failed)
	 52 - testDistSrc4Pes (Failed)
	 88 - test_vcs_verify_boxfill_basics (Failed)

**Comment by danlipsa** [comment]
Do: test

**Pull request merged**
