### PR TITLE
Conda build

### PR DESCRIPTION
**Pull request by doutriaux1**
@aashish24 @sankhesh @danlipsa @chaosphere2112 @dnadeau4 

This is ready and passes on my computers. But let's carefully review baselines changes at: https://github.com/UV-CDAT/uvcdat-testdata/pull/142

### CODE REVIEW

**Comment by aashish24** [comment]
@doutriaux1 I will have a detailed look at it today.

**Comment by sankhesh** [comment]
**Buildbot dashboard**

[Gitlab](https://gitlab.kitware.com/UV-CDAT/uvcdat-mirror/merge_requests/2258#note_118980)

[CDash](https://open.cdash.org/index.php?compare1=63&filtercount=2&field1=buildname%2Fstring&project=UV-CDAT&field2=buildstarttime%2Fdate&showfilters=0&limit=100&compare2=83&value1=ce4c96af&showfeed=0)

**Comment by aashish24** [comment]
@sankhesh looks like conda is missing on the shell.

**Comment by sankhesh** [comment]
@aashish24 Yes, it was missing for the earlier builds.

Look at the latest one.

**Comment by sankhesh** [comment]
@doutriaux1 What is the path to `conda` on crunchy?

**Comment by aashish24** [comment]
thanks @sankhesh On karma right? its building now.

**Comment by doutriaux1** [comment]
@sankhesh it should be in my ${HOME}/anaconda2/bin/conda

**Comment by chaosphere2112** [comment]
@doutriaux1 Building now

**Comment by doutriaux1** [comment]
i merge master in, I'm updating the baselines for you vcsaddons.

**Comment by chaosphere2112** [comment]
@doutriaux1 @aashish24 Passes tests for me, I'm going to merge.

**Comment by stefraynaud** [comment]
I successfully installed uvcdat using conda on a supercomputer where I haven't been able to do it for years using cmake. So will the conda system be the prefered way to install uvcdat in the future?

**Comment by williams13** [comment]
Yes.

Best regards,
Dean

**Comment by aashish24** [comment]
> I successfully installed uvcdat using conda on a supercomputer where I haven't been able to do it for years using cmake. So will the conda system be the prefered way to install uvcdat in the future?

@stefraynaud cheers :tada:  yes, conda is the preferred way for installation for the end-users. Also I would like to point out that conda is a package management system and cmake is the build system. Underneath conda, you are still using make and cmake for individual packages. 

I am curious if you were able to use system MPI for your supercomputer?

**Comment by aashish24** [comment]
> I am curious if you were able to use system MPI for your supercomputer?

If not, I am wondering if you can point mpi4py to use system MPI. It should be possible but may require some manual work.

**Comment by doutriaux1** [comment]
@aashish24 mpi4py states:
```
Install

Once you have a working MPI implementation and the mpicc compiler wrapper is on your search path, you can install this package
```
so for system mpi you probably will need to install mpi4py in your conda environment after the fact.

**Comment by doutriaux1** [comment]
we will be providing builds against openmpi though.

**Comment by aashish24** [comment]
> @aashish24 mpi4py states:

@doutriaux1 that's what I was thinking too but this would be manual process as I stated.

**Pull request merged**
