### PR TITLE
Fixed inconsistent test names and other related issues

### PR DESCRIPTION
**Pull request by aashish24**
From now on, we will follow this naming convention
1) test_vcs --> test vcs code
2) test_cdms --> test cdms IO code
3) test_genutil --> test utility code

### CODE REVIEW

**Comment by aashish24** [comment]
@UV-CDAT/developers its not ready for review yet. I am just posting it here so that you know its coming soon + plus I need to look at the diff carefully (how github is showing it).

**Comment by aashish24** [comment]
Also, I may push sorting as different branch since I had to update my branch with latest changes which was little tricky.

**Comment by aashish24** [comment]
data: https://github.com/UV-CDAT/uvcdat-testdata/pull/121

**Comment by aashish24** [comment]
* This branch fixes few issues mainly related naming inconsistencies 
* I have done partial sorting of names but will push another branch to finalize that

I would like this to be merged to master asap so that I can avoid the conflict again if possible. 

@doutriaux1 @danlipsa

**Comment by aashish24** [comment]
@danlipsa @chaosphere2112 I believe @doutriaux1 is out. Could you two
please review it?

**Comment by danlipsa** [comment]
LGTM.

**Pull request merged**
