### PR TITLE
Vcs2d interactions updated

### PR DESCRIPTION
**Pull request by aashish24**

### CODE REVIEW

**Comment by aashish24** [comment]
@chaosphere2112 it seems that you may not have the developement hooks setup correctly? I fixed few things (whitespace, end of line, file size issues etc). Did you run SetupForDevelopement.sh script?

**Comment by aashish24** [comment]
@chaosphere2112 these are the tests failing:
	298 - vcs_addons_preview_2x2 (Failed)
	299 - vcs_addons_test_12_plot_one_leg_per_row (Failed)
	300 - vcs_addons_test_12_plot_one_leg_per_row_right (Failed)
	301 - vcs_addons_test_EzTemplate_12_plots_margins_thickness (Failed)
	302 - vcs_addons_test_EzTemplate_12_plots_legd_direction (Failed)
	303 - vcs_addons_test_EzTemplate_12_plots_mix_glb_local (Failed)
	304 - vcs_addons_test_EzTemplate_12_plots_spacing (Failed)
	306 - Hovmoller_volume_test (OTHER_FAULT)
	307 - dv3d_vector_test (OTHER_FAULT)
	308 - dv3d_slider_test (OTHER_FAULT)
	309 - dv3d_volume_test (OTHER_FAULT)
	310 - dv3d_surface_test (OTHER_FAULT)
	311 - dv3d_constituents_test (OTHER_FAULT)
	312 - dv3d_hovmoller_test (OTHER_FAULT)

**Comment by aashish24** [comment]
With my latest fix: only these now:
298 - vcs_addons_preview_2x2 (Failed)
299 - vcs_addons_test_12_plot_one_leg_per_row (Failed)
300 - vcs_addons_test_12_plot_one_leg_per_row_right (Failed)
301 - vcs_addons_test_EzTemplate_12_plots_margins_thickness (Failed)
302 - vcs_addons_test_EzTemplate_12_plots_legd_direction (Failed)
303 - vcs_addons_test_EzTemplate_12_plots_mix_glb_local (Failed)
304 - vcs_addons_test_EzTemplate_12_plots_spacing (Failed)

**Comment by aashish24** [comment]
With my latest fix, all of the tests are passing now. Merging it.

**Comment by chaosphere2112** [comment]
@aashish24 I do on my work computer, but not my personal, I'd wager. Thanks for merging!

**Pull request merged**
