### PR TITLE
Cmake find activate

### PR DESCRIPTION
**Pull request by doutriaux1**
@danlipsa please review and merge that fixes aeq

### CODE REVIEW

**Comment by doutriaux1** [comment]
goes with https://github.com/UV-CDAT/uvcdat-testdata/pull/144

**Comment by aashish24** [comment]
@doutriaux1 what is activate needs?

**Comment by doutriaux1** [comment]
@aashish24 what's your question exactly?

**Comment by aashish24** [comment]
nm @doutriaux1

**Pull request merged**
