### PR TITLE
BUG: proj4 over option causes problems with polar projections

### PR DESCRIPTION
**Pull request by danlipsa**
On certain machines, +over option to proj4 results in wrong
projections. It is not clear why there is a difference between different
computers - we have seen this behavior on both unix and mac. +over
does not wrap points outside of -180, 180. This is not necessary for
polar projections so we remove this option in that case.

### CODE REVIEW

**Comment by danlipsa** [comment]
https://github.com/UV-CDAT/uvcdat-testdata/pull/100

**Comment by doutriaux1** [comment]
@danlipsa THANKS! I will do a bit of testing for lambert as well, maybe it's better to go with a simlar approach than the one we have for labels, create  a list of known projection that need `over` and only set it for these, that should limit the bug a bit further, no? see: https://github.com/UV-CDAT/uvcdat/blob/master/Packages/vcs/Lib/projection.py#L21

**Comment by danlipsa** [comment]
Now I know some projections which don't work well with over: polar (non gctp), aeqd and polar stereographic. For polar projections you don't need over because when you wrap you end up in the same place - so that is no problem.

I think passing over to all projections should work - and it does on some machines :-)
So maybe we think about rearranging the code after we upgrade to the latest proj4 which may work more consistently.

**Comment by doutriaux1** [comment]
ok, but lambert fails with over as well for sure.

**Comment by doutriaux1** [comment]
that's a lot of elif, also with the restrcturing happening in lambert branch, it seem the gctp will not get the parameters autosets?

**Comment by doutriaux1** [comment]
really why not simply check against a list of proj that do not need this parameters, seems like a little more flexible, let me try to implement it in my lambert branch and lets compare ok?

**Comment by danlipsa** [comment]
Sure, no problem.

**Comment by danlipsa** [comment]
Does lambert (on your branch) fails only on annie or it fails everywhere?

**Comment by doutriaux1** [comment]
on annie and macs were the -3 tests fail. Wors when -3 works.

**Comment by danlipsa** [comment]
@doutriaux1 @aashish24 I wonder if this is a compiler issue. This is one thing that is different between annie/my laptop and my desktop. Annie has gcc 5.2.1, my laptop has llvm 7.0.2 my desktop has gcc 4.8.4. The proj4 we are using is over 10 years old so the new version should have many fixes.

**Comment by danlipsa** [comment]
@doutriaux1 @aashish24 In my mind +over should be always passed as proj4 wraps around only points which create problems with the cells of the dataset. So we should revisit this after we upgrade proj4 and try to always pass +over. (for polar projection an wrapped point ends up in the same place so it should not be a difference there)

**Comment by aashish24** [comment]
@doutriaux1 can we merge this branch since its passsing on  anie and other machines and then fix the lambert?

**Comment by aashish24** [comment]
@doutriaux1 I am merging this as I think it looks good to me.

**Comment by doutriaux1** [comment]
no non no no no NOOOOOO! It's the wrong approach I talked about it with @danlipsa this does not solve anything.... I will revert this. Beside it doesn't fix anything the issue is in proj4, it still fails on macs....

**Comment by danlipsa** [comment]
@doutriaux1 Which tests are failing? I have not seen anything in the buildbots.

**Comment by doutriaux1** [comment]
when i implement this in my lambert branch, the lambert test gives a different plot every time I run it. 

Anyway the lambert+proj4_updated is almost done building on my mac which exposes all the issue, I have hope...

**Comment by danlipsa** [comment]
@doutriaux1 @aashish24 I don't have anything against restructuring this code. If this code does not work with the lambert branch should be fixed/adjusted by that branch. I don't think that we should delay fixes for the master branch because those fixes don't fit some work in progress. If a fix passes all tests it should be good to go. Now lambert branch has to fix everything that this branch fixed plus what it was fixing. Plus we delay valid fixes for master.
In this particular case, as long as lambert goes in quickly and fixes everything, I don't have a problem with this. :-)

**Pull request merged**
