### PR TITLE
Sync release

### PR DESCRIPTION
**Pull request by aashish24**

### CODE REVIEW

**Comment by aashish24** [comment]
@doutriaux1 @chaosphere2112 please review.

**Comment by doutriaux1** [comment]
ok building on my mac right away

**Comment by doutriaux1** [comment]
@aashish24 I wqas working with master on friday. There are so e glitches in the new org of VCS/VTK.

As far as the tests failing. @dlonie did you merge in the changes from #1308

**Comment by doutriaux1** [comment]
100% tests pass for me on my mac.

**Pull request merged**
