### PR TITLE
Flake8 thermo

### PR DESCRIPTION
**Pull request by sankhesh**
Fixes #1416

### CODE REVIEW

**Comment by doutriaux1** [comment]
@sankhesh we need to tell flake8 to accept line up to 120 characters.

**Comment by doutriaux1** [comment]
@sankhesh also can you please move the files in Test into the testing directory the nc file should go in uvcdat-testdata/data/Thermo or something similar, look at my WK branch. Thx.

**Comment by sankhesh** [comment]
@doutriaux1 Sure thing.

**Comment by sankhesh** [comment]
@doutriaux1 Looking at your WK branch to make similar changes to Thermo. I see that you moved the `Packages/WK/Test/*.py` to `testing/WK/*.py`. Why not delete the `Packages/WK/Test/` folder now?

**Comment by sankhesh** [comment]
@doutriaux1 Thermo testing changes are in the [thermo_testing](https://github.com/UV-CDAT/uvcdat/tree/thermo_testing) branch.

**Comment by sankhesh** [comment]
@doutriaux1 All tests are passing here. Needs review and merge.

**Pull request merged**
