### PR TITLE
Add PYPTHONPATH explicitly to cmake to make sure the right CYTHON is …

### PR DESCRIPTION
**Pull request by dnadeau4**
…chosen.  There is a conflict on Ubuntu with Cython installed by the system.

Fix SciPy conflict with Cython installation from repository.

### CODE REVIEW

**Comment by aashish24** [comment]
thanks @dnadeau4. Should we set it here instead (In else): https://github.com/UV-CDAT/uvcdat/blob/master/CMake/cdat_modules/python_pkg.cmake

**Comment by dnadeau4** [comment]
@aashish24 python_pkg.cmake is used to make python.  It is not needed at that level.  For a python package running setup.py we need to set PYTHONPATH to "%PYTHONPAHT%".  I learned that double quotes are important.

**Comment by dnadeau4** [comment]
@doutriaux1 thanks!  I was just checking the "checks passed".

**Comment by aashish24** [comment]
@dnadeau4 we include python.pkg regardless. So the idea I was proposing to set the environment there and then for everyother package PYTHONPATH would have been set vs us setting PYTHONPATH for individual packages. 

@doutriaux1 would have been nice to wait for the discussion to complete. I didn't approve the branch as we were still discussing.

**Comment by aashish24** [comment]
https://github.com/UV-CDAT/uvcdat/blob/master/CMake/cdat_modules/python_pkg.cmake#L38

**Comment by doutriaux1** [comment]
@aashish24 didn't see that you commented until after I merged :stuck_out_tongue_winking_eye: sorry about that. It's actually a good idea, probably worth adding in another branch. I'm worried it might break something else though, so it's better to do it in two separate branches.

**Comment by aashish24** [comment]
No problem @doutriaux1 thanks for the consideration. It shouldn't break anything and if does then that would mean that we have some other issue / bug that we need to fix. I am just thinking that if SCIPY needs PYTHONPATH and it is likely that other python packages needs it too and may be that they are using system python and we are just lucky that we didn't run into any issue. 

+1 for pushing in separate branch

**Comment by doutriaux1** [comment]
let's do it. I remember some user running into issues on mac where it would pick up the system numpy rather than ours this might hel pwith this (unreproducible on my end) issue.

**Comment by dnadeau4** [comment]
Just came back from training.  If you think that adding PYTHONPATH to python_pkg.cmake would fix the problem for many packages, we should do it.  I can try it maybe tomorrow, today I have another meeting at 1:00pm to prepare.

**Comment by dnadeau4** [comment]
@aashish24 I tried all afternoon to compile SCIPY modifying python_pkg but it fails every time.   I added these line on line 22

 * set(ENV{PYTHONPATH} "@PYTHONPATH@")
 * message("[INFO] ***** Python Path is @PYTHONPATH@")

cmake shows the following message
* [INFO] ***** Python Path is /home/dnadeau/uvcdat-latest/15-09-03/lib/python2.7/site-packages
  CMake Error at /software/build-uvcdat/CMake/SCIPY_configure_step.cmake:59
  (message):

 * Error in config of SCIPY
 
Same compilation error.
 * CMake Error at /software/build-uvcdat/CMake/SCIPY_configure_step.cmake:59 (message):
 * Error in config of SCIPY

Since we already have solution that work, I prefer to work on another more important issue.

**Comment by aashish24** [comment]
@dnadeau4 thanks for trying this. No problem, I am surprised it didn't work. It could be that env is not getting passed to SCIPY for some reason. I will have a look at it but like you said this is not higher priority since we have  a solution in place. Thanks for looking into it.

**Comment by dnadeau4** [comment]
It was worth a try,  I would have liked it to work.  Somehow the PYTHONPATH set in python_pkg is not passed when compiling SciPy.

**Pull request merged**
