### PR TITLE
Issue1029 durack1 update ffmpeg 0.11.1 to 2.7

### PR DESCRIPTION
**Pull request by durack1**

### CODE REVIEW

**Comment by doutriaux1** [comment]
@durack1 works and confirmed animation work on my mac. Was about to approve but now you tried to sneak in your travis.yml in...
@aashish24 @jbeezley can you look at the travis.yml changes and confirm they wn't hurt anything? so that we can merge this in.
Thanks.

**Comment by doutriaux1** [comment]
I wonder why the buildbot doesn't see vtk?

**Comment by durack1** [comment]
@doutriaux1 the stability of these buildbot machines and their testing is problematic, the opendap error keeps occurring so #1380 [opendap fail](https://open.cdash.org/testDetails.php?test=344170858&build=3855046), #1369 [opendap fail](https://open.cdash.org/testDetails.php?test=342344087&build=3844793) and many other cases..

**Comment by jbeezley** [comment]
The addition to `.travis.yml` isn't going to hurt anything; though it also isn't accomplishing anything either.  The purpose of the command is to fix timeouts of a single command.  I.e.
```yaml
before_script:
  - travis_wait do_something
```
What it does is run the command `do_something` in the background and output a message to stdout every 1 minute while the command is running.  In the case of bcdd30927a5533816b6ab317aeba128e07e38f23, it just immediately returns.

The opendap error is a problem with the stability of the test server at http://test.opendap.org/opendap/hyrax/netcdf/examples/ECMWF_ERA-40_subset.nc, not the buildbot machines.  I'm not sure what happened with vtk in the latest build, but I'm looking into it.

**Comment by jbeezley** [comment]
From the vtk build:
```
make[5]: *** No rule to make target `/home/buildbot/buildbot/uvcdat-garant-linux-release/build/install/Externals/lib/libavformat.so', needed by `lib/libvtkIOFFMPEG-6.3.so.1'.  Stop.
/home/buildbot/buildbot/uvcdat-garant-linux-release/build/build/VTK/IO/FFMPEG/vtkFFMPEGWriter.cxx: In member function 'int vtkFFMPEGWriterInternal::Start()':
/home/buildbot/buildbot/uvcdat-garant-linux-release/build/build/VTK/IO/FFMPEG/vtkFFMPEGWriter.cxx:183:29: error: expected type-specifier before 'CodecID'
   c->codec_id = static_cast<CodecID>(this->avOutputFormat->video_codec);
                             ^
/home/buildbot/buildbot/uvcdat-garant-linux-release/build/build/VTK/IO/FFMPEG/vtkFFMPEGWriter.cxx:183:29: error: expected '>' before 'CodecID'
/home/buildbot/buildbot/uvcdat-garant-linux-release/build/build/VTK/IO/FFMPEG/vtkFFMPEGWriter.cxx:183:29: error: expected '(' before 'CodecID'
/home/buildbot/buildbot/uvcdat-garant-linux-release/build/build/VTK/IO/FFMPEG/vtkFFMPEGWriter.cxx:183:29: error: 'CodecID' was not declared in this scope
/home/buildbot/buildbot/uvcdat-garant-linux-release/build/build/VTK/IO/FFMPEG/vtkFFMPEGWriter.cxx:183:72: error: expected ')' before ';' token
   c->codec_id = static_cast<CodecID>(this->avOutputFormat->video_codec);
                                                                        ^
make[5]: *** No rule to make target `lib/libvtkIOFFMPEG-6.3.so.1', needed by `lib/libvtkIOFFMPEGPython27D-6.3.so.1'.  Stop.
```

From the FFMPEG build:
```
bin/sh: 1: yasm: not found
/bin/sh: 1: yasm: not found
strip: 'libavfilter/x86/af_volume.o': No such file
/bin/sh: 1: yasm: not found
/bin/sh: 1: yasm: not found
strip: 'libavfilter/x86/vf_gradfun.o': No such file
etc...
```

Yet, in the FFMPEG configure
```
install prefix            /home/buildbot/buildbot/uvcdat-garant-linux-release/build/install/Externals
source path               .
C compiler                gcc
C library                 glibc
ARCH                      x86 (generic)
big-endian                no
runtime cpu detection     yes
yasm                      yes
```

So, it is finding yasm at configure, but not at compile.  In this case, yasm is not installed on the system.  It looks like the uvcdat install `PATH` is set at configure, but not during install.  I'm not sure why.  The other buildbot machine isn't failing because a system yasm is installed.

There are really two issues here maybe @sankhesh can look into them.
1. Difference in `PATH` between configure and build for FFMPEG
2. Build errors being silently ignored for both FFMPEG and VTK.

**Comment by doutriaux1** [comment]
Thanks! I can take care of this.

**Comment by doutriaux1** [comment]
but if @sankhesh beats me to it that's great. in the ffmpeg_configure there is some (commented out I think) bits about yasm. @dlonie that's one reason sometimes I like to "just" comment out things rather than completely deleting, because sometimes a fix is needed again 2 or 3 years later and nobody remembers it if it's completely taken out :wink:

**Comment by durack1** [comment]
@jbeezley should the `travis_wait` precede the `cmake` call then? Would this catch the timeouts when source downloads hang?

**Comment by doutriaux1** [comment]
I'll take the travis.yml out, retest on Linux to fix the VTK issue and merge. Please do the travis in a separate issue thx.

**Comment by jbeezley** [comment]
@durack1 Yes, that will prevent travis from killing the build because no output is emitted for several minutes.  It won't restart the download though.  If the download is hanging indefinitely (as is likely the case), this will only cause travis to wait the full 60 minutes before it kills the job.

**Comment by doutriaux1** [comment]
let's definitely take this to another issue, @jbeezley would that allow us to test "full" builds?

**Comment by jbeezley** [comment]
No, not at all.

**Comment by durack1** [comment]
@doutriaux1 @jbeezley @aashish24 I've created a new issue #1384 for the build testing - please feel free to edit/add any info there

**Comment by doutriaux1** [comment]
ok looks like it fixes garant, will wait for laptop results and merge

**Comment by doutriaux1** [comment]
that also removes ONE dependency in UVCDAT! Yeah!

**Comment by ThomasMaxwell** [comment]
Has anyone tested the UVCDAT 2.2 binary release for OS X 10.8.5?    A user just installed it here and it appears to be thoroughly broken.    Dragging variables onto any plot repeatedly displays “Please drag another variable” despite the fact that the plot may take only a single variable.   I don’t have a 10.8 Mac to verify.

— Tom

**Comment by durack1** [comment]
@ThomasMaxwell you've just posted this to a closed issue related to updating the ffmpeg source - if you want this question to be answered/addressed, I'd recommend generating a new issue at https://github.com/UV-CDAT/uvcdat/issues

**Comment by doutriaux1** [comment]
@ThomasMaxwell something is up with your setup, you've been doing this a lot lately. Should we delete your comment above though?

**Pull request merged**
