### PR TITLE
issue1718 durack1 update Python 2.7.10 to 2.7.11

### PR DESCRIPTION
**Pull request by durack1**
[WIP] Test 2.7.11rc1

### CODE REVIEW

**Comment by durack1** [comment]
#1718 - Current work in progress, testing `RC1` with final release due later this week

**Comment by durack1** [comment]
@doutriaux1 it seems that the `*nix` machines are happy with this, but the `OS Xers` aren't.. Might be a good idea to pull `Python2.7.11` into your `XCode7` working branch and solve both issues at once..

Also looks like `crunchy` bot server has hung - wanna reboot/restart?

**Comment by doutriaux1** [comment]
@durack1 the bots are dead daily thanks to lab patches... I `cleaned` them today care to trigger a restart?

**Comment by durack1** [comment]
@doutriaux1 it looks like the `bot-suite` has hung again.. Any idea's what is going on?

**Comment by doutriaux1** [comment]
there is some test on RH that never ends, I need to figure out which one. Looks like it might be propagating to Mac now...

**Comment by durack1** [comment]
@doutriaux1 looks like a [missing test image](https://open.cdash.org/testDetails.php?test=401832004&build=4146820):
```
ERROR: In /export/doutriaux1/bots_oceanonly/build/build/VTK/IO/Image/vtkPNGReader.cxx, line 116
vtkPNGReader (0x22474d0): Unable to open file /export/doutriaux1/bots_oceanonly/build/uvcdat-testdata/baselines/vcs/test_vcs_meshfill_vertices_issue.png
```

**Comment by durack1** [comment]
@doutriaux1 is that rogue test causing the [problems with `crunchy`](http://aims4.llnl.gov:9981/master/crunchy.llnl.gov:9982/UV-CDAT/uvcdat/0303888e3c1d1e08bede23ddbf6110b597f73716/ctest__-j1__-D)?

**Comment by durack1** [comment]
@doutriaux1 can you review this for merging please? I'm keen to get these 10-20% performance increases happening..

**Pull request merged**
