### PR TITLE
[WIP] Issue1477 durack1 update spyder 2.3.8 to 3.0.0b2

### PR DESCRIPTION
**Pull request by durack1**
[WIP] Update Spyder 2.3.8 to 3.0.0b2 #1477

### CODE REVIEW

**Comment by durack1** [comment]
This PR will need to be updated with the latest dependencies for `Spyder 3.x` listed at https://github.com/spyder-ide/spyder#runtime-dependencies

**Comment by aashish24** [comment]
@durack1 same here.

**Comment by durack1** [comment]
@aashish24 note the `[WIP]` in the PR title.. I'm waiting for the next beta to drop, so we're one step ahead and have resolved all dependencies etc before the final `Spyder 3.0` release. The planned updates that are coming with `3.0` are certainly worth the effort

**Comment by aashish24** [comment]
> @aashish24 note the [WIP] in the PR title.. I'm waiting for the next beta to drop, so we're one step ahead and have resolved all dependencies etc before the final Spyder 3.0 release. The planned updates that are coming with 3.0 are certainly worth the effort

Sounds good to me. Any reason why cannot we close this one and open it again when you have more time?

**Comment by aashish24** [comment]
@durack1 I am closing this but not deleting the branch. Feel free to open this when the time is right.

**Pull request closed without merging**
