### PR TITLE
Issue 1158 auto magic time labels

### PR DESCRIPTION
**Pull request by doutriaux1**

### CODE REVIEW

**Comment by doutriaux1** [comment]
@dlonie @aashish24 @chaosphere2112 please review
goes with https://github.com/UV-CDAT/uvcdat-testdata/pull/30

**Comment by doutriaux1** [comment]
goes with https://github.com/UV-CDAT/uvcdat/pull/1178

**Comment by dlonie** [comment]
`test_vcs_lon_axes_freak_out` fails for me, but it looks like the baselines just didn't get merged. Otherwise LGTM. I'll merge the other testdata in, too.

**Comment by aashish24** [comment]
thanks David!. I am deleting the branch as well.

**Pull request merged**
