### PR TITLE
Vcsaddons histo polar

### PR DESCRIPTION
**Pull request by aashish24**

### CODE REVIEW

**Comment by aashish24** [comment]
Ref: https://github.com/UV-CDAT/uvcdat/pull/1999

**Comment by aashish24** [comment]
@chaosphere2112 cdtime.reltime is a function and not a class so the change 

isinstance(v, cdtime.reltime) is invalid and that's why broke many tests on my machine. I pushed a fix on this branch and also created a ticket for it (https://github.com/UV-CDAT/uvcdat/issues/2026). I think both reltime and comptime should be classes (as you and I would expect).

**Comment by aashish24** [comment]
this is ready to be merged now. I am going to do a clean build run all the tests and merge it.

**Comment by danlipsa** [comment]
@chaosphere2112 @aashish24 I get 
[~/projects/uvcdat/build]$ "/home/danlipsa/projects/uvcdat/build/install/bin/python" "/home/danlipsa/projects/uvcdat/src/testing/vcsaddons/test_vcs_addons_histogram_defaults.py" "/home/danlipsa/projects/uvcdat/build/uvcdat-testdata/baselines/vcsaddons/test_vcs_addons_histogram_defaults.png"
Traceback (most recent call last):
  File "/home/danlipsa/projects/uvcdat/src/testing/vcsaddons/test_vcs_addons_histogram_defaults.py", line 12, in <module>
    histo.plot(vals, bg=True, x=x)
  File "/home/danlipsa/projects/uvcdat/build/install/lib/python2.7/site-packages/vcsaddons/histograms.py", line 132, in plot
    dsp = template.plot(data,self,bg=bg)
TypeError: plot() takes at least 4 arguments (4 given)

Do I have to install something?

**Comment by chaosphere2112** [comment]
@danlipsa There was an update to vcs in addition to the update to vcsaddons; that might be the source of your problems, not sure.

**Comment by aashish24** [comment]
@danlipsa I didn't see these failures on my machine when built from scratch. I will have a look tonight.

**Pull request merged**
