### PR TITLE
Star and triangle fix

### PR DESCRIPTION
**Pull request by chaosphere2112**
Star and triangle markers are both broken in current master branch.

Star markers, despite passing validation as a real marker type in VCS_validation_functions.checkMarker, generate these error messages when plotting:

```
$ python marker.py 
/path/to/uvcdat/python2.7/site-packages/vcs/vcs2vtk.py:1113: UserWarning: unknown marker type: star, using dot
  warnings.warn("unknown marker type: %s, using dot" % t)
/path/to/uvcdat/python2.7/site-packages/vcs/VTKPlots.py:80: UserWarning: Press 'Q' to exit interactive mode and continue script execution
  warnings.warn("Press 'Q' to exit interactive mode and continue script execution")
```

where marker.py looks like this:

```
import vcs

canvas = vcs.init()

m = canvas.createmarker("markers")

m.x = [.5]
m.y = [.5]
m.type = "star"
m.size = 50
m.color = 1
m.priority = 3

canvas.plot(m)
canvas.interact()
```

and generates this image:
screen shot 2015-01-09 at 12 23 25 pm

I added star to vcs2vtk (1091:1120 and 1287:1313), so with my patch we'll get this:

screen shot 2015-01-09 at 12 23 11 pm

Marker types triangle_left, triangle_right, triangle_up, and triangle_down are currently displaying filled, despite the existence of triangle_left_fill, et. al.
For the script:

```
import vcs

canvas = vcs.init()

m = canvas.createmarker("markers")

m.x = [[.2], [.3], [.4], [.5]]
m.y = [[.5], [.5], [.5], [.5]]
m.type = ["triangle_left", "triangle_up", "triangle_right", "triangle_down"]
m.size = 100
m.color = 1
m.priority = 3

canvas.plot(m)
canvas.interact()
```

we get the image 

screen shot 2015-01-09 at 11 40 57 am

With a one-line fix (adding `gs.FilledOff()` at line 1034), we now get this:
screen shot 2015-01-09 at 11 42 27 am

### CODE REVIEW

**Comment by doutriaux1** [comment]
@chaosphere2112 could you plase add a simple test case that would be awesome.
Thanks.

**Comment by doutriaux1** [comment]
example a test code
```
import vcs
x=vcs.init()

m=x.createmarker()
m.type=["triangle_right","star","triangle_right_fill"]
m.x=[[.25,],[.5,],[.75,]]
m.y=[[.5,],[.5,],[.5,]]
m.color=[242,244,242]
m.size=300
x.plot(m)
```

**Comment by chaosphere2112** [comment]
Added a test; is there somewhere I should be sticking the baseline image?

**Comment by doutriaux1** [comment]
yes please add the test into CMakeList.txt (in testing/vcs) and the png baseline into a branch at:
https://github.com/UV-CDAT/uvcdat/uvcdat-testdata (inside baselines/vcs)
thanks

**Comment by chaosphere2112** [comment]
OK, I'm cloning uvcdat-testdata right now; I'll submit a PR over there shortly.

**Pull request merged**
