### PR TITLE
BUG #1947: isofill does not handle out of bounds levels correctly.

### PR DESCRIPTION
**Pull request by danlipsa**
When smallest level is bigger than min scalar value or biggest level
is smaller than max scalar value isofill creates the wrong image.

### CODE REVIEW

**Comment by danlipsa** [comment]
@doutriaux1 @aashish24 Please review.

**Comment by danlipsa** [comment]
@doutriaux1 The confusing part here was that we color by the cell data generated by vtkBandedPolyDataContourFilter. These are the bands from 0 to len(l) - 1. But we can also color by the scalar in the original data - this is point data: this is what you've done in  your PR. Your PR looked correct, but I did not understand initially how this was working before. I forgot about the bands generated by vtkBandedPolyDataContourFilter.

**Comment by doutriaux1** [comment]
@danlipsa did you also test the last example I posted, I don't think this fixes it. 
```python
import cdms2
import vcs

x=vcs.init()
f=cdms2.open("HadSST1870to99.nc")
s=f("sst")
print s.min(),s.max()
iso=x.createisofill()
iso.levels=[-15,-14,-13,-12,-11,-10,-9,-8,-7,-6,35]
x.plot(s,iso)
```

**Comment by danlipsa** [comment]
@doutriaux1 I run a selection in ParaView for all cells >= -6. This selects most cells - note ParaView does not show blanked cells because I save polygonal data which does not support blanking.

isofill-interval


This is the image generated by uvcdat - if you look carefully you'll see different colors at the top.
isofill-interval

**Comment by danlipsa** [comment]
@doutriaux1 Actually, I think you are right, there is something going on here. Some black should have been white. See the following image:
isofill-interval

**Comment by doutriaux1** [comment]
@danlipsa yes that is odd. But at least the levels seem to be picked up correctly (on your first plot). I still don't see how it's possible from the code, but it seems to work.

**Comment by doutriaux1** [comment]
@danlipsa I merged `conda_build` into your branch (locally) and was able to test it quickly, it seems to work ok. Not sure about the black bit though as you mentioned.

**Comment by danlipsa** [comment]
@doutriaux1 @aashish24 Please review. This solves all problems I know of.

**Comment by doutriaux1** [comment]
@danlipsa looks like it's working now. Thanks. But why do we do a `pointtocell` ? 
The reason I'm asking is that I was hoping we could draw isofill/isolines on unstructured grid, even if they did not have vertices information, simply using a point dataset.

**Comment by danlipsa** [comment]
@doutriaux1 putMaskOnVTKGrid needs to draw black (masked) any cell that has any points hidden. That is why I need pointtocell.

You won't be able to do isolines/isofill for a point dataset. Both need interpolation which only works if you have cells - topology information. Otherwise the algorithm won't know which points to use for interpolation.

**Comment by doutriaux1** [comment]
@danlipsa I'm attaching a sample zipped nc file, that has coordinate info (lat/lon) but no bounds info (in CF format), vcs cannot plot it, but it should be able to, since we know the point data (lat/lon). It's definitely something for 3.0 anyway, just wanted to ask you about it now before I forget.
[add.zip](https://github.com/UV-CDAT/uvcdat/files/324157/add.zip)

**Comment by doutriaux1** [comment]
@danlipsa I updated the baselines, it's good to be merged in as far as I'm concerned. If it's good with you as well, go ahead and merge please.

**Pull request merged**
