### PR TITLE
Part-1 of improved RST docs for VCS

### PR DESCRIPTION
**Pull request by aashish24**
* This is the part-1 of VCS documentation
* Updated to latest version of vcs 
* Added new examples and text on conda install

Feedback and suggestions are welcome. Part-2 will be "Deep dive in VCS" explaining plots in detail.

### CODE REVIEW

**Comment by aashish24** [comment]
You can visit ReadTheDocs for VCS here: http://uvcdat.readthedocs.io/en/rst_docs/user-guide.html

**Comment by aashish24** [comment]
@doutriaux1 @danlipsa please review.

**Comment by doutriaux1** [comment]
This is an awesome start! Thanks @aashish24

**Comment by danlipsa** [comment]
@aashish24 Are these errors from your branch?
CMake Error at /usr/local/share/cmake-3.5/Modules/CPack.cmake:423 (message):
  CPack package description file:
  "/home/danlipsa/projects/uvcdat/src/docs/README.txt" could not be found.
Call Stack (most recent call first):
  /usr/local/share/cmake-3.5/Modules/CPack.cmake:427 (cpack_check_file_exists)
  CMakeLists.txt:849 (include)


CMake Error at /usr/local/share/cmake-3.5/Modules/CPack.cmake:423 (message):
  CPack license resource file:
  "/home/danlipsa/projects/uvcdat/src/docs/Legal.txt" could not be found.
Call Stack (most recent call first):
  /usr/local/share/cmake-3.5/Modules/CPack.cmake:428 (cpack_check_file_exists)
  CMakeLists.txt:849 (include)


-- Configuring incomplete, errors occurred!

**Comment by aashish24** [comment]
@danlipsa yes, seems like it, I will push a fix shortly. Thanks @doutriaux1

**Pull request merged**
